### ISSUE TITLE
XML for Letters and Historical Documents: Something to guide me

### ISSUE THREAD

**Issue by mjb232** [ebeshero/DHClass-Hub#100]
So I was wondering if one of the returning students could post an example of the latest homework assignment. I'm more of a visual learner, so seeing an actual code and how it relates to a text will help me tremendously. I'm going to do a Virginia Woolf letter, so I'd prefer an example that wasn't one of her's, this way my code will be all my own and not an accidental copy.

**Comment by ghbondar** [comment]
We have already provided you with an example: Our comments on your graded first assignment should help and you should read them closely. At this stage the actual markup is entirely up to you. First and foremost, we will look for all assignments to be well-formed, producing a happy green square in oXygen. We are also looking for nested elements and the use of attributes. Beyond these basics, ask yourself, "What is interesting and important about this letter?" and mark-up accordingly. What is the basic structure of this letter? ...and indicate this through your mark-up. 

Finally, the best mark-up will also consider that each letter is part of a larger corpus of letters that may need to be compared through a mark-up system applicable across multiple texts.

**Comment by ebeshero** [comment]
@mjb232 Hi Matt! There is one big difference between coding an historic letter (or any historic document) vs. coding a recipe is that we kind of have to handle the historical document with kid gloves. In our commentary on your recipe code, we suggested you could tuck some of the words of the recipe into elements and attributes just because the whole point of making a bunch of XML files to collect recipes might be to use XML code to make basic information like vegetables and starches and quantities available in the elements and attributes for searching. 

With an historical document, we don't want to alter the text, and so it remains text. When we apply markup, our elements typically help to mark the structure. (Don't assume because there's white space in the file you copied from that a computer parser understands that to mean a "paragraph": It doesn't, and that white space will be meaningless (the XML parser runs all the text together unless we've told it otherwise.) So, in XML, you need to mark off paragraphs and other structural parts of the letter, like, say, the date line and the salutation and the close, etc. We call that **structural markup**. 

Now, our coding wouldn't be very interesting if it only blocked off the structure of the text. Look at the kinds of information you're reading in the letter. What might be interesting to mark if you were studying the text you chose? Would there be people you'd be interested in tracking down? Places/Addresses? Book titles? Meals? Dates? Events? Those are just some suggestions for things that humanities scholars are often interested in learning more about when they study personal letters. If the letter is left in plain text, we'd  have to go hunting for specific search strings to find people's names, but if you used code, you could help **mark up** where to find all the personal names, all the places, etc. And we could then collect a list of places in this letter, or represent them with color coding or do something to highlight them in some way for readers. 

Here's an example of HTML that we generated from the Digital Mitford project's XML of Mary Russell Mitford's letters: http://digitalmitford.org/1821-04-18-BRHaydon.html
In this, I'm just going to show you the HTML, because the underlying markup is a really big and complicated file--just look at the webpage to get a sense of what we're doing. When you use your mouse, and mouse over the names, you can see there's more information about each person--and that's stuff that's being stored in another file. We aren't asking you to look up all that information, but if you wanted to do a little research and add footnotes and commentary to your letter, you could do that with a <note> element, perhaps positioned inside an element like this:

`<p>blah blah blah blah I saw <name type="person">Mr. Bean<note>Mr. Bean is a friend of the letter-writer, and they've known each other since kindergarten.</note></name> <date when="2016-01-10">today</date>, and we talked for an hour. New sentence here, blah blah blah blah... </p>`

See how I've positioned the note inside the "Russian doll" of the <name> element? That makes sense here because the note is "inside" information about the name, and that could be a strategy you use with your coding. 

Now I've suggested marking off different kinds of names and information that people might want to look up now or later in studying this text, but you could also take an interest in grammatical forms. Would it be interesting to mark off unit sentences, and the subjects and main verbs of each? Or what other kinds of information might be interesting to mark? 

It's a typical practice to mark paragraphs so you can break these apart from a big block of text, but you don't really have to mark sentences unless sentence units are interesting, and say you wanted to collect each sentence and have the computer count them for you. (We'll show you later how to write code to read through your XML markup and count up everything that's of a kind, and even add numerical counts in an attribute automatically. (This is why we usually tell you not to bother hand counting things yourself, because we'll teach the computer to do it more accurately than humans typically do.) But think of things you might want to collect, study, count, or otherwise document in more detail, and try to apply your markup accordingly! 

Hope that helps.

**Comment by mjb232** [comment]
Thanks! Both of these have been helpful! I think I get what needs done. Also, @ebeshero's advice about the "note" was very helpful, I wasn't sure if I should add separate information in.

**Comment by ebeshero** [comment]
@mjb232 Yay! Glad that helped! And this is great use of our Issues board. :+1: @ghbondar says I should add my post here to a new tutorial page to add to our [Intro to XML](http://newtfire.org/dh/explainXML.html), and I think it's probably a good idea. (This issues board is good for us instructors, too!)
