### ISSUE TITLE
Syncing and Committing with Command Line

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#101]
@mjb232 @mmm202 @jlm323 @laurenmcguigan 

Hi new students, 

Here are the comments on using command line that were on the board yesterday:

First open your  GitHub GUI (desktop client).
You should see the DHClass-Hub repo on the left side. Right click on the repo.
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/12373384/751dbd58-bc45-11e5-96b6-a57dac13dc79.jpg)
Select "Open in Git Shell".
In order to **sync** any changes made on the remote repo (as in the repo that we all have access to change) and to pull in any of changes to you local version of the repo follow these commands:
type `git status -uno` then hit enter -- if changes were made that you are behind on you should get a similar message as the one below:
![clonerepo_gitstatus-uno_behind](https://cloud.githubusercontent.com/assets/8645521/12373585/ea815b8a-bc4b-11e5-9b7c-56ca075c1a7e.jpg)
Otherwise iT will say you are up to date with the origin/master (which is the remote repo located on the GitHub server).
From here you want to do `git pull` then hit enter. This command "pulls" in those changes. Git Shell should now look like this:
![clonerepo_aftergitpull_when behind](https://cloud.githubusercontent.com/assets/8645521/12373593/5ace51b8-bc4c-11e5-86ef-2fd48a02911c.jpg)
Now check to see if you are up to date with the `git status` command (again hitting enter after typing the command).
![clonerepo_aftergitpull_thengitstatus_up2date](https://cloud.githubusercontent.com/assets/8645521/12373598/9f38f7cc-bc4c-11e5-9a47-af66fc88bdb0.jpg)
Now let's say you **added files** on your local computer and you want to commit them to the remote repo. First you save the files in local directory configured with GitHub. Then once in Git Shell you run the following commands:
It is always best practice to first do `git status` or `git status -uno` to see where your local repo stands against the remote origin. If you have added files to the directory Git will now inform you that you have "untracked files" that needed added:
![clonerepo_untrackedfile_gitstatus](https://cloud.githubusercontent.com/assets/8645521/12373636/f1f798dc-bc4d-11e5-9a7d-bc49459cf238.jpg)
To "push" those files into the remote origin do the following:
`git add .`
`git commit`
At this point a text box will pop up where you should type your commit message (describing the changes you are making), then hit save and close.
The final command is `git push` and this moves the locally changed files into the remote origin.
![clonerepo_gitpushgitstatus_up2date](https://cloud.githubusercontent.com/assets/8645521/12373692/504d680c-bc4f-11e5-9bf4-42ce67055299.jpg)

@spadafour @nlottig94 @brookestewart  I encourage you all to mess around with these basic commands and to use them instead of the "gooey" GUI client. You will find using command line allow you to really see under the hood of how GitHub stores your files and it is typically quicker. A tutorial detailing more commands is on the way so stay tuned :)

**Comment by ebeshero** [comment]
Thanks for developing this, Becca! The screen captures are really helpful. :+1:

**Comment by RJP43** [comment]
For more on this please visit our [Git Shell tutorial page](http://newtfire.org/dh/explainGitShell.html)

**Comment by alexkrongel** [comment]
Hello! Sorry if I'm responding to the wrong topic, I wasn't quite sure where to give feedback on the main git tutorial. 

The one change I thought might be good in the beginning is a comparison between this and other version control systems. For example, students might not know Dropbox also has version control, albeit only allowing you to fully revert (edge: Git, etc.) 

I liked how thorough the account and repo sections were. However, I think it might be nice to move the account setup section to a separate page. I think most people will not have trouble with this section, and it adds a lot of length to the tutorial which makes it look more intimidating than it actually is. 

One other thing that we've all been discussing is public versus private repos. I think something could be said in the best practices section about always leaving your code public unless there is a specific reason like copyright for doing otherwise (though I understand if that might be going a bit more philosophical than the scope of this tutorial.)

Awesome work @RJP43 !

**Comment by jrzodkiewicz** [comment]
This looks great. I have two suggestions. First, the reader may be disoriented by the way you start the tutorial by referring to the GUI. The instructions seem to abruptly change directions at that step: "Here's how to use the command line. Step one, open the GUI." Adding a sentence or two as a transition would make it read more smoothly. And, since this is a command line tutorial, it might also be helpful to add some alternate initial steps to explain how to do these things without using the GUI at all.

Second, explaining the commands in greater detail would teach the students more and probably help the students remember them. For example, what does the "-uno" flag do? Right now I just see it as a thing to memorize, and since it has no semantic links to anything else in my mind, memorizing and recalling it might be difficult. Of course, this isn't meant as a definitive Github textbook, so we don't need to know all of the details, but if students engage with the commands' internal logic, they'll understand the system better, and better retain that understanding.

**Comment by RJP43** [comment]
Thank you both for these helpful suggestions and comments... this is technically our Class Hub and we have a separate repo. for web development where this conversation was meant to be had (found [here](https://github.com/ebeshero/newtFire-webDev/issues/27)). I think it is fine that these comments sit here but I am providing the link for any future comments/suggestions. Thanks again, to both of you, for taking such a close look at this tutorial. :+1:
