### ISSUE TITLE
Graphing and Validity: Discussion Assignment for Wed. 1/27

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#113]
## The Assignment 
(reposted by Dr. B, who also repaired the links!) @RJP43 @brookestewart @nlottig94 @spadafour @mmm202 @jlm323 @laurenmcguigan @mjb232 
It's much too easy to lie with numbers and graphs on digital humanities projects. Let's face it, we are Humanists and we don't do numbers. We will be posting links here of the good and the bad with graphing and using digital visualizations to share qualitative information on DH projects. 
Please begin by reading [**"A short tour of bad graphs"**](http://people.stat.sfu.ca/~cschwarz/Stat-650/Notes/PDF/ChapterBadgraphs.pdf)  Read this carefully, think about the advice given about graphs, and look carefully at the examples and discussion of problematic visualizations of data. 

### Discussion points:
* See if you can understand what's wrong with the examples in the reading, and if you have questions, about examples or advice in the reading, post them here! 

* Each of you in your posts should look on the web for two examples of bad graphs, and tell us what's wrong with them!

* There's no minimum or maximum number of posts: We'd like you to comment on each other's examples, discuss interesting examples from the reading, and locate two examples of your own from the web, just to practice your critical eyes and give this some thought collectively! Let's see what you all come up with.  

To start this out, [here is an example of a bad graph](http://nelson.newtfire.org/DaubeSVG.html) on Nelson 1.0, from Fall 2014. 
**What is bad about this graph, and why?**

**Comment by brookestewart** [comment]
And [here's an example of an awesome graph](http://dickinson16.newtfire.org/dash.html) from the Dickinson Project!

**Comment by nlottig94** [comment]
Here is an [example of a validity issue](http://networkingwomen.sixdegreesoffrancisbacon.com/) in a large representation of a network of data regarding the network of relationships within [Six Degrees of Francis Bacon](http://sixdegreesoffrancisbacon.com/).

**Comment by ghbondar** [comment]
@RJP43 Becca, the link that you posted does not work :(

**Comment by RJP43** [comment]
@ghbondar oh yes ... I just moved Nelson 2.0 over to Obdurodon. I will fix this and make the graph available again s later tonight. I will post here when it is available again, sorry!

**Comment by RJP43** [comment]
Here is a good link for the[bad Nelson graph](http://nelson.newtfire.org/DaubeSVG.html)

**Comment by laurenmcguigan** [comment]
I just have a question! Can someone explain to me what it means to adjust dollar amounts in a graph for inflation? Thank you!

**Comment by laurenmcguigan** [comment]
http://nelson.newtfire.org/DaubeSVG.html

This is the graph from the Nelson project. I found a few things wrong with it, let me know if you agree of disagree or if you have anything to add. 
- For the amount of occurrences it only lists 12.5 and 25. I think the graph should list more numbers, maybe intervals of 5 instead of 12.5. 12.5 doesn't make sense for number of occurrences, there can't be half an occurrence. Also, maybe on top of each bar it should list the actual about of occurrences. 

- Also, could the colors used cause problems for people with color blindness. Red and green could be confusing. 

- There are a number of different "change in voice tags" at the top, and you can compare the masculine, feminine, and Nell Nelson voices, and you can compare the articles to the book, but you can't compare changes. For example, you wouldn't be able to compare tones of woe vs. sexual tone. 

-Would the way someone says something, or the type of tone they used be left up to the interpretation of the reader? Is this a graph of fact or opinion?

**Comment by laurenmcguigan** [comment]
![piechart](https://cloud.githubusercontent.com/assets/16612030/12590868/2636110e-c433-11e5-958b-cbf4c865bdec.jpg)

CHECK OUT THIS PIE CHART. 
Thought you all might enjoy it.

**Comment by mmm202** [comment]
@laurenmcguigan I agree with you about the nelson project amount of occurrences. It seems like there may need to be more values because the graphs don't seem to go much higher than 12.5. You can see that changes are happening in the graph but it is hard to tell exactly what those changes are and to compare them. I believe that your pie chart is lacking some data since there is nothing in it! It made my day though.

**Comment by mmm202** [comment]
![capture](https://cloud.githubusercontent.com/assets/16582103/12591677/fccb46a0-c436-11e5-92b9-07237d9f9429.PNG)
This graph I believe has way too much information on it. Can anyone actually tell what it is even about??

**Comment by mmm202** [comment]
![image](https://cloud.githubusercontent.com/assets/16582103/12591775/8677dcd8-c437-11e5-9ba8-89720b11864a.png)
This graph has the information needed to make it easily readable. Does anyone see any flaws?

**Comment by ghbondar** [comment]
@laurenmcguigan Inflation here refers to the decrease in the value of the US Dollar over time. For example: a comfortable new car that costs $25,000-30,000 today might have cost around $3,000 back in 1973, more or less. So, usually, it is safe to assume that money in the past was more valuable than the equivalent amount of money today. For most of the past 20-years, inflation has been very low (prices increase 1-2% per year), but before then, inflation was much for significant (more than 5% per year). So, in short, to compare dollar amounts over time, changes in value due to inflation most be accounted for.

**Comment by jlm323** [comment]
@mmm202 The second graph you posted is a lot easier to read. The first one is hard to conceptualize and there are too many graphics that get in the way of actually understanding what it's trying to say. I think it is trying to show how many different countries goes into producing Starbucks coffee and also how many sales fast food restaurants get but it's just too confusing because there's too much there. 

The second graph, while it's easier to read, doesn't have a title. Also the silhouettes of the children in the background might be distracting to some. I don't think it's conducive to the understanding of the graph. The intervals on the x-axis don't seem to increase like they should. They sort of go up at random numbers.

**Comment by nlottig94** [comment]
![image](https://cloud.githubusercontent.com/assets/14095715/12598269/356054a4-c457-11e5-9094-4c8fb76054be.png)
This graph is bad because it has WAY too much information, and it is a pie chart.  Also, if someone is going to represent all of the countries that contributed to the food that was consumed in the UK, then absolutely all of the countries should be represented.  There should not be an "Other" category!

**Comment by laurenmcguigan** [comment]
![graph_bad_7_0](https://cloud.githubusercontent.com/assets/16612030/12598315/9c88abb8-c457-11e5-920b-2950e77c1c62.PNG)

- Here is another example of a bad graph. First of all, it is a pie chart, so that makes it bad right away

- .Also, it has a lot of information squeezed into a small space making it impossible to see the difference in size. It might be better to make it a bar graph.

**Comment by laurenmcguigan** [comment]
@nlottig94 

we literally just picked the same graph at the same time...

**Comment by jlm323** [comment]
![exampleofabadgraphpiechart](https://cloud.githubusercontent.com/assets/16583817/12598278/438cc274-c457-11e5-9d0c-89cfdb3f7982.png)

The data in this graph would have been better suited to a line graph because this information deals with land use over time. Looking at in in two separate pie charts makes it harder to see the differences. Also, there are no values for any of the categories, forcing people to try to make sense of the angles of each piece of the pie chart.

**Comment by nlottig94** [comment]
It's okay @laurenmcguigan!  I'll pick another!
![image](https://cloud.githubusercontent.com/assets/14095715/12598440/557cd838-c458-11e5-9270-ae85ff0aef98.png)
This graph is bad because it has WAY too much information on it, which makes it hard to read.  Also, we know that these are individual grades, but we don't know what the grades are for or who each individual is.  I also don't understand why the y-axis goes the whole way to 120%...
This could be fixed by creating an average of all the grades.  If the individual grades did need to be graphed, however, it would look better if the grades were just plotted as points rather than bars.

**Comment by laurenmcguigan** [comment]
![badgraph](https://cloud.githubusercontent.com/assets/16612030/12598488/9e2e3cac-c458-11e5-9e5d-5909769ac3a5.png)

Here are two more examples of bad graphs. The way they use the bar to represent infections makes no sense. If they are stacked on top of each other does that mean there are more or less. For example, in less developed regions, the size of HPV and Hepatitus B/C virus bars are the same, but does one have more than the other because it is higher up on the scale? 

The graph also does not have a title, and it may have been better as a line graph. Does anyone have any suggestions as to what would make this graph better? Do you think it could be a line graph, or would it be better as two separate bar graphs?

**Comment by nlottig94** [comment]
![image](https://cloud.githubusercontent.com/assets/14095715/12598601/3d9f5276-c459-11e5-8277-e1fbe4ec842a.png)
This graph is a very bad graph because it does not put anything into perspective.  It looks more like a board game!  It does have a legend, though, which makes it a little better than the last graph I posted.  Also, the random graph-like lines makes the graph look even worse!

**Comment by laurenmcguigan** [comment]
@jlm323 I agree with you on the land use chart! I also think it would be better to add percentages or numbers to the pieces to show how many there really are, or how many there are in comparison to one another. I think a  line graph would solve that problem by the amount or percentage on the graph.

**Comment by jlm323** [comment]
![misleading-graph-2](https://cloud.githubusercontent.com/assets/16583817/12598928/6ce031f2-c45b-11e5-800c-b414f0c456fd.jpg)

The small graph on the right is misleading because it looks like The Times have much higher sales than Daily Telegraph, but really it is the scale of the graph that makes it appear to be so different. The Times had 485k sales while Daily Telegraph had 446k which is only a 39k difference.

**Comment by ebeshero** [comment]
@jlm323 That's not just a bad graph (on sales of The Times vs The Telegraph)--it's a deliberately misleading visualization! By altering the width of one bar the publishers make it look to our eyes a lot shorter. That's lying with a picture. (Great example!)

**Comment by ebeshero** [comment]
@laurenmcguigan hmmm. I'm looking at the stacked bar graphs of the various kinds of infection in less developed vs. more developed regions. I'm not sure it's misleading because we are looking at a number of infections on the y axis, and stacking the bars helps us to see how much of each kind of disease is part of the total number of infections. There's a convention in stacking bar graphs to stack the bars with the largest proportions on the bottom and the smallest ones on top. I see your point that if you were to compare a total number of just the human papilloma virus between undeveloped vs. developed regions it's a little hard to compare, so my suggestion here might be to include a number of outbreaks of each kind inside the bar. Alternatively, you might set the percentage of human papilloma in relation to each bar's stacked total if comparing the relative proportion of total outbreaks actually matters more than the literal number. I could see uses for each approach (actual number of infections of X kind in undeveloped regions, and percentage of X type of outbreak to the total in undeveloped regions). 

But I do think a stacked bar graph **is** appropriate for showing proportion of a total. I am not sure you want a line graph, do you? Line graphs are good for expressing trends over time, so it would make sense to plot a line graph showing a reduction or increase in outbreaks in undeveloped regions over, say, a 50-year period. How were you thinking of plotting a line graph of the data here? (I might be missing something...)

**Comment by spadafour** [comment]
Yeah, that Nelson graph is BAD. First off, the underlying data behind the graph makes the entire thing disingenuous; the idea was to tag things like positive, negative, sarcastic, etc. However, as @laurenmcguigan sort of pointed out, the coding was entirely subjective; the graph pulls in data from multiple articles coded by different people. Results would be different every time another person coded a document. Attempting to compare the books to the articles offers no real tangible insight.

Also noted was the poor labeling. Notice that most bars don't even reach the halfway point on the graph, meaning that it is basically a guess to the number of occurrences for each tag. Also, the halfway value for the number of occurrences was 12.5; how can we count half of an occurrence?

(sorry, @RJP43 ! Did you make that, or did Shane?)

**Comment by spadafour** [comment]
@mmm202 the average weight of an American female child is odd. The choice to section weight off into intervals of 6 (which isn't entirely consistent; one of the intervals is 7) is hard to read; why not section it off into intervals of 5?

**Comment by spadafour** [comment]
Here's a subreddit dedicated entirely to bad data visualizations: https://www.reddit.com/r/dataisugly/#page=1

**Comment by spadafour** [comment]
Here are some terrible Fox News examples!
![0701-ff_unemploymentchart](https://cloud.githubusercontent.com/assets/14111815/12602858/b59fe6e8-c47a-11e5-881d-9e3ac2f611c8.jpg)

They picked three arbitrary months and connected the unemployments rates with a straight red line. The red line is nothing but intentionally misleading. The months are not equidistant.



![bush_cuts2](https://cloud.githubusercontent.com/assets/14111815/12602921/655b679c-c47b-11e5-8c33-90049d82e0b6.png)

Here, they truncated the y-axis, making the disparity between both bars significantly exaggerated.

**Comment by brookestewart** [comment]
![chartjunk](https://cloud.githubusercontent.com/assets/14084707/12603179/442bce6a-c47e-11e5-9cf2-21164527df13.jpg)
Okay, I don't know who could have thought that this pie chart was a good idea. First, there's no title, so you can't even tell what it's about, or if it's even measuring anything. Second, it's REALLY hard to see where the actual sections are. The 3D aspect is very poorly done and would be better off if left 2D. Third, there is way too much information here, it's hard to tell what goes where. 
I'm sure there's more wrong with this, but those are the main problems I found.

**Comment by brookestewart** [comment]
![dob](https://cloud.githubusercontent.com/assets/14084707/12603302/7929c314-c47f-11e5-8077-01268ad9da53.gif)
This graph is also pretty confusing. The stacked bars are difficult to make sense of since the lighter bar isn't being measured from 0. You can easily compare it to the darker bar, but it would be difficult to figure out the exact number associated with the lighter bars. There's also quite a lot of information on the graph, which makes it hard to read. Also, I don't understand why there are gaps in the bottom two bars. The graph is just overall confusing to me. However, I do like how they did the background color - it makes it easy to see the overall level of water availability with the combined resources.

**Comment by brookestewart** [comment]
![f2 large_-1024x684](https://cloud.githubusercontent.com/assets/14084707/12603495/4381c84a-c481-11e5-9cbc-14de9961ea34.jpg)
Bonus! This is so awful. Someone help!

**Comment by RJP43** [comment]
Wow, some of these are absolutely horrible. In response to @spadafour the Nelson 1.0 graph had both Shane's and my hands on it. I did the querying of the data, while he produced the graph (the javascript and svg). Now I will say, in our defense, we were working under rough circumstances and the Nelson project was in its first year of development. It took spanning out further and adding more editors for the project to move away from the original subjective nature of the markup. Also, the successful javaScript was an accomplishment in itself. Finally the graph was made with the intention of future project development to not only finish the titling and explanation of the graph, but to also provide more articles and chapters. Having more data would have boost the number of occurrences and if I remember correctly Shane chose the max number to account for when the additional data would be added. There is no doubt though that the graph is flawed immensely. Surely with more experience under our belts the Nelson team can better graphs.. right? To answer that I would say yes and no. So yes we won't make the same mistake twice with the subjective markup; however, as the project is still in development sometimes information that seems clear cut turns out not to be. Let's take for example another visualization out of the Nelson project (this one from last semester). The following image is a table represented in one of the Nelson project texts that displays survey information: 
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/12604159/fac94992-c486-11e5-922a-ed93c29843db.jpg)
There are several parts of this table that are confusing. The large amount of information clustered into such a small graph makes it difficult to read and understand. So last semester we worked to better this table by turning into a [graph](http://newtfire.org/dh/ebbWSGAOutput.svg). As the semester went on we came to realize that our underlying markup to create the graph was skewed because there was a portion of the table  (the numbering system in the original table referring to the order questions would be asked or skipped pending on participants' answers) that was confusing and left out. This is a good example of how data can be skewed during the digitization process. In one sense the new graph was a better representation of the data because it became clearer; yet, the data is also incomplete until the question order is included in the new graph.

**Comment by RJP43** [comment]
![badgraph2](https://cloud.githubusercontent.com/assets/8645521/12604510/2971e526-c48a-11e5-9275-751f0711caa4.png)
![badgraph3](https://cloud.githubusercontent.com/assets/8645521/12604511/29765908-c48a-11e5-9383-e2ae6959591b.png)

pictures of little animals and candles do not act well as bar graphs
the sizing of the different little images is inconsistent
the purpose of the graphs are unclear
the little images are distracting

**Comment by ghbondar** [comment]
:-0= *augh!* Those sure are some terrible graphics, guys... nice job! Some observations in no particular order:
- One of the few benefits of a pie-chart is that you _can_ cram a whole lot of categories into a fairly concise space, if you need to. @laurenmcguigan 
- Stacked bars that do not sum to 100% do no make much sense ... even then, you basically have to label the individual segments it seems. @laurenmcguigan 
- 3D-effects: @brookesteart your first example shows that just because you can do 3D-effects, doesn't mean you should! An object-lesson (in 3D) to us all!
- Stacking icons or using pictures instead of a bar is probably not a good idea, even when you _are_ comparing four puppies to three cats. @RJP43
- Using child-outlines on a graph comparing children's body-size _could_ be intuitive, @mmm202, but in this case, the outline appears to be arbitrary and is a distraction because is _should_ have meaning. 
- You Nell Graphs @RJP43 at least need more subticks, say at every 5.... 12.5 is meaningless since you are only reporting integers.
- ... and always check with www.snopes.com after watching Fox News! @spadafour

**Comment by mjb232** [comment]
![image](https://cloud.githubusercontent.com/assets/16612002/12633875/fc712136-c542-11e5-8530-fcff184d9629.png) 
So for this first graph there's a whole mess of issues here which mainly deal with bad UX
1) there are no labels! What exactly are we looking at?
2) Looking in the center is disorienting
3) They use very similar reds for two different pie charts (top right and bottom center)
4) Since the graph is so busy, the tiny green sliver in the top right is sort of obscured

 While the last graph was more confusion and hard to look at, this one is less busy and more simplistic. However, this new graph struggles to convey it's actual data:
![image](https://cloud.githubusercontent.com/assets/16612002/12634062/679ad488-c544-11e5-97ce-e75b315fcede.png)
1) The actual averages for each player is unclear, for Emily's seems to be just above the 130 line, Hilde's seems to be somewhere in the middle of 110-115, and the inaccuracy of the previous two bars cause us to doubt the accuracy of Diana's which seems to lie on 120
2) The Y axis should be labeled with some kind of title or unit, especially for those who know nothing about bowling (like me). Diana has 120 what? Points? Pins? Shots?

**Comment by Pomilui** [comment]
Here is one of those 3-D Pie Charts (ugh) where the viewer has to read the percentages on the side and try to compare them with the area of the slice.  The 3-D effect makes it seem that the smaller parts won't fit into a circle if all of the slices are added together.  
![ted talk](https://user-images.githubusercontent.com/35349892/35474990-931e3566-038e-11e8-83ca-66a548b3903e.jpg)
