### ISSUE TITLE
Network Analysis Discussion: Southey's Thalaba the Destroyer

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#117]
Read my blog  on an XML-based network analysis project I am working on, [Spectacular intersections of place in Southey’s *Thalaba the Destroyer*](https://digitalromanticist.wordpress.com/2013/08/23/spectacular-intersections-of-place-in-southeys-thalaba-the-destroyer/) and post here to reflect on the following:

* What are you coming to understand about network analysis and how it works?
* What kinds of things can you study with network analysis? 
* About the Thalaba project: what might we be learning from using network analysis here? What questions do you have about how it works, or about what we can learn from looking at the graphs?
* Look at some other network analysis projects are mentioned in the blog (such as the *social network analysis* Six Degrees of Francis Bacon)? What ideas are you learning about the kinds of things or people or ideas can you network together? 

Discussion posts are due as part of the homework for Monday 1-25. Each of you should post at least two or three times, and the class as a whole should try to cover the range of questions I've set here.

**Comment by mmm202** [comment]
Network analysis is a method of analyzing complex problems by representing the problem as a network of lines and nodes. It can be used to study relationships and graphs as a representation of either symmetric relations or asymmetric relations between discrete objects.

**Comment by ebeshero** [comment]
Thanks for getting this started, Megan! So--here's a question: What do we mean by symmetric vs. asymmetric relations? The phrase is interesting and has a definite meaning when we study networks... 

"Discrete objects" just means distinctly separate things. Separate people, separate books, separate places. We could connect people to people because they all turn up in the same place at the same time, and in that case the distinct people would be the "discrete objects" in Megan's definition.

**Comment by nlottig94** [comment]
Well, in reference to the last question, in the *Six Degrees of Francis Bacon* project, I learned much about the relationships between people in early modern Britain.  However, because of the time period, not many women were or have been cataloged in their project.  Today, for example, was the day where the site wanted to incorporate many more relationships within the already complex network of relationships.  As a participant, I found out a lot about the woman, Anne Lucas, that I researched solely based on her personal relationships.  For example, I learned that she had two husbands and when she was with her second husband, Queen Elizabeth stayed in their home for a night.  Unlike Southey's novel, all of the people and connections and relationships between these people were 100% real and happened.  I also learned how and through what connections Anne Lucas was eventually tied to Francis Bacon!

**Comment by ebeshero** [comment]
A small correction: Southey wrote a long epic poem, and hinged notes on it that contained information about places and cultures around the world, and what was understood about those places at the turn of the 19th century. Some of those place nodes are mappable, physical places, but some are in the domain of myth and religion, so what I tried to network is something a lot different from the Six Degrees project, though we can still use the same tools to study those relationships. Why in the world would anyone want to study a network of imaginary and real places anyway? (I ask myself that all the time...)

**Comment by nlottig94** [comment]
Ahh, but isn't that the beauty of your study @ebeshero?  I think it's fascinating!  Especially because it's so much like our lives.  For example, we're in real places when we're awake, but when we're asleep and we dream, aren't we really in imaginary places sometimes?  I think that's a very cool thing to study!

**Comment by brookestewart** [comment]
Network analysis is commonly used visually map out social relations between people, whether they are real or fictional. The nodes in the visuals can differ in size, depending on the number of connections to that node. However, this doesn't dictate the importance of the node. For example, a smaller node with only one or two connections could be a vital one, connecting two important people. Network analysis can also be used to study things other that social connections, such as locations, as we see in the Thalaba project. The project studies the intersections of the places mentioned not only in the main text, but in the paratext of the poem.

**Comment by jlm323** [comment]
Using network analysis with the Thalaba project allows one to see the diversity of the places mentioned in both the poem and Southey's notes. It also is able to show the frequency with which certain places are mentioned. For example, Greece seemed to only come up twice although it was also mentioned with a number of other locations that were referred to more than that. So, network analysis not only deals with interconnections of subjects but also how frequently they appear, especially when working with multiple volumes or documents of text. 

I thought it was interesting how imaginary places, or "metaplaces," were included with real places. The metaplaces of the Tombs and such seem to be just as significant as places that actually exist. We can see how Southey connects these imaginary places with real ones through the network analysis as well.

**Comment by laurenmcguigan** [comment]
As I started reading your blog post, I really liked the idea that Southey's poetry comes not only from readings and his perceptions of the world, but his observation of other's around him. As a communication student who has studied ethnography, with an interest in social psychology, I find it fascinating that a poet draws inspiration from people of other cultures rather than just relying on his own experiences. While I find poetry to be a way of adapting text to your own life experiences, it is interesting that poetry can also work to help us understand others. I know this wasn't one of the questions, I just thought I would mention it!

**Comment by laurenmcguigan** [comment]
@jlm323 I agree with you that network analysis is a great tool to see the diversity of places mentioned in a text. It reminded me of the Lord of the Rings project we looked at in class. On their page you were able to type in a single word and it would tell you how many times that word was used in each of the books or movies. It is a great way to study a lengthy text and pick up on patterns that are not easily detected by the human eye.

**Comment by laurenmcguigan** [comment]
"while with Southey, the intellectual inheritor of an eighteenth-century “Information Age,” we have the re-tooling of the ancient epic poem to model and study mythic thinking and ritual practices around the planet. "

This got me thinking about how we can use xml to find patterns in different myths. For example, every country may have a different idea about Santa Claus. But by using xml, we can find patterns that each "myth" or "tale" to see what they have in common and how the myth has changed over time. Does that make sense or am I getting too off topic??

**Comment by jlm323** [comment]
@laurenmcguigan That makes sense to me! We could look at how similar or dissimilar things are, in this case, Santa Claus, and represent that in a graph or something of the sort. I think this is similar to what Nicole and Brooke are doing with the Dickinson project, although they're looking at poems and how they changed over time from different editions. But with myths, I think using xml could definitely help looking for patterns. Like how similar is Santa Claus to the Bavarian mythical creature, Krampus, who punishes children for their bad behavior, and etc.

**Comment by mmm202** [comment]
@laurenmcguigan I think that you provided a good example, it also makes sense to me and made me understand more about it. @jlm323 I agree that xml could help with looking for the patterns and that you could go many different ways with it to include different information.

**Comment by laurenmcguigan** [comment]
@brookestewart I agree with you. Nodes, not matter how small, can play important roles in WHO they connect, not just HOW MANY they connect. I know in the Thalaba project nodes are used to connect locations, but how else can we use nodes other than to connect people and places? That is to say, what other things could you connect, or are their even other things that would be useful to connect? (If anyone has any thoughts?)

**Comment by nlottig94** [comment]
@laurenmcgui

**Comment by brookestewart** [comment]
Another aspect that I like about network analysis is that it (obviously) gives a strong visual representation of information. I find that it's easier to keep people and places straight when you have them mapped out in a visual that you can constantly refer back to. For me, it seems like a convenient way to guide someone through a text, especially one that has so many people or locations that would otherwise be jumbled in your mind as you try to read.
