### ISSUE TITLE
Project Brainstorming Discussion: Where Might We Go From Here?

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#12]
Choose one of the following Greensburg project sites under development. Your first post should describe (in your own words) at least one significant topic it seems to be exploring, and reflect on what we might want to try next to improve the "UX," and/or develop the research areas of the project. Then let's develop this into a conversation--everyone should post at least twice here and discuss with each other some directions we might take together with one or more of these ongoing projects this semester:

* [The Nell Nelson Project](http://nell.obdurodon.org/).This is the project Becca launched last year, and there's much new work to be done here!
* [Digital Mitford Project: Letters Introduction](http://mitford.pitt.edu/letters.html). First review the bottom section: "Digitizing a Mitford Letter: Photofacsimile, Transcription Markup, and Versioning Markup": Think about what the side-by-side view shows us and what we might we be able to learn from it. Comment on the reading views of the letters: What kind of research is involved here/ what kinds of questions have we been investigating to generate our views of these letters? What (besides coding some thousands more letters) could we try to build from our markup?
* [Digital Archives and Pacific Cultures](http://pacific.pitt.edu): This is a complicated site, so you may want to choose just one aspect of it (voyage narratives, mapping, graphs and charts of cultural responses, reading interface, etc.) to address. This project site represents the origins of our Pitt-Greensburg digital humanities projects—it was our starting point and first collaboration with students. What do you think we should do with it next?
* [Emily Dickinson's Fascicle 16: Eleven Poems] (http://www.pitt.edu/~ebb8/EmilyDickinson16/1601.html) A small "ad-hoc" project site that could grow in some interesting ways.

**Comment by RJP43** [comment]
@ebeshero The link for the Digital Archives and Pacific Cultures is leading to the Mitford Letters.

**Comment by ebeshero** [comment]
fixed! Thanks, Becca!

**Comment by nlottig94** [comment]
I chose to look at the Emily Dickinson's Fascicle 16: Eleven Poems project.  One significant topic that the project explores is the re-purposing an older project of Michele Ierardi's that analyzes Emily Dickinson's poems throughout the different editions of her work throughout the years.  That is all I could really get from the project in terms of what it explores.

I found the project very difficult to understand.  For example, the link just takes us directly to the first poem and a bunch of different scans of other things written by Dickinson.  I like how we can actually see the real manuscripts, which have captions of what the manuscript is, but nothing on the page tells me how all of these different scans are related to the poem (other than they are all by Dickinson).  I think the project would be easier to understand if there was a homepage that came up first that tells me what the site is about, like Becca's The Nell Nelson Project does.  Overall, I think the project should have a different layout so that it is much easier to understand all of the content.

**Comment by blawrence719** [comment]
Like @nlottig94 I also chose the Dickinson project and also found it very hard to understand even after reading the "About" page. I also thought that the project should have a more clear homepage because I was immediately confused when I came to the site and just found a collection of poems, which I was not sure how they were organized or related. I wished that the organization of the site was laid out more clearly so that I understood what was going on. I liked being able to see Dickinson's handwritten drafts with text beside it telling me what it said. However, unless I missed something along the way, I don't understand how the poems at the bottom relate to each poem at the top of every page. Also, when it comes to the scanned images of published poems, it is hard to know which line of text is describing which set of poems. Perhaps I've missed something, but like Nicole, I found the site confusing and also wish for a different layout or organization.

**Comment by spadafour** [comment]
I took a look at Becca's Nell Nelson Project. While content is lacking (understandably, with only 2 attributed contributors), the structure is definitely there. The tab, 'Methodology and System Analysis' lists out all of the elements (as well as providing links up and down the page - nice!), but I would like to see the graph at the bottom separated in to its own tab. The graph labeling a count of the text split in to the different voices is great! But its buried underneath all of that code for reference. Data analysis is neat; I would definitely like to see more of that. Maybe a chart to see which issues of the time Nelson associates with which voice? (e.g.: the graph represents voice against emotions like woe, intimidation, and pity, but what about voice against, say, livingConditions or workingConditions? Maybe even Woe and intimidation vs. livingConditions and workingConditions?)

The text itself, however, isn't really yet on the site. Some links from the articles are active, but they only lead back to an unformatted home page. Maybe take the links down until the text is ready? The one article that has text associated with it (date: 1888-08-04) needs some white space to spread out the text on the page for an easier reading experience.

Overall a very neat topic!

**Comment by amielnicki** [comment]
I, like @spadafour, also looked at Becca's project. I also noticed it was lacking content, but when I went to the list of articles, I was confused by the full list being there, but only 4 of the links being active. Also the homepage is helpful, but it could use a bit of design work, in way of the interface. For example, when you resize the page, the page adapts to it. However, there is always a bit that hangs off the side, requiring you to horizontally scroll on the page. Also, what @spadafour talks about with the "unformatted home page" is the landing pages for the respective articles. Since the site look is consistent on all other pages, I don't see why those pages don't have the styling applied.

Some suggestions would be to reformat the design, keeping the colors (if so desired) but making it more user accessible and easier to follow. Another would be to eliminate links that are not yet linked to pages so as to not confuse the readers. You can include the list of the articles somewhere, but on the links page is confusing.

I really enjoyed the data visualization!! I would recommend changing its location and changing the style of the graphs to match a revamped look of the site. The content is great, but if people can't follow it, you are dead in the water. You have an average of 10 seconds to capture the reader's attention on the homepage before they consider leaving your site. The homepage should be engaging enough to draw them in, but not overly so to be the only page they visit. The homepage would be a great place for some examples of what the graphs will look like when there is more data - a sort of future drawing, if you will.

**Comment by brookestewart** [comment]
I looked at Emily Dickinson's Fascicle 16: Eleven Poems. The site seems to explore different publications of Dickinson's poems and the variations between the versions. I have to agree with @nlottig94 and @blawrence719 about the confusing layout. The home screen is simply a poem with no explanation of where it came from or what purpose it serves. I think the first page should include some sort of short description to first make clear where the poems are from or why they are significant, etc. I really like the idea of being able to see both the old manuscript and the digitized text on the same page. It's also easy to view the TEI XML code, as the link is right under the title of the poem. 

As the others mentioned, I find the scanned pages at the bottom a bit confusing. Do the poems go with the captions? I think it would be easier to understand if they were arranged in a more organized way. It seems like there is the same text, or captions, on every page, but not the same scanned poems. Some clarification here would help.

**Comment by nlottig94** [comment]
Since @blawrence719, @brookestewart , and I all agree that the Emily Dickinson project seems a tab bit confusing, I think that overall, the site should be a little more descriptive with everything.  I think that we could include a very descriptive homepage that tells what the project is about and what people can use it for.  Also, I think on the other pages that include the poems, we could really rework the scans so that people will know what they are for.  I think the project needs much more text for explaining.

This project could be very cool, if people could understand what it is all about!

**Comment by CodyKarch** [comment]
I specifically looked over some of the letters of the Digital Mitford Project. Aside from the tiny problems I noticed liked, the tags not showing information or not displaying because it was at the end of the page, I thought it was very well presented, informed, and connective to the actual texts. Literary-wise, I appreciated how the meanings (like the references) were held in place for the reader's own desire. A main critique I would have for the letters portion of this site would actually be aesthetic: I think the tags had a slight problem balancing out {meaning that they either were very informational or not very informational}, the smaller crediting text area on the left could be sized into a better form in a smaller portion of the page {to draw more focus upon the main letter}, and the text area on the right (with hyperlinks) could possibly be balanced more into focus to fill any empty space.
That goes without saying, it had noticeably great information with connection.  
~http://mitford.pitt.edu/1820-09-09-Elford.html
~http://mitford.pitt.edu/1821-04-18-BRHaydon.html

**Comment by KariWomack** [comment]
I took a look at Becca's Nell Nelson project and several things stood out. The missing content, blank subjects/unfinished links for one, but it also held a lot of potential! I also agree with @spadafour's idea of a chart to display the voices and their relation to the issues of the time. I also agree with @amielnicki in needing an eye-catcher for the readers on the home page. I can't stress this enough in web design: PRESENTATION IS EVERYTHING!!!!!!! Its great when the information is present, but ultimately, your first impression of a book IS its cover, and you want it do be visually pleasing as well as informational.
Very interested in this!!!!!

**Comment by brookestewart** [comment]
I agree with @CodyKarch about the information in the boxes when you hover over the highlighted text. Some boxes are quite large and packed with information, while others are not even a complete sentence. However, I think the amount of information given is proportionate to the amount needed to understand the given word. To clarify, there is a lot of information given for people and particular events, while there is very little information given for geographical locations. It's more important to know about the people in the letters than a location, which could easily be looked up on a map. I think it's very helpful to have the background and definitions readily available, rather than having to leave the letter to look something up. An idea would be to have a link to a map or some other feature that shows where the place is. If not, it could always just be looked up by the reader.

**Comment by blawrence719** [comment]
I think it would be easier to know what to "fix" on the Dickinson site if we knew what the site was currently trying to accomplish and how the poems are being organized at the moment. As of right now, I'm not sure what to suggest as far as organization goes, because I'm not sure if the poems are meant to be related or not like @brookestewart  mentioned. I also agree that there should be more text present with the scanned poems at the bottom and I agree with @nlottig94  that there should be a homepage explaining what the project is trying to accomplish. Overall, more information about the original intent would help to know what needs to be changed.

**Comment by ebeshero** [comment]
OK, @blawrence719 @nlottig94 @brookestewart : here's some more info about the Dickinson project: The site reproduces a collection of poems that Emily Dickinson wrote out by hand and bundled together with a needle and thread. (She made lots of collections of her own poems this way, and it's interesting to look at a group of poems as she decided to bind them.) The poems present some challenges for representation though: Dickinson presented many alternate variations of words and phrase for particular lines of text, and it is not always clear whether she intended to delete a word and substitute another word, or if she was just signaling and jotting down an equally good alternative! (In fact, we think she really wrote these poems to hold variations without excluding or deleting anything. 

Traditional print editions of Dickinson's poems would eliminate variants. Editors would choose a particular phrasing, and sometimes not even signal that Dickinson wrote down some alternatives! Or if they did note an alternative, they'd put it at the foot of the page in tiny footnote. Even more problematic, though, the early print editions actually *interfered* with Dickinson's text by "normalizing" it! That is, the early editors would change her punctuation and even cut lines of her text to "improve" it. Later editors have returned to Dickinson's manuscripts to try to represent them more fully and accurately as she wrote them, but reproducing her variants (as we call her alternative phrases) is a challenge to do in print-based media. The web gives us a few more options that we are starting to explore with our project!

There is so much we need to do here: As you are noticing, it's not clear how the pictures of the print editions relate to the manuscript and transcription. We could write XML code to record the alterations made in each print text, to document the changes and try to analyze and study them! What do you think? Try studying one or two of the poems and see if you can spot some differences between print editions and manuscript. What kinds of changes do you see? What might we do to try to highlight them? 

(I have some ideas for this, and you'll probably have some too after our exercises with TEI tomorrow...more on that soon!)

**Comment by spadafour** [comment]
Since not a lot of people are talking about it, I looked at the Digital Mitford Project. It's a great example for what the Nell Nelson site could strive for: full of content, with lots of contributors and some intense (albeit initially confusing) data visualization.

But with so much more content, I had a difficult time taking it all in. The tabs and layout of each page could be more consistent; for example, the welcome page (which displays a different picture at each load - neat!) displays the navigation bar at the top, whereas the Letters page has a floating nav bar to the right. Also, the link titled 'People, Places, and Networks' on the nav bar leads to a page called 'Visualizing the Worlds of Mary Mitford.' And the page info ('maintained by'/'last modified' info) appears as both a header on one page and a footer on another. These small issues make the user second-guess their orientation at each page load.


The content, however, is definitely there. I liked the 'document location' page and the links out to the respective library/university. The staff page is neat, too, having dropdown boxes for credentials.

**Comment by ebeshero** [comment]
Good work with the preliminary discussion of projects, everyone! I'm closing this conversation to move us over to the Project Proposal stage, but you can always find your comments here by looking for the Closed Issues on our GitHub.
