### ISSUE TITLE
Regex Exercise

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#121]
Can anyone help get me started with this homework because I do not understand it at all.

**Comment by RJP43** [comment]
Hi @mmm202 did you read through the [tutorial](http://newtfire.org/dh/explainRegex.html)?

Begin by right clicking on the link for the text file and downloading it. You will want to open that file(in oXygen) and an additional text file (I prefer using notepad). Once you have both of these open you are going to navigate to the find and replace window in oXygen. This screen shot shows you how to get there:
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/12698553/837f44c4-c76d-11e5-9134-5e3620ac886f.jpg)
And this screen shot shows you what your find and replace window should look like: 
![screenshot_2](https://cloud.githubusercontent.com/assets/8645521/12698555/8b1d3de4-c76d-11e5-9cff-a63643ad88c7.jpg)
The first step in the homework is to find the reserved characters that may (or may not) appear in the text file (ie. `&`, `<`, `>`) so that as an XML file you won't get an angry oXygen. You can find the step by step on how to set up the find and replace window along with the steps in finding those reserved characters under the "Autotagging: Up-conversion from Plain Text" titled section of the Tutorial. It will be really useful to keep this tutorial up while you work on this exercise.  

I hope this was helpful in pointing you to the exacts of where you need to begin... if you can specify in detail what you are struggling with maybe I can assist you further

**Comment by RJP43** [comment]
@mmm202 what you are doing is trying to format the text file so that you can turn it into a well-formed XML document

**Comment by ebeshero** [comment]
@mmm202 Do you have the file you're working with open in oXygen? If you're having trouble with that, make sure that 1) You have downloaded and saved the file of the Blithedale Romance from the homework page. (On a PC computer, you'd right-click on my link to download a file to your computer--or do whatever you did to download and save files when you took the test on Friday). You need to save the file on your local computer and then go to open it in oXygen.
* Open up oXygen, and then go to File--> Open to open the Bithedale text.  
* Look carefully at Becca's screen capture that she posted. Make sure you have the Regular Expression box marked in the Find & Replace window! And make sure you carefully read [our tutorial](http://newtfire.org/dh/explainRegex.html)  and the [Regex Quick Start tutorial](http://www.regular-expressions.info/quickstart.html). Keep those open for ready reference in your web browser, so you can look up things. But the homework assignment should guide you step by step with what you need to do. Please tell us where you are stuck if we haven't figured it out here!

**Comment by mmm202** [comment]
[novel.txt](https://github.com/ebeshero/DHClass-Hub/files/111087/novel.txt)
This is what I have done so far and everything is wrong and I just don't understand any of it .

1.found \n{3,} and replaced with \n\n
2.found \n replaced with </p>\n<p>
3. found ^<p>(\s.+[XVI\.])p> replaced with <title>\1 title>

**Comment by ebeshero** [comment]
@mmm202 HI Megan--I'm taking a look now, and walking through your steps...give me a few minutes.

**Comment by ebeshero** [comment]
@mmm202 Hi Megan-- First of all, I went and edited your comment to put those tick marks around your code, because I couldn't see your full regex patterns! (Remember, whenever you type angle brackets into this message board, you need to put the ` mark around them (not an apostrophe, but the little character at the top left of your keyboard) so they will render literally! 

Looks like you're stuck on step 3, but you're **really** close! Your pattern matches on a line that starts with a `<p>`, but then I see a problem. Look at a line in the file that has a chapter title on it (I'm looking at `<p>I. OLD MOODIE</p>` In the file you posted, (and in my file too), I don't see a white space before the Roman numeral, do you? Where does that white space actually appear? 

Also, think about the number of Roman numerals you may need to match on. I wouldn't include the literal period inside the character set, since you really will only have one period, but you will sometimes have more than one Roman numeral (like in Chapter XIII, and XIV, etc.)  Does this help?

**Comment by mmm202** [comment]
This helped a lot thank you! I don't know why I had such a hard time getting a grasp on this but I ended up getting a green square when I saved it as an XML file.

**Comment by ebeshero** [comment]
@mmm202 Yay! I'm glad you worked it out! The first regex assignment is always tough--and it's important you figured it out, and you made good use of this board, too! :+1:

**Comment by mjb232** [comment]
Note that there is a difference between /n and \n. I spent a whole hour being super confused about why xml would select my blank spaces.

**Comment by nlottig94** [comment]
@mjb232 Yes, that is a really common error I had when I first started using Regex.  It was super confusing to me because I was used to using `/` instead of `\`.  It'll get easier to type once you've been working with Regex for a while!

**Comment by laurenmcguigan** [comment]
Hi everyone. I have started working on marking up the novel and this is what my document looks like so far:
Find: \&

Replace: &amp;


Find: \>

Replace: &gt;


Find:  \<

Replace: &lt;


Am I doing this right so far? When I typed each of these in, it said "string not found" is  that how it was for everyone else? And is this how you want us to write it down in our document?

thank you!

**Comment by nlottig94** [comment]
@laurenmcguigan so you're in the right track because you know what you want to find: `&, <, and >`.  However, you're saying that you're replacing them with the exact same characters.  This isn't right.  Remember when we were doing XML and you had to use certain character codes when trying to output the ampersand, less than, and greater than signs?  We want to use these in our replace window instead of only the real characters themselves.
Does this help?


Sent from my iPhone

**Comment by laurenmcguigan** [comment]
Hi Nicole!

I have been using those special codes, but github doesn’t understand them and changes &lt; to <
does that make sense?



On Jan 31, 2016, at 9:08 PM, Nicole Lottig <notifications@github.com<mailto:notifications@github.com>> wrote:

@laurenmcguigan so you're in the right track because you know what you want to find: `&, <, and >`. However, you're saying that you're replacing them with the exact same characters. This isn't right. Remember when we were doing XML and you had to use certain character codes when trying to output the ampersand, less than, and greater than signs? We want to use these in our replace window instead of only the real characters themselves.
Does this help?


Sent from my iPhone

**Comment by nlottig94** [comment]
@laurenmcguigan Yes, that does make sense!  Remind me tomorrow before class to show you the ticks we use in GitHub to display code.  So if that's what you're doing, you're on the right track!!  Keep on chugging!  When completing the assignment I also got No string found for those characters :)

**Comment by laurenmcguigan** [comment]
@nlottig94 thank you for your help!
