### ISSUE TITLE
Regex 2/5

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#131]
Is there an easier way to identify all the speakers with out having to search for each one individually and can someone point out what a speech is in a play.

**Comment by RJP43** [comment]
Hi @mmm202 [this is an example of our XML for Regex 3](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/Regular-Expressions/Exercise3/pygmalion-tagged.xml) and hopefully answers your question about what a speech is in a play.

**Comment by spadafour** [comment]
What exactly are you grabbing with your search right now? If you post your regex, I'll be happy to offer some suggestions.

**Comment by laurenmcguigan** [comment]
is there a way to find all capital letters?

**Comment by brookestewart** [comment]
Yes! You can use what we call a character set, as mentioned in the [Regex Intro](http://newtfire.org/dh/explainRegex.html). For example, `[A-Z]` will find any capital letter, `[a-z]` will find any lower case letter. So, if you wanted to find a capital letter at the beginning of a line, what character would you put in front of `[A-Z]`?

**Comment by mjb232** [comment]
@RJP43 So I was working with the example you gave us (thanks for that by the way, its been super helpful) but I found an abnormality in the text/code: look at line 2040 (or just search for the word "quickness") of the example you provided us. In the original text this chunk of dialogue is supposed to be spoken by both Higgins and Pickering at the same time, and looks like this:

  HIGGINS.    You know, she has the most extraordinary quickness of ear:
  PICKERING.  I assure you, my dear Mrs. Higgins, that girl
  HIGGINS.    just like a parrot. I've tried her with every
  PICKERING.  is a genius. She can play the piano quite beautifully
  HIGGINS.    possible sort of sound that a human being can make--
            etc.

However in the code this is represented as all speech by Higgins. This is tricky because their lines being spoken at the same time, so how would you represent this in code? We have the stage directions indicating what is happening, but should we break Higgins and Pickering's gibberish apart to make it look more like the text? Or leave it as it is, because technically it is all one "speech" since its being spoken all at once.

**Comment by mjb232** [comment]
Also make sure that everyone runs through their steps again from scratch! Little mistakes, such as a random space or lack there of, can mess your whole code up and hurt your grade! It only takes a few minutes to run through it again.

**Comment by laurenmcguigan** [comment]
thank you @brookestewart :)

**Comment by ebeshero** [comment]
@mjb232 Hi Matt! If I'm understanding you right, you're suggesting our example XML code might be flawed at this point in the text...Let me go have a look...

**Comment by ebeshero** [comment]
@mjb232 ...Aha! I see that you're right...I feel sure I've got a copy where I've properly marked those as separate speakers...so let me go hunt for it! Yes, you can and should mark those as separate speakers, though it may be a bit tricky! Did you figure out how? (One thing you could do is make it one speech with multiple speakers inside, and it would be okay to go back and work on that with a little manual code because it's just a few lines.) This a good moment to comment on WHY we use Regex in the first place: We typically use it for tasks that are really, really big, like marking up a whole novel or voyage log or play...where we don't want to do all the structural markup of paragraphs or speeches or lines by hand. It's perfectly reasonable to leave some small things imperfectly marked that we go back and fix up by hand...and this could be one of them. (That said, I bet you've found a way to mark Higgins and Pickering as separate speakers here...as yes, you certainly should!)

**Comment by mjb232** [comment]
@mjb232 Already ahead of you! Should I post the Regex I used?

**Comment by ebeshero** [comment]
:+1: Go for it!

**Comment by mjb232** [comment]
so first I just wrapped the whole thing in a <speech> tag then marked the speakers using:
`(\n\s\s[PICKERING|HIGGINS]+\.)`

**Comment by ebeshero** [comment]
Ha! That's some neat usage of a character set!

**Comment by mjb232** [comment]
:D
