### ISSUE TITLE
xpath exercise 2

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#144]
![capture](https://cloud.githubusercontent.com/assets/16582103/13023320/dbb0ac08-d1b5-11e5-99ca-f842f7b19098.JPG)

I am having trouble finding attributes and I'm not sure exactly what I am doing wrong. Can I have an example of searching for an attribute? In the picture I have the xpath written and the error that pops up when I search for it.

**Comment by ebeshero** [comment]
@mmm202 Great question--reaching an attribute is surprisingly tricky, depending on how you want to reach it. In the picture it looks like you're missing the opening square bracket to put the attribute inside a predicate. It looks to me like you are searching for all the `<geo>` elements that have an `@select="lon"` and for that you just need the opening square bracket to signal you're putting the attribute in a predicate.
But! You were asking how to find JUST the attribute, not the element holding it. For that you want to take a path step over to the attribute axis. If that's what you seek--just to land on the attribute, take your path step like this:
`//whateverElement/@attribute`

The problem is when you want to specify just the attribute with a certain value. Try writing your expression like this and see what result you get: `//whateverElement/@attribute="setValue"'` 
When I do this, my oXygen result tells me "true" or "false", but doesn't actually turn up a list of multiple locations where this attribute sits. The true / false result is what we call a "Boolean" response--when we phrase an XPath expression with an `=` at the end, we're asking IF such a condition exists. (That kind of expression is going to be useful to us when we write Schematron rules to test for a condition.) 
So, let's say we just want to reach *only* the attributes *that have a setValue*: We're going to need a path step over to the attribute axis *and* a predicate expression with the dot, phrased like this:
`//whateverElement/@attribute[.="setValue"]`

Does that help? I think I should probably add this detail to our Follow the XPath tutorial, do thanks for posting the question!

**Comment by mjb232** [comment]
so for number four on the xpath 2 exercise am I trying to locate both <geo> types ("lat" an "lon") by searching for sibling elements, or for attributes? I'm kind of confused on how either searches would look as well.

**Comment by laurenmcguigan** [comment]
@mjb232 

`//body/div/div[1]//p/geo/@select[.="lat"]`
 this is what I got for number one, but I can't figure out number 2: find the paragraphs that contain the lat attribute. I've tried putting parentheses around the p element and around everything from p to the end and nothing had worked.

**Comment by mjb232** [comment]
ok so right now your xpath is searching specifically for the the attribute `@select[.="lat"]`, when you want to find every `<p>` that contains any instances of `@select[.="lat"]`.  What you need isn't parenthesis, but brackets. Brackets that follow an element mean "I want to select all the elements that contain whatever is in the brackets."

**Comment by laurenmcguigan** [comment]
@mjb232 i did this:
`//body/div/div[1]//p[/geo/@select[.="lat"]]` and it came back with no results. I'm confused as to what I am doing wrong.

**Comment by laurenmcguigan** [comment]
do I need to add something like count or name or parent? or just brackets?

**Comment by ebeshero** [comment]
@mjb232 Hi Matt: You're stuck on number 4, and the hint I will give you is that you can set predicates side by side next to each other on the same element... Does that help?

**Comment by mjb232** [comment]
no, you don't need to add anything like that. You have all the pieces, you simply need to get them in the right order. Ok, so this much of your xpath is good: `//body/div/div[1]//p` but the second half is what needs fixing. in the brackets after your `//p` do you need those `/` between geo and `@selcet`? So far when I've described an element with an attribute I've done it like this:
 `//element [@attribute="value"]`

**Comment by mjb232** [comment]
@ebeshero I think so, let me hack at it. Also, am I leading Lauren on the right path? I don't want to say anything wrong or misleading

**Comment by ebeshero** [comment]
@laurenmcguigan @mjb232 Lauren: basically, listen to Matt here! He's got this.

**Comment by ebeshero** [comment]
@mmm202 @laurenmcguigan @mjb232 @jlm323 Hold tight--I'm going to return your XPath Ex 1 in the next hour...maybe that'll help with some of this predicate-writing stuff.

**Comment by mjb232** [comment]
@ebeshero  I think I figured out number four! It was a lot easier than I thought it was haha.

**Comment by ebeshero** [comment]
Yay!

**Comment by mjb232** [comment]
@ebeshero  what does the `[.="value"]` do? I see Lauren's using it and it worked fine for the first part of the homework, but not the second. Why is this?

**Comment by ebeshero** [comment]
@mjb232 It's my own fault--@mmm202 posted a question about how to find an attribute, and I took her literally and showed her exactly how. What I think she (and Lauren) really meant was, how to find an element *that contains* an attribute... and for that you want the simpler predicates we've been writing here.

But to answer your question, this construction basically makes a predicate when you put an attribute at the end of your XPath steps--as the last place you land. So imagine you step down element to element to element and then step *over* to the attribute axis, like so...
`//element//element//element/@attribute`
...and you want to pull up ONLY the attribute that has a particular value--and ONLY the attribute, mind you, not the element that holds it, THEN you'd use this predicate with the dot (referencing the self::axis) as you wrote it like so:
`//element//element//element/@attribute[.="specialValue"]`
It's the way you have to write this if you want to land ONLY on an attribute when it has a set value. We don't often want to do that...but sometimes (later on in the course) we'll want to grab the attribute values specifically and we will need to step over to the attribute axis to grab them, instead of finding the element that hosts a particular attribute.

**Comment by mjb232** [comment]
@ebeshero I see, that makes sense.

**Comment by laurenmcguigan** [comment]
Thank you!! @mjb232 @ebeshero
