### ISSUE TITLE
Discussion: Wendell Piez and LMNL

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#146]
In preparation for a special visit by Wendell Piez to our class on Wed. 2/17, please read and discuss his article [Hierarchies within Range Space](http://www.balisage.net/Proceedings/vol13/html/Piez01/BalisageVol13-Piez01.html) . Here are some reading and discussion prompts to get us started:

* What is LMNL and how does it relate to XML? Can the two work together?
* What do you understand of the OHCO model, recalling that this stands for Ordered Hierarchy of Content Objects: How has this idea been important to computer modelling of texts?
* What's so important about overlap, and why might we want to represent and study it?

@mjb232 @mmm202 @laurenmcguigan @jlm323 @brookestewart @spadafour @nlottig94 @RJP43

**Comment by brookestewart** [comment]
This article brought to my attention that the OHCO model assumes that every document has a single hierarchy, and attempts to force those that don't to fit the mold. While we are working inside that model, we also start to become limited in our thinking in the sense that we're always trying to enforce the hierarchy. While hierarchy is useful to organize documents, it also hinders our thinking when we assume that there is only the possibility of one hierarchy. The LMNL model allows for a broader range of study, as it allows for one, none, or overlapping hierarchies.This can open up more research regarding hierarchies and how/why they need to be enforced, if at all.

**Comment by ebeshero** [comment]
Thanks for getting us started, Brooke! I'm herewith inviting @wendellpiez to join our discussion, as he's visiting and speaking in our class this Wednesday!

**Comment by RJP43** [comment]
Every time I read this piece I am reminded of how I markup text physically. I mean with a highlighter and pen. The highlighter can drag across segments of words grouping sections creating a hierarchy of grouped highlighted sections each contained by the start and end of where I highlight (kinda like XML markup). Once and a while I will star the start of a concept I am reading or circle a keyword again reminding me of XML (place-markers and self-closing tags). Then when I group multiple sections with margin writing and underlining segments of text and making connections between what is underlined in one highlighted portion with text outside of the highlighted portion I realize that my way of physical markup is more closely related to the LMNL model. Sometimes I wonder if how we use the XML OHCO model putting everything in boxes (highlighted segments) are we taking away the possibility of other interpretations (what we would write in the margins to take what one part of the text is saying and have the box left open to relate or even disassociate with a future or previous part of the text). LMNL explores these other interpretations by using the organization of markup, but never implicitly requiring the closing of any of the hierarchical boxes. Texts have layers OHCO markup sees those layers as definitions of boundaries, whereas LMNL seems to allow those layers to have flux.

**Comment by djbpitt** [comment]
We humans can't avoid noticing that XML objects to overlap and LMNL doesn't because it's hard for us not to think of XML and LMNL each as a stream of text with tags inserted into it. We know that that's wrong, at least for XML; what we see on the screen in an XML editor is a *serialization of a tree*, but because we're dumb humans, the serialization tyrannizes our imagination and we see *overlapping tags*, even though XML is a tree and trees don't have tags. Perhaps a characterization of the issue that's rooted in the essential tree-ness of XML would be based not only what it is (it isn't overlap, since overlap isn't compatible with the tree perspective), but on what it isn't: text isn't a rooted directed acyclic graph, that is, it isn't a tree.

Meanwhile, because the LMNL data model is one of ranges over a continuous data stream, rather than trees, the visualization with tags in LMNL is closer to the range-model reality than the visualization with tags in XML is to the tree-model reality.

What neither XML nor LMNL models well, though, is discontinuity, and we seem to be as blind to discontinuity today as we were to overlap on the day that the OHCO model was born. Oh, sure, we know that there is discontinuity, but we view it as untidy exceptions, and not as essential to the inherent nature of text—as essential as overlap. Associations among discontinuous substrings of the full text can be encoded (with pointers, for example) in either XML syntax or LMNL syntax (that is, in either the XML or LMNL serializations with tags inserted into the stream of text), but neither abstract model (tree, range) and neither syntax (both tag-oriented) represents a discontinuous entity the same way as a continuous one. In that sense, both assume that contiguity is somehow intrinsic to being an entity in the model, and both have to handle discontinuity with patching and special pleading. This doesn't mean that either was designed badly; what it means is that the range model, like the tree model, also fails to capture part of the essence of what text is.

OHCO seized our imagination a long time ago because we believed at first that text really *was* an ordered hierarchy of content objects. We grew disenchanted with this (mis)understanding when we came to recognize that overlap is part of what text is, and of the way we need to model text, and that it's a common property of texts, and not just an exception that arises in edge cases. Reconceptualizing text within a range model instead of a tree model solves the overlap problem conceptually (although it raises computational challenges for which we'll want to seek answers from computer scientists; can we interrogate and navigate ranges as efficiently as we can navigate trees?).

The point of the preceding is that when we came to recognize that text isn't fundamentally a tree, that is, an OHCO, that doesn't mean that it *is* a bunch of ranges. What text *is* needs to recognize that discontinuity, like overlap, is not an exception.

There may be a useful analogy to be drawn from the history of phonological theory. There are certain phonological properties of language that are inherently discontinuous; common examples include inflection by interfixing into tri-consonantal roots in Semitic languages, vowel harmony in Turkic languages, and stress valences in Proto-Balto-Slavic (and in some models of modern Baltic and Slavic languages). A general framework for representing these types of discontinuity is called *autosegmental phonology*, and it's a framework for erecting multiple trees of *association lines* over a common segmental *tier*. I don't have an analogous textual data model to offer (yet?), but I think it's worth recognizing that an alternative to trees that can deal with overlap is only part of the answer, and we need an alternative that can also deal with discontinuity.

**Comment by nlottig94** [comment]
Overlap is important because of the way that authors wanted the texts to be read. If we only use OHCO markup, we may not be getting the entire meaning that the authors wanted us to have. However, if we would be able to mark up the overlapping text as just that, we may be able to see and understand the texts in different ways (or the way that the author actually intended). We might be able graph and represent these trends as well!

**Comment by laurenmcguigan** [comment]
So what I am getting from this is that LMNL is a different form of XML, where hierarchies do not need to be nested, and their is possibility for overlap. I can see in some instances where this is helpful, but for someone who started doing markup first with XML and can be a little confusing to understand the system. I guess with any new idea added to the world of coding, there has to be adjustments made for new and better ideas!

**Comment by laurenmcguigan** [comment]
Also, I suppose that XML and LMNL could work together if you use XML for things that can be nested and LMNL for things that can not be; such as one of the exercises we did at the beginning of the semester where we needed self-closing tags. What I am wondering is if they can work together like html and xml work together, or would they not be compatible? For instance, if you flip between different types of code (XML and LMNL), would that make things less "human readable" for the next person who tries to update your markup.

**Comment by jlm323** [comment]
I can also see that LMNL allows for overlapping hierarchies while this is not possible in XML. I'm not sure that it would work together because XML deals more with nested hierarchies/elements while LMNL deals with ranges with no hierarchical relation to each other. LMNL would therefore be better suited to texts with overlap, like Piez points out in Frankenstein, and XML would probably be better suited to texted that are more ordered and nested in their elements.

**Comment by ebeshero** [comment]
@jlm323 and @laurenmcguigan Wendell has been showing me how LMNL and XML work together today after dinner. He has written a "pipeline" of processing code that can parse LMNL and generate an XML interpretation of LMNL's range space--and that is how he is able to plot the bubble graphs and publish a rendering of LMNL via HTML and SVG over the web...He'll tell us more about it tomorrow!

Welcome, @djbpitt ! (That is David Birnbaum of our sibling DH course in Pittsburgh and he taught me and Greg most of the coding we know...He's talking about linguistics and phonology here to suggest an alternative way of thinking about language--In phonology, studying sound patterns, people mark discontinuities in sound in diagrams that serve as a model--and it doesn't have to be either unified or overlapping, but can be marking divergence and shifts. I found this introduction with some pictures: http://www-01.sil.org/linguistics/GlossaryOfLinguisticTerms/WhatIsPhonology.htm
XML is often used in linguistics projects, marking phonemes rather than (just) words and sentences--and such markup can get pretty complicated and interesting...but something like phonological discontinuity might be a *caesura* (or a long pause in the middle of a line of poetry, and one that disrupts the anticipated metrical beat). Marking that is interesting--do we set the pause point apart, wrap a puctuation mark in a self-closing tag? Of mark it in LMNL with the stop of one range and the start of another? (But how do we convey the pause, or break in the flow?)

**Comment by djbpitt** [comment]
Caesura is one of the focal topics of http://www.balisage.net/Proceedings/vol15/html/Birnbaum01/BalisageVol15-Birnbaum01.html because it involves overlapping hierarchies: foot boundaries and word boundaries. One of the interesting parts of that (well, for me) is that we often don't tag for word boundaries when we mark up poetry, letting white space stand in as pseudo-markup.

**Comment by wendellpiez** [comment]
Hi,

Just a few followup notes to all the interesting things that have been said
so far.

It was suggested that a difference between the LMNL approach and XML
approach is in their suitability for different kinds of texts, and this is
true, but I think it's also a matter of the purpose for which you are
describing the text - using code, aka the markup - and whether that purpose
requires or rewards you for doing it one way or the other (i.e. permitting
overlap, or taking advantage of the power of the tree).

Basically any text can show an overlap problem if you look at it the right
way, in other words. However, this may not always be a very useful thing to
do, and it can be expensive - it's like choosing to live in the woods,
instead of the city - especially in what are called "opportunity costs".

The structure of verse (where we are looking at metrical structures vs,
say, linguistic structures like words and other grammatical or phonological
units ) is an excellent one for unearthing interesting cases of overlap and
- it helps that this is poetry - it is relatively easy to proceed to see
significance in these ebbs and flows. Narrative structures (nested
narratives etc.) such as what is going on in the Frankenstein demo provide
another set of examples. But there are many many other possibilities -
really the possibilities are boundless - and, what is more (in my
experience) the most interesting examples are also the most peculiar, i.e.
the most distinctive, asking for their own special treatment - which leads
to its own set of issues.

One thing I would love to see in LMNL markup would be rhetorical tropes
such as metaphor, metonymy and all our other friends, but perhaps precisely
that sort of description should be done one poem at a time. (And then the
concern becomes something we didn't talk about, namely what happens when
the markup starts getting really "thick".)

Yet there is also much more work to do in learning to exploit the markup we
already have and many more demos to build. Thanks again for letting me show
you this one!

Regards,
Wendell

On Wed, Feb 17, 2016 at 8:23 AM, djbpitt <notifications@github.com> wrote:

> Caesura is one of the focal topics of
> http://www.balisage.net/Proceedings/vol15/html/Birnbaum01/BalisageVol15-Birnbaum01.html
> because it involves overlapping hierarchies: foot boundaries and word
> boundaries. One of the interesting parts of that (well, for me) is that we
> often don't tag for word boundaries when we mark up poetry, letting white
> space stand in as pseudo-markup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ebeshero/DHClass-Hub/issues/146#issuecomment-185203117>
> .
>



-- 
Wendell Piez | http://www.wendellpiez.com
XML | XSLT | electronic publishing
Eat Your Vegetables
_____oo_________o_o___ooooo____ooooooo_^
