### ISSUE TITLE
I need help on the next assignment!

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/DHClass-Hub#15]
I pushed two files to Troubleshooting (https://github.com/ebeshero/DHClass-Hub/tree/master/Troubleshooting).  I have an error in my schema and cannot figure out how to fix it!  If anyone could figure it out, I would really appreciate it!  Thanks!

**Comment by ghbondar** [comment]
In your schema, the splats associated with the attribute values in quotes seems to be causing your error.

**Comment by ghbondar** [comment]
I think the issue is one of having more than one of your attribute values: why would you want to have more than one of the same attribute value, or one indicated either/or with an or-pipe | ?
This one works: Question Mark: ( ? ): Zero or one
These ones cause an error:
Plus sign: ( + ): One or more
Asterisk or “splat”: ( * ): Zero or more

**Comment by nlottig94** [comment]
Thank you!!  I have it back up to par now!!
