### ISSUE TITLE
XSLT 3

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#156]
Getting this error message "When 'standalone' or 'doctype-system' is specified, the document must be well-formed; but this document contains more than one top-level element", not sure what is wrong?

```` 
<xsl:template match="/">
    <xsl:apply-templates select="$dickinsonColl//body"/>
        
    </xsl:template>
    
    <xsl:template match="title">
        <h2>
            <xsl:apply-templates/>
        </h2>
    </xsl:template>
    <xsl:template match="lg">
        <p>
            <xsl:apply-templates/>
        </p>
    </xsl:template>
    
    <xsl:template match="l">
        
        <xsl:apply-templates/>
        <br/>
    </xsl:template>

 
    
</xsl:stylesheet>`

**Comment by ghbondar** [comment]
@mmm202 In case you're still stuck, I see that your first tag is an end-tag... this is _a_ problem, though not necessarily THE problem....

**Comment by mmm202** [comment]
I didn't notice all my code didn't go in 
`    
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    <xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>
    
    <xsl:template match="/">
    <xsl:apply-templates select="$dickinsonColl//body"/>  
    </xsl:template>
    
    <xsl:template match="title">
        <h2>
            <xsl:apply-templates/>
        </h2>
    </xsl:template>
    
    <xsl:template match="lg">
        <p>
            <xsl:apply-templates/>
        </p>
    </xsl:template>
    
    <xsl:template match="l">
        <xsl:apply-templates/>
        <br/>
    </xsl:template>
    
</xsl:stylesheet>`

**Comment by jlm323** [comment]
I'm not getting any sort of output and I put this (without the weird spacing because GitHub removes the xsl variable otherwise):
` <
xsl:variable name="dickinsonColl" select=
"//collection('Dickinson')"/>

            <xsl:template match="dickinsonColl">
                <xsl:apply-templates select="$dickinsonColl//body"/>
            </xsl:template>`

I saved the Dickinson directory and I have my XSLT stylesheet saved in the same area but it isn't working.
![dickinsonstylessproblem](https://cloud.githubusercontent.com/assets/16583817/13441701/a0f8826a-dfc6-11e5-8195-41731764d26b.png)

I have also tried just `"collection('Dickinson')"` and `"..//collection('Dickinson')"` but those don't work either.

**Comment by RJP43** [comment]
@jlm323 anytime you refer to the collection you need to include the `$`

**Comment by ebeshero** [comment]
@jlm323 I'm away from the assignment, but remembering it, and your detailed notes and image of your file directory helps here. Here's what I think you should do:
1) You've saved your xslt file to sit in the directory *above* the XSLT file. That's **good**. Don't move anything. But to refer to it, treat it like it's on the child axis in an XPath expression. You are *not* looking down multiple directories, but just taking one tiny immediate step down. So in your definition of the `<xsl:variable>` you do **not** need (or want) the leading slashes to define the variable. In fact you can just give the name of the collection with nothing in front of it.

**Comment by laurenmcguigan** [comment]
how do I copy the Dickinson directory?

**Comment by laurenmcguigan** [comment]
I think I just moved it to my computer and took it out of the class folder. I hit make a copy and it didnt do anything

**Comment by laurenmcguigan** [comment]
nevermind I got it

**Comment by ebeshero** [comment]
@laurenmcguigan First, just pull it in to your local computer's DHClass-Hub, but then, just make a copy of the directory somewhere outside your GitHub--to a directory where you typically do your homework. You don't want to delete the directory in GitHub, because if you push changes in, you'll delete it for everyone else!

To copy a file directory on a Mac, can you click on the directory and see if there is a "copy" option? @spadafour how do you do this?

**Comment by ebeshero** [comment]
Good--glad you got it!

**Comment by mmm202** [comment]
"When 'standalone' or 'doctype-system' is specified, the document must be well-formed; but this document contains more than one top-level element"

still don't know what this error message means......

**Comment by ebeshero** [comment]
@mmm202 Check at the top or bottom of your document--is there a rogue element sitting out of place trying to be a sibling of the root element? I take it this is happening in your XSLT?
If that's not it, try pushing your file in to the Troubleshooting directory and we'll take a look...

**Comment by jlm323** [comment]
I got that error too but then I added `$dickinsonColl` to my template matches in front of what I was trying to match. Like this: `"$dickinsonColl//lg"`. It made the error go away although I'm not sure if that's correct.

I'm still not getting any output though.

**Comment by mmm202** [comment]
i pushed my file to troubleshooting

**Comment by laurenmcguigan** [comment]
I am having the same problem as @mmm202 I can't create an output because there is no xml selected in oxygen. It won't even let me click the output button.

**Comment by laurenmcguigan** [comment]
i put the kublakhan XML in the input as a place holder, but when I try to do an output it says "F content is not allowed in prolog"

**Comment by ebeshero** [comment]
@mmm202 @laurenmcguigan @jlm323 I'm going to take a look at Megan's file first. In the mean time, why don't you two (Lauren and Jessica) push your files into Troubleshooting too...

**Comment by ghbondar** [comment]
Not that it should matter, but you might try using a Dickinson poem in the xml-window.

**Comment by ebeshero** [comment]
@mmm202 @laurenmcguigan @jlm323 I've just figured out the problem in your file, Megan! And I fixed it and posted it for you in Troubleshooting here: https://github.com/ebeshero/DHClass-Hub/blob/master/Troubleshooting/Mills_XSLT3_correbb.xsl

Jessica, I'll look at yours now, but have a look at Megan's file and see if that's the same problem you were having?

**Comment by ebeshero** [comment]
And @mmm202 I'm sorry we didn't catch this yesterday when you first posted! I just edited your initial question--we couldn't see the entire code block, so @ghbondar thought you were starting your XSLT code with an end-tag! That was not the case, but I had to look in the edit view of your message to see it. To make sure your full block of code shows on our issues forum, put four tick marks in a row in the line above your code, and do the same in the line below your code.

**Comment by jlm323** [comment]
I added the HTML elements and it works now! Thank you!

**Comment by ebeshero** [comment]
@jlm323 In your case, it's BOTH the HTML elements, AND that you really don't need to be using the `$dickinsonColl` variable anywhere but in the first xsl:apply-templates line. That basically says, start applying template rules from within this specific context...and all the OTHER template rules you write will be running JUST within that set context.

**Comment by ebeshero** [comment]
@jlm323 @laurenmcguigan @mmm202 Here's my repaired version of your code, Jessica!
https://github.com/ebeshero/DHClass-Hub/blob/master/Troubleshooting/milewski_xsltEx3_correbb.xsl

**Comment by mmm202** [comment]
I think i got most of it figured out now just have to fix a few things Thank you!!

**Comment by ebeshero** [comment]
@mmm202 Huzzah! :+1:

**Comment by ebeshero** [comment]
And @jlm323 huzzah! :+1:

**Comment by laurenmcguigan** [comment]
@ebeshero can you look at mine? After looking at Jessica's it doesn't seem like anything is wrong, but I'm still not getting an output..

**Comment by laurenmcguigan** [comment]
@ebeshero I even tried creating a new file and just copying your corrections to her file and placing it in mine and it is giving me the same error.

**Comment by laurenmcguigan** [comment]
@mmm202 @jlm323  can you guys take a look at mine and see if anything is wrong?

**Comment by ebeshero** [comment]
@laurenmcguigan I'm taking a look now....

**Comment by ebeshero** [comment]
@laurenmcguigan It's working fine for me! Your use of the html `<ul>` element is not right, though! (But you are definitely, definitely getting output). I like how you numbered the ul's but that's not the element you want there. ul sets up an unordered list, but is not the list items themselves...Here's a thought: your @n attributes aren't going to show in the output html because they're attribute values--they're information if we look under the hood at your code, but not visible. Think about if you want the line numbers to show, maybe wrap them in a span or something that that you can style with CSS? (I'd maybe want to make them smaller than the text, and consider whether you want the numbers to sit at the start or the end of the line.

That's just some fun styling stuff to think about, since your XSLT does produce output! But why aren't you getting output? I wonder what's going wrong?

**Comment by ebeshero** [comment]
@laurenmcguigan Since we know the problem isn't your code, I'm going to take a guess that you've saved your XSLT in the wrong place in relation to the Dickinson collection. Look at where you are saving your XSLT. Is it being saved in the directory immediately *above* the Dickinson collection?

**Comment by mjb232** [comment]
Can I have a hint at how I should replace my `<rdg>`? Replacing the element itself is simple, but how do I give it an attribute that carries the same value as `@var`?

**Comment by ebeshero** [comment]
@mjb232 Hint: AVTs are useful! Remember the `<span>` and `@class` we worked with in XSLT 2? Might be helpful here...

**Comment by mjb232** [comment]
Am I on the right track with this? 
`<xsl:template match="rdg">
        <span class="{SOMETHING}"> <span>`

**Comment by mjb232** [comment]
wait i lied dont tell me! I'm really close to figuring it out!

**Comment by mjb232** [comment]
Ok, I lied again. Im stuck with this:
`<span class="{//@wit}">`
Ive managed to select the right values but I don't know how to filter it so that only one var value shows up, and that its the right one for the line.

**Comment by ebeshero** [comment]
@mjb232 The Dickinson team output all the variants, so they'd sit side by side, and color-coded them...(Later on they wrote JavaScript so that you could click a button and see only the variants form one particular edition. The variants were still all there in the code, but if you have them wrapped in spans with @class attributes you can grab them with CSS and style them as you wish.

**Comment by mjb232** [comment]
So my code is good then? They just filtered them through CSS?

**Comment by mjb232** [comment]
Also I was working with @laurenmcguigan and for the love of me I couldn't figure out what was wrong with it. Its not her code so it has to be a file placement issue, but she showed me a picture of her file explorer and everything checks out. Maybe its a Mac issue?

**Comment by ebeshero** [comment]
You can filter and style those variants with CSS, yes...I bet it's a file positioning issue with @laurenmcguigan, and make sure it's sorted out in class if you haven't figured it out already!
