### ISSUE TITLE
Discussion of Stephen Ramsay's Readings and Visit

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#165]
Stephen Ramsay and I have been corresponding to plan his visit to our class, and we agreed this would be a great moment to discuss the big picture of, in his words, **"what we're doing and why"**. To that end (between now and class on Wed. morning 3/23), please respond (at least twice) and discuss with each other one or both of the following prompts, after you've read the following:

* ["DH and CS"](http://stephenramsay.us/2013/04/30/dh-and-cs/)
and either
* ["The Hermeneutics of Screwing Around; or What You Do with a MIllion Books"](https://web.archive.org/web/20140604085234/http://www.playingwithhistory.com/wp-content/uploads/2010/04/hermeneutics.pdf), or
* ["In Praise of Pattern"](http://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1056&amp;context=englishfacpubs)

Here are some discussion prompts to get us started:
* What's "humanistic" about the coding we do? Is it the use of tech and code on humanities materials (like our Decameron project)?  Is it just that we're working on [The Decameron](https://github.com/jlm323/DecameronProject) (and [Emily Dickinson](http://dickinson16.newtfire.org/), and [City Slave Girls](http://nelson.newtfire.org)) that makes our work "humanities" research?  Or, as Steve asks us to consider, "is there actually something about this work that is already humanistic even when we're in the weeds of coding?" 

* Is there something distinctive about the way we work with computing methods that makes this distinctively *humanities* work, and not computer science? 
* As you are working on and thinking about your projects and reading Steve's work, what do you notice about the way you're thinking about "doing research" with coding? What do you think of Steve's perspective on "screwmeneutics" (for example) and the way we explore humanities with tech tools to find patterns? 

I've located Steve on GitHub, so I'm herewith inviting him to the discussion! I'm also inviting our friend and previous guest speaker Wendell Piez (if he likes) to come back and join us here! Please begin whenever you are ready. David, feel free to invite your students to join in, as well, with the understanding that my students are officially assigned these readings for Wednesday!
@sramsay 
@wendellpiez
@djbpitt 
@RJP43 @nlottig94 @brookestewart @spadafour @mmm202 @andrewntz23 @alexkrongel @jlm323 @mjb232 @laurenmcguigan @ghbondar

**Comment by brookestewart** [comment]
I'm not sure if this is distinctively humanities work and not computer science, but I had never thought of the way we do research as "screwing around" before. "The Hermeneutics of Screwing Around; or What You Do with a MIllion Books" opened my eyes to the different ways that we actually conduct research. I had always thought: "here is my question, how do I find the answer?" when in reality, browsing is really just stumbling around, looking for who knows what. Browsing and letting yourself wander and find new things can lead to new places and research questions that you may have never thought of. So, "screwing around" is not always a bad thing. Although there are concerns where organization is concerned, I think it's interesting how looking for nothing in particular can take you to another world entirely.

**Comment by mmm202** [comment]
I can say that DH and CS are similar in many ways but also different in other ways. From having a Web design class and this class in the same semester you can see everything that is similar like the html and tags and so on. You also see how advanced our coding can be versus a regular web page because we are working more with code to discover something with the text that we work with. I don't think there are ways to distinctively separate DH and CS  because of the all the similarities. One man difference I can point out is with my CS class I am working more on presentation then the actual text within the site which is the opposite for DH.

**Comment by laurenmcguigan** [comment]
It is interesting that we talk about this because at the beginning of the semester, I remember saying, "I'm not very good with computers." When in fact, most of what we do, specifically in our projects, is deciding what we pull out of the text, and what we can understand from the things we pull out. While there is a certain amount of "computer science" we must learn in order pull things from the text and create a website from it, the actual purpose of it is linked to the humanities. As a person who is pursuing a degree in the humanities I know that most of what we do is subjective where as coding is more of an exact science. However, I agree with Mr. Ramsay that it is important that those of us who consider ourselves part of the humanities find ways to further our understanding through "computer science".  For example, Dr. B mentioned that some refer to XML as distant reading. It is this kind of "science" that allows us to understand our texts at a deeper level, and find things that the human eye would be unable to find on it's own.

**Comment by jlm323** [comment]
I do think that what we're doing in class is humanistic because we are diving into these texts, whether it is the Decameron or Emily Dickinson, and looking for interesting things to markup and tag to answer research questions. And in a way, I do think we browse a lot, like the Hermeneutics of Screwing Around article discusses. I think this is especially true for the Decameron because we started out not knowing exactly what to look for but now that we've begun reading and marking this text up, we're finding out interesting topics to continue to research. I would not have known about how the narrative of the Decameron was actually set up or what places were mentioned if I had not looked through it and marked the place names, so I think digital humanities is especially useful for looking for patterns quickly and efficiently and outputting graphics and webpages to share this information with others.

**Comment by nlottig94** [comment]
I believe there is something specifically _humanistic_ in what we do in DH, as opposed to computer science.  For example, we analyze a text in terms of what we specifically want to see, such as places, people, or even types of words.  I feel as though in computer science, it's more mathematical, and the goals are different.  The computing methods we use (as in the ways that elements are set up, etc.) are similar, but because _what_ we are looking for in a text is more, for lack of a better word, _human_, it makes our methods distinct.

**Comment by RJP43** [comment]
After reading the three articles here and listening to @sramsay speak tonight on "The Art of Digital Humanities" I really began thinking about the methodology that has shifted in the Nelson project these past three years as many different students have come and gone in the collaboration on the project. At tonight's talk @sramsay spoke about reinstating the art aspect of humanities into digital humanities, which has become increasingly "scientized". My mind immediately went to the Nelson project and the big shift made last semester to move from the more subjective markup done in the previous year to our currently _more_ objective markup. I have to say _more_ objective here and not an all inclusive deeming that it _is_ objective because in a sense imprinting any sort of hierarchical structure on the text that didn't necessarily have that in the first place is the kind of subjectivity I began to question after hearing @wendellpiez speak on XML's handling of overlapping hierarchies. So with that understanding that there is always some kind of subjectivity that becomes inevitable in marking up a text @ramsay has made me consider perhaps the other past objective markup wasn't necessarily poor practice of DH and more of a a focus on the "H" of the DH; whereas, the concern of the project then was less on what is quantitative and instead more on what was human. That past system's focus was on interpretation and and perhaps as @spadafour and I momentarily bounced  around last semester (when trying to figure out where to go next with Nelson) there might be more to see in the very humanistic ways that the old markup was implemented pending on the constraints and understandings of the text by the different coders. I think certainly the facts are important and that first and foremost I want the focus of the Nelson project to be a representation of Nelson's work including data visualizations that highlight her points of contrast with other more well known muckrakers; however, I can imagine future DH work consisting of studying a more abstract or even "artistic" outlook on the way the Nelson text gets browsed reader to reader and (more specifically what I already have data regarding) coder to coder.

**Comment by laurenmcguigan** [comment]
@RJP43 It is interesting what you say about subjective vs objective in your work with the Nelson project. I guess the question is, even in a computer based system, it is still almost impossible not to be subjective. But I suppose that is because we are humans and not computers, which is where the digital humanities is distinctive from computer processing. The humanities is in fact HUMAN.

**Comment by sramsay** [comment]
Wow.  These are thought-provoking responses to hard questions, and I can't tell you how much I'm looking forward to furthering this discussion with all of you this morning!

**Comment by mmm202** [comment]
@laurenmcguigan I agree with you that digital humanities is Human and that is why it can't really be objective. I love your reasoning behind this also that we are humans not computers.
