### ISSUE TITLE
SVG 3

### ISSUE THREAD

**Issue by mmm202** [ebeshero/DHClass-Hub#168]
Don't understand the ```format-date($yourDateVariable, '[?]')``` I don't  know where I am supposed to put it and what variable to use.

**Comment by ebeshero** [comment]
@mmm202 That's something the assignment asks you to look up, either in the Micharl Kay book or by following the web link to the list of different values you can use inside the square brackets. You need to find the one format that will convert the month and day into the number of days into the 365-day year this is (so February 2 turns into day 33 of 365).  **Very important**: make sure you use square brackets around the letter value you choose here.

Also, we used format-date() once before in the course, in [XPath Ex 4](http://newtfire.org/dh/XpathExercise4.html). It is used with special square brackets, sometimes in series, to convert dates from one format into another, and can be really handy for the date arithmetic we need to do here.

**Comment by ebeshero** [comment]
@mmm202 You will need to define two variables that use format-date(): one for the earliest date of a Haydon letter, and one for the latest date of a Haydon letter. If you choose the correct format, you get a value in days, that you then add to the year position of the earliest and latest Haydon letters.

**Comment by mmm202** [comment]
I just keep getting errors and I don't understand it

**Comment by brookestewart** [comment]
`err:XPTY0004 checking function parameter 1 in call format-date(untyped-value-check[xs:date, $minHaydon], "[d]"): Type mismatch: the actual type of parameter 1 does not match the type declared in the signature of function: format-date($value as xs:date?, $picture as xs:string) xs:string. Required type: xs:date, got xs:string. [at line 18, column 42, source: String]` 
I get this error on this line: `declare variable $minDay := format-date($minHaydon, '[d]');` 
I've tried different arrangements with and without format-date(), but nothing seems to work. Does anyone see what's wrong with it?

**Comment by ebeshero** [comment]
@brookestewart Let's take a look at your `$minHaydon` variable: Is it in the form of yyyy-mm-dd? It needs to be that full value of the date for it to work in the `format-date()` function.

**Comment by brookestewart** [comment]
This is what I have for `$minHaydon`: `declare variable $minHaydon := min($HaydonDates);` I thought it was already in yyyy-mm-dd form. Do I need to to format it to be yyyy-mm-dd first?

**Comment by nlottig94** [comment]
@brookestewart try to use `let $minHaydon := min($HaydonDates)` inside your curly braces where you're returning whatever you're returning....just try it and tell me what it does :)

**Comment by brookestewart** [comment]
@nlottig94 I think it worked! It's giving me output at least. Let me try to plot the line and I'll let you know if it works. My computer keeps freezing, so it might take a bit.

**Comment by nlottig94** [comment]
@brookestewart YAY!!!!!  Let me know!  I think I remember @RJP43 and I having an issue with that too!

**Comment by mmm202** [comment]
I keep getting this error ````err:XPTY0004 'xs:string(1821)' can not be an operand for - [at line 24, column 41, source: String]```` for this line ````declare variable $minYears := ($minDate - $minYear)*365;```` it worked before but now its not

**Comment by ebeshero** [comment]
@mmm202 and others: You're likely to see this error when your variable is read as a string of text instead of a number. In order to subtract one year from another year, you need for both values to be read as integers. Which one of your variables is likely outputting that 1821 in the error message? Check and we if you need to wrap it in xs:integer() to convert it into a number.

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart It shouldn't matter whether you declare that variable for the `min()` of the Haydon dates. The global or local variables would work the same! I wonder what the difference was? If it worked, good! My guess is you could have declared $minHaydon twice (because this two-stage XQuery gets pretty complicated and you've been declaring a lot of variables), and maybe in one you tokenized and extracted the year. If that happened, the *last* time you name a variable supersedes and overrules the earlier times you declared it.

**Comment by ebeshero** [comment]
@brookestewart If you are still having trouble, let's take a look at your definition of `$HaydonDates`. If it ends in `string()` that could be the problem...

**Comment by brookestewart** [comment]
@ebeshero it does right now. I tried to tokenize it the same way the first one was, but it was giving me problems then too

**Comment by ebeshero** [comment]
@brookestewart sorry for the time lag! I keep looking in after grading a paper...but if you haven't done this already, try removing `string()` so that the `@when` is not converted into text. And you don't want to calculate your `min()` date from a tokenized year only, since you want the full version of the earliest date (yyyy-mm-dd). That way, when you go to plot the exact date on your timeline you can find out what number day it is out of 365 so you can add that value to the year.

You need one variable that holds the full date of the first Haydon letter, and another separate variable just to hold its year. You need the year to figure out where it sits in relation to the earliest point on your master timeline (which we plotted in years only). Then we do "date arithmetic" with format-date() to figure out how far into that year we plot our starting letter to Haydon. We need to add that day value to the year.

**Comment by brookestewart** [comment]
@ebeshero okay, that makes sense. Thanks! My laptop is pretty much totally frozen right now so I'm on mobile. I'll try this when I get my laptop working

**Comment by laurenmcguigan** [comment]
So I have everything working and it is almost finished except when I try to do the end of the line by adding format-date the max date is being output as October 1st 1823, which is like the 210th day of the year, but instead of adding 210 it's only adding 74? I did the exact same thing for the minimum date and it is adding the correct about (44) for February 13th, but it is not adding correctly for October 1st. I saved it in exist if someone could take a look at it and see if there is something I'm not seeing?

**Comment by laurenmcguigan** [comment]
I think it is a problem with my $newEnd variable, but I don't know what because it looks the same as my $newStart variable...

**Comment by laurenmcguigan** [comment]
Never mind I figured it out lol

**Comment by ebeshero** [comment]
@laurenmcguigan good! But what was causing the problem? (I didn't peek at your XQuery...)

**Comment by brookestewart** [comment]
I thought I had it figured out, but I'm getting an error that says `"err:FORG0001 cannot construct xs:double from '1821-10-31' [source: String]"` but it's not firing on a specific line. I'm not sure what's wrong.

**Comment by jlm323** [comment]
I'm getting the same error. I got rid of the `string()` after the `@when` for the `$HaydonDates` global variable. I don't know what the issue is..

**Comment by ebeshero** [comment]
@jlm323 @brookestewart I should have looked into eXist last night--I misled you both! Sorry!! Okay--now that I'm actually looking into eXist this morning, I can see what's happening, and it's an exercise in converting data types!
* To access all of the full dates of all the Haydon letters in the first place, I see that I *do* use `string()` after the `@when` attribute. (That wasn't the issue, then.)
* Now, those dates are in a string format, which is okay, because we do two things with them:
--In one variable, we `tokenize()` and grab only the years. And to use those years in calculations later, we have to convert them to integers with `xs:integer()`.
--later on in your XQuery (and I think this is what both of you need), you have to convert the string value of the Haydon letter dates you need into `xs:date` in order for the format-date() function to work. So here is the variable I wrote:
````
declare variable $HaydonStartDays := xs:integer(format-date(xs:date($HaydonStartDate), '[d]'));
````
I did that comparatively late, but you might make a variable early on in the process, when you calculate your minimum start date for Haydon, to ensure that the `yyyy-mm-dd` format is read as a date.

Again, I'm sorry I didn't catch this last night--I wasn't looking at eXist then and working from foggy memory!
