### ISSUE TITLE
Undergraduate DH Conference!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#17]
There's [an undergraduate Digital Humanities conference](http://unrh.org/), sponsored by a group of students, to be hosted at Davidson College in North Carolina, November 6-8. Read about it here: http://unrh.org/ The organizers are trying to make it as affordable as possible for students to participate: there's no fee for housing, food, or registration. We'd just need to find a way to cover travel to Davidson College, and we think we can pull together some campus and university resources to try to go!

**Are any of you potentially interested in going and presenting from our projects?** We're asking about an extension on the deadline for this, since we're generating project proposals this weekend, and the proposals to the conference are due on Sunday 9/20.  If they're willing to give us a couple of days extension, we can probably submit something based on your write-ups this weekend, and based on a show of interest here. 

If you are interested in being part of a presentation team from Pitt-Greensburg, please indicate your interest by responding here!

**Comment by RJP43** [comment]
@spadafour post your formalized research question here and we can further discuss within the next day if you would like to be included in the proposal. Even if you don't get around to formalizing your question and expressing the kind of visualization you want to use by tomorrow I have correspondence with the conference people and they seem to be willing to work with submissions and additions to submissions made prior to Sept. 25th. I am going to add my proposal to the sandbox so you and anyone else interested in the Nelson project or in submitting their own proposal can reference it.

**Comment by RJP43** [comment]
@nlottig94 and @brookestewart the two of you and anyone else that shows interest within the next day should consider submitting an application and proposal outlining the purpose of the research and development you wish to do on the Emily Dickinson's Fascicle 16: Eleven Poems Project. @ebeshero and/or I would be happy to help you quickly write up the necessary 2-3 page proposal so that you also can attend the conference. Since the project is already under development and you both have clear ideas and a direction you wish to take the growth of this project you meet the requirements of what the conference is looking for students to present... please let us know if you are interested and even if only one of you is you can still submit! At the very least check out the link above and feel free to reference my proposal (will be in the sandbox sometime this evening).

**Comment by RJP43** [comment]
I was just informed this morning by the people holding the conference that they received so many promising proposals that they will not be able to review any proposals coming in after the submission date (last night 9/20). For the people that stated interest in the Nell Nelson Project if you refer to my proposal in the Sandbox you can see I mentioned some of @KariWomack and @spadafour ideas in regard to adjusting the web aesthetics, adding the chapter/article texts, and data analysis of the voice elements vs issues raised as well as some of the other directions we can take in growing this project.  I am hoping that if the proposal gets accepted I will be able to write to the conference people (since we have been tweeting and emailing anyway) and ask if my co-editors can join in presenting the work we will have done by the time of the conference. If those mentioned or anyone else who decides to work within the Nelson team could please shoot me email if you are interested. You would be attending this conference not just on behalf of Nell Nelson, but as a representative of UPG Digital Humanities and the entire emerging undergraduate scholarship of DH :) I'm going to close out this issue and we can discuss this more in class today/this week or over email once we find out if the proposal is approved (10/1).
