### ISSUE TITLE
Using $pos in Xquery

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#171]
Hey everyone ( @laurenmcguigan @spadafour @mjb232 @mmm202 @nlottig94 @brookestewart )

````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
declare variable $genderColl := collection('/db/Nelson/ChicagoTimes_XML_gender/');
declare variable $genderFile := $genderColl/*;
let $fileDates := $genderColl//tei:teiHeader//tei:fileDesc//tei:title//tei:date/@when/string()
let $fileNum := $genderFile//tei:teiHeader//tei:fileDesc//tei:title/@corresp/substring-after(.,'CT')
let $countFiles := count($genderFile)
let $peeps := $genderFile//tei:said/@who/substring-after(.,"#")
let $distinctPeeps := distinct-values($peeps)
let $dPeepArray:=
        for  $dpeep in $distinctPeeps
        let $countPeep := count($peeps[.= $dpeep])
        order by $countPeep
        return $dpeep
for $dp at $pos in $dPeepArray
return ($dp, $pos)
````
Okay so about ten minutes after class @ebeshero and I figured this out and now we can use the `$pos` in the plotting of *a sorted array* of x-values. 

@ebeshero will get on here a little later (maybe after some sleep) and explain this further

**Comment by ebeshero** [comment]
Everybody: Here's what I was working towards at the end of class today. The issue was this:
* We wanted to plot a graph based on the **distinct-values** of people's names in a collection of files.
* For each name we wanted to plot a bar, based on **the number of times that person appeared in the collection.** 
* We wanted to use the syntax with `$pos` that I showed you in class, so it would assign **a position number (an integer)** to each name in our "for loop" :
````
for $dpeep at $pos in $distinctpeeps
````
* And naturally, we wanted a way to *organize* the list of values in the array: We needed a way to output them in order from lowest to highest (or highest to lowest), and we needed a way to *put these in a order, in an `order` statement* so we could then make the `$pos` be from a sorted order. 

This is tricky to write and I probably should have planned ahead that I was going to do this before class(!) but I worked it out with Becca in 10 minutes after class, and asked her to post her code here. Let's walk through what's going on in--and these should be just the relevant parts of her XQuery that we need:
````
xquery version "3.0";
declare default element namespace "http://www.w3.org/2000/svg"; 
declare namespace tei="http://www.tei-c.org/ns/1.0"; 
declare variable $genderColl := collection('/db/Nelson/ChicagoTimes_XML_gender/');
declare variable $genderFile := $genderColl/*;
let $peeps := $genderFile//tei:said/@who/substring-after(.,"#")
let $distinctPeeps := distinct-values($peeps)
let $dPeepArray:=
        for  $dpeep in $distinctPeeps
        let $countPeep := count($peeps[.= $dpeep])
        order by $countPeep
        return $dpeep
for $dp at $pos in $dPeepArray
return ($dp, $pos)
````
Here's what's happening: 
Becca reaches into her `$genderFile` collection, grabs all of the stuff that identifies people in the Nelson project: (Apparently these are sitting in the `@who` attributes on the tei:said element and she's grabbing the substring-after() the hashtag (#).) She takes distinct-values() to make a list of $distinctPeeps, but it's in *no particular order* and we want these to be plotted *in order based on how many times the person appears.* 

To sort the array, we made **a new variable named `$dPeepArray`, and we made it hold its own FLWOR** so that it processes each name on the list and maps it back on the XML tree to get a count:
````
 let $countPeep := count($peeps[.= $dpeep])
````
That gave us a count of how many times each person appears in the collection. We then used that count in an **order** statement and returned the list of $dpeeps in sort order: **to be held inside its own variable**:
````
let $dPeepArray:=
        for  $dpeep in $distinctPeeps
        let $countPeep := count($peeps[.= $dpeep])
        order by $countPeep
        return $dpeep
````
Now, $dPeepArray is a variable that holds a sorted list! 
To make sure it's sorted properly, we first output a pair of results, and held them together inside a set of parentheses, which is really all XQuery needs to return **just one thing**. Try this:
````
let $dPeepArray:=
        for  $dpeep in $distinctPeeps
        let $countPeep := count($peeps[.= $dpeep])
        order by $countPeep
        return ($dpeep, $countPeep)
return $dPeepArray
````
The results come back:
````
unidentified
1
messenger
6
benefactor
14
employer
37
workingGirl
38
````
"Yay!" we said. This new variable is perfect! We have a list of people being output *in the order of how many times they appear* from lowest to highest.

Now, if we want values to use in an X and Y axis to plot a graph, we can use our new variable, $dPeepArray: It is the sorted list of distinct-values. We break it into component parts, and **now** the $pos variable has meaning in the sort order. We can use it to help us space each member of the our freshly sorted list across the X axis:
````
for $dp at $pos in $dPeepArray
return ($dp, $pos)
````
This outputs each name with its number in the sort order. Now, we are *also* going to need plot the count, and you might think you already have that variable ready to go, but if you try to use the $countPeep that's inside the FLOWR defining $dPeepArray, **it's not available** in the outer FLOWR! That's annoying, but it makes sense in a way, because you are now inside *another "for loop" entirely--in your *sorted array*. We simply create a new variable now to hold those counts for each value of $dp in the $dPeepArray. Try this:
````
let $dPeepArray:=
        for  $dpeep in $distinctPeeps
        let $countPeep := count($peeps[.= $dpeep])
        order by $countPeep
        return ($dpeep, $countPeep)
:for $dp at $pos in $dPeepArray
let $countdp := count($peeps[.= $dp])
return ($pos, $dp, $countdp)
````
Now we just output, bound together, **the position number**, **the name**, and **the count**. You could replot this in SVG elements so you can use those values: `$pos` to space across the X axis, the `$countdp` to plot the height of a rectangle or on a bar, and the name in a line of text. 

Hope this is helpful to you as you're working on your graphs!
