### ISSUE TITLE
Javascript 1 HW

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#177]
Hey @ebeshero , I think I'm close with getting Javascript 1 done, but I don't know where I've gone wrong. I uploaded my .html and .js files into the dropbox; can you take a look and let me know what's not working and why?

I think it has to do with how I am attempting to grab p elements with specific id's within my if/else function.

**Comment by spadafour** [comment]
@ebeshero judging by the flow of dropbox updates I'm getting, you're working through it now. I think I see where you're brain's at: adding the variables in for document.getElementByID("toggle2") makes sense (also adding in quotations makes sense too).

A big question I have: making the text go away is one thing, but what is it called to bring it back? inline? block?

**Comment by ebeshero** [comment]
Hi @spadafour! Yes, I think I debugged your code--and I got a little help from the console log in my web browser. (In Chrome, it's called Developer Tools and it opens a little panel that shows you what is happening live as you click on things--if a JavaScript function is firing, or not finding something it needs, etc.)

Two things:
* Think of your JavaScript as a narrative or a performance, scripted by events that you plot out. It's a screen writing experience! But that means that every event needs to be tied in to a function that's firing. In order that's going to be:
1) what happens on "DOMContentLoaded"....Fire function init!
2) function init() fires your alert--good. But then nothing happens when we click on your buttons--and that's because you signalled that buttons had to be clicked *outside* of any function--so...function init(), our initalizer, needs to trigger what's going to happen next. You need to move your button-clicking stuff *inside* that function init() because currently it doesn't have a context in a function. 

3) Once you click those buttons and trigger the next function, you're working with function show_hide1() and show_hide(2). You've got those if () ... else statements scripted out right--good. You're best off with your != "none" to start off  since your display is on, but it's not clear what *kind* of display it is: is it block or inline? You're covering all options if you just say the display is **not equal to none**--which indicates the the paragraph is showing. If it's showing then you set it so the display **is equal to none**. And then you set an else statement to cover the **other** possibility: if you click that button and the display **is** equal to none, then set the display to show! You can make it show with one of the following three options:
* display = "block"
* display = "inline"
* display != "none" (if you can't make up your mind!) ;-)

**Comment by ebeshero** [comment]
@spadafour And yes, you need to put those Id and TagName values in quotation marks--I know that's not clear from the examples on w3schools, but you want something like:
````
function init() {
    alert ('Did the page load? Yes. Yes it did.');
    var buttons = document.getElementsByTagName("button")
buttons[0].addEventListener('click', show_hide1, false)
}
````

**Comment by spadafour** [comment]
Okay, awesome, I have it working now! Haha! Javascript finally!!!!!!

I had essentially 2 typos:
- It's not getElementByID, it is get ElementById (lowercase d)
- And I had p2.stype, not p2. style

So it's totally working!
Thanks!

**Comment by ebeshero** [comment]
Huzzah! @nlottig94 --I'm looking at your Schematron now...

**Comment by spadafour** [comment]
Okay, now I have the javascript working and my html online, but my server side includes are not working. My permissions are set correctly, and yes, I am checking it online, not locally. Should the ssi be sitting at the top of the body in my html? Is that where the problem is? Thats where I have it. But right now, I don't see anything from my ssi.
