### ISSUE TITLE
Mac issues with GitHub

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#191]
Hi Elisa,

I'm unable to sync my awesome pic of empanadas for two reasons. 1) I'm getting an error message that says I don't have access and 2) I'm getting conflicting files because of syncing issues with multiple Mac temporary files (the DS_store files). I asked Dave about this and he poked around online and apparently you can set the DHClass-Hub somehow not to synch temporary files? Not sure about any of this but it is clear that empanadas are not entering the sandbox.

**Comment by ebeshero** [comment]
Hmm...the DS_store files shouldn't cause us problems, but I will look into it. What concerns me more is that you are having trouble sending the empanadas to the remote DHClass-Hub. Did you try doing a commit and push from the command line terminal per instructions? (Don't be using the desktop client--which might actually be causing problems like what you describe here...)

**Comment by ebeshero** [comment]
@setriplette Also, I see I added you as a collaborator, but the DHClass-Hub tells me you need to accept my invitation on your side. I think you may have an email about that!

**Comment by setriplette** [comment]
I accepted the invitation. It's funny, the button said "view invitation" which didn't indicate to me that I needed to do anything. I think the empanadas are in the sandbox now. I tried to push them by both methods and I'm not sure what worked.
I hate to admit but I'm having trouble understanding the tutorial because there are a lot of words. Is there anywhere I can look for a list of common git terminal commands which might be quicker once I'm a bit familiar with what we're doing? I admit to having little understanding of the terminal and its terminology.

I was definitely having problems reconciling versions of the DS_store file though--I think maybe Lauren uploaded something from a Mac too, which might have caused the issue--a temporary file of same name?

**Comment by setriplette** [comment]
Never mind, there is exactly that list already. I just didn't see it because I got scroll-sick before I got that far down. Could "Common Git Commands" be put on a separate clickable page for lazy people (i.e. me)?

**Comment by nlottig94** [comment]
@ebeshero @setriplette 
I'm sorry to be commenting on your discussion, but I have a cheat sheet that I started using last semester when I started using command line for the first time. Are you guys working with forking and branches?

**Comment by nlottig94** [comment]
@setriplette This is the cheat sheet I made last semester! Note that this is if you're working with forks and branches. Also, the stuff in angle brackets does not actually need angle brackets around it in your command!
![gitshellprocess](https://cloud.githubusercontent.com/assets/14095715/18170217/81ccbc62-702b-11e6-9805-7b13be30ec8e.jpg)
I hope this helps! It definitely helped me a bunch last semester! Have a wonderful semester!

**Comment by mjb232** [comment]
You are a goddess for that haha

Sent from my iPhone

On Sep 1, 2016, at 10:19 AM, Nicole Lottig <notifications@github.com<mailto:notifications@github.com>> wrote:


@setriplette<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fsetriplette&data=01%7c01%7cmjb232%40pitt.edu%7c5459a69f9d3244ef5c3f08d3d272ef32%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=2eG0GvvgreMT86XQVa6ujVwgdkz466rM0v%2belRrzvkc%3d> This is the cheat sheet I made last semester! Note that this is if you're working with forks and branches. Also, the stuff in angle brackets does not actually need angle brackets around it in your command!
[gitshellprocess]<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f14095715%2f18170217%2f81ccbc62-702b-11e6-9805-7b13be30ec8e.jpg&data=01%7c01%7cmjb232%40pitt.edu%7c5459a69f9d3244ef5c3f08d3d272ef32%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=PMZOgW9PQA74sD5eHmGSkZ%2fLRmVN55eAbhIoii6DGs4%3d>
I hope this helps! It definitely helped me a bunch last semester! Have a wonderful semester!

-

**Comment by RJP43** [comment]
Thanks @nlottig94! Also the tutorial has a section that gives a quick reference of common commands: http://newtfire.org/dh/explainGitShell.html#cheatSheet

**Comment by ebeshero** [comment]
@nlottig94 We're not starting out on forks or branches yet--so we could make the quick list even shorter.

**Comment by nlottig94** [comment]
@ebeshero
So,
`git pull`
`git add .`
`git commit -m "..."`
`git push --all -u`
Anything else? :)

**Comment by ebeshero** [comment]
@setriplette A good exercise for each of you, as you are learning GitHub, will be to *make your own* handy checklist working from the tutorial. It's a good way to learn. Eventually, the process will get into your fingers and you won't have to look!

**Comment by setriplette** [comment]
What are you adding when you put `git add .`?

**Comment by RJP43** [comment]
So what @nlottig94  has commented above as the simplified list is a little outdated to our current recommendations. However, the general steps still work the same.  @setriplette to answer your question the `git add .` simply adds any modifications to your working directory to the staging area (the pre-commit area) of your repo. We suggest instead to use `git add -A` because this makes sure not only modifications but deletion and addition of new files are added as well. Now as for the `git push --all -u` this becomes more important when working with branches and forks. The --all means push all changes in all branches and the `-u` command means track those changes to you (so then edits to a branch made by you can be traceable when merged into a forked repo). No saying all that this is all a bit more advanced then we really want the class to focus on at this point. I would suggest as @ebeshero does above ... read over [this section](http://www.newtfire.org/dh/explainGitShell.html#working) of the tutorial again and write out your own quick guide for the basic git commands used in a repo you own or are a direct contributor to and then we will modify it with another git exercise that explores branches and forks.

**Comment by nlottig94** [comment]
Sorry if I made it more confusing :(

**Comment by setriplette** [comment]
I like it Nicole! Thank you!!

**Comment by ebeshero** [comment]
Thanks, @nlottig94 ! It's a good list--and a great example of how to take control of the learning process! What I like is that you hand-wrote your list. We do so much with copy and paste, working fast, but taking a few minutes to write out the steps of a new process by hand can really help to increase your comfort level and make it familiar to you!

**Comment by ebeshero** [comment]
On the matter of those annoying .DS_Store files, I'm going to try this: http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

which supposedly banishes all .DS_Store files from the remote repository, so they don't cause issues when multiple Mac users work together on a repo. I hope this works...

**Comment by ebeshero** [comment]
...And I'm creating a .gitignore file for our repo, with guidance from https://gist.github.com/octocat/9257657

**Comment by ebeshero** [comment]
@setriplette I have now pushed a `.gitignore` file to our repository that should block those pesky local `.DB_Store` files from entering our remote repo. Let's see if this resolves the Mac problem.

**Comment by ebeshero** [comment]
I switched to a Mac this summer, and didn't install the Desktop client at all when I installed Git. I just cloned my repositories inside the terminal, and I configured my GitHub account there, too, in a couple of quick steps.

The key thing to me in working with GitHub is to:
1) Always know **where** to find my files in the Finder and in the Terminal. So I need to save them in a place I can easily see them. 
* In the Finder, I just made myself a "GitHub" directory under "Documents." 
* In the Mac Terminal (command line shell), I can navigate to my directory from my computer's root by typing:
`cd Documents/GitHub/`
cd means "change directories" and here I am *stepping down* into Documents and into GitHub. I usually pause there and take a look down at what I have inside:

* If I need to **clone** a repository, I do so here, because then the new repository will sit as a *child* inside my GitHub directory. I go to the git remote website and get its Download/Clone URL by copying it. 
Then I type `git clone` and paste in the the URL after that. so it looks like this for our DHClass-Hub:
````
git clone https://github.com/ebeshero/DHClass-Hub.git
````
I hit enter, and the repository clones inside the GitHub directory. 

2) I interact with my local directory the way I would any other. I drag files into it using the Finder. I save files into it. And I check in with the remote repository to **pull** new files in. So this is what I do:
I open my Terminal, and I step down into my GitHub directory, and then down into the DHClass-Hub, and check using `ls` that I am where I think I am, so I see the directories I want. 

* To make sure I'm in the right directory, the top level of the DHClass-Hub, I also check to see the directory name at the terminal prompt. Mine looks like this right now, and the key part is "DHClass-Hub":
`gbg-wireless-pittnet-150-212-105-8:DHClass-Hub ebb8$ `

Then to pull in any changes from the remote "mothership" repo, I type:
````
git pull
```` 

3) When I want to share my local files with the remote mothership and my collaborators, I need to **add**, **commit**, and **push** those changes. Here's how I do it:

* I make sure I'm in the DHClass-Hub repo at the top level
* Then I type:
````
git add .
````
The period means *all*-- add *all* new files to be tracked by Git.

* If I type `git status` at this point, I see highlighted the new files I'm going to add! 
* Now, I need to **commit** those changes. I type the commit, and write a message, because Git *always* makes me document my changes when I push to a remote "Mothership" repo:
````
git commit -m "I'm committing a picture of a llama to the DHClass-Hub Sandbox"
````

* Next I push the commit through, with this:
````
git push
````
And gears turn and lines of text whirl on the screen, and my file goes up. I always check on the web repository to see if my commit went through. 

That's how I do it.
