### ISSUE TITLE
Interesting discovery with Relax NG-Compact

### ISSUE THREAD

**Issue by jonhoranic** [ebeshero/DHClass-Hub#199]
This goes out to anyone having the same issues with getting the schema to associate properly if you have elements nested like this: 

````
<example>
    <line> Text </line>
    <line> Text </line>
    <quote> "This space will screw up your schema association" </quote>
    <line> Text </line>
    <line> Text </line>
</example>
````

To explain a bit, think of this example section as a paragraph. You nest all the text inside the `<example>` element and proceed to label the `<line>`s as you go until it is "stopped" by the `<quote>` (this "stop" is the important thing to note) that is marked halfway through before continuing. Reading through it looks normal to us humans but to the computer I seems to assume that the quote is a breakage of some sorts. My first attempts to get the RNGc to go green involved a line similar to this: `example = element example {line+, quote,}` Which I thought would cover everything within because XML was not flipping me the "redErrorMark" that I seem to receive quite often. I then associated the schema and oddly every element labeled <line> after the `<quote>` section was adorned with those scarlet-squiggles. Once hovered over an error reading (heavy paraphrase) "element 'line' is misplaced, expecting 'quote' in it's place." appeared below.

I tinkered around for about 25-30 minutes or so when I came across a solution. The `+` indicates that there is one or more but ALWAYS ONE within the element you are writing for, and the computer reads that until it hits an element that is not the one with the `+` in the sequence, and that is shown with a comma. If the comma acts as a sequence marker, then just continue the sequence chain! `example= element example {line+, quote, line+}`

Doing this makes the computer read "there will be one `line` element and some others `+` until `,` a single `<quote>` element then there will be one `<line>` and some others `+` until `,`..." where before the computer was just reading "there will be one `<line>` element and some others `+` until `,` a single `<quote>` element."

I should state that I have no clue if this is the correct way or just a haphazard work-around but for now I know it worked to solve my issue. Hopefully this helps someone out in the future.

**Comment by ebeshero** [comment]
@jonhoranic I added some additional tic marks to format your code a little more clearly! Thanks for this insight about the use of the comma, which dictates a sequence. Here's another way you might code the rule, so you don't have to repeat the `<line>` element, but make it possible for the `<quote>` to appear anywhere in the sequence of the element contents: Try this:

````
example = element example {(line | quote)+}
````
There are a few different ways to write this, but this code wraps the line and the quote inside a pair of parentheses and uses the "or pipe" to say that the element example MUST contain at least one or more than one of *either* `<line>` *or* `<quote>`. When you associate the schema, it will check each element that is nested inside `<example>` and see whether it is a `<line>` or a `<quote>`, and as long as it finds at least one of either, it will be satisfied. It should also be okay if there is only a `<quote>` *or* only a `<line>`. 

There's an even more flexible way to write that, but it might be *too* generous:

````
example = element example {(line | quote)*}
````

This says, the element example *may* contain zero or more of either `<line>` or `<quote>`. That might be *too* permissive because technically, it might contain neither of them!
