### ISSUE TITLE
Project Proposals: Lope and Graveyard

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#201]
**Title of project: Lope de Vega’s Golden Age**

**Short project scope:** 

I propose that we (or I) develop a corpus of at least six and preferably many more Lope de Vega texts in English and Spanish. I want to use TEI (or TEI-inspired) coding to identify the diction of emotion and see whether it maps to the diction of honor, the law, landscape, or the body. I “feel” that Lope is using the language of emotion in a very deliberate way for the stage, and I want to build an “emotion dictionary” and an “emotion association map” for the corpus we are able to process. For comparison, I’d like us to look at the same set of words in some Lope poems and prose works. I wonder whether Lope is simply an emotionally charged author, or whether there is a deliberate nature to the language he uses for the stage. I would also like to build a website with resources for people who want to take a historical or cultural approach to Lope, with a personography, placeography, a mythography (Lope is all about gods and goddesses) and a map of the places in the works. As far as I can tell, no one has yet done the sort of project I propose.

**For students working in English:**

I have identified three Lope texts we can work on in English translation, including a play, a prose romance, and the dramatic manifesto “The New Art of Comedy.” The mapping and prosopography-oriented tasks should also be English-friendly. The issue with building a huge English corpus is that Lope has only become popular in translation in the last fifty years, and most things are still in copyright.

**For students working in Spanish:**

There are online texts of (almost) everything that is extant as it is all in the public domain. We will have too many options. There is also the possibility of doing our own translations, especially of small selections of text. I even found an inedited play in manuscript images, if anyone wants to learn a little transcription. It’s not Lope’s handwriting, but it’s a guy he knew, so the spirit of Lope is almost-almost in there somewhere.

**Comparable projects:**

There are two DH projects on Golden Age comedia, and both are information/bibliography oriented. Out of the Wings (from Kings College London) is a resource that identifies translations for Spanish works, and collects performance information. The Association for Hispanic Classical Theatre runs a blog that has 24 digitized Lope plays in Spanish and a good bit of information about contemporary performance. We would be adding something new by suggesting a pedagogy-friendly critical approach to Lope, and I think that instructors might potentially use such a website to help them prep survey or Golden Age classes.

http://www.outofthewings.org

http://www.wordpress.comedias.org

**Detailed Background:**

Lope de Vega (1562-1635) was the most innovative and prolific author to write for the Golden Age Spanish stage. Of his approximately 1500 plays, about 300 are extant, and several have been translated into English. Lope is also the author of love poetry, Boccaccian-style novellas, a Heliodoran romance, an epic about Sir Francis Drake, and my personal favorite, an epic about cats. Despite his astounding literary productivity, Lope often had money troubles and supported himself with a number of typically Golden Age odd jobs. Lope was a soldier, a priest, a writer of letters for hire, and an all-around loveable scamp / maddening genius. Lope’s plays still communicate themselves well on the stage today, and Pittsburgh’s Quantum Theatre company just put on a production of Peribañez in translation in summer 2017.

For this project, I want to look at the diction of emotion in Lope de Vega’s literary works. My working thesis is that the Golden Age stage is laboratory for the transfer of emotion; actors use emotionally charged vocabulary in order to transmit feelings to the audience. I have noticed that Lope plays are full of feeling, but I would like to nuance and test my theory by looking at how emotion travels through Lope works more generally. Fortunately, Lope wrote a poem, “The New Art of Comedy,” articulating his own theory of theatre, which urged playwrights to break the rules and give the audience what they wanted: blood, honor, and love. One of the things I want to see in the long term is what specific words Lope plays have in common in order to appeal to the audiences’ baser and finer instincts.

Golden Age theatre is particularly interesting as a counterpoint to Shakespeare studies, as the Spanish legal context is quite different from the English. Actresses have always participated in Golden Age plays, and they were the most famous and highly paid parts of their troupes. Lope had several scandalous affairs with actresses, and he wrote many of his best parts for women. The only restriction actresses faced was that they had to be the wife or daughter of someone employed in the company. Lope himself wouldn’t have counted; playwrights were not part of acting troupes, and Lope wrote for many different companies. 

Critics have traditionally divided Lope’s plays into several categories, some of them familiar to those of you who might have studied Shakespeare. There are histories, honor plays, cape-and-sword plays, mythological plays, and religious plays. You might notice that comedy and tragedy are missing. The Spanish “comedia” combined both into one; Spanish audiences distrusted a happy ending without a dose of bitterness and couldn’t stand a bloodbath without any jokes. This makes going to a Lope play a bit of a weird experience for those of us used to the Anglophone standards. One question I would like to ask is whether the different “genres” use emotion words differently.

**Lope works available in English:**

Fuenteovejuna (Play: “The Sheep Fountain”: messy PDF, will need cleaning by hand. Difficulty: 4/10
http://worldrepublicofletters.com/sites/default/files/excerpts/Fuenteovejuna_excerpt.pdf

El peregrino en su patria / The pilgrim of Castile (long prose romance): Project Gutenberg, ideal situation. Difficulty 1/10
http://www.gutenberg.org/ebooks/49847

Hathi trust translation of the Christopher Columbus play (image only). Difficulty 8/10 (hand transcription)
https://babel.hathitrust.org/cgi/pt?id=mdp.39015033579718;view=1up;seq=8

English translation of “The New Art of Writing Plays”. OCR that’s not too bad. Difficulty 6/10 but mercifully short.

http://www.archive.org/stream/newartofwritingp00vegauoft/newartofwritingp00vegauoft_djvu.txt

**In Spanish:**

PDFs of 24 different plays: www.comedias.org
I would like to look at Fuenteovejuna, Peribañez, El perro del hortelano, La dama boba, and “El arte nuevo de hacer comedias.” Corpus subject to change--I might sub out some of these famous plays for less-known ones for better comparison. 

Just for fun: link to digitized manuscript of inedited “Mujeres y criados”
http://bdh-rd.bne.es/viewer.vm?id=0000131052&page=1

Here is “El castigo sin venganza,” the most violent/objectionable Lope play I can think of. It will be a nice contrast to the lighter fare.

https://es.wikisource.org/wiki/El_castigo_sin_venganza

Many full text Lope works are available from wikisource. These might actually be the best to use, and thery are the most comprehensive.

Their page on Lope, massively rich resource.
https://es.wikisource.org/wiki/Félix_Lope_de_Vega_y_Carpio

An alternate “El arte nuevo de hacer comedias”:
http://www.edu.mec.gub.uy/biblioteca_digital/libros/L/Lope%20de%20Vega%20-%20El%20arte%20nuevo%20de%20hacer%20comedias.pdf

I am definitely coding Lope’s epic poem about cats, La Gatomaquia. The protagonist’s name is Mizifuf (!) and he’s been a very bad kitty.

https://es.wikisource.org/wiki/La_Gatomaquia

Unfortunately (and ironically), the Project Gutenberg English text, the best English one for this project, is one of the few Lope texts for which there is no Spanish text online. There is an image-only PDF that is way too complicated to use at  http://bivaldi.gva.es/es/catalogo_imagenes/grupo.cmd?path=1004547.
This work was much more popular abroad than in Spain (still is) thanks to a 1621 translation. The publication industry is and always has been weird.

**Comment by msb81** [comment]
Since I am Dr. T's Green Scholar this semester, I totally agree with what she is saying. What I really want to do is use the original copy of Amadis and the Montalvo version and see how the language has changed from then to now. I am doing this kind of thing in my green scholar project, but I want to go more in depth. Spanish has changed so much over the years, like any language but I love to see how the language progresses. What I love about Amadis in Translation is that its exploring how the actual manuscript compares to the english version. While comparing those two are the vital, I really am interested into learning how the language changed during this time which you can see in text. Maybe we could look at both sets of text, and see how its changing and compare them. For people who don't speak spanish, they could compare the english translation instead of box Spanish ones. Just a thought!

**Comment by msb81** [comment]
I also have a new project proposal. Amaris has many different translation in various languages. So, what I though we could do is focus on one specific chapter of the book. I can translate the Spanish side of it (what i'm already doing as a green scholar) and then have other people compare the english versions to each other to see what is different about them, whats the same, what has been changed and why, etc. This way its concise but theres still a lot of room to work and develop things. I think it would be an awesome project. Let me know what you think!

**Comment by setriplette** [comment]
To add to Madee's proposal: I thought it might be possible for students to expand the English half of the Digital Amadis project. The Robert Southey text is available in some kind of electronic file, and it could be great to wrangle it into XML and a reading view. I don't really see a reason to translate the Montalvo ourselves, but what we could do is take a chapter and look at it in the Montalvo (we'd choose one that's already done) and in translations by Herberay and Tressan (French) and Munday, Southey, and Place (English). I'd do the French part whether or not I'm on the project team, and display them in some kind of engaging way. I'd also be interested in a personography, a placeography, and background info on Romanticism on the site. Our project as it is now is a little skewed toward the medieval Spanish side because that is what I know. Where students could help me is getting a handle on the poetics of Romanticism and figuring out how to add that into the site in a way that would help readers understand the Southey text better.

**Comment by jonhoranic** [comment]
Alright! In order to fully conceptulize this idea I have going, humor this post by following this bit of a journey I went through. 

**Storytime**: After looking at the [Digital Archive and Pacific Cultures](http://pacific.pitt.edu/) site I had an idea to take other types of obscure records and compile them. However what records to chose from was a bit of a conundrum, and after sitting through some of the examples of Wednesday's class I shot an idea to Pat about gathering obituaries. It did not feel like a specific enough project thesis until I spent some time stewing over it-**by procrastinating on YouTube!** Now, I am going to have to admit this to move forward, but I watch some pretty dark videos on YouTube. Before you get any ideas! Here are some content creators in the gene of "dark matters" that I enjoy watching for deep and sometimes disturbing content: [Rob Dyke](https://www.youtube.com/user/TheRobDyke) and [Cayleigh Elise](https://www.youtube.com/user/cayleighelise/videos) I was browsing through wracking my brain what to do and then, suddenly, in the middle of watching one of Cayleigh's videos she mentioned a grave search tool that allows people to locate specific gravestones near them. A little buzzer went off in my head, why not do something similar but instead of just locating a spot, why not dig deeper like these videos do?

**Actual Proposal**: Sorry for not getting to the point, but here it is: I would like to compile grave maps and obituaries from a local cemetery and with a web interface link them together. Something to the effect of hovering over a spot on a plot map that can be selected that brings up and overview of the person (perhaps a photo if one is on record and some background info of their life and/or bodily metrics) and links to various obituaries and/or gathered mentions/letters/eulogies/works/headlines/etc. (permissions to use these may come into play, I am rather uncertain). What I am most intrigued by is the aspect of the statistical charts, I would like to propose a timeline map of the individuals from conception of the graveyard to a present time on a line graph or calendar map. Perhaps give a brief summery of the history, mention any newsworthy or "paranormal" events on a separate section. The biggest thing I want to suggest for this is to have a cause of death correlation field, display a year and chart out separate cases to find patterns or link activities to a timeline such as outbreaks of a sickness or a rise in a certain condition. Overall, it is a slightly morbid dip into ever to often dismissed look into the realm of the deceased, there is plenty to gain from the stories of their lives and the information they can leave behind unknowingly.

**In Short**: This project sets out to look into the information surrounding graveyards
1. Select and describe local graveyard(s) histories.
2. Create an archive that links grave sites to their respective documentation (obituary/other written passages/events/etc).
3. Note any legends, strange events, and/or occurrences.
4. Provide a reasonable timeline, up to a modern date, showing the progression and additions over time.
5. Create charts or graphs that study the relationships and commonalities of the "cause of death" to visualize periods of epidemics, health changes, averages of certain deaths, etc.

If anyone has any thoughts or suggestions on the proposal I would be interested to see what can be added or tweaked. This is just a work in progress kind of idea so I would love any and all critique!

**Comment by setriplette** [comment]
@jonhoranic There's a graveyard right by campus. Might be a matter of local curiosity. Also, I walk right by Homewood Cemetery in Pittsburgh (I think--it's the one near Frick Park) all the time and it is huge and might be interesting.

**Comment by jonhoranic** [comment]
@setriplette I had no idea there was a graveyard so close! I am not too familiar with with the Greensburg area overall. There are at least four different graveyards in my related areas that I have helped maintain due the various Boy Scout projects (I am sort of smack in the center of Irwin, Adamsburg, Penn, Jeannette and Manor on the map so the scouts I worked with were from all over the place too.) of my youth. The best/worst thing is that I live near the infamous Brush Creek cemetery, where lots of strange tales seem to crop up. Just walk up the driveway, down a dip, crest a hill, make a left, follow path cut for the gas line, and boom! Headstones.

Having grown up with those stories being told around the Scouting campfires and the fact that I live so close, perhaps is the reason why I gravitated toward this idea more and more. I feel like trying to preserve some of those stories is important, but I would like to balance them with the stories of those people buried there because those can be equally or even more captivating. That is just my perspective though, others find it a bit off putting. As long as it can be tasteful and respectful to the deceased I'm sure it can garner some attention.

**Comment by ebeshero** [comment]
@jonhoranic I keep thinking of how the DH class might plan an early web release of this project around Halloween...raising the dead in virtual space? Well, let's see if the idea catches on...

**Comment by ebeshero** [comment]
@jonhoranic Seriously, gathering texts and data for this will be interesting--we'd need to chase down some research leads, perhaps starting with visiting the owners of each cemetery, who will certainly keep labelled maps of their grounds, even if just on paper. Offering to build a digital resource out of a grave yard might be a matter of local community interest, too--might make an interesting new regional resource! 

That reminds me that there's interest in our Digital Studies program from the West Overton Historical Society director--and the sort of thing you're proposing to do here might be a contribution to an historical society. The West Overton director was telling me last weekend that historical societies in the area badly need a better web presence and someone to help them make an attractive digital collection of the piles and piles of local documents they are swimming in.

**Comment by jonhoranic** [comment]
@ebeshero Chalk up another for the "attention gained" board! I seem to be on a roll!

Horn tooting aside, it is easy to see that I am starting to get attached to this (giddily so) and to its possible reach. If this can actually make some sort of deeper impact then I previously conceptualized, I am all ears! Knowing that this project bridges a lot of content within one web source, I would be happy to work with local groups and correspond as much as required.

This whole planing process reminds me of my Eagle Project planing phase, so assuming that if this takes off those involved will hopefully be ready to deal with me (especially when I am giddy over something, my tangents and side-tangents become a bit lengthy)! Though that is all part of the fun I suppose, if a bunch of Scouters can work to replace a bunch of ceiling tiles in a ballroom? Then bunch of  like minded humanities focused people/collegians/coders can work to make compelling resources!

**Comment by RJP43** [comment]
@jonhoranic it is such excitement and giddiness that makes coding fun and sustains project interest!

**Comment by etj27** [comment]
Is there an actual rubric for what qualifies to be project material?  Such as things required, expectations and or guidelines.  I was originally just going to join a group since I don't personally care what I work on and have no special interests. But, hmm.

Perhaps a catalog describing the history of internet memes, going into the real life and online events that inspired their creation, the situations they are used in and aren't supposed to be used in, what emotion they are supposed to represent, as well as tracking the dates they were created (and or became popular, tracking creation might be a problem), creating a sort of legend/timeline for the world of online memes.  The real life events would also be cataloged and noted for their importance.  This would also keep track of the time periods in which memes go in and out of popularity since, just like phone technology, there are new memes that become massively popular it seems per month.  Is this project worthy?  I'm uncertain.  There are other things that can be added onto this.  I haven't thought any of it through but this is just an idea, nothing is final for it.

**Comment by RJP43** [comment]
@etj27 we do have [project guidelines](http://newtfire.org/dh/projectGuide.html) that we have students check near completion of projects.

**Comment by ebeshero** [comment]
@etj27 This is a neat idea--and basically what you need for a project is *some kind of text base*: something readily available in text that your team would up-convert to XML to investigate a research question. So for this project idea to fly, we'd need to access some text base in social media--such as a Twitter feed--and maybe you and your team would want to refine the topic to address a particular group of memes or a collection of feeds that seems especially strong as a meme resource. There have been a couple of Twitter projects in the past few years run by students in our "sibling" class in Oakland--take a look at [The Twitter Parody Project] (http://parody.obdurodon.org/about.html) which tracked Twitter feeds of people who pretended to be celebrities on fake accounts. 

Here's the other Twitter project, [Twitter Neologisms](http://neologisms.obdurodon.org) which ran last year, and randomly selected 20 new words invented on Twitter to track their use. I remember that team had a tough time trying to "scrape" plain text versions of feeds with all the data they wanted, but you may find their methods interesting! They had a programmer on their team who was flexing his Python skills, but there may be other "web scrapers" to try, or old-fashioned copy-paste out of Twitter might work too. 

In our Greensburg course, when Justin Harvey first proposed what became the YouTube Comments project, I think that team originally wanted to work with Twitter, but found YouTube comments easier to scrape. That was a few years ago, though, and the way we access feeds might be different now in both mediums!

**Comment by mjb232** [comment]
@jonhoranic  John, I too have an odd attraction to cemeteries, so I would TOTALLY be down with this. Now, we have to be careful here! Graveyards are massive places, meaning there's massive amounts of data we'd have to work with. We cant bite off more than we can chew. Remember that not only are we looking up plot maps, data on individuals, and history about the graveyard, but we are also creating a website complete with: Interactive map, charts, and timelines. I think this is feasible if we focus on one cemetery of a smaller scale. The information might also be hard to track down, but this could lead to  us working with actual physical texts, which is pretty rad.

**Comment by mjb232** [comment]
So, as for my OWN project, I'm not giving up on my man's William Blake! So, essentially I wanted to take poems from 'songs of innocence and songs of experience,' and correlate the poems with the illustrations presented with each poem. There is, in truth, a site that already deals with the Blake poems, buuuuuuuuuut it focuses on comparisons betwixt the two collections, with the images only used aesthetically. With our project we would actually mark up both poem and image in order to correlate instances from the poems with specific elements within the illustrations. There would also be room for us to compare various illustrations of the same poem to one another, since they weren't all the same. We can also just do a better job at the website design than the already existing site, just saying.

**Comment by jonhoranic** [comment]
@mjb232 I agree. We walk a fine line within the quantity/quality ratio of records.

- Large scale? The records will no doubt be rather accessible, but then we are swamped with just that, not even touching the other aspects
- Small scale? Indeed more manageable amounts of content, but the availability and accuracy of those records comes into question.

It would be best if we (dare I say it) start scouting out reasonable middle sized sites and narrowing down which one to be the project point. No doubt this may just turn into a passion project, but that remains to be seen. Regardless, your concerns are like my own, so if you have any leads (even if you wish to work on another project) I will take anything you got.

**Comment by mjb232** [comment]
Also, if no one was interested in Blake, I had a similar comparison project revolving around Thomas Wyatt and his translations/adaptations of Petrarch's poems. We wouldn't use the original Russian (or we could if someone speaks Russian), but a rigid translation. We'd compare elements of the original and Wyatt's side by side.

**Comment by ebeshero** [comment]
@jonhoranic @mjb232 Out of curiosity, and because you'd need a good *text base* to help facilitate a large- or medium-sized project, I did a little googling to survey cemetery records online, and discovered this potential goldmine: [Interment.net](http://www.interment.net). Take a look! Next week, we'll start teaching you how to work with plain text documents and *up-convert* them into XML using something called *regular expression matching*. As long as there are regular patterns of white spaces, tabs, symbols, etc, you can use those as sort of handle-holds to grab onto and replace with XML angle bracket tags--so that you can transform gigantic files pretty quickly. And if the files are in HTML it's super easy to change the tags at scale. So I think with help from a giant online database of cemetery records, together, maybe, with local records, you could really cover a lot of (cough! cough!) *ground* in a graveyard research project. Much depends on your research question, and it'll really help to survey the materials available to work with, analog and digital!

**Comment by ebeshero** [comment]
@jonhoranic I noticed the records in Interment.net are pretty sketchy, and the site links out to genealogy sites where you search by name. The question is going to be, how best to compile detailed records on specific graveyards, and I think you might really want to check in with a local cemetery director to see what kinds of records are kept...but I haven't done more than 5 minutes of searching here: Maybe you could do some hunting this weekend to see about sources of intel: obituary records, etc? With a team dividing up some streamlined data collection, what *kind* of ground can you cover quickly?

**Comment by jonhoranic** [comment]
@ebeshero Quick visits is something I can do ASAP, with so many nearby I can just swing by potential sites and gather basic contact info (or at least leave a message to contact me back) and work from there. As for those obituary records, I may have to fan out further to check some libraries or local government buildings. Even if they do not have records I would assume they could point me in the right direction. Then it would be a "rinse and repeat" cycle  to see what is available on the surface before jumping in. My first task will be to dabble with online leads, just to see if I can attain contact information or at least some idea of where to start. Overall, I think once I find the right place to start I can start matching content quickly within a spreadsheet format before actually getting to the individual coding. I will see what I can get done over the weekend, I'll will keep posting.

I am under the assumption that I could just open an issue for specifically this project's discussion and update schedule, but I will hold off from doing that until I have a true starting point to go from.

**Comment by ebeshero** [comment]
@jonhoranic Feel fee to start a new issue just on that, since this one is filling up! And we'll close this thread, I think, once we decide which projects we'll run with.

**Comment by JaredKramer40** [comment]
I don't have many ideas for projects but I like the idea of doing something different and modern like the youtube comments or something related to social media but honestly I'm game for anything.

As for my idea, I am very interested in art, specifically Neoclassical art and the artists themselves. I think it would be cool to compile data of some of the more popular artists of the neoclassical period. Maybe a timeline would be appropriate for something like this.  Analyzing different paintings on style and different aspects of how they were created might be a good start.  Even a single artist and all of their paintings based on the different art movements they have contributed to.  I think this would be a cool and new project to work on that I would definitely enjoy.

**Comment by setriplette** [comment]
@jonhoranic Somewhat counter-intuitively, for something like this you want to work with an OLD graveyard that has already interested a civic group, like a historical society. Rather than getting 100% coverage of a single site, you want to find a site for which people will read the coverage and for which you will get information from different eras. There are books that do what you want to do on big cemeteries like Père Lachaise in Paris--what's our local equivalent? Any place where war dead are buried? I know we have some French and Indian war sites around here, but I'm not sure if that yielded a graveyard that got continued use. If I were choosing a graveyard in my hometown, I'd pick the one in Old Salem, next to the colonial part of the village, which has been in use ever since and has probably already been partially mapped the old-fashioned way. What would be the equivalent in this region? When you were a scout, what graveyard did you tell ghost stories about? That would be the one to pick. Also, first contact might be the local historical societies to see if there are any cemeteries that interest them. They are probably interested in genealogy more than the cemetery itself, but they would probably love to help you on your cemetery residents. Also--think about the dimension of race/ethnicity as well as time when you're looking at your cemetery mapping. You will often find African-American or Jewish sections of cemeteries, especially in older cemeteries. There can also be special sections for veterans.

**Comment by jonhoranic** [comment]
@setriplette These are all fair points, many of which I had not considered. The fact that sub categorization would exist in a graveyard completely escaped me. Your comments make me think a little more heavily about the selections at hand. I may end up settling with a section of Brush Creek, since it is both a historical site and its various hill plots are separated by pavement, which in my mind would work as a "section" marker of sorts. It is also the one that has had many stories tied to it, both with physical vandalism and strange reports that make for campfire tales. I believe that Brush Creek it is still connected to the Norwin Historical Society, I do not know if it has since then been merged with any of the larger ones in Westmoreland, so I will see what I can do with that. As for other potential areas I am still going to see what I can find out before Monday. 

Thank you very much for your input!

**Comment by setriplette** [comment]
I am so excited about this graveyard project. It reminds me of a discussion I had with someone who disparaged public history. This is not my academic field but I would totally go on the graveyard tour mapped out by your site (by the way--you should make a printable/downloadable walking tour module).

**Comment by setriplette** [comment]
@mjb232 You mean Italian? I can help with Petrarch in Italian, but the problem I see with this project is that, if done exactly as you suggest, it wouldn't be adding anything new to Petrarch studies / Wyatt studies. I like looking for translation projects that have not already been done by traditional means, and Petrarch is one of the least neglected writers in existence, so it's hard to find the undiscovered country with him. I suppose you could also compare the hundreds of Petrarch translators (incl Wyatt, who changes the poems so much he's really writing something new) of one poem (or a few poems) against each other. You'd learn a lot about the Renaissance and about translation studies by doing that, and maybe about Wyatt, esp if you could compare him to other Renaissance writers who recycled Petrarch (I could give you a list for Spain and France, but there must be more in England than just Wyatt!). The real "find" with a project like this would be to make connections among a network of translator-poets, famous and not famous, through their texts, and compare that to their social networks (who knew who). You could make one of those spaghetti monster graphs and track a famous Petrarch poem all over Europe, as it circulated in translations among coteries.
One of the master's exam questions during my time at Berkeley was what "courts" and "coteries" had to do with Renaissance poetry. As I remember no one had a particularly good answer--it blindsided me and this is what I study. This kind of project would actually show you a real answer. You could also track the movements of poets as they traveled to Italy. Many of the big Petrarch imitators did, either through diplomacy (Wyatt), military service (Garcilaso) or tourism (Du Bellay). I am talking myself into liking this idea. Even though you could look up each individual piece of the project elsewhere, mapping them all would be new.

**Comment by RJP43** [comment]
@jonhoranic saw this scrolling through Facebook
http://m.mentalfloss.com/article.php?id=68990

**Comment by laurenmcguigan** [comment]
@RJP43 This is awesome!

**Comment by jonhoranic** [comment]
@RJP43 Leave it to mental_Floss to deliver even more cool factoids! I am glad you found this, this will be interesting when viewing the possible imagery on the stones.
