### ISSUE TITLE
Relax NG Issue 2

### ISSUE THREAD

**Issue by msb81** [ebeshero/DHClass-Hub#202]
Hey guys! Im just about finished with my relax NG 2. My schema document is green and so is my xml before I put in the schema. When I associate the schema, it underlines the element directions in my xml and says that "directions is not allowed anywhere, expect end tag" but the end tag elements is before it. Can anyone maybe help to figure out this problem? 
 
RNC Document:
````
start = root
root = element root {ingredients}
ingredients = element ingredients {type, text, produce, juice, choppedSeasoning}
juice = element juice {text}
choppedSeasoning = element choppedSeasoning {text}
directions = element directions {text, textureAvocado, prep, season, type, mixGuac, type, taste}
prep = element prep {text}
season = element season {text, type}
mixGuac = element mixGuac {text, type}
taste = element taste {text}
type = attribute type { "fresh" | "pickAvocado" | "salt" | "foldIngredients"}
produce = element produce {text}
textureAvocado = element textureAvocado {text}
end = root
````
XML Document
````
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="bredice_09-14_xml-14.rnc" type="application/relax-ng-compact-syntax"?>
<root>
<ingredients type= "fresh"><produce>Two fresh avocados</produce>
<juice>2 tsp lime juice</juice>
<choppedSeasoning>2 tbsp cilantro (chopped)
1/4 cup red onion (finely chopped)
1/2 jalapeño, including seeds (finely chopped) 
1/4 tsp kosher salt</choppedSeasoning>
</ingredients>
<directions type= "pickAvocado"><textureAvocado>Choose the right avocado. It should feel squishy yet firm (like the palm of your hand), and be a nice dark green color on the outside.</textureAvocado>
<prep>Cut the avocado in half and then remove the pit (carefully!)
Scoop the avocados and place in a medium bowl.</prep>
<season type= "salt">Toss and coat with lime juice.</season>
<mixGuac type= "foldIngredients">Add the salt and using a fork or potato masher, mash until a smooth consistency is achieved.
 Fold in the remaining ingredients and mix well.</mixGuac>
<taste> Taste the guacamole (over and over) and adjust seasoning if necessary</taste></directions>
</root>
````

**Comment by RJP43** [comment]
@msb81 First I want to remind you when you give us large snips of code be sure to include the tic mark (it likely is on the same key as the tilda `~` on your keyboard) before and after the segments of code otherwise we won't be able to see anything with angle brackets. I went ahead and added those in for you so we can see your entire code. 

Okay now for your actual question it is good that your schema is firing that rule because you have not included the `<directions>` element inside of you rule declaration for `<root>`. Notice that your first rule (after start) says `root = element root {ingredients}` well to spell that out you are saying the element root will only have the element ingredients directly inside of it.  Hope that helps!

On another note could anyone in the class or you spot another issue in the `<directions>` rule declaration that may cause an issue if this schema was applied to other recipes. Hint: what are all those commas saying?

**Comment by RJP43** [comment]
@msb81 I am heading into a meeting now but if you would like to meet after I will be in FOB Lounge.

**Comment by msb81** [comment]
What time?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Sep 13, 2016 at 11:31 AM -0400, "Rebecca Parker" <notifications@github.com<mailto:notifications@github.com>> wrote:


@msb81<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fmsb81&data=01%7c01%7cmsb81%40pitt.edu%7c9b3eb98fd0424d83882608d3dbeb1427%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=bkmFUznoUkyyC%2bgY8t7zq5GLrIxnARJZG4mFO83DI9A%3d> I am heading into a meeting now but if you would like to meet after I will be in FOB Lounge.

-

**Comment by RJP43** [comment]
Should be out of this meeting by 1:15... so sometime after that?

**Comment by msb81** [comment]
1:30 okay?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Sep 13, 2016 at 11:36 AM -0400, "Rebecca Parker" <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be out of this meeting by 1:15... so sometime after that?

-

**Comment by RJP43** [comment]
@msb81 Sounds Great!!!!

**Comment by RJP43** [comment]
@msb81 running a little late bit I will be there soon. Sorry!
