### ISSUE TITLE
Project Proposals: More

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#208]

**Comment by laurenmcguigan** [comment]
My Proposal:

 I think it would be interesting to look at YouTube videos and analyze them as they did in the past. In particular, I think it would be cool to look at coming out videos to compare the negative and positive reactions. The only difficulty with this is that we would nee to mark-up all the comments, which would be very time consuming, but I am into it.

Some questions I want to discuss:

1. Are the comments primarily positive or negative?

2. Do the comments come from others struggling with sexuality?

I would like to look at more popular coming out videos, but it might also be interesting to look at less popular ones and see if they differ in positivity/negativity.

These are just some general ideas, but if there are others who are interested in a project like this feel free to add to this proposal.

Things to think about:

- are there other sources we should look at and code to compare to the comments section like they did in the other YouTube project?

-could we possibly look at other social media sites: Facebook/Twitter to look for feedback on these videos?

OR

If you have any ideas as to what other things we could search for in the comments of a coming out video besides positive/negative!

**Comment by jonhoranic** [comment]
@laurenmcguigan I would like to see what conclusions you could draw from this, but I would also like to stress to be careful because some of the things you will find are downright vile, and comment chains on videos can go on and on. Being a YouTube binge watcher, I would like to give you some interesting places to look for some data spreads and the various demographics involved.

- Look at the [update history of YouTube](https://en.wikipedia.org/wiki/History_of_YouTube): There have been at least three major YouTube updates that have had their share of controversy since the prior study. The Google+ comment integration was removed (sort of) and the comment system changed, the release of YouTube Red brought massive Fair Use issues and Ad-Safe updates, and most recently the Community/Backstage update that adds Facebook like posts to channels. 
- Look at some of the highest disliked videos ever. The [2016 Ghostbusters Trailer](https://www.youtube.com/watch?v=w3ugHP-yZXw) and [Call of Duty: Infinate Warfare Trailer](https://www.youtube.com/watch?v=EeF3UTkCoxY). These say a lot about how the internet consumes and reacts to media.
- Look at various channels media content and how drastically the comment sections are. Can internet memes and in jokes be linked to blind fandom or real passion? Does bandwagon-ing fans make positive or negative impacts on people? Does drama related content have a place on the internet? I will make a list of a few big YouTube celebrities from various genres for you and you can browse through and see what you find.
- I wonder how "real" topics are balanced against satirical or fictional content, do viewers really get passionate about real world events or is it more about the site?

**Comment by jonhoranic** [comment]
**If anyone wishes to edit this list to add more suggestions feel free.**

Commentary/Drama/News:
- [Leafyishere](https://www.youtube.com/user/LeafyIsHere) 
- [Scarce](https://www.youtube.com/user/GoScarce/featured)
- [DramaAlert](https://www.youtube.com/user/NewDramaAlert)
-[Phillp DeFranco](https://www.youtube.com/user/sxephil)

Movie and Game Review:
- [RedLetterMedia](https://www.youtube.com/user/RedLetterMedia)
- [YourMovieSucksDOTorg](https://www.youtube.com/user/YourMovieSucksDOTorg)
- [IGN](https://www.youtube.com/channel/UCKy1dAqELo0zrOtPkf0eTMw)
- [GamingSins](https://www.youtube.com/user/GamingSinsdotcom)

Mixed/Educational Content:
- [VlogBrothers](https://www.youtube.com/user/vlogbrothers)
- [CGP Grey](https://www.youtube.com/results?search_query=cgp+grey)
- [ExtraCredits](https://www.youtube.com/user/ExtraCreditz)
