### ISSUE TITLE
Project Teams

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#212]
**Lope de Vega** (Spicy Spanish Theater Networks) Repo: https://github.com/setriplette/golden_age
     @setriplette -- Project Leader
     @msb81 
     @ahunker 

**Graveyard**  Repo: https://github.com/jonhoranic/theGraveyard
      @JaredKramer40 
      @laurenmcguigan 
      @jonhoranic -- Project Leader

**H.P. Lovecraft** (Cthulu Mythos) Repo: https://github.com/PPH3/Eldritch
      @etj27 
      @PPH3 -- Project Leader
      @mjb232 

Evidence of project selections: 
![img_4118](https://cloud.githubusercontent.com/assets/8645521/18637424/501f4e86-7e5a-11e6-9ee2-a1bad6a383bf.JPG)

**Comment by nlottig94** [comment]
First off, thank you all for letting @spadafour and I listen in on your project proposals! All the projects for this semester sound fantastic!!
Second, pertaining to the Graveyard Project (@JaredKramer40 @laurenmcguigan @jonhoranic), I found a cool project that is kind of what I imagined yours to be like, except yours is going to be more personal (and much cooler!!!). [Check it out here!](https://julfaproject.wordpress.com/)
I can't wait to see what these projects turn out like!!

**Comment by jonhoranic** [comment]
@nlottig94 Thank you for sitting in! Secondly, thank you for sharing! I think this helps put a face to our project by acting like a standing model. I commend the ACU for documenting this site, but they also have compiled all those breathtaking images. This is information I never had any knowledge of until now, and it  it brings a sense of wonder to this otherwise unknown place. I love when something can take me past the content and deliver a feeling of discovery. To that effect, its something I wish that our Graveyard Project will instill in its viewers, at least one day.
