### ISSUE TITLE
Trouble viewing my page on Newtfire

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#219]
So I was all excited about making my own web page and I can preview it. I think I've added it to the psc using fetch, but when I go to www.newtfire.org/~set37 it says forbidden. I went back and made sure permissions were right. I can view Becca's newt fire page, but not Dr. B's or mine.

**Comment by RJP43** [comment]
@setriplette This is probably a permissions error... give me a minute to get my computer on and I will go in and see what permissions are set.

**Comment by RJP43** [comment]
@setriplette Okay, so I cannot edit your permissions (@ebeshero and I had the ability to do this last semester so not sure why I can't now). What you need to do is change your permissions on your public-HTML directory. From what I can see your permissions are set so only you can read, write, and execute. 
You will need to go into the permissions for that folder and change it so that the group can read and execute and others can read. In WinSCP, I have the option to set permissions and ownership recursively and I imagine other FTP clients have a similar choice; you will want to check that option if you have it so all files inside this folder will have same permissions set.  Your permissions on your public-HTML folder and all of the files inside of it should then have permissions that match mine:
![permissions](https://cloud.githubusercontent.com/assets/8645521/19016370/c45609c2-87e5-11e6-824d-e0c99f935729.jpg)

**Comment by setriplette** [comment]
Ok! It works now. I had only set the permission my set37 folder, not on the public-html.

**Comment by RJP43** [comment]
Huzzah! Just make sure if you were not able to check the option so set permissions recursively that all files you move into the folder or replace in the folder get the permissions set correctly!

**Comment by RJP43** [comment]
@setriplette btw fantastic start! I am going to leave this issue open for now in case other students run into a similar issue!

**Comment by RJP43** [comment]
@JaredKramer40 @PPH3 @jonhoranic @ahunker @etj27 @msb81 This will be a common issue across the board if you can't see your site once you have successfully moved your files to the PSC. Refer to my response above to set permissions correctly on your main folder and then recursively for all interior folders and files or you will not be able to view your site on the web. Happy coding :)

**Comment by RJP43** [comment]
Correction: 
Owner (you) should be able to read write and execute
Group  (others like us with access to PSC) should be able to read and execute
Others (people accessing site from web) should be able to read and execute
