### ISSUE TITLE
linking photos

### ISSUE THREAD

**Issue by PPH3** [ebeshero/DHClass-Hub#220]
I can't seem to make the photo available. I think this involves the alt=. Not sure what to list here.
I think the src is fine. I just need the title of the photo with .jpg right?

**Comment by setriplette** [comment]
My photo link looked like this. I first moved the actual picture into a folder I named images inside that html folder.
`<img src="images/profile_picture.jpg" alt="profile picture of stacey triplette"/>`

**Comment by RJP43** [comment]
@PPH3 push your files into you personal page repo and I can take a close look at what the issue might be. A couple things to check for if you right click the photo in you file explorer and select properties you should be able to see what the file extension on the image is. It may be .jpg or .JPEG or a variety of others and you will want to be sure you write the file extension in your src attribute so that it is correctly grabbing the image.  The alt attribute is less important that is just text that appears when the image link is broken.  As @setriplette points out above if you have placed your image in a folder you will need to first call on the folder and then the image.

**Comment by PPH3** [comment]
I just put the link in the src. That did the trick. Thanks.

**Comment by RJP43** [comment]
@PPH3 AHHH ok happy you fixed it. 

For future reference or in case others get stuck:
On a Windows platform (possibly on Mac too) the properties of an image can be found with a right click. Once the properties window is open you will want to click on details and scroll till you see the information on the file's name to determine the correct file extension. This is also a handy place to look for image size in case you need to know how many pixels (height and width) the image is when trying to size padding and margins on your site. Here is an example of the properties window for an image on my computer: 
![image_properties](https://cloud.githubusercontent.com/assets/8645521/19016479/057b2006-87e9-11e6-8113-de371ee35a42.jpg)
And this is how I would write the `<img>` element to grab it:
`<img src="ILiADS_July2016.jpg" alt="picture of Rebecca Parker from ILiADS conference"/>`

**Comment by msb81** [comment]
where does it tell you in the tutorial to upload the picture? Bc I'm confused. Lol I'm so sorry I have so many questions.

**Comment by RJP43** [comment]
My comment above should walk you through how to link an image. Just have to make sure the picture is in the same directory as the page calling on the image. If you look on the [tutorial](http://newtfire.org/dh/explainHTML.html) about 3/4 of the way down you will see where we discuss image linking.
