### ISSUE TITLE
Need a hint - (づ｡◕‿‿◕｡)づ

### ISSUE THREAD

**Issue by etj27** [ebeshero/DHClass-Hub#224]
Started working on the homework and I got stuck on b and c of problem 2.  Now I know I'm not going to get an answer here and maybe I'm out of the loop because I wasn't able to attend last class but these problems are triggering me because I can't do the letters after this since they rely on previous answers.

So these are what I was able to come up with, and I know that somewhere along the line all of these are wrong, I get results for b and c but they are the same result, which is not correct.  I've spent the past 45 minutes putting in as many different lines of code as possible, all yielding either no result, the same, or so many oxygen crashes.  So all I need is a little theory correcting because at first i thought I did B correct but I know that if I had, then distinct-values would work at some point as I changed its location to everywhere possible.  

```
b. Using the name() function, build on your previous XPath expression to return the names of these attributes.
//attribute::node()//name()
```

```
c. Now, return only the distinct-values of those attribute names: What XPath expression does this?
//attribute::node()//distinct-values(name())
//distinct-values(attribute::node()//name())
//distinct-values(name(attribute::node()))
```
//distinct-values(name(attribute::node())) - when i thought to do this code i thought "yay, this makes sense, but then i got the error that i cant more than 1 item and i got stumped because you can't place anything in node(). so here i is

**Comment by RJP43** [comment]
@etj27 You are very close here and doing this in a unique way. So the reason you are getting an error is because you are not clearly saying what you want the distinct-values of. So if your entire expression `//attribute::node()//name()` is what gets you all of the names of ANY attribute in the document you need to include the part of the expression that clarifies the ANY attribute ANYWHERE in the document. 

Sometimes we take for granted that the beginning double slashes actually means drop down into all of the descendants of the document. If you want the distinct name values of ANY attribute appearing anywhere in the document you need to include the XPath portion that says ANYWHERE in the document inside of your distinct-values function.

**Comment by etj27** [comment]
@RJP43 
Wow, it was that simple...okay lmao.  I'm a little mad.  Thank you very much for the clarification!  You rock!

![giphy](https://cloud.githubusercontent.com/assets/21312713/19284392/ba0e0998-8fc3-11e6-9a0d-3aa219b16c27.gif)

**Comment by RJP43** [comment]
@etj27 lmao... Honestly, this was part of the clarification we went over in class on Monday so it was just bringing you up to speed with what we discussed in class. Now I mentioned you are doing this in a unique way and what I mean by that is your use of `node()` instead of the asterisk (reference [our example from Friday](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XPath/XpathOnMitfordSiteIndex.md) to see how the `*` could simplify your expression) ... `node() may cause complications as the assignment asks you to make your expression longer and longer. I say keep doing it as you are but be aware of how you can possibly simplify by referencing our solutions and posted class-example.
