### ISSUE TITLE
Could I have help with the dates?

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#226]
I'm having trouble guessing the syntax for working with xs:date in the xpath window. This is relevant to question 3b 

> 3b. Now, what if we want to return those dates in their ISO format, as yyyy-mm-dd? Can you retrieve that with XPath? 
> (Hint: Look at the attribute values on the date elements.)

What I tried:

I took the class example 
   `//date[matches(@when, "\d{4}-\d{2}-\d{2}")]`

This outputs the whole element date

This 
`//head//date[@when[matches(.,"\d{4}-\d{2}-\d{2}")]]/./text()`
Gets me just the dates in the format I don't want, the M 09-07

I eventually hit upon
`//xs:date(@when)` 
which gets me the list I want.

BUT it causes a problem when I get to question 3c.

> 3c. Return a string-joined list of all these dates, separated with a comma and a space.

I could string-join the dates formatted the non-desired way quite easily:

 `string-join((//head//date[@when[matches(.,"\d{4}-\d{2}-\d{2}")]]/./text())," , ")`

But it proved beyond me to do the same with my list of xs:dates. They couldn't be string-joined because they are not a string. I tried to make them a string and it didn't work:

 `string(//xs:date(@when))` 

This also didn't do anything for me

`//date[xs:date(@when)]`

Could someone point out where my thinking is going wrong?

**Comment by RJP43** [comment]
Each part of question three builds of the previous part. SO lets get all three questions listed out here:

a. What XPath returns all the Fridays on the syllabus? (Scroll through the document looking for the date elements to help determine this.)  

b.  Now, what if we want to return those dates in their ISO format, as yyyy-mm-dd? Can you retrieve that with XPath? (Hint: Look at the attribute values on the date elements.)

c. Return a string-joined list of all these dates, separated with a comma and a space.

Okay to start this question you first want to look at the format of a date (a Friday date in particular) to see where you need to grab down into to get only dates that are Fridays.
So `//date` gets you all of the date elements. 
Now by scrolling thru those results you can see what a date that specifies it is a Friday looks like: 
`<date when="2015-09-04">F 09-04</date>`
And of course since we are working with XPath we should look at its surrounding hierarchy: 
````
<div type="day">
                  <head>
                     <date when="2015-09-04">F 09-04</date>
                  </head>
...
````
So from here how would you grab dates THAT HAVE an indication that they are Fridays? --  And that will be 3a

Now to get to 3b notice that the `@when` attribute gives the ISO format of the dates. So take your XPath from 3a that gets you only Friday dates and take another step so you get the `@when` of those. 

Finally 3C is a string-join ... now the format for string-join from our [class-example](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XPath/XPath-StringFunctions.md) should follow this format `string-join(arg+,"text separator")`
So essentially you should be able to drop your entire path from 3b into where arg+ is in the format above and get the answer. 

Does this help?

**Comment by RJP43** [comment]
For 3A, notice you have to reach into the text-node of the date element to get the dates that contain the letter F (indicating it is a Friday date).

**Comment by RJP43** [comment]
I think you making this more complicated thinking you have to use the xs:date from the class example that links with question 5 when we ask you to **re-format** the dates.

**Comment by setriplette** [comment]
I got it. Where I was wrong in my thinking was that I thought attributes could only be in a predicate and not be path steps. It seems so simple. Does it not work sometimes, or am I just imagining that?

**Comment by RJP43** [comment]
@setriplette anytime you use a predicate statement you are grabbing the last element in the path step that has whatever is in the predicate. So if you have an attribute in a predicate you are saying such-and-such path to an element that has that attribute: `//Element[@attribute ]`

The predicate works like an adjective of the element used to describe the specifics of an element. If you want the actual content of the predicate you have to take another step to get that:
`//Element [@attribute]/@attribute` now this says go down in the document get me the elements that have "this" then get me whatever "this" is

**Comment by setriplette** [comment]
Thank you!
