### ISSUE TITLE
Question 2 & 3 on Schematron Exercise 2

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#229]
This is asking me to guess so many new things at once that I can't get anywhere with it.

I need something with a following something axis in it. (But the things I want to target aren't siblings of each other or seemingly related at all--so how?)

I need something with substring()

What I have to do is dig into the the element title, grab its number out of its text, and make sure that this number is the corresponding number dragged out of the text of the preceding title +1.

I have no earthly idea how to begin writing any of that. I tried something bastardized out of a class example, but it didn't work. The only thing I'm confident on here is the `<rule context="title">`. What's my next step after that?

`<pattern>
        <rule context="title">
            <assert test= "//div/head/title/preceding-sibling::text()[1]">
                The number of the poem must equal the number of the preceding poem plus one.
            </assert>  
        </rule>
    </pattern>`

**Comment by RJP43** [comment]
@setriplette okay let's try to take this piece by piece. The first and second bullet points of question three are in regards to setting your rule context. When I XPath down into the file for just title (`//title`) I notice that I am not just grabbing the title elements that separate each of the poems. So you want to revise the rule context to grab the titles that sit in a certain spot in the document hierarchy.  The titles you want to grab sit in this immediate hierarchy:
````
 <div type="poem">
            <head>
               <title>Poem 2. (J 607: 1862/1929)</title>
            </head>
````
So your XPath pattern in your context needs to end on the title element but you need to start it out by defining a bit of the hierarchical path beforehand that gets you to only these specific titles. 
Also, remember to use the tei prefix (`tei:`) or your rules won't fire at all.

**Comment by RJP43** [comment]
@setriplette Now the second bullet point suggests that not only do you need to grab the title elements that specifically sit in that hierarchy, but you want to start your context with a poem that is immediately followed by another poem. So in your stepping down into the hierarchy you first want a div THAT HAS the specific indication that it starts a poem and that also HAS a following-sibling div with that same specification. Basically, you are looking at a double predicate before even stepping into grabbing title elements. This sets you up so that you can write your assert or report on specifically the poem titles and also so you are starting on a poem that has a poem before it.

**Comment by RJP43** [comment]
@setriplette Now the bit about substring is telling you how to pull the number from the poem titles so you can convert it into a number using that number function and then add 1 to it so you can set that equal to the number of the following poem title number. This would then be checking that whatever poem title number landed on plus 1 is equal to the next poem title number. So this will be a bit complicated to write but I can map it out in a skeleton perspective and hopefully it becomes a bit clearer. 

(number(substring(XPath to title which with the above context will be self, character-position-number-to-start, number-of-characters-to-extract)) + 1) = number(XPath to the immediately following poem title/substring(XPath to the title again being self because of our context, character-position-number-to-start, number-of-characters-to-extract))

Now hopefully that extended skeleton along with reading the step by step explanation in the assignment for number 3 you can figure it out. If not ask another question to lead me down where you need further explanation.

**Comment by setriplette** [comment]
Thanks for the help!
I am now here and stuck again, in your second part. What is the grammar for writing in the following::sibling part? I'm still not quite understanding how I read this and my oxygen is red on my schematron file.

`<rule context="tei:div[@type="poem"][following-sibling::tei:div[@type="poem"]//tei:head//tei:title">`

**Comment by ebeshero** [comment]
Aha! You are missing a square bracket--do you see where? In the second main predicate, starting with following-sibling::tei:div.

**Comment by RJP43** [comment]
@setriplette Yea I was catching it at first either where you were going wrong, but if you take out the TEI prefixes and drop it into the XPath window of the XML file with two leading slashes you get an error saying you are missing a square bracket. I do this a lot where I try the expression in the XPath window to test first.

**Comment by PPH3** [comment]
Any insight into number 2? This is where xpath and regex knowledge helps.

**Comment by ahunker** [comment]
@PPH3 Try using count() in number 2 and refer to the following since you're looking at wanting one or more of the rdg element inside the app element:
equality: eq or =
greater than: gt or &gt;
greater than or equal to: ge
less than: lt or &lt;
less than or equal to: le
not equal to: ne or !=

I could use some help as well but on question 3. I looked at what @RJP43 had written above, but I am still very lost.

**Comment by setriplette** [comment]
I think I'm getting warmer but I still have an error somewhere. In my schematron, I see an error message telling me I'm missing my second angle bracket, but that's there, so I'm not sure what's up. It fires an error if I cut and paste into a new file as well so I think it's really there.
` <rule context="tei:div[@type="poem"][following-sibling::tei:div[@type="poem"]]//tei:head//tei:title">
            <assert test="(number(substring(., 6, 2)) + 1) = number(following-sibling::tei:div[@type="poem"]/substring(., 6, 2))">
                The number of each poem should be the number of the previous plus one, ie poems should be in sequence.
            </assert>
        </rule>`

**Comment by RJP43** [comment]
@setriplette after the equal sign you need to find your way down to the following title getting the substring on the div[@type="poem'] won't get you anything equal to the substring of the current title landed on.

**Comment by RJP43** [comment]
@ahunker what in particular are you stuck on? does @setriplette last comment help clarify? She is very close!

**Comment by setriplette** [comment]
Ok, good point. Now I'm here though and my schematron is still firing red on my rule context line
`<rule context="tei:div[@type="poem"][following-sibling::tei:div[@type="poem"]]//tei:head//tei:title">
            <assert test="(number(substring(., 6, 2)) + 1) = number(following-sibling::tei:div[@type="poem"]//tei:head//tei:title/substring(., 6, 2))">
                The number of each poem should be the number of the previous plus one, ie poems should be in sequence.
            </assert>
        </rule>`

**Comment by RJP43** [comment]
@PPH3 did @ahunker clarification help?

Question 2: Make sure there are one or more `<rdg>` elements inside an `<app>` element. For this rule we want to check that an `<app>` element has a count of at least one or more than one `<rdg>` element. 

So we know we need to have our context match on any and all `<app>` elements because our assert or report will need to tell us about the number of `<rdg>` elements inside of those. Then you test on either a report or assert will look very similar to this rule from the solution to [Schematron Exercise 1](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/Schematron_Exercises/SchematronEx1.sch)'s optional challenge:

````
<assert test="count(place) eq 4"> <!-- Optional bullet point #1 part A -->
              There should be four place elements in results.   
          </assert>
````
except you will have to change the comparison operand and the number to match what the question is asking for.

**Comment by RJP43** [comment]
@setriplette I think your issue is that you have double quotes inside of double quotes. So whenever we use one kind of quotes we have to alternate to the other kind inside of it or you get an error.

**Comment by setriplette** [comment]
Thank you! Now that I think of it someone mentioned that yesterday and I didn't absorb it.
