### ISSUE TITLE
Mac Issue with XSLT 5 (see instructions here for how to fix)

### ISSUE THREAD

**Issue by ahunker** [ebeshero/DHClass-Hub#236]
I am having trouble with this exercise. I can't get the poems to appear in my transformation window. I saved the folder of poems inside the folder that holds my XSLT document and referenced it the way it suggests in the instructions, but I'm coming up with errors saying 'Content is not allowed in prolog.' I've read through the tutorial several times but I'm not understanding what I'm doing wrong. Here is my code so far:

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml"
    version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    <xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>
    <xsl:template match="/">
        <html>
            <head><title>Emily Dickinson’s Fascicle 16</title></head>
            <body>
                <h1>Emily Dickinson’s Fascicle 16</h1>
                <h2>Table of Contents</h2>
                <ul><xsl:apply-templates select="$dickinsonColl//body" mode="toc"/></ul>
                <hr/>
                <div id="main">
                    <xsl:apply-templates select="$dickinsonColl//body"/>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
```

 I know it's pretty much what is shown in the tutorial, but I'm stuck on what to do. The only output I'm getting is 'Emily Dickinson's Fascicle 16' and 'Table of Contents'. Should I be getting the poems or do I need to add in something else to get the content of the collection?

**Comment by ebeshero** [comment]
Hi Audrey-- Two things to check:
1) Where are you saving your XSLT file in relation to the collection of Dickinson files?
2) If oXygen is giving you a red square on your XSLT file saying "content not allowed in prolog" there might be some extra characters, like white space or something, in front of your <xsl> document node, and we've seen that issue on Macs before. Try copying and pasting your XSLT into a new file--is oXygen green again? 

Meanwhile, I'm going to try out your code here, to see how it looks on my machine in oXygen. @ahunker

**Comment by ebeshero** [comment]
@ahunker If you are (as I think you are) working on a MAC, there's a Mac-specific problem with running an XSLT over a collection of files, and it has to do with the way Mac creates .ds_store files in each directory. Here is how to solve it, from an issue posted last fall on this very exercise:
https://github.com/ebeshero/DHClass-Hub/issues/157

**Comment by RJP43** [comment]
@ahunker have you selected a source xml? Just open any one of the poems (or any XML really) and make sure you have selected it. The XSLT needs a dummy file even though it is being run over a collection.

**Comment by RJP43** [comment]
Just making that suggestion since @setriplette ran into that problem on Friday when she was working on this.

**Comment by ebeshero** [comment]
@RJP43 Good call! Here's the relevant snippet from the assignment sheet, easy to miss because you're typically concentrating on how to write the XSLT instead of how to run the transformation!

"Note on running the transformation: Unlike other transformations we do on single XML files, when we run the XSLT in <oXygen/> it actually doesn’t matter what file we have selected in the XML input, because we have indicated in the stylesheet itself what we are processing, with the collection() function. We can actually set even a file that is outside of our collection as the input XML file (and we ran it successfully with the HTML file of the previous exercise selected). You do need to enter something in the input window, but when you work with the collection() function, your input file is just a dummy or placeholder that <oXygen/> needs to have entered so it can run your XSLT transformation."

@ahunker When I paste your XSLT into oXygen, it's green, so I'm not seeing the "content not permitted in prolog error..." Let me try running it over the collection to see what happens...

**Comment by ebeshero** [comment]
@ahunker ...and the answer is, I am getting good output of the whole collection (as text) inside one output file, so the code you posted is just fine for your start.

**Comment by ahunker** [comment]
I deleted the .ds_store files the way you suggested and I am getting the poems in the transformation window, so if anyone else using a Mac has the same problem I had, I would suggest following the instructions in the issue referenced by @ebeshero above.

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
