### ISSUE TITLE
simple question: XSLT over a collection XML input selection?

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#238]
When we set up xslt in oxygen, do we need to open all the files in the dickinson folder or just one?

**Comment by ahunker** [comment]
I just opened one poem from the Dickinson folder and it worked for me.

**Comment by RJP43** [comment]
From @ebeshero on issue #236 : Here's the relevant snippet from the assignment sheet, easy to miss because you're typically concentrating on how to write the XSLT instead of how to run the transformation!

"Note on running the transformation: Unlike other transformations we do on single XML files, when we run the XSLT in it actually doesn’t matter what file we have selected in the XML input, because we have indicated in the stylesheet itself what we are processing, with the collection() function. We can actually set even a file that is outside of our collection as the input XML file (and we ran it successfully with the HTML file of the previous exercise selected). You do need to enter something in the input window, but when you work with the collection() function, your input file is just a dummy or placeholder that needs to have entered so it can run your XSLT transformation."


See Issue #236 for additional issues you may have running an XSLT over a collection on a mac.

**Comment by RJP43** [comment]
@laurenmcguigan you do need to make sure that your Dickinson folder is sitting in the same space as your XSLT and if not you need to change the path when you create the variable (`<xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>`) or move it so your XSLT and the entire folder are siblings in the same space.

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
