### ISSUE TITLE
xslt 6: Trouble Sorting TOCs and with Attribute Value Templates (AVTs)

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#239]
I am not able to change the table of contents order. For the alphabetical order, I'm at a real loss, because the poem titles are already in alphabetical order (their names are Poem and a number), and the part I would alphebetize is inside the first lines, which I don't know how to reach.

In my attempt to sort for the number of variants, which seemed simpler, I tried this:

`<ul>
                    <xsl:apply-templates select="$dickinsonColl//body" mode="toc"><xsl:sort select= "count(rdg)"/></xsl:apply-templates>
                </ul>`

I am up in the document node section here. I tried it in the style portion of the xslt also but that yielded nothing. I am out of ideas.

I also have another issue, with the `<a href>`

This made a link but I have no confidence that it actually links to anything. The id number does show up in the source documents, but above the body. Is that a problem?
`<a href="#p{idno}">`

Also, what are the goals of the assignment? As far as I understand I am to:

Make each of the poem titles a link
Change the toc order to sort alphabetically (and comment this out? Because it cannot be both sorted this way and by variants in the html output, right?)
Change toc order to sort by number of variants
Make a css that showcases the variants in some way

Did I miss something?

**Comment by ebeshero** [comment]
@setriplette May I refer you to your very own post of yesterday on the matter of *how to reach into the first lines*? You had it figured out yesterday and posted about it right here:
https://github.com/ebeshero/DHClass-Hub/issues/237

**Comment by ebeshero** [comment]
@setriplette On the goals of the assignment, yes, that should be it:

* Link from the poems in your list down to a special distinct `@id` you've planted at the head of each poem. 
* Change the toc order to sort alphabetically
* Output *another* list after it that sorts by the number of variants. (You don't need to comment it out! The two lists can be output in the same document using modal XSLT! Later on, we'll show you how you can use CSS and JavaScript to hide one or the other list, and show the one a user wants to see on demand!) 
* Make a css that styles the whole thing and highlights the variants!

**Comment by setriplette** [comment]
By planting an id number at the head of the poem, do you mean that I have to open up each xml file for each poem and write in an id number? If so where? Specific element/attribute location would be helpful.

**Comment by setriplette** [comment]
Also, I tried putting the `<xsl:sort/>` command in the indicated place and the list did not sort. No matter where I put that sort command it does not seem to sort.

**Comment by RJP43** [comment]
@setriplette no, you do not want to open each XML file and put an ID number in each poem. The ID number is already there in each poem file in the `<idno>` element in the TEI header.  What you want to do is inside of your template match where you are creating the contents of the table of contents you want to create the link setup (the `<a>` element) and then in the `@href` value you need a hashtag because that is how you will reference the ID number later in the HTML and then create an attribute value template (with the curly braces) that goes up to the document node and walks down to the `<idno>` element. So since your template match will likely be on body and idno sits above body you will have to walk the tree "backwards" to get the corresponding idno. 
Then in the template match that output the whole poems you will want to use the same "backward tree walking" in another attribute value template  except withtout the hash tag before the ATV and this time on an HTML tag sitting around where you are outputting the poem title before the poem lines.

**Comment by RJP43** [comment]
@setriplette as for sorting the table of contents the `<xsl sort>`  notice in [this example](http://www.w3schools.com/xml/xsl_sort.asp) that the sorting happening inside of the document node match... just like all other things you want to happen once in your new HTML document. So in the document node match for each of the tables of contents where you make your apply-templates selection you want to drop your `<xsl:sort>` there inside of the `<xsl:apply-templates>` element. This prob. seems unusual since we are used to seeing that element as self-closing.

**Comment by etj27** [comment]
So just started the program and I'm trying to figure out the first step by looking at the comments here and I feel that I'm confused.  

` <xsl:template match="body" mode="toc"> 
     
    <li>
        <a href="#{attribute::idno}">
            <xsl:apply-templates select="attribute::idno"/>
        </a>
    </li>
    </xsl:template>`

I felt that this is what you were hinting at was needed?  the attribute (i initially tried ancestor and preceding to no avail).  Is this what was needed in the first paragraph of your explanation @RJP43 ?  and then after we have done this we do a

<xsl:apply-templates select= "WhateverWeDidBefore" /> in the 

`<ul><xsl:apply-templates select="$dickinsonColl//body" mode="toc"/></ul>
                <hr/>
                   
                <div id="main">
                    <xsl:apply-templates select="$dickinsonColl//body"/>
                 
                </div>
              
            </body>
            
        </html>
    </xsl:template>`
 
part of our code?  Just feels like i'm not getting anything, my output is just a # with nothing after it so I know I'm messing up concept wise somewhere

**Comment by etj27** [comment]
Link from the poems in your list down to a special distinct @id you've planted at the head of each poem.  [figured this out except for whatever this means 

> Then in the template match that outputs the whole poems you will want to use the same "backward tree walking" in another attribute value template (except without the hashtag before the AVT) and this time on an HTML tag sitting around where you are outputting the poem titles before the poem lines.
Then in the template match that outputs the whole poems you will want to use the same "backward tree walking" in another attribute value template (except without the hashtag before the AVT) and this time on an HTML tag sitting around where you are outputting the poem titles before the poem lines.

]

Change the toc order to sort alphabetically [Nope]

Output another list after it that sorts by the number of variants. (You don't need to comment it out! The two lists can be output in the same document using modal XSLT! Later on, we'll show you how you can use CSS and JavaScript to hide one or the other list, and show the one a user wants to see on demand!)
[Nope]

Make a css that styles the whole thing and highlights the variants! [Obviously can't do this with 2 previous nopes]

Well thats good enough for me.  i'll see if i care to do more in the morning

**Comment by ebeshero** [comment]
@etj27 You tried to use the `ancestor::` axis to reach up to the `<idno>` element, but that didn't work. That is because of the structure of TEI. You tried to walk up the ancestor axis to find idno, but it isn't actually an ancestor of the body element. You have to climb up to the tree to the **common** ancestor that holds them both, the TEI root element or the document node, and *then* walk down the tree.

Study the tree structure of one of the TEI files to understand this. Does that give you enough to reach up, and then down into the idno element in the teiHeader?

**Comment by ebeshero** [comment]
@etj27 Just for illustration, here is the basic structure of the input TEI document:

````
<TEI>  (can't remember if it's capitalized or not in the Dickinson files--check this!)
      <teiHeader>
              <!--The <idno> element is somewhere inside this.-->
       </teiHeader>
       <text>
             <!--The <body> element, with the poem, is in here.-->
       </text>
</TEI>
````

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
