### ISSUE TITLE
SVG 3 help wanted

### ISSUE THREAD

**Issue by setriplette** [ebeshero/DHClass-Hub#246]
Hi all,

I'm trying to figure out how to place the stacked bar graphs on the x axis, but I've come up against a problem--the questions aren't numbered like the chapters in Alice were!

Do I have to write some kind of xslt to give them numbers before I start? Otherwise I don't know how to space them out differently from each other.

Would appreciate a hint.

**Comment by setriplette** [comment]
Or is it just that I can't use xsl: for each and have to make a separate match for each question?

**Comment by ebeshero** [comment]
@setriplette You certainly don't need to make a separate match on each question! You may use *either* xsl:for-each *or* a new template match on the fs elements you need to work with. My numbering in the sample output, as I mention in the assignment, is based on *sorting*: I used xsl:sort to organize the questions based on the highest percentage of a particular answer that interested me. (It doesn't matter which one you choose--that's up to you.)  In the end, when I output Question numbers, they were based on the sort order. I used the position() function to retrieve the numerical position of each question in the sort order as it output.

**Comment by ahunker** [comment]
I could use some help with my percentage calculations. I've been messing around with it, but I can't get the equation to work. 
```
<!-- GLOBAL RULES -->
    <xsl:variable name="xSpacer" select="50"/>
    <xsl:variable name="ySpacer" select="5"/>
    <xsl:variable name="numQ" select="count(//f[@select='Yes'])"/>
    <xsl:variable name="max_xValue" select="$xSpacer * $numQ"/>
    <xsl:variable name="max_yValue" select="100 * $ySpacer"/>
    <xsl:variable name="yes" select="//fs/f[@select='Yes']/@n"/>
    <xsl:variable name="no" select="//fs/f[@select='No']/@n"/>
    <xsl:variable name="blank" select="//fs[@select='Blank']/@n"/>
    <xsl:variable name="sumN" select="//fs/f[@select='Yes']/sum(@n)"/>
    <xsl:variable name="yesPerc" select="$yes div $sumN * 100"/>
    <xsl:template match="/">
        <xsl:comment><xsl:value-of select="$yesPerc"/></xsl:comment>
        <svg width="850" height="850" viewBox="0 0 1000 1000">
            <g transform="translate(100 750)">
                <xsl:comment>X-axis</xsl:comment>
                <line x1="30" y1="0" x2="{$max_xValue + $xSpacer}" y2="0" stroke="black" stroke-width="2"/>
                <xsl:comment>Y-axis</xsl:comment>
                <line x1="30" y1="0" x2="30" y2="{-$max_yValue - 100}" stroke="black" stroke-width="2"/>
            </g>
        </svg>
    </xsl:template
```

**Comment by RJP43** [comment]
@ahunker since you are defining those percentage calculating variables outside of a more specific template match than in the document node match or xsl:for-each you are likely getting the following error: 
` A sequence of more than one item is not allowed as the first operand of 'div'`
This is because without the template match or xsl:for-each you are calling on **ALL** of the specified kind of `<f>` elements. You need a template match or xsl:for-each to loop through each one. Make sense?

**Comment by RJP43** [comment]
You could keep some of these as Global Variables. Like these ones: 
````
<xsl:variable name="xSpacer" select="50"/>
    <xsl:variable name="ySpacer" select="5"/>
    <xsl:variable name="numQ" select="count(//f[@select='Yes'])"/>
    <xsl:variable name="max_xValue" select="$xSpacer * $numQ"/>
    <xsl:variable name="max_yValue" select="100 * $ySpacer"/>
````
but the others need to be part of the many to one setup of a xsl:for-each or separate template match

**Comment by RJP43** [comment]
@ahunker in doing that you will have to adjust the path steps of your XPath expressions in reference to the context of the for-each or template match

Also, you are doing something a little funky with the variable you are calculating the response totals with. Look back at our [solution for XSLT 3](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/XSLT_Exercises/XSLT-Ex3/XSLT-Ex3.xsl) to see how you have misplaced your sum() function.

**Comment by ahunker** [comment]
Ok, so I've got output now, it's giving me the percentage of yes answers, but I'm having two problems now. First, my bars underneath my graph, going below the x-axis rather than above it. I've tried making the height of the rectangle negative, but then nothing shows up. Second, all my bars are in one spot. I could use a hint as to how I would start the solution to this. Would I have to use a preceding-sibling:: or something in order to move each bar over? 
```
<xsl:variable name="xSpacer" select="50"/>
    <xsl:variable name="ySpacer" select="5"/>
    <xsl:variable name="numQ" select="count(//f[@select='Yes'])"/>
    <xsl:variable name="max_xValue" select="$xSpacer * $numQ"/>
    <xsl:variable name="max_yValue" select="-(100 * $ySpacer)"/>
    <xsl:template match="/">
        <svg width="850" height="850" viewBox="0 0 1000 1000">
            <g transform="translate(100 750)">
                <xsl:comment>X-axis</xsl:comment>
                <line x1="30" y1="0" x2="{$max_xValue + $xSpacer}" y2="0" stroke="black" stroke-width="2"/>
                <xsl:comment>Y-axis</xsl:comment>
                <line x1="30" y1="0" x2="30" y2="{$max_yValue - 100}" stroke="black" stroke-width="2"/>
                <xsl:for-each select="//fs[f[@select='Yes']]">
                    <xsl:variable name="yes" select="f[@select='Yes']/@n"/>
                    <xsl:variable name="no" select="f[@select='No']/@n"/>
                    <xsl:variable name="blank" select="f[@select='Blank']/@n"/>
                    <xsl:variable name="sumN" select="sum(sum($no, $blank), $yes)"/>
                    <xsl:variable name="yesPerc" select="($yes div $sumN * 100)"/>
                    <svg width="850" height="850" viewBox="0 0 1000 1000">
                        <rect x="50" y="0" width="{$xSpacer}" height="{$yesPerc}" fill="purple" stroke="black" stroke-width="1.5"/>
                    </svg>
                </xsl:for-each>
            </g>
        </svg>
```

**Comment by RJP43** [comment]
@ahunker I am trying to figure out how to flip the rectangles (I generally work with lines because they make more sense to me, but there must be a way to do this so bare with me as I try to scrape the internet to figure that out). In the meantime there are a couple of other things:

First, the reason all of your bars are sitting on top of each other is because your x value isn't dynamic. To make this dynamic try creating a variable that uses the position() function multiplied by a specified amount of space: like this `position()*$xSpacer` . The position() function gives you the position of the current node within the "current node list", which is whatever was selected by your for-each. This is useful because it gives every question a unique position and when you apply your xsl:sort in the for-each it rearranges the position according to how you sorted (so if you sort by the @n value of the yes questions you will get the questions in order / re-positioned according to which was answered yes the most). 

Second, you have over-complicated your `sumN` variable. Remember that since you are in each fs if you fet the sum of all the f elements' @n then you will get the total number of responses for that question. In our posted [solution to XSLT 3](https://github.com/ebeshero/DHClass-Hub/blob/master/Solutions/XSLT_Exercises/XSLT-Ex3/XSLT-Ex3.xsl) we did found the total with this expression `sum(f/@n)`. Your current expression excludes the possible Yes_but_fined answers.

**Comment by RJP43** [comment]
@ahunker Also, You don't need to repeat the SVG superstructure in your xsl:for-each

**Comment by setriplette** [comment]
I'm chiming in with one of the few pieces of this assignment I figured out.

Even if you use the position function, all your bars will output on top of each other unless you sort them by something. The thing I did below sorts by the number of yes answers (ascending). Write it right after the `<xsl:for-each select=>` bit

`<xsl:sort select="descendant::f[@select='Yes']/@n"/>`

You can sort by any of the values that interest you, but the important thing is to give your for-each a means by which to make an array and not a pile.

**Comment by ahunker** [comment]
I could use some help stacking my bars. I've looked at the assignment instructions but I'm not sure what I'm adding together to get my y values and where that equation would be placed in my code.
```
<!-- GLOBAL RULES -->
    <xsl:variable name="xSpacer" select="50"/>
    <xsl:variable name="ySpacer" select="5"/>
    <xsl:variable name="numQ" select="count(//f[@select='Yes'])"/>
    <xsl:variable name="max_xValue" select="$xSpacer * $numQ"/>
    <xsl:variable name="max_yValue" select="-(100 * $ySpacer)"/>
<xsl:for-each select="//fs[f[@select='Yes']]">
                    <xsl:sort select="f[@select='Yes']/@n"/>
                    <xsl:variable name="yes" select="f[@select='Yes']/@n"/>
                    <xsl:variable name="no" select="f[@select='No']/@n"/>
                    <xsl:variable name="blank" select="f[@select='Blank']/@n"/>
                    <xsl:variable name="yesFined" select="f[@Yes_but_fine]/@n"/>
                    <xsl:variable name="sumN" select="sum(f/@n)"/>
                    <xsl:variable name="yesPerc" select="($yes div $sumN * 100)"/>
                    <xsl:variable name="noPerc" select="($no div $sumN * 100)"/>
                    <xsl:variable name="blankPerc" select="($blank div $sumN * 100)"/>
                    <xsl:variable name="yesFinedPerc" select="($yesFined div $sumN * 100)"/>
                    <xsl:variable name="xPos" select="position()*$xSpacer"/>
                    <line class ="Yes" x1="{$xPos}" y1="0" x2="{$xPos}" y2="-{$yesPerc}" stroke="purple" stroke-width="30"/>
                    <line clas="No" x1="{$xPos}" y1="-{$yesPerc}" x2="{$xPos}" y2="-{$noPerc}" stroke="yellow" stroke-width="30"/>
                    <line class="Blank" x1="{$xPos}" y1="-{$noPerc}" x2="{$xPos}" y2="-{$blankPerc}" stroke="red" stroke-width="30"/>
                    <line class="YesFined" x1="{$xPos}" y1="-{$blank}" x2="{$xPos}" y2="-{$yesFinedPerc}" stroke="green" stroke-width="30"/>
                </xsl:for-each>
```

**Comment by ebeshero** [comment]
@ahunker I'd do the stacking at the point where you're drawing your SVG lines. One strategy for this is to draw your stacked line *from the point where you stopped on the previous line*. So you can *start* the next bar at the point of the variable that takes you to the top of one bar. 

Does that help?

**Comment by RJP43** [comment]
Hey @ahunker sorry for not getting back about getting the rectangles flipped. Honestly, I fell asleep after several failed attempts last night. Since you have decided to move to lines (into my comfort zone) I can def. help you out here. 

Okay so after you have your first bar the second bar needs to start (y1) where the previous bar ended and then needs to be as tall as or end (y2) where the first bar and whatever the second stacked bar would be together, and so on for each bar after that. So the third bar would need to start where the first two bars end and end where the first two bars and the new bar would be together. Now since only one of the questions will have four stacked bars consider how and where you will need to include a conditional statement that outputs that fourth stacked bar **if** it appears.

**Comment by jonhoranic** [comment]
Ok so I am trying to remember the **if and when** xsl structure, where should I look for a model or example so I don't cause my chart to blow up?

**Comment by ebeshero** [comment]
Hi @jonhoranic : Scroll down to the "Conditionals" section on this page:
http://dh.obdurodon.org/xslt-basics-2.xhtml

**Comment by ebeshero** [comment]
@rjp43 @ahunker @JaredKramer40 To get an svg `<rect>` element to plot upward and not down, you need to set its y value at the *top* of your bar and give it a negative sign, but set its height as the positive value, like so:

````
 <rect x="{$xPos}" y="-{$yesPerc}" width="{$xSpacer - 10}" height="{$yesPerc}" fill="yellow" stroke="yellow" stroke-width="2"/>
````
The svg line is perfectly good, too! But as I know you were working on this over the weekend, I wanted to chime in here...

**Comment by jonhoranic** [comment]
I have met some frustration in my attempts to output the Yes_but_fined bar and I have attempted using the `<xsl:if>` to no avail. I have fiddled with it and got some interesting results that painted my ENTIRE stacks orange, but still did not fill that tiny gap! 
`<line class ="Yes" x1="{$xPos}" y1="0" x2="{$xPos}" y2="-{$yesPer * $ySpacer}" stroke="blue" stroke-width="30"/>
                    <line clas="No" x1="{$xPos}" y1="-{$yesPer * $ySpacer}" x2="{$xPos}" y2="-{($noPer + $yesPer) * $ySpacer}" stroke="red" stroke-width="30"/>
                    <line class="Blank" x1="{$xPos}" y1="-{($noPer + $yesPer) * $ySpacer}" x2="{$xPos}" y2="-{($blankPer + $noPer + $yesPer) * $ySpacer}" stroke="green" stroke-width="30"/>
                    <xsl:if test="$fine">
                        <line class="Yes_but_fined" x1="{$xPos}" y1="-{($blankPer + $noPer + $yesPer) * $ySpacer}" x2="{$xPos}" y2="-{($finePer + $blankPer + $noPer + $yesPer) * $ySpacer}" stroke="orange" stroke-width="30"/>
                    </xsl:if>`
Here is what I have currently for my line outputs, I expect I might have to nest those inside a `<xsl:choose>` if the link @ebeshero sent my way is the proper model. So far just testing to see if this works for me or not.

**Comment by ebeshero** [comment]
@jonhoranic In your code, what does `$fine` refer to? Have you defined this variable?

**Comment by ebeshero** [comment]
@jonhoranic Seems to me, you want to replace $fine with an XPath expression to test for the presence of the yes-but-fined response...

**Comment by jonhoranic** [comment]
@ebeshero I have defined that above with the proper Xpath for that variable, let me just grab that section now. I also tired using the Xpath first, but I assumed that it did not work do to some conflict/etc. BUT that is what we do...troubleshoot!
`<xsl:variable name="yes" select="f[@select='Yes']/@n"/>
                    <xsl:variable name="no" select="f[@select='No']/@n"/>
                    <xsl:variable name="blank" select="f[@select='Blank']/@n"/>
                    <xsl:variable name="fine" select="f[@select='Yes_but_fine']/@n"/>`

**Comment by ebeshero** [comment]
@jonhoranic Aha! I think I see the problem!
In the `@select` on the variable named "fine", you are missing one letter at the end. It should read: `'Yes_but_fined'`.

**Comment by ebeshero** [comment]
@jonhoranic When you get that working, think about the totality of that stacked bar that contains 'Yes_but-fined'. Where do you want it to sit? If it sits atop 'Yes', you need to put the 'No' and 'Blank' on top of it, only in that conditional statement.

**Comment by jonhoranic** [comment]
Yay! It output at the top and it is gonna stay there! An oddly underwhelming little goof there compared to the other crazy issues we solved in class, but hey a second set of eyes does help! Speaking of the quirks we covered in class, I also tweaked that lifted section from the Alice code and it fits nicely now with no major edits taking place.

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
