### ISSUE TITLE
JavaScript 03

### ISSUE THREAD

**Issue by laurenmcguigan** [ebeshero/DHClass-Hub#253]
alright so I have output the tables and the graph, but now I am really stuck on the javascript. This is what I have so far:

````
window.addEventListener('DOMContentLoaded',init,false);

function init(){
    var svgSelect = document.querySelectorAll('g[id]');
        for (var i = 0, length = svgSelect.length; i < length; i++)
        {addEventListener('click', barClick, false)
        }
    
    
}

function barClick () {
    var trow = document.getElementById('QA1');
}

        function tableShow() {
                 hide_last();
    
               }
    
    function hide_last() {

        }
````
Am I even remotely in the right direction? If anyone is still awake.

**Comment by ebeshero** [comment]
@laurenmcguigan  OK, let's walk through this step by step:
1. Your opening act is the window, which listens for the document to load and fires the init() function.
2. Next, in function init() you set up a variable named "svgSelect" which stands for the <g> "group" elements in your SVG. That's smart because each <g> element contains all the components of a stack. And if you output those <g> elements with `@id` attributes, you'll select each of those in turn. As the user clicks on a bar, the next function fires: barClick(). 

Before we continue, I think the part where you're stuck has to do with how you're going to match up the `@id` on the SVG `<g>` element with the `@id` on the table row.

**Comment by ebeshero** [comment]
@laurenmcguigan To work with the table row, if you're following our assignment, you really need to define that `trow` variable much earlier. We first set it up as a named global variable, and then in function init(), we assigned its value to the first "default" table row that you have showing when the window loads.  

Now, as I'm looking at your code, I think, you don't really need that function barClick(), since you can just add that variable definition up in function init().  

Also, you need to define `trow` as a **global variable** up at the top of your file before you begin any functions. That means that variable *will be available in any function you call*, but you need to be continually redefining it.  In function init() (which fires when the window loads) you get the variable trow to mean the default showing table row  (the one with @id = `QA1' if you used the same values we did on the table). 

What we do next is

**Comment by ebeshero** [comment]
Two helpful resources to look at:

* [CSS display properties](http://www.w3schools.com/csSref/pr_class_display.asp): there are far more than "block" and "inline" and "none" and "hidden", and since we're working with tables, it's useful to see the ones associated with table rows and cells.
* The [Obdurodon clickable Elections graph](http://dh.obdurodon.org/election.xhtml), which is the inspiration for our assignment. The source data is different but the display issues are pretty much the same. The JavaScript code on this page shows you how the three functions I described above work together. View the page source and open up the JavaScript.

**Comment by jonhoranic** [comment]
@ebeshero @RJP43  I am attempting to grab the xml:id for each bar, so I have this nested inside my xml:for-each statment:
````<!--BAR NAMES-->
                    <xsl:variable name="barName" select="//fs/@xml:id"/>
                    <!--STACKING-->
                    <g class="bar" id="{$barName}">````

The idea is to assign the ID to each bar (each g element) in preparation for the JavaScript, but in my output I keep getting this on all of them:
````<g class="bar" id="QA1 QA2 QA3 QA4 QA5 QA6 QA7 QA8 QA9 QA10 QA11 QA12 QA13 QA14">````

Is this possible to untangle and just get the specific xml:id to go to the specific bar? Or would it be better to do this with handmade changes on the output?

**Comment by ebeshero** [comment]
@jonhoranic The issue, I think, is that you're walking the tree *all over again* in each loop of your for-each loop. Notice the value you've set in your <xsl:for-each>. You don't want to *duplicate* that. Where is the `@xml:id` sitting in *in relation to the value you've set for your for-each loop*?

**Comment by ebeshero** [comment]
Ha. I want an image for "walking the tree" for use in this course and posters for it. We're gonna "walk trees" in this course... Is it like walking a pet? Or more like walking up and down a tree, literally? (I think the latter, with a ladder...)

**Comment by jonhoranic** [comment]
Not too sure about "walking the tree" but I am familiar with _a_ walking tree.
![image](https://cloud.githubusercontent.com/assets/21690665/20735589/0335ef56-b66f-11e6-8fc0-ddf9f66cdb38.png)

**Comment by jonhoranic** [comment]
@ebeshero Speaking of, I used the "self" (the "./" in this case) step and it now grabs the proper xml:id for each group as it should. Thank you for the hint, I am sure I will be back shortly with JavaScript questions after I set up the HTML and CSS proper.

**Comment by RJP43** [comment]
Closing for Spring 2017 Semester
