### ISSUE TITLE
Discussion of Traversing the Tree: Overlapping Hierarchies

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#264]
### The reading:

Read Gabrielle Kirilloff, “[&lt;Traversing_the_Tree/&gt;](http://gk.obdurodon.org/seminar/seminarPaper.xhtml)”, the short article, “[Frankenstein novel analyzed](http://www.idsnews.com/article/2015/04/frankenstein-novel-analyzed)” and scroll through Wendell Piez's [conference talk and images for the Balisage Markup Conference 2014](http://balisage.net/Proceedings/vol13/html/Piez01/BalisageVol13-Piez01.html). If you like, you can take a close look at [his LMNL code of Frankenstein](https://github.com/wendellpiez/Luminescent/blob/master/lmnl/frankenstein-as-published.lmnl) on GitHub. 
_Special note of interest:_ Gabi Kirilloff was a student in [a digital humanities course at Pitt like the one you are taking](http://dh.obdurodon.org), and she originally wrote &lt;Traversing_the_Tree/&gt; for a seminar paper assignment in another class. 
### The discussion prompts:
- What perspective does Kirilloff provide on the kinds of XML markup we are learning, the history and context of hierarchical markup, and its potential issues?
- Consider the examples of overlapping hierarchies that Kirilloff and Piez present to us: Which of these did you find especially interesting? 
- What ideas do Kirilloff or Piez present for how to deal with these in code, and how effective might these be? Is it possible to write XML to get around the problems raised in these pieces? 

The discussion is worth points to you as a homework exercise. For full credit, your posts should make specific reference to passages in Kirilloff's essay, and reflect on those passages. **Note:** You (as an individual) do not have to respond to every one of the discussion prompts, but the class as a whole should cover them all. A good strategy would be to try to respond in some way to at least two of the prompts in the list above. Raising questions is encouraged, and so is responding to each other, but responding should do more than simply say, "yes, I agree." A good response will add something new to the conversation, or help promote more discussion. You should make **at least two substantial posts** to fully contribute to the discussion.

As you're drafting your comments, see if you can apply "Markdown" formatting if you'd like to use bold or italics or make a list, form a link, add an image, etc. Follow the link to "Markdown supported" at the top right of the comment "Write" screen for an orientation to Github's markdown.

**Comment by ebeshero** [comment]
@bsf15 @ajnewton1 @gretchenuhrinek @Samantha-Mcguigan @ahunker @jonhoranic 
Here is the first GitHub discussion assignment that I promised to post. I hope you'll enjoy Gabi Kirilloff's article and the view of code "under the hood" of the piece! See prompts for discussion above.

**Comment by ajnewton1** [comment]
This is funny... I actually encountered a problem with overlapping and didn't know how to fix it but now I do! I thought Kirilloff made some interesting points. One in particular, he stated,
"While this type of solution [overlapping hierarchies] does allow the scholar to search for the text between two empty element tags, it does not acknowledge the existence of an overlapping hierarchy of word and line elements. Essentially, it is a way of tricking the system." 
Its always fun to 'trick' anything let alone the system. I can't wait to come across this problem again just so I can try this out.

**Comment by bsf15** [comment]
**-**	Kirilloff’s perspective on the history of XML, and in particular, SGML, touched on the intended purpose of the data encoding software which was originally meant to store and share large documents dealing with the law, government, and industry. Now using XML, which derived from SGML, for marking up literature, for example, is fascinating as this technology was able to be adapted to benefit the humanities. It makes me wonder how much XML adapted from SGML to be used for marking up literature as opposed to law documents? Does it vary primarily only due to the single hierarchy system?
Also, the mention of how XML’s tags do not have to be specific such as the tags in HTML really shows how it can work so well with humanities, as Kirilloff expressed with the example of a line of text featuring line breaks in between paragraphs. Being able to specify that the line is incomplete or broken up among parts could be very helpful when looking into the piece itself. Kirilloff really shows that XML allows a specification of exactly what that text shown is, how it fits into the piece of work it was pulled from, and etc. That perspective pointed out the benefits of what I could focus more into while working with XML, such as really taking advantage of the labeling of tags. 

**-**	I found Kirilloff’s example of overlapping hierarchies to be interesting as the example she provides with the poetry enjambment contrasts with the typical “tree data structure”. The tags surrounding each bit of the word engineers makes sense as it encases what the actual poem did, but I can see how it would cause confusion within XML. Also, the solution she provides of using empty elements to help contain the part that is overlapping was a good idea of keeping the substance of how the poem is traditionally presented.  Like @ajnewton1 mentioned, it is really a unique way to fix overlapping by "tricking the system".

**Comment by Samantha-Mcguigan** [comment]
In her article, "<Traversing_the_Tree/>" Gabrielle Kirilloff explains the concept of overlapping hierarchies and enjambment through the use of poetry. She states that overlapping hierarchies happen when "The relationship between words and lines in this poem does not corresponded to a strictly parent, child, and sibling structure." In other words, a problem occurs when a text is not able to fit into a hierarchal structure, or when different levels of a text "overlap." I found this idea particularly interesting in the article about Wendell Piez and his coding of Frankenstein because I have read the Mary Shelly novel and I am particularly interested in literature. The article states that by coding the novel Piez discovered thet "each word and line on each page was intentional in the structure of the novel." This particular structure, according to Piez, allowed him to uncover "true focus of the story," the monster. This shows how important it is to fix the root of the problem of the overlapping hierarchies through the code, as Kirilloff believes, rather than changing the text itself or "tricking the system" because even changing where lines begin and end can change the meaning of a text. It is highly important then, that this does not happen.It is interesting then, that, despite this, some people still do not believe that the coding programs need to be changed. In turn, I have to ask, what texts have had their meaning changed from overlapping hierarchies and how has their meaning been changed? Because of this could we never know the real meanings of some texts?

**Comment by Samantha-Mcguigan** [comment]
In her article, Kirilloff gives an example of how to deal with overlapping hierarchies. First, she gives an example of a poem: 

"The four eng-/ineers/Wore orange/brassieres." 

Then she gives an example of how this would create an overlapping hierarchy in code, when trying to deal with words and line breaks with the word eng-ineers, as it is one word on two lines: 

"<line><word>eng-</line>ineers</word>"

After this she gives an example of how to deal with it by using"empty elements to delineate the start and end of the word" :

<line>The four<word/>eng-</line>ineers<word/>

As a beginner, and for our class, I think this solution will be effective, and as shown above, it is possible to write XML to get around this problem by using empty elements but As Kirilloff states, while this "allows the scholar to search for the text... it does not acknowledge the existence of an overlapping hierarchy of word and line elements." I agree with Kirilloff here that it solves the current problem but there is a bigger problem of overlapping hierarchy that is created by the current markup procedure that needs to be addressed. 

I also have a question about why, at the beginning of the line of code, "The" and "four" are not marked as separate words? If the coder was marking each word, doesn't this create a problem? I'm super confused by that.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan That's a good question! I've definitely seen markup where every word is coded, and that means there's an element representing each word sitting at the same level of the XML hierarchy. That might be a good decision here. But here I think the coder is only using those self-closing `<word/>` elements to unite the parts of a word that are "broken" around a line ending. We call these self-closing elements "milestone-style" elements because we can drop them into a text just as signals of something, instead of wrappers around text. 

Honestly, I think I'm with you, I'd prefer to see *every* word coded here, inside the lines and around them! What if we treated the <line/> elements as self-closing instead?

**Comment by ebeshero** [comment]
Great work with this discussion @Samantha-Mcguigan @bsf15 and @ajnewton1 !
