### ISSUE TITLE
Relax-NG: Syntax Error

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#267]
[Newton_EX1.zip](https://github.com/ebeshero/DHClass-Hub/files/705333/Newton_EX1.zip)

**Comment by ajnewton1** [comment]
On my xml code, it is saying there is a syntax error and I am not sure why

**Comment by ahunker** [comment]
@ajnewton1 The first syntax error is because you're missing an equal sign at the beginning of your code between the words 'start' and 'poem', so your opening line should look like this:
start = poem
Once I filled that in, a few more errors popped up. It looks like you have multiple definitions of one attribute and some spelling errors. Try working through those and see if you can get Oxygen green.

**Comment by RJP43** [comment]
@ajnewton1 So one thing to realize is that if you remove the schema line (`<?xml-model href="Newton_rncEX3.rnc" type="application/relax-ng-compact-syntax"?>`) from the top of your XML document then your XML is green again. That is good and means your XML is well-formed. If you associate a Relax NG file that is not well-formed then oXygen indicates an error (in this case a syntax error) in both files. 
Once you fix the error @ahunker made mention of above you should see there are a couple of other quirks in your Relax NG file. Let us know if you need further direction and remember you can always push your files into the [troubleshooting folder](https://github.com/ebeshero/DHClass-Hub/tree/master/Troubleshooting) if you want us to have another look.

**Comment by ajnewton1** [comment]
[Newton_rncEX1.zip](https://github.com/ebeshero/DHClass-Hub/files/712782/Newton_rncEX1.zip)
I believe I got it right this time. The only thing I am having trouble with is my nested elements. It is saying there is an error and I am unsure how to resolve it.

**Comment by ajnewton1** [comment]
Never mind... I figured it out.
