### ISSUE TITLE
Discussion of Network Analysis and Thalaba project

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#270]
Read my blog  on an XML-based network analysis project I've been working on, [Spectacular intersections of place in Southey’s _Thalaba the Destroyer_](https://digitalromanticist.wordpress.com/2013/08/23/spectacular-intersections-of-place-in-southeys-thalaba-the-destroyer/) and post here to reflect on the following:
- What are you coming to understand about network analysis and how it works?
- What kinds of things can you study with network analysis? 
- About the Thalaba project: what might we be learning from using network analysis here? What questions do you have about how it works, or about what we can learn from looking at the graphs?
- Look at some other network analysis projects are mentioned in the blog (such as the _social network analysis_ Six Degrees of Francis Bacon)? What ideas are you learning about the kinds of things or people or ideas can you network together? 

Discussion posts are due as part of the homework for **M 1-23**. Each of you should post at least two or three times, and the class as a whole should try to cover the range of questions I've set here.
@ajnewton1 @ahunker @bsf15 @gretchenuhrinek @Samantha-Mcguigan @jonhoranic

**Comment by bsf15** [comment]
The network analysis done here is particularly interesting as if deals with both standard places and metaphysical places within the epic poem. The way of separating the metaphysical places and real places and how they all connect through edges and nodes help show how often places correlate with each other, how often they are mentioned, and go into the closeness centrality. One thing I notice is how easily it is to map what background info pertains to the main text, especially when looking at the closeness network that shows the various places within the actual text and those in the annotations. The use of a network in this example works very well in showing all the variety and how each piece of additional information specifically ties back into the poem and the places being mentioned in the poem. Another thing I noticed was when metaphysical places were taken out and places were taken out you could learn a lot through seeing the breaks and loss of network coherence. It furthermore elaborates how important each element of information within the poem is to fully understanding and grasping the piece. Also, I thought the removal of the metaphysical places causing the loss of network coherence was really interesting as the metaphysical is so important in actually connecting the concrete places. Overall, I think using this to connect characters  with how fundamental a character is to the piece and how does each character connect would be very similar to the places, but offer different types of information. I also think, networks like this could make reading more challenging pieces with lots of side information slightly easier as it is presented with all the  points connected. It really helps show how different things within text can influence each part in a visual and highly informative way.

**Comment by ajnewton1** [comment]
As far as network analysis goes, I am really digging the visual effects on this article. The things that you can compare are infinite and the way you compared metaphysical places and actual places and how they connect throughout Thalaba the Destroyer. One of my favorite features are the different color nodes that are used. The orange nodes are for the mundane places, the purple nodes are for the metaplaces, and the green points for the line groups. The use of these different colors not only make visual appealing to look at, it makes it a lot easy to depict what the visual is supposed to resemble. Everything going on in the graph has a reason. The thickness of a line is for a purpose and also the dotted or solid line. They all mean something and I think that is very interesting.

**Comment by bsf15** [comment]
I definitely agree with @ajnewton1 about the strength of the visual features being varied by color, thickness, and pattern. When looking at all the information, the color coding in particular makes noticing the different things they represent, such as metaphysical places and actual places, very clear and concise. All you have to do is quickly familiarize yourself with what this color represents or what is the difference between a thick line or a thin line and then referencing the network provides a large amount of information very quickly in an engaging way. Then, when considering the format of the network analysis, the placement of where a specific thing is, such as a place, can indicate even more. Like in the one example that was set up about Thalaba's places and metaplaces plotted by average shortest path, the viewer could clearly see the importance of Arabia as it is located at the top and has all those lines connecting to and from it. I would be curious to see other ways you could set up a network to present a large quantity of information in a highly visual and unique way.

**Comment by Samantha-Mcguigan** [comment]
In looking over the over the blog Spectacular intersections of place in Southey’s Thalaba the Destroyer and the network analysis done, I have come to understand more about network analysis. From discussion of the network analysis done for Six Degrees of Francis Bacon, it seems that network analysis was originally used to study relationships between people. For example it states, "Network analysis is more typically used to map social relations." It goes on to say that this is the type of thing used for social media sites such as Facebook and Twitter. This helps me to better understand how network analysis can be used. It works to show relationships within a text. Just as there are relationships between people on social media, so other things like places as we can see in the network analysis for see in the network analysis for Thalaba the Destroyer. This also helps me to understand better the types of projects we should be proposing and what we will be working on in the future. We should look for texts that can be coded to show the relationships that exist within them that would be too plentiful to do manually but that must be done systematically through network analysis to see any real meaning behind these relationships. In doing so, we will be able to come to a better understanding of the text itself.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Well, you don't have to do network analysis in your projects, but you'll learn how to make one, anyway! :-)  @bsf15 : You mentioned wanting to see some other examples. Here are a couple that are really striking, representing social media consumption, and political blogging:

https://humancomputation.com/blog/?p=7046

https://github.com/briatte/awesome-network-analysis

**Comment by Samantha-Mcguigan** [comment]
The network analysis shown for Six Degrees of Francis Bacon makes more sense to me than the kind of network analysis done for Thalaba the Destroyer. It seems as if it is more simple. The nodes each encircle a person and the bigger the node, the more connections that person has with other people. "betweenness-centrality" makes sense to me as the closer the person's node is to the middle of the network, the more central they are to the relationships of all the people in the network. If I am understanding this correctly, they are the ones who connect other people or nodes together the most? On the other hand, I have a few questions about the cytoscape network analysis done for Thalaba the Destroyer. I understand that it had the same basic principles as the other network analysis and that the nodes in this case represent places rather than people, but after that I get confused. What does the size of the nodes in this case represent? Are the nodes bigger the more the places are mentioned in the text, the more they connect one place to another, or something else? Or do the intersecting lines or "edges" have nothing to do with the relationships between the places? It seems that we are looking more at the relationship between where places appear within the stanzas and the books rather than the relationships between the places themselves? Anyway, this is all a little confusing to me, so I guess I am just asking is someone can help explain the relationship between the nodes and edges for the Thalaba the Destroyer network analysis?

**Comment by Samantha-Mcguigan** [comment]
@bsf15 Your discussion of network analysis and the connection of physical and metaphysical places makes me think of "Gulliver's Travels." It could be interesting to do a network analysis of the places mentioned in the book.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan The place-nodes on the Thalaba graph are actually a lot like the ones in Six Degrees of Francis Bacon: The more connected the node is, the more connections it has to the other nodes, the higher its **degree**, and in both projects, we made those highly connected nodes be larger so they stand out. 

Edge connections in the graph of Thalaba are formed when places are mentioned together: So *one* point of connection is simply Book 1 stanza 1, every place that's mentioned together there. If Arabia is mentioned together with London in that place in the poem, there's a solid "edge" line connection between them. If London is connected in a footnote, it gets a dotted line edge to Arabia. Then, Arabia is mentioned again and again in Books 2-5 (for example), so all of its connections to other places make more and more edges. Arabia is a single node, and every time it's mentioned , its edge connections mean each position in the poem where it's "wired in" with other places.

One way I think of a network of places is like an airport network--like this:
https://aeroscape.files.wordpress.com/2011/10/continental-network-usa1.jpg
Only this one we can totally plot on a map: The airport locations are stable nodes, and their edge lines represent every possible connection they have to other nodes around the planet. In a way the "planet" in Thalaba is our whole poem, and each stanza of it gives Southey an opportunity to wire places together in an interesting way. Our network graph shows every connection we marked between all the places distinctly mentioned in the poem. There are lots of connections, and their "closeness" or "distance" refers to how many hops you have to make to get from one to another. Arabia is so frequently mentioned and so highly connected to other places in this poem that it is literally *closer* to every other place in the poem because it's most likely that other places will be mentioned alongside it. But a place *far away* from it on the map wouldn't be mentioned in the same stanza, and it might take 3 or 4 steps to get from a mention of the Yang-tze River back to Arabia. 

That's a little like how we can't fly directly from Pittsburgh to London, but have to fly through a more highly connected airport, like Chicago or DC to get there! Hope this airport analogy helps...

**Comment by ajnewton1** [comment]
@ebeshero the Human Computation network analysis really has me going. Showing the difference between Facebook and Twitter is really interesting to me. The Twitter network is way more modules than the Facebook network. Its almost like the Twitter network shows both sides pulling away from each other and the Facebook network won't budge and will always be together. Very interesting to look into.

**Comment by ahunker** [comment]
I'm actually starting to get a better understanding of network analysis and how it works. If I'm understanding this correctly, it is essentially a visual way to depict connections in a text. Connections such as contact between people, who talks to who or who knows who, or connections between different places mentioned. I feel like you could study a lot of different things using network analysis. If you're able to find established relationships, whether that's between people or places or anything else you find in your analysis of the text, I think you'd most likely be able to create a network graph. In the Thalaba project, it looks like you're finding connections between different places mentioned in the text. As others have mentioned above, I like the colors you've used and how you've included metaphysical places along with real world places. It helps me, as someone who has never read the text, understand that the metaphysical world is very important in this story.

**Comment by gretchenuhrinek** [comment]
While reading the article, I couldn't help but compare Thalaba the Destroyer to Mark Z. Danielewski's contemporary novel House of Leaves. I don't know if any of you are familiar with it, but House of Leaves is a beautiful mess of an experimental novel known for its labyrinthine annotations and footnote digressions, some of which cover multiple full pages. Because I'm unfamiliar with Thalaba the Destroyer, this comparison really helped me understand just how neat networking analysis can be. (side note: I remember seeing a reference to House of Leaves in one of our previous readings and while it would be an enormous undertaking, it would be super cool to look over a distant reading of it).

I really like your ideas regarding place and space, and how distance can be measured in ways beyond the physical. I'm also really digging on how you tackled the metaphysical places. At least for me, concepts like that are almost intangible without a visual reference, so the maps you've designed are awesome in that I was able to gain a clear understanding of Southey's mental map of the world (mundane, meta, or otherwise). The colors and thickness of lines to display edge betweenness really makes the maps easy to follow, and clearly shows the importance of places in this poem. And while I've heard of 6 Degrees of Francis Bacon (well, I've heard of 6 Degrees of Kevin Bacon), I never really grasped how much effort went into designing that.

**Comment by ahunker** [comment]
I agree with @gretchenuhrinek above when she says that metaphysical places are much easier to understand with a visual reference. Rather than just putting these places on a world map, which would limit your visuals to the real world, you've made a map of your own, concentrating on what is important in your text.

**Comment by jonhoranic** [comment]
Coming to this discussion a little bit late, I am more or less just commenting on what others have said prior. I can see that it does help establish literal "threads" that helps bring all the narrative pieces together in one large map of sorts. I like these network graphs more when used as overlays like that airport graph was, because it gives me a more understandable interpretation of the information of the graph. Without it I get slightly lost in the graphs, where they become more like computerized art renders like fractals and I feel while they are neat to "look at" they are more difficult to understand without a lot of background information, interactive code (cursor highlights, on click drop downs, etc.), or just a different format of presentation. I love the idea of the relationships being marked and plotted for study, but I feel a little intimidated by the sheer scale and vicious overlapping that makes it difficult to read. Perhaps there are other ways to format these graphs to be more reader friendly (or at least "Jon readable"), but I know that is why I am here in DH again to broaden my knowledge and find the way to do so!

**Comment by ebeshero** [comment]
@jonhoranic Filtering the graphs to concentrate on interesting sections always helps. It's a lot easier for me to read the network graph I plotted because I'm closer to the poem--but that means I have a LOT of explaining to do to newcomers! It's more readable to view the nodes and their connections in pieces, to say, let's just look at everyone that's two path-steps away from Arabia...

That said, I think @RJP43's networks that she made in this class last spring for the Nell Nelson project are wonderfully clear and readable, because she's using them to feature information in one article at a time. Try this one for example: http://nelson.newtfire.org/CSGNetwork.html 
A little easier on the eyes? :-)

**Comment by ebeshero** [comment]
@gretchenuhrinek I love that comparison to _House of Leaves_! Yes, we read about it in Gabi Kirilloff's web essay on overlapping hierarchies--and it's an amazingly weird book in the genre of *ergodic literature* or literature that doesn't have a clear start or end point. Gabi's point is that it might be impossible to model it digitally with an XML hierarchy! Read more about it here: https://en.wikipedia.org/wiki/House_of_Leaves
