### ISSUE TITLE
html and css exersize 1

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#276]
I have been playing around with my website and I accidentally deleted the index.html file that we put into our public.html folder so now my site http://newtfire.org/~sem150/ is working but when I put index.html at the end it says Not Found. Is there any way to fix this?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Good morning! :-) It looks to me like you may have fixed this: when I plug in ' http://newtfire.org/~sem150/index.html` to my browser, your default "Hello world!" index page shows. You should be able to see it in your public html directory...I can go take a look if you're having trouble finding it! Have you uploaded other pages to your folder?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Wait a second--maybe I wasn't awake yet. No, you're right. I'm not seeing it as `index.html`. Let me see if I can look inside your public html directory when I log into SFTP. *Something* is clearly sitting there to display your page...

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Now the way you have it, you've put your site in a directory named my-page-repo. I wouldn't recommend doing that, because to view your website, you have to use a URL with that directory name (properly hyphenated) in it, like this:
````
http://newtfire.org/~sem150/my-page-repo/
````
or
````
http://newtfire.org/~sem150/my-page-repo/index.xhtml
````
The problem you're having with the main directory is your file extension. The original page that is sitting *above* the `my-page-repo` folder has a simple `.html` extension.  You can delete it from the public_html directory, and upload your new files in its place. I would **change** your file extension from `.xhtml` to `.html`: it works better later when we experiment with server side includes and scripting in our server environment at the PSC.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I'm keeping an eye on your pages: I see you've now deleted the `my-page-repo` directory (good; because you don't need it), and now you just have two different index pages:
`index.html` and `index.xhtml`. Delete the old `index.html` file to get rid of it, and you'll be fine. I'd also **rename** your new index file to give it the simple `.html` file extension (and use that for all your html files at the PSC).

**Comment by Samantha-Mcguigan** [comment]
I did it! Thank you for your help!

**Comment by ebeshero** [comment]
Yay! Let's leave this open in case anyone else is having similar issues.
