### ISSUE TITLE
Discussion of Steve Ramsay’s Readings (Due W 2/15)

### ISSUE THREAD

**Issue by RJP43** [ebeshero/DHClass-Hub#278]
@ahunker @jonhoranic @bsf15 @Samantha-Mcguigan @ajnewton1 @gretchenuhrinek 

Between now and class on Wed. morning 2/15, please read and discuss ["DH and CS"](http://stephenramsay.us/2013/04/30/dh-and-cs/) and choose at least one of the following two to continue reading and discussing: ["The Hermeneutics of Screwing Around; or What You Do with a Million Books"](https://web.archive.org/web/20140604085234/http://www.playingwithhistory.com/wp-content/uploads/2010/04/hermeneutics.pdf) **AND/OR** ["In Praise of Pattern"](http://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1056&context=englishfacpubs)

Here are some discussion prompts to get us started:
- What's "_humanistic_" about the coding we do? Is it the use of tech and code on humanities materials?  Is it just that we're working on literary/historical figures and social issues that makes our work "_humanities_" research?  Or, as Steve asks us to consider, "is there actually something about this work that is already humanistic even when we're in the weeds of coding?" 
- Is there something distinctive about the way we work with computing methods that makes this distinctively _humanities_ work, and not computer science? 
- As you are working on and thinking about your projects and reading Steve's work, what do you notice about the way you're thinking about "doing research" with coding? What do you think of Steve's perspective on "screwmeneutics" (for example) and the way we explore humanities with tech tools to find patterns? 

Happy coding and discussing, 
 @rjp43 and @ebeshero

**Comment by bsf15** [comment]
I found Stephen Ramsay’s “DH and CS” article to be very interesting and I liked reading about his perspective on computer science. I liked how he mentioned that computer science is not restricted to being one thing, and can contribute to helping fix many problems for all types of people. The article made coding a solution for various problems for people outside of those who study computer science. Ramsay mentioned Hal Abelson who claimed that computer science is not particularly concerned with computers, and that opens up coding more for the humanities and allows more than technology focused people to apply coding to what they do. 

I think the subject material being coded does help define the coding we do as humanistic, but I think what really makes the coding we do apply to the humanities is that we are coding in a way to simplify or contribute to pieces of work for people. There is an element of needing to have some humanities intended knowledge to mark up some of the things we work on, such as poetry. We are identifying whether or not preserving line breaks in a poem matters or not, or we are marking up certain parts of speech within the code. I think, they way we code helps make the type of coding we do particular to humanities.

I then decided to read his article, “The Hermeneutics of Screwing Around; or
What You Do with a Million Books” and really liked the mention of going to find information just by stumbling around. When thinking about the project I am working on about Hamilton, I can definitely compare my thought process to the one Ramsay shared about Frank Zappa and Varése. When researching, I find further things to investigate and look into by just looking into all types of various sources briefly. For the Hamilton project, the idea of looking into repeated phrases to mark up wasn’t my initial idea going in, I just thought it would be interesting to do something with the musical. After noticing the patterns of repeated phrases and being aware of what I was capable of doing with coding, I got my idea. Using technology though to explore patterns is beneficial as we have access to finding unique information quickly compared to looking through books or other methods. As Ramsay said in this article, Zappa took a long time until he finally got ahold of a Varése record. Now, with technology to categorize information and have it available to scan through quickly and find inspiration and ideas, we could do something that took Zappa over a year to do, in a matter of minutes.

**Comment by ajnewton1** [comment]
I actually enjoyed reading this article that Stephen wrote. I think it is interesting how he states "computer science != programming" however, all the classes offered on Pitt Greensburg CS course are all program related. I get what he is saying but I feel like most people still refer to CS as coders. I also liked how he transitioned to the DH aspect of the article. What @bsf15 said about what makes our code humanity like is "in a way to simplify or contribute to pieces of work for people." I actually never thought about it in that way. I always just assumed it was a 'HM' course because of the types of literature we are working with. 
I think this class can correlate with the CS classes mainly because it still is coding. I am in a class right now dealing with HTML and CSS but the main difference is that were not working with literature. We are working with graphs and numbers. It is hard for me to think of another reason why this class is a HM class other than the reason that we deal with specific subject material.
Just screwing around and stumbling on project materials would be fairly easy for the News Analysis team. News is everywhere and I personally look at it quite often.

**Comment by jonhoranic** [comment]
When it comes to discussions like these where the labels and definitions get blurred, I always notice an odd trend. Whoever is supporting the ideas of breaking down the terms into digestible parts is always on the defensive. Every. Single. Time. It is almost a reflex action to address quirks, misunderstandings, and important separations in the language presented before even making a single cohesive point in an argument. I find it fascinating how it rolls like clock work; preface the topic and main ideas, thesis, explanation of the critique/statement/issue, dissection and wordplay, points are made, conclusion. Sometimes the form will shift, but I cannot help but to notice the pieces of these kinds of arguments.

The main content is focused on breaking the "hasty generalizations" of computer fields that are connected to computer science but are not entirely "science" based. It is like a nesting problem of language, the best example being: "All bananas are plantains, but not all plantains are bananas." Digital humanities is a form of computer sciences, but not all the aspects of computer sciences apply to digital humanities. This is where the point of separation is most important, and why the semantic argument has to take place in order to help distinguish the separate functions the humanities bring to the table.

Digital humanities opens up a lot of prospects that involve rudimentary/surface level programming to develop projects in digital interfaces, the article even uses an example addressing the abilities and ambitions of Silicon Valley techs. Thinking it over, Steve Jobs was not a computer scientist really. He was more or less a man working with the humanities that got involved in the digital sphere (by hacking into pre-existing hardware in order to rip schematics and data to format their own compact models with his friends in a garage...probably highly illegal, but hey we got Apple products out of it so who's really complaining?) and pretty much revolutionized the consumer electronics market. All Jobs did was take a premise and use aspects of computer science to achieve a "humanist" result. Just like how his own love for music inspired him to find a way to gather and catalog digital files to make music something accessible.

I find that are projects are not as "grandiose" in a sense, we understand our limitations and what we can do within a short semester. However I think there is some merit seated in the construction and presentation of these ideas. Be it; respect for the deceased but still being able to make a useful and interesting resource that sparks curiosity (albeit slightly morbid) like theGraveyard project, a passion for how different languages can present ideas and emotion while showing the literary changes and edits like the Lope and Amadis projects, or just an interest in bringing back genre pieces/lesser known authors in way that allows for a broader interaction with the texts at hand like the Mitford and Eldritch projects, they all have a connection to the influences found in the academic study of humanities. These being the big four: content, process, applications, and speculation.

I would conclude that making the distinctions are important, but must be done in a way that will not alienate those from these normally distant fields of humanities and computer studies. I think the best way to find that merge point is to play on reasoning and creative thinking, because these two things are essential to the most basic levels of these fields. If more arguments can be made that show that digital humanities can act as an extension or a balance of trades I think more people would be open to addressing coding as a form of "writing,"  more or less a practical skill. I also think it could bring in more of the wider visioned thinkers that look for a Jobs-like outlet to produce digital content in a similar style that can be "the next big thing" by bringing in those fresh interpretations of the humanities.

Who knows, only time will tell! Until then, more coding for us, lets see what else the mix of discussions and troubleshooting can bring.

**Comment by Samantha-Mcguigan** [comment]
In his article _The Hermeneutics of Screwing Around; or What You Do with a Million Books_ Stephen Ramsay states, "A humanist scholar—of whatever discipline, and however postmodern—is by definition a believer in shared culture." Humanism, from what I gathered from a quick search on the internet, is the belief that humans are not only able to learn, but can improve themselves through education. Humans are better when they understand other cultures rather than just the culture than surrounds them. I would agree that coding humanities materials allows us to learn more and study other cultures but coding is also inherently humanistic. Not only do we learn a new skill, but, creating code, as Ramsay discusses in _DH and CS_ allows us to educate ourselves more efficiently. It allows us to separate what needs to be learned. Just like a history book takes the most important and influential events that we need to learn, so does coding create a compact reservoir of information that allows us to learn only what is most important to be fully educated and in turn, humanistic.
I would also add, that the way we work with computing methods to code humanities-based texts makes it both humanities _and_ computer science work. As I believe Ramsay discusses in his articles, the two are not mutually exclusive. Just because we are working specifically with humanities in this class does not mean that we are not also studying computer science. How can you say we are not studying computer science with all the coding we have learned? While the type of coding we are learning is based on how it can be used to study the humanities, that does not mean that what we are limited to being humanities scholars or that we do not understand there is more to the world of computers than just the way we use it. 
For example the New Analysis that we are doing will help us to study the linguistics in the humanities side of the class, but the methods we use to understand the language is news articles is are distinctly based in the computer science side of the class. So, our projects and the class itself allows us to educate ourselves in both humanities and computer science, thus making us all more humanistic.

**Comment by Samantha-Mcguigan** [comment]
I like what @jonhoranic stated in his comment : "I think the best way to find that merge point is to play on reasoning and creative thinking, because these two things are essential to the most basic levels of these fields"  The reasoning and creative thinking required for both the humanities and coding is what makes them both inherently humanistic. The use of coding in humanities allows us to understand more about our research in the humanities than we could with out it. As Ramsay discusses, you do not need to be able to write well to understand literature. Similarly, we do not need coding to study humanities, but knowing how to use coding allows us study the humanities more efficiently.

**Comment by ahunker** [comment]
I found _DH and CS_ to be an interesting article to read. I agree with @jonhoranic about this piece, that it is trying to define and separate computer science, programming, and digital humanities. That they're connected but different. I liked your "All bananas are plantains, but not all plantains are bananas" example, it perfectly described what I was trying going to try to explain. Yes, digital humanities use many aspects of computer science, but not all of digital humanities fits underneath computer science. Digital humanities are more human, it's based more on our own interpretation of literary works. We could all tag the same book structurally, but when we analyze it, same as when we write essays, it will vary from person to person as to what they believe the author is trying to convey or what literary devices are the most important to note. This really linked into _In Praise of Patttern_. He talks about how most sciences follow a specific structure when researching and analyzing specific things. They know what they're trying to find out. Stephen mentions how while we analyze things in humanities, like literature, we often find patterns we weren't looking for in the first place, similar to what @bsf15 mentioned above when discussing _The Hermeneutics of Screwing Around; or What You Do with a Million Books_. I really like this aspect of humanities in comparison to computer sciences. No matter how many times I read a book or poem or article, I always find some new aspect to it, often when I'm not looking to find it in the first place. I'm finding that the more I listen to the _Hamilton_ soundtrack and read over the lyrics, I'm thinking of new patterns we could look at and different ways we could try to visualize represent them.

**Comment by ebeshero** [comment]
A major question for me is what is happening to the "boundaries" between disciplines...Do we pioneer "scientific methods" in the humanities when we work on pattern analyses? Or do we bring humanities to the computer sciences as an application for creative *and* scientific expression and processing?
