### ISSUE TITLE
XSLT 2

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#284]
In the directions it says that the only thing we need to change at the top is to add the `<xsl:output>` line and it should look like this:

   ```
       <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
```

but if the only thing you change is adding the `<xsl:output>` line it looks like this:

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
```
So I'm confused should we delete the whole thing and copy and paste the example from the directions? Or follow what it tells us to do and just add in the one line?

**Comment by Samantha-Mcguigan** [comment]
Also the directions say:

Then create separate template rules that match on each of the inline elements. 

Are inline elements those that appear inside the body? Does that mean that inside the new xsl template rule that match should equal "body"? So it looks like

`<xsl:template match="body">`

**Comment by RJP43** [comment]
@Samantha-Mcguigan so just go ahead and remove the top matter of your XSLT and replace it with what we give you in the assignment (@ebeshero and I will need to look over that bit of the assignment to clarify the language there for future students). 

As for your other question... The inline elements are all sitting inside of either  `<articleBody>` or `<head>` You will need to approach this with the many to one versus one to many thought process that we mentioned in class. Since there is one and only one body element it makes sense to call on `<articleBody>` in the match on the document node (where you are laying out your HTML structure).   

You might also want to make an apply-templates selection on the `<head>` element above where you are selecting on the entire `<articleBody>` OR you can make a single selection on what holds both the `<articleBody>` and the `<head>` elements: `<root>` but being cautious of how to no output the `<toneElements>` since these are not an actual part of the article text but it also sits within `<root>`.   

Once you have told XSLT to output the entire `<articleBody>` and `<head>` elements **ONCE** within your HTML structure if you run the XSLT you will just see the entire text of `<head>` and `<articleBody>` plopped into your HTML. Now you will need to write the template matches to grab on inline elements wherever and however many there (**this is the many part hence why they each get processed in new template matches**).   

So if you want to process the paragraphs you will match on the `<p>` elements: `<xsl:template match="p">`  and so forth for each of the inline elements you want to process

**Comment by Samantha-Mcguigan** [comment]
This is what I have so far:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    
    <xsl:template match="/">
        <html>
        <head>
            <title>HTML Transformation of 1888-07-30 Nelson Article</title>
        </head>
        <body>
            <h1><xsl:apply-templates
                select="descendant::newspaperTitle"/>
            </h1>
            <h2><xsl:apply-templates
                select="descendant::seriesTitle"/>
            </h2>
            <h3><xsl:apply-templates
                select="descendant::head/date"/>
            </h3>
            <h4><xsl:apply-templates
                select="descendant::byline"/>
            </h4>
            <p><xsl:apply-templates
                select="descendant::articleBody"/>
            </p>
        </body>
            </html>
</xsl:template>
  <html>
    <xsl:template match="toneElements"></xsl:template>
    
    <xsl:template match="root">
      
      <xsl:template match="nellVoice">
          <xsl:apply-templates/><span class="nellVoice"></span>
      </xsl:template>
    </xsl:template>
</html>
</xsl:stylesheet>
```

And I'm so confused! Are you supposed to put an `<xsl:template match="">` inside another one? I don't understand what the point is of having a `<xsl:template match="root">` . Why do we not just match on what we need to apply templates to? None of this is making sense to me! Please Help!

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Uh oh! I see why you're confused...What @RJP43 meant by `<root>` is your template match you've already written on the document node: your `<xsl:template match="/">`. You've already written that. (It just happens to match on the `<root>` element of our source XML. 

So, **no** you don't need to write another template to match on the `<root>` element. 
And, no, we don't ever nest `<xsl:template match="">`. We set one at a time. The one template match that is very special when transforming from XML to HTML (or some other kind of markup language) is the one that matches on the document node (sometimes called "root"), because it handles the conversion of the top-level structural elements: sets up the root element to be HTML and sets up its head and body. 

Later template matches are for processing elements like paragraphs and internal items that appear multiple times throughout a file. Write one template to match on any `<p>` wherever it lies, and that will process all of them (so long as there's an <xsl:apply templates/> up in the document node that says go and apply template rules from this point onward).

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Your first template match is setting up your HTML document, and that looks very good! So you don't need or want the `<html`> element that you've set **after* that point. And you don't need a template match on root. What you want to start writing are template matches on the specific elements of `<articleBody>` that you want to process specially so they appear within their own HTML tags.

**Comment by Samantha-Mcguigan** [comment]
okay I think I'm understanding a bit better now. I think I was just reading the directions wrong. So this is what I have now:

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    
    <xsl:template match="/">
        <html>
        <head>
            <title>HTML Transformation of 1888-07-30 Nelson Article</title>
        </head>
        <body>
            <h1><xsl:apply-templates
                select="descendant::newspaperTitle"/>
            </h1>
            <h2><xsl:apply-templates
                select="descendant::seriesTitle"/>
            </h2>
            <h3><xsl:apply-templates
                select="descendant::head/date"/>
            </h3>
            <h4><xsl:apply-templates
                select="descendant::byline"/>
            </h4>
            <p><xsl:apply-templates
                select="descendant::articleBody"/>
            </p>
        </body>
        </html>
    </xsl:template>
    <xsl:template match="nellVoice">
        <span class="nellVoice"><xsl:apply-templates/></span>
    </xsl:template>
    
</xsl:stylesheet>
```
I guess my only concern now is that this:

```
    <xsl:template match="nellVoice">
        <span class="nellVoice"><xsl:apply-templates/></span>
    </xsl:template>
```
is only outputting `<span class="nellVoice">` where there is a `<nellVoice>` element and none of the attributes that are inside the element. Is that okay?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Good! Yes, that looks much better. Right, you won't be able to capture the attributes in the source XML *unless* you write them in as new attributes over in HTML. Think about whether you'd like to do that. (What are some of the attribute values we're not processing here?)

Usually when we transform from XML to HTML we lose some detail we coded, and it's because we make judgment calls about what matters most to represent. The assignment sheet here does some of that by saying don't process this or that part of the file. Sometimes we lose some of the detail of attribute values, but there will always be a way to output it. One way might be nesting `<span>` elements or adding an `@title` attribute to sit alongside the `@class` attribute, since you can grab those with CSS in similar ways. For one project, I remember I found a way to mash together a couple of attribute values into one `@class` like this:

Say my source XML reads: `<ref type="location" subtype="underground">trenches for pipelines</ref>`. (I'm just making this up on the spot).  And for my HTML output, I just want a convenient way to highlight and style all the references to locations, and have the underground and aboveground ones come out with different colors. Just to keep the HTML output simple without so many attributes, I write an xsl:template like so:

````
<xsl:template match="rs[@type]">
<span class="{@type}_{@subtype}"><xsl:apply-templates/></span>
</xsl:template>
````
Now, when I process an rs with an `@type="location"` and an `@subtype="underground"` it comes out in the HTML like this:
````
<span class="location_underground">trenches for pipelines</span>
````

See how that works? I can actually set *two* attribute value templates in curly braces to read the attributes on my source `<rs>` element, and if I want to, I can put a little string of text in between them. Or I could separate them with white space! In my CSS I can write rules that help me process these the way I want to, so all the elements that have `@class` that contains the string `location` come out underlined, and all of them that *also* contain the string `underground` are colored brown.

**Comment by Samantha-Mcguigan** [comment]
For the rest of the assignment so far I have:

```
    <xsl:template match="nellVoice">
        <span class="nellVoice"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="workingConditions[@category='toneElements/category[@tone]']">
        <span class="{@tone}"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="unclear">
        <xsl:text>[missing word(s)]</xsl:text>
    </xsl:template>
```
and the only results I am getting in my output are for the `<span class="nellVoice">` elements and for that my CSS looks like this

```
span.nellVoice{
color:green;
font-family:arial, helvetica, sans-serif;
}
```
but I'm not getting any results with that either. I don't even know where to begin at this point

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I'm taking a look now! On first glance, I think there's something amiss with that template match on workingConditions: the predicate looks funny. 

How much output are you getting? Are you processing the output from the first template match (on the document node) okay? 

Have you associated your CSS file with your output HTML? (You can actually write that link association line right into your XSLT stylesheet where you've written up your `<head>` element.)

@jonhoranic  and @ahunker  Want to help me troubleshoot this?

**Comment by Samantha-Mcguigan** [comment]
I am not getting any output for workingConditions at all. The first template match on nellVoice is working just fine. I did associate my CSS file inside the head element. This is my entire code:

```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math" exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml" version="3.0">
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    
    <xsl:template match="/">
        <html>
        <head>
            <title>HTML Transformation of 1888-07-30 Nelson Article</title>
            <link rel="stylesheet" type="text/css" href="mcguigan_Feb_27_XSLT_2_CSS.css"/>
        </head>
        <body>
            <h1><xsl:apply-templates
                select="descendant::newspaperTitle"/>
            </h1>
            <h2><xsl:apply-templates
                select="descendant::seriesTitle"/>
            </h2>
            <h3><xsl:apply-templates
                select="descendant::head/date"/>
            </h3>
            <h4><xsl:apply-templates
                select="descendant::byline"/>
            </h4>
            <p><xsl:apply-templates
                select="descendant::articleBody"/>
            </p>
        </body>
        </html>
    </xsl:template>
    <xsl:template match="nellVoice">
        <span class="nellVoice"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="workingConditions[@category='toneElements/category[@tone]']">
        <span class="{@tone}"><xsl:apply-templates/></span>
    </xsl:template>
    <xsl:template match="unclear">
        <xsl:text>[missing word(s)]</xsl:text>
    </xsl:template>

    
</xsl:stylesheet>
```
I don't know what I'm doing wrong but no matter what I try I am not getting any output. Sorry for all the questions but nothing is working.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I just ran it, and *most* of it is working (for code), but I didn't try experimenting with the CSS (don't have the file). You could try pushing it to Troubleshooting here on the DHClass-Hub.

So, I see that the template match on `<unclear>` is working, and so is the match on `<nellVoice>`. You might try controlling the formatting a bit and preserve the `<p>` elements from the XML. Since there's no rule for those, XSLT by default just spits out plain text, so we're losing that. 

Now the problem is `<workingConditions>` and the reason it isn't processing is because the template rule match doesn't yield anything to match on. Think about what the `@category` on workingConditions is supposed to match up to up in the toneElements list. Isn't that `@category` value supposed to match an `@id` in that section? If so, the part after the = sign has to lead to the attribute (and not to the contents of the category element, which is how it's leading now).

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Since I've got hold of your file now, and *most* of it is working, I'm just going to delete it from this Issues board so we're not giving too much away to the others! :-) We've isolated the problem spot now, right?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan A couple of things are going wrong here:

````
<xsl:template match="workingConditions[@category='toneElements/category[@tone]']">
````
You have the right idea to look up to see what XPath *is equal* to the value of `@category`, but you don't want to put that XPath in single quotes b/c the computer thinks that's a literal string and not an XPath. 

The next thing that won't work, though, is the **start** of that XPath. toneElements is sitting **way** up the tree in relation to workingConditions. I'd recommend setting that XPath expression to start from the document node (or root) and just look down the tree to toneElements. How do you start an XPath from the document node?

Now, there's something more that's problematic about the `@class` attribute on the `<span>` element, but let's first get you matching successfully.

**Comment by Samantha-Mcguigan** [comment]
yes, thank you for your help! I will start working on it again!

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Don't feel badly about this: It's the hardest part of the assignment! Also, I think we should be explaining it more clearly. There's a part of it that I don't think we're preparing you well for. When you *do* make the match on the template rule, we're going to have to write the XPath kind of in reverse on the `<span class="{}">` attribute value template, and for that you need a way to:
1) set the `@class` so it's walking down from `toneElements` to reach the `@tone` attribute you want, considering that
2) That `@tone` is sitting *on the `<category>` element whose `@id` equals* the **current** workingCondition element's `@category. 

To write this, you actually need something I don't think we showed you in the XSLT tutorial or this assignment. It's a notation in XSLT called **`current()`**, and it refers to the **current** element being processed in a template match. Keep in mind that XSLT is matching on each `<workingCondition>` element in turn, and each of them have different `@id` attributes. In cases like this, `current()` indicates the **one** `<workingCondition>` element you've stopped on. 

I'm going to ping the others, because this is a tough patch for everyone, and I really need to write up something more in this assignment sheet to lay out how to write this. So this is what I'd be adding: info about how to work with `current()` in XSLT!
