### ISSUE TITLE
XQuery #1

### ISSUE THREAD

**Issue by ajnewton1** [ebeshero/DHClass-Hub#286]
For the second question, wouldn't you have to use contains() as well as count() and distinct-values()

**Comment by ahunker** [comment]
If you're talking about the second question, you really only need to add text() or data() or string() to the end of the expression for question one. I think you meant to say question three though and for that one I used a predicate statement and put count() and distinct-values() inside square brackets. That seemed to work for me.

**Comment by ahunker** [comment]
So I'm struggling with both the tokenize() and FLWOR in questions 4 and 5. The problem I'm having with tokenize() is I'm not sure where to put it in the XPath expression. This is what I currently have:
`collection('/db/shakespeare/plays')/PLAY[count(distinct-values(.//SPEAKER))gt 40]/TITLE/base-uri()`
I tried doing this:
`collection('/db/shakespeare/plays')/PLAY[count(distinct-values(.//SPEAKER))gt 40]/TITLE/base-uri()/tokenize("/","\s")[last()]`
But that doesn't work. I think it's because base-uri() isn't a step down the tree in the document and trying to add tokenize onto the end causes the error. In regards to FLWOR, I don't know what I'm doing. I've read through the different tutorials and I'm not any closer to understanding it. I tried playing around with it, and I've reached this point:
`let $shakespeare := doc('/db/shakespeare/plays')
let $TITLE := $shakespeare/PLAY[count(distinct-values(.//SPEAKER))gt 40]/TITLE
return $TITLE`
It doesn't return anything, but it doesn't give me any errors. Am I on the right track with this or am I completely lost?

**Comment by ajnewton1** [comment]
I am not sure about the tokenize part but for your last one, this is what I have.
`let $shakespeare := collection('/db/shakespeare/plays')
let $play := $shakespeare/PLAY[count(distinct-values(.//SPEAKER)) gt 40]
return $play/TITLE/text()`

**Comment by ajnewton1** [comment]
@ahunker do you still need help with the tokenize function

**Comment by ebeshero** [comment]
@ahunker and @ajnewton1 The problem, I think, is just your formulation of the `tokenize()` function! Remember, this is one of the string functions, a little like `contains()` and `matches()`, in that you set it up with two arguments. The first argument refers to **the thing you want to tokenize** which is what you're stopping on, and the second argument is the character you want to use as a divider. In this case, we tokenize() on a slash to break the result of base-uri() into pieces... I'd put the base-uri() function *inside* tokenize() as the first argument. So walk down the tree to the point you want to stop, then take the tokenize() function to break the base-uri(.) into pieces, and take the last piece... Hope that helps!

**Comment by jonhoranic** [comment]
I am having similar issue with the tokenize function, no matter where I place it it either causes an error or just outputs the base-uri without breaking it up, I am confused as to where it needs to be placed.

**Comment by ebeshero** [comment]
@jonhoranic  I typically place it at the end of an expression. Stop at the end of a path-step, though. It won't work if you set it after the base-uri(), function. You'll need to take the base-uri() function *inside* the first argument of tokenize() for it to work.

**Comment by jonhoranic** [comment]
I now see my big mistake, I was putting quotation marks around base-uri() function and that was what was causing the issue! It will still fire, but the results were so wrong I thought I must have been misunderstanding. All good now!
