### ISSUE TITLE
Div Naming? And CSS Selectors

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#29]
Hey, does anybody remember how we are to assign specific names to each div element so that the CSS can modify each individual one? I think it had something to do with `div#top` , I only remember there is something with a hashtag.

**Comment by ebeshero** [comment]
In HTML you can give a div element an @id attribute like this:
 ` <div id="top"> `.  And then in your CSS you can refer to an element with an @id attribute by using that hashtag notation just as you did here: the hashtag is shorthand for an @id in HTML. 
 `div#top ` is a CSS selector for  ` <div id="top"> `.

**Comment by ebeshero** [comment]
Here's a handy reference page on all the CSS selectors (maybe worth bookmarking). It shows LOTS of things you can do with CSS with the right selectors. For example, you can actually use CSS to insert a string of characters right before or after an HTML element! And this shows you how you can select any element with any attribute.

http://www.w3schools.com/cssref/css_selectors.asp

The hashtag notation and the dot notation in CSS are just standard abbreviations for @id and @class, since these attributes are very common in HTML. To specify other attributes, you can put them inside square brackets, and the page shows you different things you can do: you can specify all the elements that just have a particular attribute, or elements with that attribute when its value is something you specify. And you can even select just PART of an attribute value, so all the div elements with an @type attribute that *starts with* the letters "en".  Check it out on the handy chart. I don't try to memorize these, but whenever I am styling a webpage I hunt up a chart to review how to write the CSS selector I need. It's good to know something of the variety of things you can select!
