### ISSUE TITLE
SVG 2

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#295]
@ebeshero 
This is what I have so far:

```
xquery version "3.0";
      declare default element namespace "http://www.w3.org/2000/svg"; 
      declare namespace tei="http://www.tei-c.org/ns/1.0";

declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterFiles := $lettersColl/*;
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1];
declare variable $distinctYears := distinct-values($letterDates);
declare variable $minDY := min($distinctYears);
declare variable $maxDY := max($distinctYears);
declare variable $years := xs:integer($maxDY) - xs:integer($minDY);
declare variable $days := $years* 365;
declare variable $DYears_Integers := 
  for $i in $distinctYears
  order by $i ascending
  return xs:integer($i);
declare variable $LettersPerYear := 
for $i in $distinctYears
let $LPY := $letterDates[//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when/tokenize(string(), '-')[1] = $i]
let $countLPY := count($LPY)
order by $countLPY descending
return $countLPY;

  <svg width="500" height="3000">
   <g transform="translate(30, 100)">
      <line x1="25" y1="0" x2="25" y2="{$days}" style="stroke:black;stroke-width:5"/>  
      
         {
           for $i in (0 to $years)
    return
        <g>
            <line x1="25" y1="{$i*365}" x2="50" y2="{$i*365}" style="stroke:black;stroke-width:5"/>
         <text x="50" y="{$i*365}">{$DYears_Integers}</text>
         <circle cx="50" cy="{$i*365}" r="{$LettersPerYear}" stroke="red" fill="purple" stroke-width="4"/>
         </g>
        
         }
        
         
   </g>
   
</svg>
```
and in my output the text I'm getting for each line is a list of all the years instead of one for each of the lines and a similar thing is happening with my circles, for the radius I am getting a bunch of the number 60 in a line. here is an example:

```
<g>
<line x1="25" y1="1460" x2="50" y2="1460" style="stroke:black;stroke-width:5"/>
<text x="50" y="1460">1818 1819 1820 1821 1822 1823 1824 1825</text>
<circle cx="50" cy="1460" r="60 60 60 60 60 60 60 60" stroke="red" fill="purple" stroke-width="4"/>
</g>
```
I'm not sure how to fix this. Do I need a for loop inside the svg elements?

**Comment by Samantha-Mcguigan** [comment]
Okay so I got how to do the years by I'm still stuck on the circles, I think there is something wrong in my declare variable

**Comment by ebeshero** [comment]
@Samantha-Mcguigan As you noticed, you are outputting a whole array of all the dates, and you want just one date--but you don't want to make a second loop in here (or you'll still be outputting every year at each hashmark). 

Whey you want is, for each of your current $i, to output just the year that it corresponds with. Your for-loop ranges from 0 to the total count of years (a single digit, I think). What if you added $i to one of your variables, the one designating the lowest actual four-digit year?

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I'm sorry I don't understand. Do I need to change `declare variable $minDY := min($distinctYears);` to have $i in it somewhere?

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I tried  adding `for $u in $DYears_Integers` and returning `<text x="50" y="{$i*365}">{$u}</text>` which kind of works but it outputs too many lines

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I was asleep--sorry! No, you don't need any more for-loops, because as you see, you will output too many lines.

What I was saying was just to think about the value of $i in that one really important line:
`for $i in (0 to $years)`

That is a value that comes out, 0, 1, 2, 3...etc.

It is doing what you want to plot hashmarks because you can multiply it by 365 (our spacer). But now you want it to output the actual year. The value of your `$minDY` offers some help: it is just *one* value, and doesn't need a for-loop. What if you work with the single, stable value of `$minDY` insude your for-loop `for $i in (0 to $years)` to calculate the year at each step? How can you use the value of $i together with `$minDY`  to tell you what year it is at each hashmark?

**Comment by Samantha-Mcguigan** [comment]
@ebeshero so I added this: `declare variable $year:= xs:integer($minDY);` to the global variables and was able to output the years by doing this:
    ` <text x="50" y="{$i*365}">{$year+$i}</text>`
but I'm still stuck on how to fix the circles

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Good: You've got the years.
The global variable you're using for the count of the letters isn't calculating what you want. It's looping around and getting the same results on every year--and I think the result is simply the total count of all the letters in our collection. I think I'd just delete that global variable because it isn't helping.

At this point in your SVG output, you want to be returning a single value: the count of all the letters in the particular year that matches up with your $i.  You've worked out how to match the year with $i, so that's the first part. Now you need to reach through the tree in the eXist-db and find all the letters whose dates match the year you're on in the loop: 
(As you just figured out, the year you are standing on in the loop is  `$year+$i` or `$minDY + $i`). 
Find the letters whose dates match just the year you're on, and count them. I'd do that inside this FLWOR and not with a global variable, since the count depends on your context.

**Comment by ajnewton1** [comment]
You can also get the radius by counting the ````$letterDates```` that contain ````$minDY + $I````as well and that will fit right inside the quotes of ````r=""````

**Comment by Samantha-Mcguigan** [comment]
I have `count($letterDates[$year+$i]) `inside `r="" `but I'm getting 0 for everything

**Comment by ajnewton1** [comment]
try to use the ````contains```` function and see what you get

**Comment by Samantha-Mcguigan** [comment]
WHOOO! I got it Thank you @ajnewton1 and @ebeshero you guys are the best!!!

**Comment by ahunker** [comment]
I know it's late, but I could use some help with my code. I've got it working but it's outputting way too many years. My timeline starts at 1818 but it continues on until 4373. I've been staring at this code for a while so I could use a second set of eyes to pick out what's wrong.
`declare variable $mitfordColl := collection ('/db/mitford');
declare variable $lettersColl := collection('/db/mitford/letters');
declare variable $letterDates := $lettersColl//tei:teiHeader//tei:msDesc//tei:head/tei:date/@when;
declare variable $letterYears := $letterDates/tokenize(string(), '-')[1];
declare variable $distinctYears := distinct-values($letterYears);
declare variable $NumOfYears := count($letterYears);
declare variable $minDY := min($distinctYears);
declare variable $maxDY := max($distinctYears);
declare variable $yearSpan :=  xs:integer($maxDY) - xs:integer($minDY);
declare variable $yearsIntegers := 
  for $i in $letterYears
  order by $i ascending
  return xs:integer($i);
declare variable $lineLength := $yearSpan * 365;
declare variable $eachDate :=
    let $distinctYears := distinct-values($letterDates)
        for $distinctYear in $distinctYears
        order by $distinctYear
        return $distinctYear;
declare variable $year:= xs:integer($minDY);
<svg width="500" height="3000">
   <g transform="translate(30, 100)">
        <line x1="50" y1="0" x2="50" y2="{$lineLength}" stroke="goldenrod" stroke-width="10"/>
    {for $i in (0 to $lineLength)
    return
        <g>
        <line x1="50" y1="{$i*365}" x2="75" y2="{$i*365}" stroke="purple" stroke-width="3"/>
        <text x="60" y="{$i*365}">{$year+$i}</text>
        <circle cx="75" cy="{$i*365}" r="{count($letterYears[contains(.,$year+$i)])}" stroke="purple" fill="pink" stroke-width="4"/>
        </g>
    }
    
   </g> 
</svg> `

**Comment by ebeshero** [comment]
@ahunker I'm taking a look...

**Comment by ebeshero** [comment]
@ahunker That `$lineLength` variable is the problem! It's causing you to output a year on every single *day* over the span of years...

**Comment by ahunker** [comment]
It's working now, thank you!
