### ISSUE TITLE
ssi and javascript exercise 1

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [ebeshero/DHClass-Hub#300]
I'm not sure where to find the ssi test folder. I'm in fetch in my folder but I don't see it

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Oops! That's an old line on the assignment page and I should remove it. (I see that we mentioned an "SSI-Test" directory that we'd place in your website directory, and we never did that.) You don't need one. Just post the ssi file to your webspace, and invoke it with your server side include line in one or more files there. And you need to change the properties on your files so the include will be activated when someone loads a page.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Thank you (as usual) for spotting our error! :-)

**Comment by ebeshero** [comment]
I've just removed the outdated material and updated the assignment page--so perhaps we'll save others from unnecessary confusion! :-) http://newtfire.org/dh/JavaScript_SSI_Exercise1.html

**Comment by Samantha-Mcguigan** [comment]
I'm trying to do the thing in the example where you click the button and I'm not sure why it is not working. This is my html file:
```
<!DOCTYPE html SYSTEM "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>My first JavaScript script</title>
        <script type="text/javascript" src="samanthaMcGuigan.js">
            /**/
        </script>
    </head>
    <body>
        <div id="links">
            <!--#include virtual="top.html" -->
        </div>
        <h1>JavaScript is fun!</h1>
        <p class="paragraphToToggle">This is a paragraph.</p>
        <div><button>Show/Hide</button></div>
        <p>This is another paragraph.</p>
    </body>
</html>
```
and this is my JavaScript:

```
var buttons = document.getElementsByTagName("button");
var button = buttons[0];
button.addEventListener('click',show_hide,false);

function show_hide() {
    if (document.getElementByClassName("paragraphToToggle").style.visibility = "visible") {
    document.getElementByClassName("paragraphToToggle").style.display = "none"
} else {document.getElementByClassName("paragraphToToggle").style.visibility = "visible"
}
}
```

**Comment by ebeshero** [comment]
@Samantha-Mcguigan This is really close, but you're missign something important to set a sequence of functions in motion over the objects on your HTML page. Basically you want to be writing *a series of functions*:

1) You need something to activate your JavaScript functions when the window loads your document. You need this line to set a sequence of functions in motion:
````
window.addEventListener('DOMContentLoaded', init, false);
````
That line says, when the window loads the Document Object Model (or the Document Object), go and fire a function we're calling "init". (That's kind of a standard, conventional name for the first, **initial** function we want to fire.) That function should contain your activation of the Event Listener on your button. So you want to write that stuff you have on the buttons as your function init, like so:

````
function init() {
var buttons = document.getElementsByTagName("button");
var button = buttons[0];
button.addEventListener('click', show_hide, false);
}
````
See how I just added that stuff into a function that's designed to fire when the page loads?

Okay...the next thing that happens in the sequence is, that when someone clicks on your button at position zero (the one and only button), you want to make the `<p class="paragraphToToggle">` appear or disappear. So that's your show_hide function, which you've properly written here, *except* for one crucial part. You've got the right idea to toggle a CSS style for either display or visibility, but I'm not sure I'd mix these two. Also, the values you're setting for "visible" are not actually proper CSS values for the visibility property. You want to take a look at the values you can work with that the web browser will understand: For CSS visibility, see https://www.w3schools.com/cssref/pr_class_visibility.asp 
And for CSS display, see https://www.w3schools.com/cssref/pr_class_display.asp

Hope this helps!

**Comment by Samantha-Mcguigan** [comment]
I have:
```
window.addEventListener('DOMContentLoaded',init,false);
            
function init() {
    alert('The page loaded!');
    }
window.addEventListener('DOMContentLoaded',init2,false);
            
function init2() {
var buttons = document.getElementsByTagName("button");
var button = buttons[0];
}

button.addEventListener('click',show_hide,false);
function show_hide() {
    if (document.getElementByClassName("paragraphToToggle").style.display = "block") 
    {
    document.getElementByClassName("paragraphToToggle").style.display = "none"
} else {document.getElementByClassName("paragraphToToggle").style.display = "block"
}
}

```
and I'm  getting a pop up window when I load the page but the button isn't working. I think its because my `function init2 () `is not set up correctly?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan  Aha! You just need to set your event listener inside function init2(). It can't be outside the function--because it's actually a scripted event to set a LISTENER on an HTML element. Your function init2() says, make me a variable named "buttons" and then should say, MAKE the zero-eth button (the  one and only button on the page) be sensitive to user clicks!

**Comment by ebeshero** [comment]
By the way, tomorrow I'll show you how to make multiple buttons sensitive to clicking--basically we set up a for-loop in JavaScript...

**Comment by Samantha-Mcguigan** [comment]
Its still not working :(

```
window.addEventListener('DOMContentLoaded',init,false);
            
function init() {
    alert('The page loaded!');
    }
window.addEventListener('DOMContentLoaded',init2,false);
            
function init2() {
var buttons = document.getElementsByTagName("button");
var button = buttons[0];
button.addEventListener('click',show_hide,false);
function show_hide() {
    if (document.getElementByClassName("paragraphToToggle").style.display = "block") 
    {document.getElementByClassName("paragraphToToggle").style.display = "none"} 
    else {document.getElementByClassName("paragraphToToggle").style.display = "block"}
}
}
```

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I think you need a closing curly brace at the end of function init2. Looks like it was moved to the end of your file?
