### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by gabikeane** [ebeshero/DHClass-Hub#326]
Use this issue to introduce yourselves!  I'll go first.

Note: Try using some markdown to style your response.  In mine, I've included a link.  You can find Github's Markdown guide by clicking the link below the comment box.  It's also available [here](https://guides.github.com/features/mastering-markdown/).

**Comment by jonhoranic** [comment]
Heyo from UPG!

**Comment by gabikeane** [comment]
Hello!  I'm Gabi Keane, one of your UTAs at Pitt--Oakland.  I'm an English literature and nonfiction writing major.  My previous research project for this class was a [Linguistic Analysis of Victorian Ghost Stories](ghost.obdurodon.org).  I really enjoy researching the history of print media technology, how information (and more importantly, misinformation) travels, and the culture of information consumption.  

When I'm not doing DH things, I like to read, dance, and annoy my friends by falling asleep during movies.  If I had to name a server after an animal (becoming a common, and honestly best, practice), my server would be nibblestheguineapig.org.  Not a very good name, I know.

**Comment by ebeshero** [comment]
guineapig.org by itself seems like a pretty awesome companion to newtFire or obdurodon...:-)

**Comment by miam1997** [comment]
Hello from UPG! Welcome!

**Comment by ebeshero** [comment]
We are hanging out in our classroom before our class begins at 10:30. To learn how to write Markdown for these GitHub Issues, click on the "Styling with Markdown is supported" line on the bottom left of an issue. (Or here's the link directly: [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) )

**Comment by zme1** [comment]
Hello!!!! I'm Zachary Enick, one of the student instructors on the Oakland campus. I just started my fourth year at Pitt, but I am not slated to graduate until 2019 because I added a minor and certificate late in the game. That said, I am a dual-major in French and Italian language studies with a minor in Linguistics and a certificate in ASL. I also sing in the Heinz Chapel Choir and in Pittch Please. The chances are high that you have seen me biking around Oakland or working at the bookstore at some point...

 Last semester as a student, 3 other digital humanists and I collaborated on Immigration Station (immigration_station is our repository name on GitHub if you want to explore it at all). I am pumped to keep learning this year and see how the class develops over the span of the semester!!

**Comment by mof11** [comment]
Hey, my name is Monica Felix and I'm a student at Pitt Oakland. I am majoring in finance and have a minor in Italian. I also know Spanish and some ASL.  This December is when I will be graduating (a semester later than planned due to changing majors my junior year). Student organizations that I am involved include Alpha Kappa Psi (business fraternity) and Alpha Delta Pi. In my spare time, I like doing hot yoga, watching anything on National Geographic, and spending time with my little sister, Mikaela.

**Comment by pab124** [comment]
Hello, my name is Patrick Brooks and I currently attend Pitt in Oakland as a Linguistics Major. If all goes as planned, I will be graduating at the end of this semester having been here for two years after transferring. The most interesting classes I've taken at Pitt thus far are under the Irish language and I would strongly recommend anyone check them out if your schedule permits. Other languages that I've dabbled in while here at Pitt include Spanish, German, Portuguese, and Quechua. Outside of class, I highly enjoy reading (the Brothers Karamazov by Fyodor Dostoevsky) as well as doing many outdoor things, like canoeing, kayaking, fishing, hiking, and things of that nature.

**Comment by jub45** [comment]
Hello! I apologize for this late posting to our introductions board. My name is Justin Boros and I am a senior linguistics major at the University of Pittsburgh. I am currently in my seventh (!!) semester of Turkish and am getting quite fluent with it, and I have various degrees of fluency/comprehension in other languages such as Hungarian, Udmurt (Moksha dialect), Azerbaijani, Turkmen, Uzbek, Crimean Tatar and Bashkir. Outside of class, my hobbies include photography, astrophotography, playing/writing music and lapidary arts. While I do have some limited experience with GitHub, HTML and Unix scripting, it has been nearly 20 years since I have worked with them. I am looking forward to learning as much as I can in this class, and I can promise that my responses will be more timely from here on out. Yazımı okuduğunuz için teşekkür ederiniz! Herkese tanıştığımıza memnun oldum! :)

**Comment by ebeshero** [comment]
Welcome @jub45 ! :-) A few years ago, I knew another Pitt student taking DH and studying Turkish who went to live in Turkey for a while--that was @andrewntz23 and helped out with some of the newtFire exercises you'll be working on...he was part of the Russian Rap project on Obdurodon: [http://rap.obdurodon.org/](http://rap.obdurodon.org/) , but there was a [Turkish Rock project](http://turkish.obdurodon.org/) too, that another friend of our course, @alexkrongel was part of. Now and again our alumni and past friends of the DH courses pop in do say hello, and I think you'd enjoy meeting Andrew and Alex! :-)

**Comment by ebeshero** [comment]
@jub45 Care to translate those last two Turkic sentences? :-)

**Comment by jub45** [comment]
Absolutely! "Thank you for reading my writing and I am glad that we all have met!" :)

**Comment by amk231** [comment]
Hey everyone! I'm probably the last one to introduce myself on here but my name is Angela Klinger, one of the undergraduate instructors for the course. This is my senior year (Wooh!) here at the University of Pittsburgh. I started off on the archaeology track, but I have recently converted to the physical anthropology side after I took an amazing forensic anthropology course with Dr. Judd. Since then I have developed  bit of an obsession with doing skeletal trauma and paleopathology analysis. I am also working on a minor in history. 

Remember, if you ever need a little help out of class, especially as we get into bigger and better things :), you can email me or just show up at my office hours (M/W 1-2 PM).  I am looking forward to working with you guys this semester!

**Comment by BMR59** [comment]
Hi folks! My name is Brandon Rodgers and I'm a Pitt main campus Linguistics major with a Portuguese minor. This is my very last semester and I am extremely excited to graduate and (hopefully) secure a nice job. I'll admit I was really anxious about this class because I have zero coding background but I am feeling much more confident now! Outside of school, I'm a big fan of running around every where I can outside before winter starts.
