### ISSUE TITLE
Help With Name function

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#33]
Hey, I'm trying to use this: `//body//name(attribute::*)` but it won't work. Help?

**Comment by brookestewart** [comment]
Try `//body//@*/../name()` I believe this works correctly...

**Comment by KariWomack** [comment]
This just pulled up errors for me...:(

**Comment by RJP43** [comment]
trying simplifying even what @brookestewart suggests.... you want to tell XPath to go down throughout your entire document `//` and find all the attributes `@`.

Brooke and @CodyKarch you both are on the right track with the asterisk. You just don't need to over complicate it especially since you will want to build off this first expression of finding all of the attributes in order to get the names of those attributes. 

After you get the first part you very simply can get the second by telling XPath to now step further `/` and get the names `name()` 

Well Done Brooke jumping on these issues with your useful tips!
