### ISSUE TITLE
UX Discussion (for Friday 9/8)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#331]
**Choose one** of the following digital archives to explore its features. Spend some time investigating until you're reading some marked-up documents on the site (a manuscript page or an historical document or a poem, etc), and think about how markup was used to design this. Then write a post on this thread that addresses:
1) something interesting the site is inviting us to explore about centuries-old texts, and 
1) the effectiveness of the user experience (“UX”) in discovering, reading, and learning about these texts.

Archives:                
                    * [Shelley-Godwin Archive: Frankenstein Notebooks](http://shelleygodwinarchive.org/contents/frankenstein)
                                    * [Map of Early Modern London](http://mapoflondon.uvic.ca/index.htm)
                    * [Emily Dickinson Project](http://dickinson16.newtfire.org/) (made by Pitt-Greensburg students in 2015-2016)
                    * [The Homeric Hymn 7 to Dionysus within the Perseus Project](http://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0013.tlg007.perseus-eng1)

**Comment by flowerbee1234** [comment]
I decided to look into the Emily Dickinson project, since I heard about it when deciding to take the DH class. One thing this site does is look at Dickinson's use of dashes. Since the dash was Dickinson's signature mark, it is interesting to see when she did this most. The site uses a graph as a visual representation of this. Clearly, in Dickinson's collection of poems, centenary edition, she uses these dashes most, and this is probably because no editors could change them. I like the visual aids, although the bright color-choice hurts my eyes. Perhaps if they adjusted the background color, it would easier to read and comprehend. Regardless, this is a nice, useful tool when comparing two or more sources. They also have a network analysis, which requires its own form of reading.

**Comment by Jamielynn92** [comment]
I've decided to look at The Map of Early Modern London, because I always enjoy information about London. The one thing I enjoy about this project is that you can interact with the London map. When you tap on a location on the map, it tells you what it is and whether or not there's more information on that place or not. Also if there is, it has a link where you can check it out. I appreciate that. Its a very thought out map. Although there isn't much information from the other links other than what source was used, but it doesn't bother me very much. The details in the map make up any lack of more 'reading' sections. The background is an easy one to look at. There's even a link where you are able look at his different ways of XML. I like this one very much.

**Comment by quantum-satire** [comment]
The Shelly-Godwin Archive was a pleasure to navigate and to use; with a friendly interface and a professional level of quality applied to it, I was really impressed by this site in particular because of the amount of work and effort that had clearly been put into it. What I loved the most is the top bar, which gives the visitor a copious amount of information, including the author, the date it was written, what state the file was in, its transcription status, and some other useful tidbits. 
![screen shot 2017-09-07 at 6 54 49 pm](https://user-images.githubusercontent.com/28074589/30188774-49d3b08e-93fe-11e7-8515-e31e8ef2a9e2.png)
The Archive invites its visitors to explore the texts hosted by allowing the viewer to see which words were written by a particular author, which words had been crossed out or annotated in, and gives the viewer the ability to have both the plaintext and the image side-by-side so that they will not have to "translate" what the handwriting says.

**Comment by pab124** [comment]
I looked into the Emily Dickinson Project, mainly because it seemed the most interesting topic of the selections and as well as the fact that I like her "Because I could not stop for Death." The project sought to find and illuminate the differences between the different editions of the poems as they were published and then analyzed the reactions of the differences. They paid a good deal of attention to the deletion or alteration of dashes throughout the poetry, which is interesting in that poetry, often being such a concise and specific medium, has very specific intentions in every aspect of the work. The project mentions the multiple and various readings that are available upon the alterations of the poems, even down to the replacement of a dash with a comma. I'm not an English Lit major or anything like that, but it is very interesting to see that the project displays the significance of the alterations in different editions of the poetry. 
As for the User eXperience, the project is pretty accessible and not difficult to navigate. It's rather straightforward in its presentation of the data and material and, as flowerbee1234 mentioned, the visual aids are a little on the flashy side. The only other minor detail is the over-sized initial letter in the sections as they're a little hefty. Other than that though, the display is easy to read, navigate, and comfortable to experience.

**Comment by tal80** [comment]
I chose to look at the Map of Early London. The site is very simple to navigate and find your way around to resources via main tabs at the top.  You have various options to select to filter and show what you want to see on the map and where it is located.  The main page of the map gives you a short introduction into the map and also the map is constructed. There are a lot of options to explore on the website but the map, which is the main focus of the site, is very easy to find and navigate. The creator of the website also always has the XML of the site linked on the side of the page.

**Comment by BMR59** [comment]
As a fan of Greek mythology, I decided to explore the Perseus Project. The site seems relatively simple in regards to navigation and appearance, and I was excited to see display options available for translation options (though after fooling around with them I realized I didn't know how they worked). I appreciated the XML viewing options, too. What interested me most was that the site extracts references and locations and provides links to explore other texts which contain them, too. Overall, while the site seems easy to navigate, there is a lot going on and it feels like a lot to take in at once. Some of the options were confusing and appeared (to me) to not affect the page, such as the display options.

**Comment by kes213** [comment]
I took a close look at the Agas Map of Early Modern London’s website, and I found it very interesting. In one tab, I was able to read through a bunch of very interesting documents, such as proclamations, excerpts from biographies and non-fiction works, poetry, etc. that was published by famous writers during the early 1600s. This website, however, does more than provide a place for a reader to find historical documents and read them; it gives readers a visual image of where these documents were published and what environment the writers would have been in as they worked. You can see where churches and town halls were located and how far of a distance is in between them. You can highlight different buildings and landmarks, and you can see where certain neighborhoods are located compared to other neighborhoods or these important landmarks. Once you select a building, the website will tell you the articles that are associated with this particular place. 

I think this is a really unique thing for a website to do. It’s cool to be able to see on a map -- an interactive map, no less -- because now you can picture in your mind where all of the events that take place in the documents are located in relation to one another and now they ultimately connect through the entire city. Providing the map of London in addition to simple links to the historical documents is a wonderful way to connect all of the different miscellaneous articles. 

I think this website does a decent job with making the user experience an effective one. The website is easily accessible in that it’s easy to navigate between tabs to find what I want to look at. Everything is clearly labeled and organized. The website also has a clear theme that connects with the topic; it has a very historical, traditional, perhaps even stereotypical graphic design, and the colors are muted as was typical during the time period analyzed all over the website. The Map of Early Modern London’s website is a very interesting website to explore.

**Comment by ttb11** [comment]
I'm currently taking CLASS 1142, Ancient Epics, so I looked at the "The Homeric Hymn 7 to Dionysus within the Perseus Project" The website is confusing and the layout isn't the best, but a few things you can look at is the number of words on the website in various languages. Another is the most commonly named places. However, it's difficult to discern what information the website is trying to explore because the website is poorly laid out.

The website and on first glance it was blah to the eye and reminded me of the internet in like 2007. It was confusing and the text first presented on the screen didn't seem like a home page (even on the home page) and the users were drawn to other places on the page. The list of links on the left side had right pointing triangles which usually (at least in my opinion) mean that there is a list when you click on it, but they were just icons which was confusing. The right side of the page was just a distraction and didn't have much to do with the rest of the page. Finally, one of the links in the bar took you to a different website which is frustrating and confusing.

However, there are a few things that I liked about the website. I liked throughout the website how there was a link to the home page. Also, I think that the information is well presented... once you figure out how to navigate.

**Comment by Blangzo** [comment]
Like @BMR59 and @ttb11, I also decided to look at the "The Homeric Hymn 7 to Dionysus within the Perseus Project" because of my past interest in ancient mythology.  
After exploring the website and the other comments in this discussion, I came to appreciate my tremendous number of hours spent mindlessly surfing the web which no doubt led me to agree more with @BMR59 that the website was simple enough to navigate rather than having the same difficulties as @ttb11.  I found the layout of the website to be the most convenient with certain tools at one's disposal where necessary. One problem with these tools however, is that each affected the position of the others when expanded or collapsed, meaning that the information on the page would shift each time you selected a different piece of text to read.
This was also, in my opinion, not the best piece of text to showcase while looking at the design because it can be perceived as confusing and certain tools useless because of the content in this text. For instance, @BMR59 said that, "Some of the options were confusing and appeared (to me) to not affect the page, such as the display options".  This is because the display options seem to be shown on every page regardless of content and some of them had no effect on this particular page.  In this case, the Greek and Arabic display option as well as the "view by default" option had no effect on the page because it wasn't supposed to; something that would not be clear without exploration of other parts of the website.
Overall, I found my time spent on this website enjoyable, and I would go as far as to say a bit instructive even thanks to the XML view option of certain parts of the website.

**Comment by bnm29** [comment]
I chose to look at "Shelley-Godwin Archive: Frankenstein Notebooks" just because it seems like not many people are choosing this option. The website is set up to where it is easy to navigate and find exactly what you are looking for. It also contains a lot of detailed information about its content. For example, I liked the fact that the website includes a picture of each handwritten page next to a picture of that page translated into normal text/code that makes it easy to read compared to the original note. There are even options to zoom, rotate, and expand the photos, which I find to be very useful. The website/archive, overall, is visually and mentally easy to comprehend and find specific files without having to do a large amount of reading or digging to find exactly what it is that you are looking for. This site gives a visitor the option to view how to use the archive as well, under the "using the archive" tab on the home page.

**Comment by emb184** [comment]
The Emily Dickinson Project promises intrigue with its collection and comparison of the poet’s fascicles. Over the years, multiple publications have produced and edited Dickinson’s work in confusing ways. This website allows you to compare editions to see just how much each edition changed from the original manuscripts.
As far as user experience goes, I found the website to be simple but effective. It was easy to navigate because the labels and options were plain but effective.

**Comment by haggis78** [comment]
I decided to have a look a the Map of Early Modern London project, since some of my work has looked at how geography and history relate. I started by reading a broadside, "The Severall Places where You May hear News", a little poem about the sorts of places where people gather and gossip. Each type of place is a hyperlink, so I clicked on "Alehouse" and it took me to a list of known alehouses/taverns/inns in early modern London. Some of these are identifiable on the Agas Map, an Elizabethan map of London, and clicking the link takes the user to them. I could even tell the map to highlight all the alehouses, and for good measure, all the churches at the same time! It seemed quite easy to navigate, at least as far as I went with it. A limitation, though: we know exactly where all of the parish churches were, because churches are well-documented and tend to stay in the same place for many centuries; but the same is not true of alehouses. Only some can be placed on the map: for the majority, there is only a name. Therefore, highlighting alehouses will not show their actual geographical distribution, since most cannot now be located.

In addition to the fact that one could have a lot of fun down this rabbit-hole, there is a very serious point: the historical and literary texts that we have referred to real places, and the people who wrote or read or heard these texts had mental maps in their heads. Even a silly ditty such as "The Severall Places where You May hear News" would have prompted the average Londoner to think of _her_ parish, _her_ tavern, _her_ local market. It reminds us that these were, in one sense, generic places -- the alehouse -- and in another sense very specific places. Reading the text by itself only takes us to the generic, but the MoEML reminds us that this was the granular stuff of people's lived experience.

**Comment by ebeshero** [comment]
@haggis78 Uh oh! You posted this on a closed discussion thread (from a couple of years ago when the prompt was a little different). Want to move your post to [the current discussion thread here](https://github.com/ebeshero/DHClass-Hub/issues/668)? 

I'll check the link from our syllabus to make sure it's pointing to the right place.

**Comment by ebeshero** [comment]
@haggis78 Indeed, I discovered my link on the syllabus was outdated! I've corrected the link--apologies for the oversight. Please do copy your post over to the current issue when you have a moment.
