### ISSUE TITLE
Help with Relax NG Homework (Due Monday 09/11)

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#332]
My brain is fried from a long week/longer Saturday, so I'm reaching out here for some help. I'm not certain if I'm having trouble understanding the fundamental concept of the schema format or if I'm only missing a few things, but either way I figure I can't be the only one having some errors so far! I'll be taking another look at it Sunday after some rest, so hopefully that will help as well. 

![screenshot from 2017-09-09 23-15-48](https://user-images.githubusercontent.com/28074589/30245882-b5aa1fce-95b5-11e7-96a3-c1ccc3309f4a.png)

**Comment by ebeshero** [comment]
Good morning, @quantum-satire! I've spotted your problem, and it's actually a good kind of problem to have as you're learning Relax NG! Let's walk through it:

Notice that in your associated XML, each of your `<note>` elements is firing an error. The error message reads, "text not allowed here: expected the element end-tag". That's a validation error, showing that your schema is working--that's a good thing! It's just not working the way you want it to.

Think about why it's firing that particular error! It is almost certainly to do with the definition of the note element: Does your note element permit the presence of text inside?

**Comment by quantum-satire** [comment]
Good morning! I changed `note = element note {chord}` to `note = element note {text}`, however I still look to be getting the same amount of errors.
![screenshot from 2017-09-10 09-12-39](https://user-images.githubusercontent.com/28074589/30249319-3d4392ce-9608-11e7-894b-f7b08315f9ed.png)
I attempted to change `song = element song {artist, head, body}` to include the element `title` as that seemed to be another triggered issue, but I realised it didn't make much sense to put it there because `title` is a sub-element to `head`.

**Comment by ghbondar** [comment]
@quantum-satire It looks like your note-element contains more than just text, but also contains an attribute...

**Comment by ghbondar** [comment]
@quantum-satire Also, note the error report in the bottom window....
It looks like your song-element contains the element-title, and title is an element, not an attribute...

**Comment by ebeshero** [comment]
@quantum-satire Actually, now that we're taking a closer look, it's going to make sense to start from the top of your schema and work your way through it line by line to debug it. 

Your schema says: start with the element song. Good. But then we see this rule:
```
song = element song {artist, head, body}
```
But when we look at your code, you have an attribute named `artist` that isn't on the `<song>` element at all. It's deeper in, part of the `<title>` element. 

Yet the next rule is also going to cause a problem. Interestingly, you redefine the label `artist` to make it an attribute whose real name is `title`! That's legal in Relax-NG but doesn't fit your XML document. Your rule reads:
```
artist = attribute title {text}
```
The problem *here* is that title isn't an attribute at all in your XML. It's an element, and it's a child of the head element. 

Basically the way Relax-NG works is that you start with the **outermost** element (your root element) and work your way one step at a time through each level of your element hierarchy. A rule can only define the immediate contents of one element or attribute. Let's start this over from the top, then, and compare the series of rules below with the XML document you have:

```
start = song
song = element song {head, body}
head = element head {title}
title = element title {artist, text}
artist = attribute artist {text}
...
```
There are more rules you need to define from here, but let's just walk through this to make sure you understand what each rule is doing, to define your document hierarchy. This little cluster of rules creates your root element song, and then indicates that the `<song>` element contains one `<head>` followed by one `<body>` element. We then define a rule for `<head>`, so that it contains ONLY what it actually contains: an element `<title>`. 

That element `<title>` has two things: an `@artist` attribute and some text content, so we need to indicate *both*. (We nearly always set the attributes first in defining the content of an element, though you don't have to--it's just easier for us to think about that way. You set an `@artist` attribute in the `<title>` tag and then indicate you expect to see text contents inside that element. Your `<title>` element doesn't seem to have any more elements tucked inside it, so it looks like we're done with this portion of the document. 

The next element we'd want to be defining would be `<body>`, since it's the *other* child of the song root element....Want to try taking it from here?

**Comment by quantum-satire** [comment]
I was able to solve most of the issues with your help, thank you for that! I have one issue left over though that seems to be a little tricky. This is the only `<note>` element that is flagged as an issue, and it may have something to do with it being in the sub-element `thought`. 
![screenshot from 2017-09-10 10-55-40](https://user-images.githubusercontent.com/28074589/30250070-a0d223a6-9616-11e7-9f1f-90be0346bfd6.png)

**Comment by ebeshero** [comment]
@quantum-satire Good! Yes, this one is a little tricky. To solve it, start with the error message you're receiving. It's saying, "element `<note>` is not allowed here; expected the element end-tag". When we see a message like that, we need to check the *context* for it. What is the element that is holding `<note>` here? You're right to see it's a child of the `<thought>` element. Is `<thought>` permitted to contain the element `<note>` in your schema?

Now, you might be wondering if you're allowed to have an element (or attribute) be nested in *multiple layers* in your hierarchy. You *can*. You only need *one* rule to define what's allowed in `<note>`. but you can indicate its placement in any element rule you like!

**Comment by quantum-satire** [comment]
I changed `thought = element thought {type}` to `thought = element thought {(type | note)*}` and now I have no errors! Yay! Thank you for the help!!

**Comment by ebeshero** [comment]
@quantum-satire I'm glad that worked! However(!) let's take a look at the syntax you're using--I don't think it reflects what you're actually doing with your XML. Your syntax is currently:
```
thought = element thought {(type | note)*}
```
And what that means is actually: the element thought contains *zero or more* of *either type or note* . Now, typically we use that syntax (with parenthetical grouping and the splat indicator) when we're alternating between two things (usually elements) and we don't care what order they are in or how many might appear of either. So your element `<thought>` might contain 25 of `type` and zero of `note`... That's perfectly legal as far as Relax NG is concerned, and it *happens* to validate your XML, but seriously, XML can only ever allow *one* of any attribute, and we're usually not alternating between the presence of **one** attribute and the possible presence of a child element. So, to write more accurate Relax NG, we might say:
```
thought = element thought {type, note*}
type = attribute type {text}
```
This is a case where you're getting the right result, but it's not the best code for a human! Just like XML code, we can expect schema code to be **read** by human beings developing projects, and you want to describe what you're doing as accurately as possible! Your schema code is a great opportunity for *documentation*, so one thing we'd love to see you do is add comments (using the `# ` to start a comment) to explain what you're defining in places where you want to be clear on what you really mean.

**Comment by pab124** [comment]
I've also been having a little trouble with my schema formatting. I think that I've 'debugged' it down to a single error, but the error description isn't very helpful, only telling me there is a 'syntax error'. I've tried a few things, but I can't really figure out what the problem is. Any help would be greatly appreciated. Also, I was having trouble fitting everything into a screenshot, so if its difficult to read I could try again. Thank You.

![xml schema](https://user-images.githubusercontent.com/31479306/30253139-02cae3be-964d-11e7-81b4-d8ec2ad24a8b.png)

![xml code](https://user-images.githubusercontent.com/31479306/30253126-cb9dfd9a-964c-11e7-8421-611e82c11ed1.jpg)

**Comment by ghbondar** [comment]
@pab124 It looks like you need a sequence indicator inside your { } such as either a comma or an or-pipe |.
`letter = element letter {header, salutation, body, valediction}`

**Comment by Jamielynn92** [comment]
So I just came back from D.C and I'm just starting on my Schema and I want to do my Lincoln speech but I don't fully understand how to start it. Is white space allowed if its the name of a battle/speech or should I use _ to separate the words.

**Comment by Jamielynn92** [comment]
![screenshot 12](https://user-images.githubusercontent.com/31480905/30254629-af8583fe-9669-11e7-96c9-9dd1471f1882.png)
So this is what I've started so far. I just wanna know if I'm on the right track. Cause it is something new and its a tad confusing at the moment.

**Comment by Jamielynn92** [comment]
![screenshot 14](https://user-images.githubusercontent.com/31480905/30254909-7559aca2-966c-11e7-8bbe-0efdc0eadbe9.png)
@ebeshero so I went for a few more lines but I'm stuck at the opening para. I'm not sure if I'm calling them the right names but I'm in the green. Am I on the right track on how I'm doing it?

**Comment by pab124** [comment]
@ghbondar I've made a few changes to the schema formatting, placing commas to indicate in which order the elements within the letter must occur. My schema appears to be well formed, as dictated by the green square. However, my XML still has a red square with the note saying 'syntax error.' But it doesn't have any errors underlined in red like the ones that I've corrected, so I'm not sure how to go about fixing whats wrong.

**Comment by ebeshero** [comment]
@Jamielynn92 I'm just taking a look now. Your schema is valid Relax NG, but I don't think it's going to fit the XML you wrote. You can't tell at this moment because you need to *associate* the schema with your XML file. 

Here are some issues I see, just visually comparing your XML file with your schema:
1) Your start element is certainly not the `<place>` element! It's `<root>`!
2) You defined `place` as the "element location" but there *is no* element location in your document. 
3) It's all good and well to define the contents of location (whether it's an element or an attribute" as "gettysburg,PA" (lowercase and no white space), but that isn't what you have in your XML file, is it? Check your spelling if you're going to delimit your text this way--your schema is actually the spell checker you're going to be running on that XML file!

I haven't caught all the problems here, but that's enough to get started! 

NOTE (to all reading this thread): Because several of you are posting *screen shots* it's not easy for me to convert those into code I can run and test in oXygen. Were you to push your files into the Troubleshooting directory we could then pull them in and test them ourselves and give you more feedback. Please use that directory!

**Comment by Jamielynn92** [comment]
thanks. I've been changing it over and over to get used to it. Using the explain relax ng and @quantum-satire as a reference even though ours are different, it definitely helps the scatter brains that I've been having. and ill try to push it if I can't figure it out for the next one.

**Comment by Jamielynn92** [comment]
I just tried, but I don't think I did it right. @ebeshero

**Comment by BMR59** [comment]
I've been having trouble with the phrase ' multiple definitions of "- - -" without "combine" attribute ' and I'm not sure how to go about fixing them. I looked through the Explain Relax NG and I'm still confused. any hints?
![compscreenshotrelaxng](https://user-images.githubusercontent.com/31479262/30256462-0b304978-9679-11e7-9196-afff11135b76.PNG)

**Comment by ebeshero** [comment]
@Jamielynn92 Keep trying! You can add comments about what you think is going wrong and turn in what you have before class if you don't get it right--we'll keep helping you debug it.

**Comment by Jamielynn92** [comment]
I think I fixed it. Does it have to be in order cause I tried to put the elements up top and the attributes at the bottom so I didn't get confused, but I did hit a snag because I used year as both and I don't know how to combine them with out messing up.

**Comment by ebeshero** [comment]
@BMR59 The problem, as you're noticing, is that you're defining multiple rules for the same element. Relax NG won't let you do that, and actually you really need only *one* rule for an element's contents, *even though* you want to nest it inside different elements. You can set the location of `<dyadicity>` inside any element you like just by including it in the contents of those elements, so your `<p_1>`, `<p_2>` and `<p_3>` may contain `<dyadicity>. But you only need to define one rule to define the contents of `<dyadicity>`. Try it!

**Comment by ebeshero** [comment]
@Jamielynn92 Sounds mostly good! After you define that start element, the rules can actually be jumbled up in any order. The computer parser just won't be satisfied until there is a rule defining the contents of every label you mention. I'm not clear on your snag b/c I can't see your code! But it sounds like you had a `<year>` element and an `@year` attribute? That's not a good idea for your own sanity as a coder--and as you're finding it's really hard to deal with for defining your schema. The simplest solution to that problem is to change either the element or the attribute name to something else! But you could also *escape* one of the names by giving it a different label, as in:

```
date = element date {year, month, day}
year = element year {yr, text}
yr = attribute year {xs:gYear}
```
(I'm messing with the datatype for a year there to be your attribute value, just to encourage you to play with datatypes!) But the thing to notice here is how I made a **label** of yr that defines an attribute named year. That's an example of *escaping* the attribute name because you're using it elsewhere in your definition of the element `<year>`. Does that help?

**Comment by Jamielynn92** [comment]
which one do I want to choose to check my schema?

**Comment by ebeshero** [comment]
Just a quick note to indicate we resolved this last question before class today.
