### ISSUE TITLE
Ongoing Projects: Where Might We Go From Here? 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#334]
Choose one of the following project sites under development. Describe (in your own words) at least one significant topic it seems to be exploring, and reflect on what research the developers might want to investigate next, the UX of the project site, and/or what ideas it inspires for new projects. Those of us (instructors and returning students) who have been involved in these projects should help introduce them to our class and point out things that need work.

- [Graveyard Project](http://graveyard.newtfire.org): Developed by @jonhoranic and team last fall, and could be continued...
- [Decameron Project](http://decameron.newtfire.org)</ref>: Developed by coding students in spring 2016, and ready to be continued.
- [Amadis in Translation](http://amadis.newtfire.org): Recently launched project: follow the link to its GitHub repository for more information and a view of the coding. We need to work on preparing the two sets of English and Spanish base texts to read and study them together, and we could choose to expand the project in a new direction of interest.
- From our Digital Mitford Project: [Letters Introduction](http://digitalmitford.org/letters.html): For the letters portion of this project, a team could develop a module to help investigate some interesting topics. 
- [Digital Archives and Pacific Cultures](http://pacific.pitt.edu/) : This site reflects the origins of our Pitt-Greensburg digital humanities projects—it was our starting point and first collaboration with students. The Voyage Maps area got us involved with using maps to represent passages from voyage logs, but the project could use an overhaul to pick up loose ends or continue where we left off a few years ago, and we could move it to our newtfire development space.

**Comment by flowerbee1234** [comment]
I thought that the Graveyard Project offered some very interesting information when looking at those buried and their lives. I hadn't even heard of Brush Creek, although I lived in Greensburg all my life, so it was interesting to learn that it had been around since the 1700's. One of the most important factors you included was the age of death. I thought it was very insightful to include which gender died at what age, when considering the context and time frame. Also, I liked how you took the time to provide pictures and a diagram. The feature of being able to click on the sites and read the information made it easier for the audience to understand.

**Comment by ghbondar** [comment]
Although listed on the [syllabus schedule](http://dh.newtfire.org/CDASyll.html#d2017-09-11), I did not remind you about this assignment in Monday's class, so please don't forget to provide some enlightened commentary before class on Wednesday. Your project for this course will be one of the main parts of your course grade, so you will soon need to be thinking about proposing your own projects for our course.
@pab124 @ttb11 @BMR59 @Blangzo @mof11

**Comment by kes213** [comment]
I think that the Digital Mitford Project is a really interesting compilation of historical letters that aren't necessarily widespread knowledge to a lot of people. The website makes it very easy to sift through a wide variety of Mitford's letters and trace both the important events of her life that she catalogued and her career development. I think it would be interesting for a team to go into each letter and analyze the grammatical structure and see how those patterns develop over time, as she grows older, experiences new things, etc. For example, tracing how her syntax changes and searching for patterns of word choice, popular punctuation, and other grammatical structures would be a cool thing to put on the sight. Looking for changes like these could really add to the site's goal of tracing Mitford's life because you can tie those key writing style elements back to how she was feeling and thinking on the particular day that she published the letter. Seeing the writing elements that remain the same over time would also give an insight into how Mitford thought and what she valued about writing.

**Comment by pab124** [comment]
I looked at the site for the Graveyard Project and it was quite interesting to see how it went through the details of each individual grave marker, and selected certain information that could be very useful in a survey type scenario. I think that another aspect that could be of real value would be a demonstration and illustration of where the occupants came from and, if they're questionably outside the vicinity of the graveyard, what may have been the reason for there eventual relocation to this particular town (ie did they marry in to the town, relocate for a job, inherit some land or something, any reason that could mean they moved and died here). The only fault that I found with the site in terms of the UX was dealing with the charts and graphs,  as the associated text seems to overlap with the presented element. Additionally, the chart that presents the names and personal details of those interned is rather low on the page and could be formatted differently. Other than that though, it is finely made.

**Comment by quantum-satire** [comment]
I went to the _Amadis in Translation_ site to look around, and enjoyed the layout and color scheme as soon as it loaded! However, only the _Aligned Contents and Translation Analysis_ page and the _About_ page worked, so the site is still under construction as far as I can tell. When I clicked on the _Translation Analysis_ page, a series of colorful charts provided a visual aspect to the purpose of the site, which is to find out the amount of changes that are made to a translated piece of literature by the editors. It's a really neat concept with both a Word Count rate and Analysis of the translated material on one side and the original work on the other. If I had to change anything, I would spend a few minutes in Photoshop to create a neat eye-popping header image to include the title of the site, rather than to host the text by itself--it would make it even friendlier as a home page!

**Comment by Jamielynn92** [comment]
I chose to look through the graveyard project. Since I live so close to it, I feel like this is such a cool project because my ancestors helped build Brush Creek Cemetery. And I don't know much about them, so this was very neat and interesting to look through. I enjoyed scrolling through all the lost souls that are buried in the cemetery. I especially appreciate the pictures taken of the gravestones, so that when I click on a spot on the grave site, it scrolls down to the persons grave. Plus I also learned how to drive there, so it means something to me in a way. The graphs are also pretty well made to when you put your curser over the age graph, and tells you how many men and women there are of each age group. Although there are weird moments when I make my screen go from big letters to small letters in/out, when I go to click on the graphs, when I'm zoomed out I guess I would call it, I'm not able to click on the different graphs. (I don't know if its just mine, but I thought it was weird.)

**Comment by Blangzo** [comment]
I looked at and found the graveyard project to be quite interesting. The project seems to document the different deaths of the people whose graves are marked throughout the cemetery based on gender, number of deaths per year, as well as common age of death.  
I think that the developers would want to continue their current research into the gravestones throughout the cemetery by adding more data in order to reveal any possible patterns.
The website design is well done, however it does contain a few problems. Certain analysis graphs overlap unless one zooms out. At this point however, the graphs are smaller than I would like, and the dropdown choices for the menu no longer stay long enough for the user to click on one.
The map of the graveyard along with the data compiled reminds me of data that one would collect from a videogame. The map akin to a heatmap of some type of stat and the data compiled used to analyze the results of a match in order to improve future games.  It would be interesting to see if I could do something similar with certain games that I play in order to practice and showcase what I will have learned in this class as well as to build a tool for my friends and I to analyze our matches.

**Comment by BMR59** [comment]
I went and took a look at the Amadis in Translation and it seems like the site is focused on tracking changes in the romance Amadis de Gaula through translations. The Navigation on the site so far seems easy, though I can tell there is still work being done. I really liked the idea of tracking changes throughout translations as that's something I've always been subtly interested in - how translation can really lose or morph important themes or meanings in texts. I like the side by side chart comparisons underneath the Aligned Contents... tab. A number of ideas could be proposed after looking at this site and one that would interest me would be comparing translations of the Bible.

**Comment by ttb11** [comment]
I looked at the Decameron project. They're researching the 14 novellas of the Decameron, specifically their "frame narrative." Unless I'm doing something wrong there isn't really much information on the website besides the welcome page, an objective, a picture, and a brief description of the Decameron.  I think the trivia on the bottom of the page is nifty, but that's the only information I'm getting from the whole website. Therefore there are many things you could do to expand the project. For example you could add more pages on the website and dive deeper into the research questions posed in the objective. Since the page is so bare, you could really do anything to add to the project.

**Comment by ebeshero** [comment]
@BMR59 Thanks for the interest in our project site! It's a neat project when we find time to work on it. The XML under the hood is worth taking a look at over on [its GitHub repo](https://github.com/ebeshero/Amadis-in-Translation): The concept is to explore the building blocks of a "sense-for-sense" translation, since Robert Southey's 19th-century (modern) English sentences are quite grammatically different from the 16th-century Montalvo text, where what we're marking are "clause-like" units.  

In our project, each unit of Montalvo is coded to pair with a chapter in Southey's translation, and we're using `@xml:id` attributes to "stitch" the documents together--to show which of Southey's sentence portions map to which "clause-like units" in the Montalvo texts. Here's a peek at a sample pairing:
[Montalvo](https://github.com/ebeshero/Amadis-in-Translation/blob/master/XMLandSchemas/Montalvo/Montalvo_Amadis_1547_1.xml)

[Southey](https://github.com/ebeshero/Amadis-in-Translation/blob/master/XMLandSchemas/Southey/Southey_Amadis_1803_2.xml)

**Comment by ebeshero** [comment]
@ttb11 Oops! The server-side include that provides the Decameron site's navigation menu is apparently broken from when we transferred to a new server over the summer, and we didn't notice. I'll see if I can fix it--there is indeed a great deal more to this website. But in the meantime, would you perhaps take a look at one of the other project sites?

**Comment by mof11** [comment]
I looked over the Graveyard project and was really fascinated by the methods utilized and the findings the team collected! First of all, I think it is a nice alternative for people to check out if they do not like going to cemeteries themselves (like me). I liked how the map was organized into a neat chart of the people buried there, including their names, gender, cause of death, etc. Also, I believe that the team upholding to the TEI standards for future developers to use this information and collaborate to the site was a good move since over time, more bodies will be buried here. The only thing I would have liked to have seen done differently were the graphs, the text explaining the graphs were displayed on top of the graphs (making it difficult to read the actual content). Otherwise, I really liked this website!

**Comment by ebeshero** [comment]
@ttb11 I've just fixed the server error that was blocking the navigation bar on [the Decameron project site](http://decameron.newtfire.org/). Try refreshing the page in your browser--there's much more to see now!

**Comment by tal80** [comment]
I looked over the Brush Creek graveyard website. I have come across this website before while researching my family tree. The author of the website should look into the clunky and 90's feel to it. That being said it does do one thing, it serves a purpose, finding graves. One of the many different issues I came about while doing my family trees was how clunky the cemetery websites are.  There is a lot of information out there to pull to integrate into your website to add more content to the gravestones. I was pleased to see that there were graphs depicting different statistics of the demography of the cemetery.  Further research could also be done by looking through church and other sources to seek information about the life and dead of the people who are buried at the Brush Creek cemetery. Overall I think the Graveyard project is a great start and also respectful to those buried there. My family came to Pennsylvania in the 1680's and settled this land along with others with the help of William Penn. Remembering our ancestors is the key to who we are. Projects like this are much needed to honoring those who came before us.
