### ISSUE TITLE
Document Analysis and TEI Exercise 1 (Due 09/18)

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#339]
I'm sitting down to work on the first TEI assignment using the Cheese Straws example, and I browsed the catalog to see if there was a way to mark the enclosed body text for underline but came up empty. Would I use the `<hi>` element for this situation? I know that HTML uses the element `<u>` specifically for underlining text but I'm not certain if I am able to use that in this case. Thanks in advance!

**Comment by jonhoranic** [comment]
@quantum-satire Indeed you would! The highlight element is used to indicate text that is "highlighted" by other marks on the page. You would want to use the proper attribute to define what the ````<hi>```` is indicating. I will give you a small hint, look through the examples the ````<hi>```` page has. It has something to do with representation!

**Comment by quantum-satire** [comment]
@jonhoranic Would I be able to use `<hi rend="underline"></hi>` in this case?

**Comment by ebeshero** [comment]
@quantum-satire Yes--good thinking here! 

You raise an interesting question about the difference between an HTML and a TEI tag--and we expect we'll be talking about this kind of thing a lot this coming week as we learn about these *controlled vocabularies*. TEI is designed to organize information **in** and **about** documents like our photographed recipe on a card: so it has an elaborate tagset (over 500 different elements) to help with all kinds of information we can describe about document artifacts. It's not meant to control the way these are presented for view, but rather to *document* information. In this case, your `<hi rend="underline">...</hi>` would accurately describe a portion of our **source** document that is rendered with an underline. 

The difference between TEI's `<hi rend="underline">` and HTML 5's newly restored `<u>` element is basically a difference of purpose: HTML elements traditionally prioritize document display in web browsers, but were note designed to contain so much detailed information as TEI. One thing we'll be doing in this class is transforming information-rich XML (and TEI) into display formats in HTML for the web. There are several ways we can *negotiate* the differences between information-storage vocabularies of TEI XML and the formats of code (especially HTML) designed for display in web browsers. We'll be talking more about that this week as we start introducing HTML--but one thing to consider now is that you could perhaps find another TEI attribute to add to your `<hi>` element, such as `@hand` if you saw evidence that a different person other than Stacey's grandmother had drawn underlines in the text, and you wanted to use an attribute to identify who that person was who left the underline marks. (I don't think we see that here, but I'm bringing it out as an example--we might see it in other documents.) HTML doesn't have a simple capacity for preserving that information in a single element tag, though we could find a way to preserve the notation of it for display! (For example, we might wrap an interesting passage in an `HTML <span>` element with a generic `@class` attribute that we set to match the information encoded in the TEI document: maybe like this: `<span class="Triplette_hand"><u>....</u></span>` . We could use those elements as signals to tell the web browser how to display the passage. But TEI would be more precise: `<hi rend="underline" hand="Triplette">...</hi>`, and it would hold that information in a clearly defined way in XML storage as an **interchange** format. 

In our class on Friday, I talked about TEI as an **interchange format**. That was one of the founding principles for this XML language as it was defined back in 1987 at the Poughkeepsie conference: the idea was to hold information about electronic documents in a systematic way with a controlled vocabulary that could be interchanged across any kind of computer system, and be **workable** for people and machines alike. By **workable** I mean, we can write code to read the structure of XML and extract data from it in graphs and charts, or publish it in related formats like HTML. It's rare that people in the Real World sit down and read an XML document--usually we read its contents in various transformed states. We'll be showing you how to transform all this XML to work with as we keep on going with this course! :-)

**Comment by quantum-satire** [comment]
@ebeshero There should be a class just on the history of computers and their languages (I really find it interesting!)

Because I am curious, I have some unrelated questions to the homework: is it ever appropriate to use `HTML <span>` if there is an element that TEI doesn't cover and to use HTML (or perhaps another language) in place of it, or is TEI more expansive and applicable to a greater number of circumstances? I'm sure the `<span>` element is used more frequently when hosting the TEI script on the internet for example. Is TEI compatible/exploitable by Python? As in, would it ever be practical to mesh the two together? Also, do we nest TEI into HTML or vice versa? I know we will learn this later, but again, I'm just curious!

**Comment by ebeshero** [comment]
@quantum-satire It would be great to see a class on that here! :-) Well, HTML and TEI tend to be used separately, but HTML pages for the web often contain other forms of XML, especially SVG (scalable vector graphics) which you'll be learning to create...*from* from your XML code! 

Yes, TEI is "more expansive" as you say--there are a lot more informational and descriptive elements for dealing with cultural artifacts--and an especially rich tagset for documenting manuscripts, for example. You *could* publish TEI directly on the web without any HTML at all, but using CSS (the styling language we use for pages designed for the web) and even JavaScript. There's a project underway called [CETEIcean](https://github.com/TEIC/CETEIcean) that uses JavaScript to assign TEI elements to HTML 5 and render them that way, but I've also written CSS to display TEI directly on the web. There are lots of reasons why that's not typically the best approach--usually when we go to build displays on the web we actually *want* the simpler tagset HTML offers, but HTML won't give us things like `<measure>` elements with unit and quantity attributes. What we do is find ways to tuck some of that information-rich material from the TEI into attributes on HTML `<span>` elements--and there's usually a net loss of information when we do that because in any given HTML transformation, we'll pick and choose what we want to feature. (You could, quite seriously, design 2 or 3 or 5 or 10 different HTML pages out of a single complicated XML document: one might be a chart, another a reading view featuring one set of tags, yet another a different reading view meant to  highlight something else...) 

You'll be learning to write code that pulls data from XML documents and transforms the tags into HTML for displays, and once you see how that works, you'll see you have lots of options to experiment with!

**Comment by Jamielynn92** [comment]
So for this homework assignment, I am at a standstill on what to make some of things to code. I want to do the 350 degree, but not sure how to type that out. And I've scoured the TEI guidelines but no luck.

**Comment by quantum-satire** [comment]
@ebeshero Thank you for the information! The TEI was a little overwhelming at first with the sheer amount of _stuff,_ but I'm really starting to appreciate it after learning a bit more about it--I think that's why I reverted back to HTML as something more familiar. I'm happy to know I can use both in the future!
