### ISSUE TITLE
External vs Inline CSS

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#346]
When I build anything with HTML and use accompanying CSS, I prefer using inline or embedded script versus external because it keeps everything simpler for myself and actually allows the scripts to load faster. May I use inline CSS for my projects for this class? [I started work on my Newtfire website using inline and uploaded it to my repo just to show what I have so far.](https://github.com/quantum-satire/DHClass-notes/blob/master/website/index) I don't want to make anything more difficult though, so I can switch if that's preferred!

**Comment by ebeshero** [comment]
@quantum-satire I understand how inline-CSS can be convenient for single pages at a time, but in this class we're going to be building sites where *multiple* pages are governed by the same CSS rules. That's why we have you write a separate CSS file, and why later one we'll have you writing your JavaScript in a separate file as well. The idea is, write the rules *once* without having to copy them into every page you draft. 

That also means that *when* you choose to write inline CSS, it should be for the pages on your site that deviate from the standard script of rules you write to govern all your pages. Make sense?

**Comment by ebeshero** [comment]
That said, if you like seeing the instant application of your CSS rules as you apply them, while you're *drafting* them, you could draft them inline, and at the *end* of the process move them out to a separate CSS file for linking. Since you'll be building sites with lots of pages styled consistently, we do require your projects to work with single CSS files that govern multiple pages.

**Comment by quantum-satire** [comment]
@ebeshero Alright, that makes much more sense! I'll move the inline CSS to its own file and re-upload to the repo/FileZilla. Thank you!
