### ISSUE TITLE
Missing Colors and Images on Personal Website

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#351]
Hi everyone, 

So I finished my HTML and CSS documents, I associated them, I saved them in a directory, and I uploaded them to my Git repository and the newtfire.org page through Filezilla. 

My problem is: when I click on the file and view it locally, the color is purple and the image of my lilacs is there. However, when I open the www.newtfire.org/~kes213 webpage, all of my words are there, but the background color is white instead of purple and there's just a little box that says "image" at the bottom. I uploaded the same file through Filezilla, so I'm confused as to why these differences exist. 

Here are the [HTML](https://github.com/kes213/Kaylee-System/blob/master/Personal%20Webpage/index.html) and [CSS](https://github.com/kes213/Kaylee-System/blob/master/Personal%20Webpage/Stinebiser_HTML_Ex1_CSS_doc.css) files. 

Thank you!

**Comment by gabikeane** [comment]
some details or a link to your code?

**Comment by gabikeane** [comment]
Ah easy fix! Upload your CSS and image files to the server too.  Right now you're linking to nothing, which is why you see a white page and your image alternative instead of your beautiful webpage.

**Comment by ebeshero** [comment]
@kes213 I think I've spotted the two problems:
1) Your CSS file has a slightly different name as you've saved it than the name you use in the `<link>` element in your HTML. Your CSS file is there on the server, but where you indicate it's Ex1 in one version, in the other it's lower case ex1. I'll recommend actually that you do NOT need such complicated filenames for your website directory. (This is a different kind of file submission than what you send up on Courseweb since you're posting in your very own web space, so you can just call this something simple: style.css for example). 

2) As Gabi just noted, the image file is missing from the server. It, too, is basically an associated file--it needs to be present in the same file directory with the HTML.

**Comment by ebeshero** [comment]
@kes213 I also notice you have a couple of index files in your public_html directory: One is named index.html.html with a double extension. You'll want to delete that one just to eliminate confusion.

**Comment by kes213** [comment]
Oh, @ebeshero I didn't even notice the difference in file names! I took care of all of that, and now it's up and running in purple! Thank you @ebeshero and @gabikeane for your help!
