### ISSUE TITLE
Trouble Using Flexboxes for Center-Alignment

### ISSUE THREAD

**Issue by quantum-satire** [ebeshero/DHClass-Hub#352]
I'm not familiar with using flexboxes and am unsure if I am implementing them correctly in my website--I am trying to align some images with links for my resume at the top just beneath the head of the page, but am having no luck as they remain aligned to the left. I used `.menu-container {
                padding: 20px 0;
                display: flex;
                justify-content: center;
            }` and `<div class="menu-container"></div>` wrapped around the images. What can I do to fix this issue using flexboxes?

[Link to code in personal repo](https://github.com/quantum-satire/DHClass-notes/blob/master/website/resume.html)

**Comment by ebeshero** [comment]
Hi @quantum-satire! sorry for the delay--I'm taking a look now!

**Comment by Jamielynn92** [comment]
I'm having the same issue. I tried to make the bottom flex boxes and I was tinkering with it, and somehow it changed it, but not in the way I wanted it too. Cant figure it out.

**Comment by ebeshero** [comment]
@quantum-satire and @Jamielynn92 : As we're checking this out, here's a little GitHub preview trick we will find useful a LOT as we work on HTML and web development: You can attach a prefix to the web view of your code in GitHub to *preview* how it would look on the web. The prefix is:
`http://htmlpreview.github.io/?` and for Ally's code, that looks like this: `http://htmlpreview.github.io/?https://github.com/quantum-satire/DHClass-notes/blob/master/website/resume.html`

So here's [the preview](http://htmlpreview.github.io/?https://github.com/quantum-satire/DHClass-notes/blob/master/website/resume.html)  

Meanwhile, I'm squinting the code and trying it out locally to see what I can see...

**Comment by ebeshero** [comment]
@quantum-satire Aha! I see you have a `<div class="box">` surrounding your resume, which of course is drawing the lovely box around the contents. It's the only HTML element sitting inside your `<div class="menu-container">`, and because of that, what's being centered is the box itself, but not the elements inside it. Flex properties aren't *inherited* by "descendents" (as we call them--elements inside elements)--the flex container governs what's immediately below it.

That said, I notice you've set your font-family on every text-containing element beneath body. That's not wrong, but it's inefficient, since font properties *are* inherited. You can set those just once, up on the body element, and everything bearing text deep down into the file will hold your font.

**Comment by ebeshero** [comment]
@quantum-satire OOPS-- scratch that. I misread your code. I was confusing your `<div class="container">` with `<div class="menu-container">` which is much deeper in and contains three `<a>` (link) elements. . .

**Comment by ebeshero** [comment]
@quantum-satire I'm going to be delayed looking at this until this evening--I've been tinkering with your code and I've managed to align your buttons vertically, which is a bit unexpected...I'll need to unpack it more later--as I have to meet with another student. In the meantime, any and all debugging help from thew group is most welcome!

**Comment by ebeshero** [comment]
@quantum-satire I've figured out a few things about your code, and I've gotten the flexboxes to behave a little differently with some tinkering. First we need to get rid of styling that is interfering.

* In your HTML you have set `@style` attributes with CSS values inside on your `<img>` elements, as in `<img src="resgd.png" style="width:15%;" />`. This is problematic--it's mixing up your CSS rules, so there are rules in multiple locations: some sitting in attributes on your HTML and some up in your `<style>` element (which is one Very Serious reason why we *urgently* prefer you to work with CSS in a separate file altogether. The w3c recommends this practice too, because the style attributes you set locally on elements start to confuse styling severely. Best to keep all these rules in *one* place--separate from the HTML itself. 

* It's problematic for another reason: When you set a **width as a percentage** on any element, you stop that element from functioning according to flexbox rules--these are conflicting. 

* So, first of all, let's remove those width percentages. Instead, since you probably want to control the size of those images on the page, go with another unit of measurement for them: work with pixels (px) instead of percentages here. And here's a quick example that may help with some clearly written CSS code that combines setting widths with flex properties: https://webagility.com/posts/fluid-layouts-done-right-with-flexbox

**Comment by jub45** [comment]
I was having problems with this as well (I still am, but have decided to keep left-justification for text for now).  I tried to add a few small image galleries and the images themselves would not resize (huge explosion of graphics all over the screen resulted!). When I set the .menu width to 900px as well as the photo-grid-item to 900px for h and w, all seemed to work well. But before I did that, it was a calamity on the screen for me.

**Comment by quantum-satire** [comment]
@ebeshero Sorry for such a late response--but thank you so much! I do have a question however: why would setting the width as a percentage for an element mess with flexbox rules? Doesn't it simply connotate a certain pixel width of a screen which keeps it relative to the viewing display? I'm curious because I specified that the width be 15% of the page width, but not which 15%.

**Comment by quantum-satire** [comment]
It looks like `flex-grow`, `flex-shrink` and `flex-auto` are better alternatives to this after reading the page you linked--and easier to work with.

**Comment by ebeshero** [comment]
@quantum-satire As I understand it, when you set specific widths as percentage of the available screen space is kind of doing what flex box is attempting to proportion on its own. Both are *relative* settings, as you observe, but they don't seem to shake hands with each other--and indeed, if you're using flex, you wouldn't need the width set as percentages. Pixel sizes are different--more of a measurement of the object itself than a proportion of screen space.
