### ISSUE TITLE
Git Bash problems again

### ISSUE THREAD

**Issue by pab124** [ebeshero/DHClass-Hub#365]
So I'm having trouble doing a git pull from our project repo and it gives me this error message about "unknown compression method" or some malarkey like that. I'm not really sure how to proceed with this, so I posted a screen shot here. I've also pushed it into the Troubleshooting folder. 
![gitpullerror](https://user-images.githubusercontent.com/31479306/31363224-ef9984ae-ad2a-11e7-8a0e-026bb62c73fa.jpg)

**Comment by gabikeane** [comment]
Have you tried googling the error message?  I can help you walk through this, but I want you to try troubleshooting on your own too.

**Comment by pab124** [comment]
so the one page, in addition to a few others, said that other people experiencing this problem used a `git fsck` command and then deleted the file that was said to be corrupted. I tried to follow along with their steps and found a similar message, but they didn't mention how to remove the files, so I'm not sure where to go from there.

**Comment by gabikeane** [comment]
[Stack Overflow](https://stackoverflow.com/questions/23725925/git-repository-corrupt-incorrect-header-check-loose-object-is-corrupt)
According to Stack, which could very well be another load of malarkey, you should nuke your local repo and use git clone to make a new local repo.  I don't recommend doing this until you've checked your remote repo to ensure what you meant to push is there, because you might lose changes if they didn't push successfully.
If you'd like, we can work on this together tomorrow morning.

**Comment by ebeshero** [comment]
@gabikeane @pab124 Just coming back online--I've been out most of the day! But my first thought here is, *has anyone else tried a git pull from Portu-WhatsApp*? Is there something wrong in the shared repo just now?

**Comment by ebeshero** [comment]
@gabikeane @pab124 Okay--*I* just made myself a test subject, and pulled from the Repo, and had no troubles...so I don't think it's anything in the repo itself.

**Comment by ebeshero** [comment]
@pab124 @gabikeane The next thing I'd try is very simple: Close your terminal, restart the computer, try again. Same result? 

If you have nothing new in the repo (it looks as if you do not since there was nothing to commit), there's no shame in deleting your local directory and just cloning it afresh.

**Comment by ebeshero** [comment]
@pab124 @gabikeane Oops--I think I misread your error screen...You *do* have new local files in the repo, right? Looks like something's wrong with them locally, because your `git status` command showed the compression error. It's pretty clear you've got a corrupted local file but which one is it?(Sorry this took me a while to work through...)

**Comment by pab124** [comment]
@gabikeane @ebeshero I shouldn't have anything new in my local repo though, as I hadn't done anything since Thursday afternoon and one of the project partners has since pulled and pushed their changes to the materials as well. I tried the restart idea, but I still get the same message. I'll double check everything again though.

**Comment by ebeshero** [comment]
@pab124 I wonder if there was an interruption the last time you did a `git pull`, then. One thing we could try is a `git log` to see if you can get a history (my guess is you won't be able to). But I think the simplest solution just now (since your repo is young and you haven't done much local work on your end yet), is to destroy this local repo and re-clone it--get a fresh start.

**Comment by pab124** [comment]
@ebeshero I tried the `git log` but it gave me the same error, so I went ahead and re-cloned the repo. Thank you for the help.
