### ISSUE TITLE
XSLT Exercise 3

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#383]
I'm extremely confused by the directions of this assignment. 

So far, I've build the typical outline of an html document and added the <table> tags, just as #1 says to do. However, I've reread #2 about five or six times now, and I honestly have no idea what it's telling me to do. 

`In XSLT, processing something normally happens in two parts. You normally have an <xsl:apply-templates> element that tells the system what elements (or other nodes) you want to process, and you then have an <xsl:template> element that tells the system exactly how you want to process those elements, that is, what you want to do with them. If you find the image helpful, you can think of this as a situation where the <xsl:apply-templates> elements throw some nodes out into space and say would someone please process these? and the various <xsl:template> elements sit around watching nodes fly by, and when they match something, they grab it and process it. In this case, then, your <xsl:apply-template> elements inside the template rule for the document node will tell the system that you want to process the <string> elements of the <f name="question"> and all of the corresponding responses (<f name="response">) and the corresponding <string> insides of the <f name="note"> element all sitting inside of the same <fs> element. In order to specify that you only want specific Yes or No Questions then the <xsl:apply-template> elements inside the template rule for the document node will tell the system that you want to process the following elements only when one of the <f name="response"> has an @select="Yes", at which point the template rule for the document node will call out what portions of the document need to be processed at this particular point. That work actually gets done by other <xsl:template> rules, the ones that you’ve written that match the <f name="response"> with @select="Yes".`

Maybe I just don't understand what I'm supposed to be making the @select attribute equal to in the first <apply-templates/> tag. Right now, I have only one table, and between the <table> tags, I have this: 

`<apply-templates select="//div[@type='table']"/>`

Is that wrong? Should I have more than one table created within the html body? Should I then have more than one <apply-templates/> tag? 

I feel as though I'm 100% lost and I don't even know how to move forward with this exercise.

**Comment by ghbondar** [comment]
Here's the text from the assignment pasted as code so that it includes the elements:
`In XSLT, processing something normally happens in two parts. You normally have an <xsl:apply-templates> element that tells the system what elements (or other nodes) you want to process, and you then have an <xsl:template> element that tells the system exactly how you want to process those elements, that is, what you want to do with them. If you find the image helpful, you can think of this as a situation where the <xsl:apply-templates> elements throw some nodes out into space and say would someone please process these? and the various <xsl:template> elements sit around watching nodes fly by, and when they match something, they grab it and process it. In this case, then, your <xsl:apply-template> elements inside the template rule for the document node will tell the system that you want to process the <string> elements of the <f name="question"> and all of the corresponding responses (<f name="response">) and the corresponding <string> insides of the <f name="note"> element all sitting inside of the same <fs> element. In order to specify that you only want specific Yes or No Questions then the <xsl:apply-template> elements inside the template rule for the document node will tell the system that you want to process the following elements only when one of the <f name="response"> has an @select="Yes", at which point the template rule for the document node will call out what portions of the document need to be processed at this particular point. That work actually gets done by other <xsl:template> rules, the ones that you’ve written that match the <f name="response"> with @select="Yes".`

@kes213 OK, you will need to have all three tables (as shown in the example on the assignment sheet) structured in your HTML template. Because each table is so different from the others, probably three different template applications would be simplest. Perhaps use the contents of the sample output to guide which data you select as you apply the templates:
Table 1: look at the order of the columns... the first column being counted is for responses that are "yes".
Table 2: similarly, the first column of data being counted is for "Water closets"
Table 3: similarly, the first column of data being counted is about workers who get to "Sit"

The other template matches should calculate the data for each cell in each of the tables.

**Comment by kes213** [comment]
I still don't understand what the structure of the XSLT stylesheet should be. I've tried numerous different templates and @select values and @match values and I don't get any output. It just gives me back a copy of the XSLT stylesheet.

**Comment by kes213** [comment]
This is what I have. I don't know where to go from here, and this isn't giving me any output. 
```
?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml"
    version="3.0">
    
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    
    <xsl:template match="/">
        <html>
            <head>
                <title>SANITARY CONDITION OF WORKSHOPS AND FACTORIES</title>
            </head>
            <body>
                <h1>Sanitary Conditions of Workshops and Factories in New York City</h1>
                <h2>Table 1: Yes or No Questions</h2>
                <table>
                    <tr>
                        <th>Number</th>
                        <th>Question</th>
                        <th>Yes</th>
                        <th>Yes, but fined</th>
                        <th>No</th>
                        <th>Blank</th>
                        <th>Total Responses</th>
                    </tr>
                    <apply-templates select="//fs[f[@select='Yes']]"/>
                </table>
                <table>
                    <h2>Table 2: Sources of Offensive Odors</h2>
                    <tr>
                        <th>Question</th>
                        <th>Water Closet</th>
                        <th>Other Sources</th>
                        <th>Total Responses</th>
                    </tr>
                    <apply-templates select="//fs[f[@select='No']]"/>
                </table>
                <h2>Table 3: Standing or Sitting at Work</h2>
                <table>
                    <tr>
                        <th>Question</th>
                        <th>Sit</th>
                        <th>Stand</th>
                        <th>Optional</th>
                        <th>Blank</th>
                        <th>Total Responses</th>
                    </tr>
                    <apply-templates select="//fs[f[@select='Blank']]"/>
                </table>
            </body>
        </html>
   
</xsl:stylesheet>
```

**Comment by ghbondar** [comment]
@kes213 Ok, the data that you want to tabulate in the xml-file are in fs-elements.
For Table 1, we only want the fs-elements that contain yes/no/blank. So we need to constrain our template to only those specific fs-elements. How would you write an XPath statement to find only those fs-elements, that contain f-elements whose select-attribute="yes" ? Use that XPath in your first 
apply-templates select= " "
Use the other fs-elements in your other tables.

**Comment by ghbondar** [comment]
@kes213 Now that I see your code, you are getting closer... your apply-template statements for the other two tables need to use xpath to get to those other fs-elements.
Then, you will need three templates to fill-in the data for each table.

**Comment by pab124** [comment]
@ghbondar I wasn't able to get started on this homework til late and I've just been having a really difficult time figuring things out after class. I'll post here so far of what I have. I'm not sure if even the slightest bit of anything is even remotely correct, so I'm looking for a little guidance of any sort.

`<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml"
    version="3.0">
    
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    
    <xsl:template match="/">
        <html>
            <head>
                <title>Sanitary Conditions</title>
            </head>
            <body>
                <h1>Yes or no</h1>
                <table>
                    <tr>
                        <th>Number</th>
                        <th>Question</th>
                        <th>Yes</th>
                        <th>Yes, but fined</th>
                        <th>No</th>
                        <th>Blank</th>
                        <th>Total Responses</th>
                    </tr>
                    <xsl:apply-templates select="//f[@name='question']"/>
                </table>
            </body>
        </html>
    </xsl:template>
    <xsl:template match="//f[@name='question']">
      <tr>
            <td>
                #
            </td>
          <td>
              <xsl:apply-templates select="string"/>
          </td>
          <td>
              <xsl:apply-templates select="."/>
          </td>
            
        </tr>
    </xsl:template>
    
</xsl:stylesheet>`

**Comment by ghbondar** [comment]
@pab124 You have a good start, but for your first apply-templates, instead of using the attribute for the f-element (that is @name='question'), why not jump down to the select-attributes with the values you need, such as `select="yes"`?

Now, you that you have structured the first table, you also need to structure the other two tables all inside your first template... after all, it's part of your HTML structure that lives in the first template, right?

Then, you will need to create additional templates to fill-in the data into the cells in your tables.

**Comment by ebeshero** [comment]
@Jamielynn92 Are you on campus now? I'm in my office and some students just took off--stop by? If not, I'll walk you through it here.

**Comment by Jamielynn92** [comment]
I am at home.

**Comment by ebeshero** [comment]
@Jamielynn92 When you save your XSLT file, it needs to have a `.xsl` extension.
When you save an output HTML file, it needs to be a `.html` extension. And you need to reopen it in oXygen to make sure it's good HTML: the output window in the XSLT view won't tell you if it's well formed. 

I don't know how to answer "on which part these templates are suppose to go", but I think the assignment sheet and our tutorial on Explain XSLT will give you examples. http://dh.newtfire.org/explainXSLT.html

**Comment by ebeshero** [comment]
@Jamielynn92 If you're confused about how to begin, remember that you start ANY transformation from XML to XSLT in the same way: with a template match on the document node. You can look at examples on the [explainXSLT](http://dh.newtfire.org/explainXSLT.html) tutorial and on previous homework solutions on DHClass-Hub. At this point, we're not going to show you how to create that template rule on the assignment sheets, because they all work the same way. There is **one** really important template match on the document node where you map out the structure of your HTML document. Then there are the template rules that you call to process different parts of the source XML document. You call template rules with `<xsl:apply-templates>` and *sometimes* you want an `@select` attribute on xsl:apply-templates to **select** what parts of the XML source document you're going to pull in and process at just **this** point. 

But you do NOT always need an `@select` attribute. You can just say `<xsl:apply-templates>` and if you don't indicate anything, the default processing applies, which just dumps out plain text nodes (no attribute values, just all the plain text). But if you write some <xsl:template match="something"> pattern-matching rules, you can then process anything that turns up *wherever* it turns up on the tree wherever it turns up. That's the whole point of XSLT Exercise 4. Does that help?

**Comment by Jamielynn92** [comment]
I’m not sure I’m doing this right. Im looked at 4 different sites and looked at the homework for 3 but I still cannot comprehend how it needs to be written out. I keep getting errors. I don’t have a good grasp on how these template rules are made. Each example I looked at just got more confusing.

**Comment by ebeshero** [comment]
@Jamielynn92 Two things: 1) Look at the code you wrote that I returned to you just now for XSLT Ex 2.
 2) Show us some code? What are you having trouble with writing? How about pushing your file into the Troubleshooting directory here, or pasting in a code block?

Remember, you can use four tic marks : ```` like that above and below some code here, so it comes through and we can read it!

**Comment by Jamielynn92** [comment]
this is what I have for the bottom of my stylesheet
````` <xsl:template match="table"/>
            <xsl:apply-templates/>
<xsl:template match="fs type="QandA">
            <xsl:apply-templates select="f name="response">
                <xsl:template select="yes"> 
                    <xsl:apply-templates >
                    </xsl:apply-templates>
                </xsl:template>
            </xsl:apply-templates>
        </xsl:template>````

**Comment by Jamielynn92** [comment]
````<xsl:template match="table"/>
            <xsl:apply-templates/>```` this with each table

**Comment by Jamielynn92** [comment]
````<xsl:template match="table"/>````
           ````<xsl:apply-templates/>```` 
and these under each table

**Comment by ebeshero** [comment]
@Jamielynn92  Okay, there's a problem here. When you write `<xsl:template match="SOMETHING">`, that SOMETHING needs to be from the XML input document. There is no `<table>` element in the XML source document for this assignment. 

Instead, you write a `<table>` element in your template rule that generates the skeleton of an HTML document. You did that before with XSLT Ex 2, remember?

**Comment by ebeshero** [comment]
@Jamielynn92 I'm sending back comments in the XSLT 3 that you submitted. I hope these will help--wait a minute and I'll send.

**Comment by Jamielynn92** [comment]
Nothing is coming to me. I'm sorry. My brain has hit a complete dead end.

**Comment by ebeshero** [comment]
@Jamielynn92 You should move on to XSLT Ex 4, then. As I wrote in my email announcement to Greensburg today, "XSLT Ex 4 is due as well, on schedule, so prioritize that for tomorrow morning: writing that code is not really similar to what's needed for XSLT 3, and usually students find this one easier to write. Studying our posted solution for XSLT Ex 2 will be sufficient to ensure you are properly outputting an HTML document from an XML source. " 

You have enough to go on with XSLT Exercise 2 to work on XSLT Ex 4. Then come back to 3 after we have class tomorrow. It'll probably be clearer then.

**Comment by ebeshero** [comment]
@Jamielynn92  You have enough to go on with XSLT Exercise 2 to work on XSLT Ex 4. Then come back to 3 after we have class tomorrow. I hope it will be clearer to you then, or perhaps after a tutoring session.
