### ISSUE TITLE
SVG Exercise 2 Variable defining

### ISSUE THREAD

**Issue by kes213** [ebeshero/DHClass-Hub#393]
I'm confused about the way in which I would Xpath to return the max number of times that Alice speaks per chapter. 

I've tried a lot of different ways, but none of them are giving me the exact return I want. 

`count(//chapter/descendant::q[@sp="alice"])`

This returns the total number of times Alice speaks throughout the whole book: 380. 

I know that I'll need to use the `max()` function to return the highest number of the count, but I don't know where to put the `count()` function. 

I tried this:
`//chapter/descendant::q/count(@sp="alice")`
which returns the number of @sp attributes with 'alice' as their value.

I tried this:
`count(//chapter/descendant::q/@sp="alice")`
And I'm honestly not sure what this is returning -- maybe the same thing because my result is just the number 1. 

I tried this:
`//chapter/descendant::count(q[@sp="alice"])`
but my computer gave me an error because the `count()` function came immediately after an axis name.

I've also tried other combinations that I can't remember now. 

I did consult the example in the Class Examples folder, but it uses the for-in-return because the example uses a collection, so I don't know how to apply that to an XSLT template that's running over a single XML document.  

Can anyone give me some assistance?

**Comment by ebeshero** [comment]
@kes213 Great question--be able to return the counts inside each chapter is central to this assignment, and you're investigating various ways to do that with XPath.

In the contexts we set with XSLT, we can make an `<xsl:for-each>` loop through each chapter as a descendant of the root node, and we then identify the `q[@sp="alice"]` inside, and can easily wrap that in `count()` as we go.  But if you're just wanting to find the maximum count, you want to do that with a single XPath expression, the kind you can write and test in the XPath window in `<oXygen>`. 

You're on the right track with the *second* expression you listed here: `//chapter/descendant::q/count(@sp="alice")`
But it's not getting what you want, because you are counting just **one** speaker attribute on each single`<q>` element. In the XPath window, you should  be seeing a long series of `1` returning.

What you want is to walk down the tree into each chapter, and get a count() inside it of `<q>` elements that have the property of being spoken by Alice. You want to be counting a certain kind of `<q>` element.  **This basic structure** is indeed a good one:
`//chapter/count()`
It's good because it'll return a `count()` of something inside each chapter. You should return 12 counts because there are 12 chapters.

Were you to take the `max()` of all those counts, you'd return the maximum of the 12. Hope that makes sense!

Incidentally, you *can* write this in the syntax I showed in class today:
`max(for $i in //chapter return $i/count(stuff))`, but I like your way better. It's a simpler XPath to write and understand.

**Comment by kes213** [comment]
Is this any closer?

`max(//chapter/count(q[@sp='alice']))`

This gave me only one result, and it was the number 3.

**Comment by ebeshero** [comment]
@kes213 Sorry we missed seeing this earlier...I wonder if you figured it out? The `<q>` element is a descendant of chapter. It must *occasionally* be a child, since you returned the number 3, but the counts per chapter are more like 30 to 50, I think. So, rewrite the expression to return the count of `count(descendant::q[@sp='alice'])`.

**Comment by ebeshero** [comment]
@quantum-satire and @kes213 I was trying not to give away the full expression in my message just now, but you're both really close here. Ally, you're trying to count the descendant q elements, but your count is return 380 because of your use of the double slash inside the function. That is going back up to the document node. Remember, this is why we prefer to write out the `descendant::` axis notation. You might also amend your expression using the dot (.) for the self node, before using the double slash.  But the computer responds most efficiently to the word `descendant::` and it's better human-readable code, too. 

Does that strong hint help?

**Comment by ebeshero** [comment]
@quantum-satire and @kes213 You're right to start this with `//chapter/count(....)` , and once you return 12 counts for each of the twelve chapters, you want wrap that whole expression in `max()`.

**Comment by quantum-satire** [comment]
@ebeshero I think got it! 12 items with 25, 32, 46 etc. Does that sound right?

**Comment by ebeshero** [comment]
Yep! Huzzah!

**Comment by quantum-satire** [comment]
@ebeshero Thank you!
