### ISSUE TITLE
Authorship Attribution, Stylometry, and Patrick Juola 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#396]
Dr. Patrick Juola of Duquesne University is speaking to the Pittsburgh DH class this (Fri. 11/10) morning, about how he works to solve questions of authorship attribution and identity, using text evidence. We're going to try to post a video of the lecture to share with Greensburg class, but we've also posted a bundle of readings by Juola and José Nilo G. Binongo on the evidence and methods used in this kind of work, and we'd like both classes to have a chance to read and talk about these. This is a discussion assignment worth points toward your grade in the class. Please read at least two of the following:
* José Nilo G. Binongo, [Who Wrote the 15th Book of Oz?](http://dh.obdurodon.org/Binongo-Chance.pdf)
* Patrick Juola, [How a Computer Program Helped Show J.K. Rowling write A Cuckoo’s Calling](https://www.scientificamerican.com/article/how-a-computer-program-helped-show-jk-rowling-write-a-cuckoos-calling/)
* Patrick Juola, [The Rowling Case: A Proposed Standard Analytic Protocol for Authorship Questions](https://academic.oup.com/dsh/article/30/suppl_1/i100/363234/The-Rowling-Case-A-Proposed-Standard-Analytic)

What do you learn from the readings (and/or Dr. Juola's talk) about how stylometry and authorship attribution works, what kinds of evidence are especially helpful in identifying authors and distinctive traits of writing. What are the issues and/or strengths of these methods--how much can they reveal about writers?

@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213

**Comment by flowerbee1234** [comment]
I really, really loved both the articles I read. I chose the Binongo piece "Who Wrote the 15th Book of Oz?" and the Juola article, "How a Computer Program.." As you know, I am not a big digital person, but as a writer and English lit major, I found both pieces to be extremely illuminating and insightful. 

The first article I read was Binongo's, which sought to differentiate both Baum's and Thompson's writing styles. After Baum, the original Oz writer, passed away, Thompson sought to recreate the Oz characters and plot-line. However, although she wrote her own variation, some claimed that she stemmed her ideas from notes left behind by Baum. The stylometry, the study of linguistic language, is not--as later stated--as distinguishable as, say, DNA--but it shows the differences between each writer and his writing style. 

This article viewed these writers' differences by charting each writer's word-choice and how often he/she used these. In doing so, those doing the study determined that Thompson's stories were very much her own and not dependent on Baum. She only adopted his former character and settings to make her own world. I found this study in particular to be captivating, to see the difference between two writers through diction.  Through this charting, they learned that "Baum, on the other hand, prefers "which" and "that." After this analysis, they were able to prove that Thompson possessed her own writing style completely independent of Baum's. 

The piece ends with a thought-provoking statement: "Literature, indeed, is not without a dimension that is open to statistical scrutiny."

Likewise, the Juola article dives into Rowling's work and compares it to that of Galbraith's, which turned out to be the same person. They made the determination (although not a flawless one) that Galbraith compared to Rowling, and it was more likely to be her than not.  I enjoyed this article as well, because it showed the comparisons between the same author under a different pseudonym. Juola looked at, for example, the distribution of word lengths and also the 100 most common words. He analyzed, in doing so, the instances of using the words "the" and "of," words such as prepositions and articles. He was able to confirm that Rowling's greatly compared to and matched Galbraith's writing style, but still, this was not one-hundred percent certain. 

Only until Rowling confessed to this did it become certain, proving that while this method is reliable, it is not fool-proof.

This helped me see digital functions in literature in a completely different light. I guess one issue would be that this is not completely fool-proof and can be wrong, but I think it has done some pretty good things in regards to writing style.

**Comment by ghbondar** [comment]
Hopefully, this will jump-start some discussion! Here is Dr. Patrick Juola's presentation from Friday, 10 Nov 2017. They are still uploading, but they should be complete soon. My camera can only record in 20-min chunks, so there are three parts, below. He generously provided his slides so that you can follow along without needing to squint at your screen!
Part 1: [https://youtu.be/X6Xvh4SONzA](https://youtu.be/X6Xvh4SONzA)
Part 2: [https://youtu.be/Sp9YDSXGi6A](https://youtu.be/Sp9YDSXGi6A)
Part 3: [https://youtu.be/Sp9YDSXGi6A](https://youtu.be/Sp9YDSXGi6A)
Slides: [https://github.com/ebeshero/DHClass-Hub/blob/master/Assignment-Files/Juola-Files/Pitt-Authorship2016.ppt](https://github.com/ebeshero/DHClass-Hub/blob/master/Assignment-Files/Juola-Files/Pitt-Authorship2016.ppt)

@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213

**Comment by ghbondar** [comment]
The videos are up!
@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213

**Comment by ghbondar** [comment]
Hopefully, this will jump-start some discussion! Here is Dr. Patrick Juola's presentation from Friday, 10 Nov 2017. My camera can only record in 20-min chunks, so there are three parts, below. He generously provided his slides so that you can follow along without needing to squint at your screen!
Part 1: https://youtu.be/u_x0Zs6_14M
Part 2: https://youtu.be/X6Xvh4SONzA
Part 3: https://youtu.be/Sp9YDSXGi6A
Slides: https://github.com/ebeshero/DHClass-Hub/blob/master/Assignment-Files/Juola-Files/Pitt-Authorship2016.ppt

@ghbondar @gabikeane @zme1 @amk231 @pab124 @jub45 @mof11 @ttb11 @BMR59 @Blangzo
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213

**Comment by Blangzo** [comment]
Going into the readings, I was very excited because I remember hearing about this when it was first discovered that Rownling had written a novel as Robert Galbraith, but I never read about how it was done. I decided to read both of the articles by Dr. Juola.

In the Scientific American article, I found a few things to be very interesting. The first was the use of the distribution of character 4-grams. This was something that I would probably never think of - I would more likely use a feature like common words and length of words.  I also found it rather interesting that 4 authors were used for comparison and that Rowling would only need to be one of the top two likely authors on the list to show similarity. And it made sense. This made the whole process seem simple, something I could do, rather than something that would require a PhD for. Even Dr. Joula himself mentioned that he had undergraduate students working on similar projects during his presentation.

In Dr. Joula's second article, I found the same things interesting, but being more indepth I found other thought provoking ideas as well. 
First was Joula's writing about the transition of a new field into "normal science" in which one can build on each other's work rather than "reinventing wheels". This served as a reminder that little work has been done regarding authorship authentication, especially aided by computers, and makes one question: if this is just the beginning, as the better known laws and theories of physics were, how far can we take this field and what unimaginable things will we be able to do with it?
I also found Dr. Joula's comparison of authentication to DNA to be very thought provoking. In part 5, the Discussion and Conclusions, Dr. Joula questions if it will ever be possible for "statistical-stylistic evidence alone to rise to the level of ‘beyond a reasonable doubt'". He then however, backs up this type of evidence by comparing it to DNA evidence, suggesting that they could be treated the same, as a piece of evidence that can be used along with others to prove something.

**Comment by BMR59** [comment]
I was really excited once I found out Dr. Juola would be lecturing because I had actually read the article about the Cuckoo's Calling/J.K Rowling situation. I had never considered that people having somewhat of a lexical fingerprint and was surprised that they could track down authorship just from commonly used words. Also, the 'sample size' was something that shocked me. Only using four different authors seem like a small amount of writers to compare but it worked. It was a nice opportunity to have Dr. Juola himself explain the process and put the concept into perspective. I can also see how this process could really tie into situations outside of authorship and it seems like there is a long list of possibilities where it could go. 

I thought this lesson also tied in somewhat nicely with our project. Some of our data was scrubbed of names and the participants' identities were unknown, but we were able to piece them together because on of the student's writing patterns (they had habit of using ".." and not using any text-speak) - so that also helped me understand that people do have distinct habits in writing that could be used to set them apart.

**Comment by ebeshero** [comment]
@jonhoranic @ajnewton1 @Jamielynn92 @quantum-satire @flowerbee1234 @tal80 @kes213 Greensburg crew! Just a reminder that participating in this discussion gives a boost to your homework score!

**Comment by quantum-satire** [comment]
It was really neat to read about the JGAAP program Juola developed--I'd previously heard it mentioned before (or something similar to it used in a university setting) and I think it has a lot of great potential. In the Scientific American article, Juola writes how his program can be used in several fields other than english such as criminology and psychology, as well as law and politics.

The algorithms are set to specific parameters that find particular usage of sequential characters such as "n th" or "nsid," marking the similarities between authors that use them on a numerical scale. Because the program is logic-based, it can pick these strings out with ease and without human error, but is not able to be 100% accurate in picking out the _specific_ author. Instead, it can best be used to rule out which authors did _not_ write the text in question. 

Because of the program's potential, it may lead to a series of new, more advanced developments in the field of stylometry. However, I think it would be wise to use it with caution; as Juola points out, it may be detrimental to the privacy of an author's published works if they choose to publish under a pen name. If an author chooses to publish anonymously, shouldn't they be entitled to that privacy?
