### ISSUE TITLE
SVG Exercise 4

### ISSUE THREAD

**Issue by pab124** [ebeshero/DHClass-Hub#400]
I started working on my SVG Exercise 4 and I have it most of the way done, but I've hit a little snag. The main problem that I'm having is with the SVG chart that I've made and displaying it properly within the browser. I know that I've had trouble before getting my SVG element to be centered within the SVG viewer upon opening it, and I figured that this was a similar scenario. The chart doesn't display in full and I was wondering how I use the @viewbox attribute to change this, if that is in fact what I'm supposed to use in the situation.

**Comment by ebeshero** [comment]
@pab124 It may be a combination of the `@width`, `@height`, and `@viewBox` you have set on the `<svg>` element, but you should also work with the `@transform` attribute in the `<g>` element, as well. To control these, I recommend trying the following:
* calculate or find out what your maximum values for X and Y will be. Add a bit more to them, and use these for your `@height` and `@width`
* your `@viewBox` has four coordinates, and typically we set that to run from 0 0 to something bigger than your maximum X and maximum Y. If you use the same values here that you used for `@height` and `@width`, you'll have stretched a canvas of 100% dimensions. (You could simply achieve that without the viewBox by setting `@height` and `@width` to 100%. The reason we use a viewBox is because we can shrink or stretch those coordinates: sometimes if I have a really long plot, I want to halve the size of this on my screen, so I'll use double the size of my max width and max height as my last two coordinates in `@viewBox`. (To read more about this and look at examples, see Sara Soueidan's tutorial on SVG coordinate systems: https://www.sarasoueidan.com/blog/svg-coordinate-systems/ )

* Okay: if you've done all that, how about centering the SVG plot on the screen? Here is where we use `<g transform="translate(x y)">`, to shift all of your coordinates to the right by x units, and down the screen by x units. 
*  If you want to draw your plots from 0,0 so you don't have to make weird calculations, you want to translate your whole plot DOWN the screen by your max Y, but then maybe as much as 2 * max Y, so that 0,0 falls vertically in the middle of the screen. 
* Think of using "transform translate" to shift your x coordinates over from 0 so they are not plotted up against the left side of your monitor--so bump those over as much as you like to make yourself a left-hand margin. 
* As you adjust this, revisit your viewport and viewBox: remember how you want to have a larger canvas than the size of the objects you're setting in it? Keep adjusting those to give you room to move over and down as you wish.

Here's a tutorial with more than you probably need on transform translate, but you may find some interesting things to play with here: https://www.sarasoueidan.com/blog/svg-transformations/

Does that help?

**Comment by pab124** [comment]
@ebeshero Thank you very much for your help. I think I've got it figured so that it works, but I fear that my methods aren't exactly the neatest and most efficient only because I have small questions. But, I think that I might benefit most from just having someone explain it slightly in person tomorrow. Thank you again for your help!
