### ISSUE TITLE
Mishap of Timing

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#41]
Hey @ebeshero and @ghbondar and @RJP43 , I happened to notice that I scheduled my advising appointment at 11AM tomorrow morning and it seems I can't simply reschedule. So I won't be able to make it to class, at least not until after my meeting. I really would like to catch up and hear what I missed for class, which means, could I meet with one or more of you at some point between 11:20 and 12:30 OR 2:30 and 3:30?

**Comment by ebeshero** [comment]
@CodyKarch yikes--You should be able to reschedule that since you are in class. I can contact your advisor if you like--email me the details. It will be so much easier if you can be in class! I have to catch up another student who missed on Friday right after class, and you could join us for that--which might help, or might be distracting! 

I'm teaching in the 2:30 time block you mentioned, but @ghbondar might be available. I hope you can come to class after all.

**Comment by ebeshero** [comment]
Cody--Greg has to teach at Penn State this afternoon. If you can't change the advising appointment, meet me right after class and we can work together with Kari to get you caught up.
I think you should reschedule the advising appointment, though!

Dr. B

**Comment by ebeshero** [comment]
@CodyKarch if you can't reschedule the appointment, meet me and @KariWomack right after class and I'll try to bring you both up to speed! Neither of us can meet later in the afternoon.
