### ISSUE TITLE
Discussion: Traversing the Tree and Overlapping Hierarchies

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#413]
### The reading:

Read Gabrielle Kirilloff, “[&lt;Traversing_the_Tree/&gt;](http://dh.newtfire.org/Kirilloff_TraversingTree/)”, the short article, “[Frankenstein novel analyzed](http://www.idsnews.com/article/2015/04/frankenstein-novel-analyzed)” and scroll through Wendell Piez's [conference talk and images for the Balisage Markup Conference 2014](https://www.balisage.net/Proceedings/vol13/html/Piez01/BalisageVol13-Piez01.html). If you like, you can take a close look at [his LMNL code of Frankenstein](https://github.com/wendellpiez/Luminescent/blob/master/lmnl/frankenstein-as-published.lmnl) on GitHub. 
_Special note of interest:_ Gabi Kirilloff was a student in [a digital humanities course at Pitt like the one you are taking](http://dh.obdurodon.org), and she originally wrote &lt;Traversing_the_Tree/&gt; for a seminar paper assignment in another class. 
### The discussion prompts:
- What perspective does Kirilloff provide on the kinds of XML markup we are learning, the history and context of hierarchical markup?
--What problems does hierarchical markup pose for encoding documents? What ideas do Kirilloff or Piez present for how to deal with these in code, and how effective or problematic might these be? Is it possible to write XML to "get around" the problems raised in these pieces? What's lost (or gained) in making XML's hierarchical structure deal with overlap?
- Consider the examples of overlapping hierarchies that Kirilloff and Piez present to us: Which of these did you find especially interesting? Are there good ways to "model" overlapping hierarchies with code? 

The discussion is worth points to you as a homework exercise. For full credit, your posts should make specific reference to passages in Kirilloff's essay, and reflect on those passages. **Note:** You (as an individual) do not have to respond to every one of the discussion prompts, but our two classes as a whole should cover them all. A good strategy would be to try to respond in some way to at least two of the prompts in the list above. Raising questions is encouraged, and so is responding to each other, but responding should do more than simply say, "yes, I agree." A good response will add something new to the conversation, or help promote more discussion. You should make **at least two substantial posts** to fully contribute to the discussion.

*As you're drafting your comments, see if you can apply "Markdown" formatting if you'd like to use bold or italics or make a list, form a link, add an image, etc. Follow the link to ["Styling with Markdown is supported"](https://guides.github.com/features/mastering-markdown/) (which you can always find at the bottom left of an Issue write screen) for an orientation to Github's markdown.*

**Comment by ebeshero** [comment]
Everyone--We discovered after class that the reading is being redirected to Gabi Kirilloff's new website--and we're working on recovering it! Stay tuned...I'll write again when I've reposted it.

**Comment by ebeshero** [comment]
@setriplette @quantum-satire @alexfell06 @garrettjoiner @dorothealint @MarkTheShark01 @Pomilui  I've posted a PDF version of Gabi Kirilloff's "Traversing the Tree", which is a little less interactive but will still get the ideas across. I've written to her to see if we can recover her original coded version.  Anyway--our links here should work, and you may begin reading and discussing now!

**Comment by ebeshero** [comment]
Actually--I've managed to rescue the very cool coded form of the document from the Wayback machine, and I'll post a link to it on newtFire shortly...stay tuned!

**Comment by ebeshero** [comment]
@setriplette @quantum-satire @alexfell06 @garrettjoiner @dorothealint @MarkTheShark01 @Pomilui I've now retrieved a copy of Traversing the Tree, and posted it on newtfire here: 
[http://dh.newtfire.org/Kirilloff_TraversingTree/](http://dh.newtfire.org/Kirilloff_TraversingTree/)

**Comment by Pomilui** [comment]
## **Consider the examples of overlapping hierarchies that Kirilloff and Piez present to us: Which of these did you find especially interesting? Are there good ways to "model" overlapping hierarchies with code?**

### One example that I found interesting is how "House of Leaves" uses visual components like font and forcing the reader to assign different "internal voices" for the three different narrators who refer to themselves throughout the story.  This concept presents a difficulty in coding the story due to an overlapping hierarchy because, according to Kirilloff, **"If the book is reorganized so that each narrator’s story occurs in sequence the text changes even though the component parts are still present. This is because the narrators respond to one another and taking them out of context changes the effect of the novel."**
[Here's a quick link on self-reference from Stanford University Philosophy Encyclopedia](https://plato.stanford.edu/entries/self-reference/)  

   A reader would be hard pressed to guess which narrator is speaking if all three fonts were replaced with random, unfamiliar fonts half way through the novel.  This is a case of where changing the format of the text changes the thrilling effect, which contradicts the OHCO concept that visual attributes and formatting aren't very "essential" to the text.  

   Although the "sub-hiearchy" concept makes sense to me, it may be too broad and allow for "connecting dots" across entire texts.  The idea that overlapping hierarchies are "exceptions" rather than part and parcel of OHCO leaves the scholar/builder to deal with them however he or she chooses.  CONCUR's concept of dealing with multiple hierarchies at the same time in the same document has some potential for a good model.

**Comment by Pomilui** [comment]
**Which side did everyone associate with more:  The ontological argument supporting OHCO (Text is an ordered hierarchy of content objects" or the pragmatic argument that SGML and the following concept of OHCO, "was not designed for fully describing texts" but the OHCO model still has practical applications and "accurately reflects the _nature_ of text?"   **    :neutral_face:

**Comment by ebeshero** [comment]
@Pomilui Thanks for kicking off the discussion! The OHCO problem is one that takes issue with a single XML tree to describe a text--and at issue for lots of us who use XML is whether the "workarounds" that Gabi Kirilloff shows in her piece are acceptable, or kind of philosophically problematic! Think about what it means to use XML to do things like:
* mark how a document is organized (say, the paragraphs or lines in a poem, and/or the sentences)
* mark specific kinds of content, say, topics being covered, mentions of people or places, references to time and place...

Part of what we do with XML is experiment with markup in a way that creates a kind of nested outline, that tree hierarchy of OHCO, and when we do that we set down an order or nested containers. Is that nesting order a big problem for the way we think about texts? (That's an interdisciplinary question: In a literature context, we look at document structures when we read poems or novels--which is why Wendell Piez's work with Frankenstein and the poems he diagrams is worth thinking about). Piez works outside the OHCO (ordered hierarchy) to model the texts, but he has to transfer back over to OHCO when he wants to show us a view of overlap/intersection--which means he effects a compromise--finds a way to express overlap within the OHCO model...

Part of why I assigned this was to get you thinking a little philosophically about what we do when we model texts using XML! What do you think?

**Comment by dorothealint** [comment]
I spent a lot of time wondering about the example of speech separated by some words that are not part of the spoken quotation.  
"Whether or not the scholar decides to label this instance as one quotation or two quotations separated by the phrase “said the girl” does not impact the way that the text can be rendered after the markup process. However, the methodology would affect a count of quotations within the text and would also impact the number of letters contained within the quotation."
I chose to see what I could do with a short play for my xml exercise 3 and I ran into stage directions in the middle of a character's lines.  In the example I had, the stage directions would be a series of flowing movements during the speech.  I labeled them separately because I knew I wanted all the stage directions to be searchable as one set and all the dialog by each actor to be searchable as another set; but after reading this, I think I would label them as part of the same stage direction tag in the future.
Now I am wondering if there is a way to sub-label such things so that the order is not lost in searching for them but that they all come up together.  It would be easy to see the proper order for a quotation as the language would have to make sense, but stage directions that build off of the previous might not be so easily seen.

**Comment by setriplette** [comment]
I'm a fond user of TEI, but I have encountered many of the difficulties Kiriloff mentions when I try to fit my texts into an ordered content hierarchy. The nesting structure seems to speak well to machines, but human minds do not necessarily nest everything, and the codex structure that has dominated how we compose, store, and experience texts since late antiquity is not nested. If you look at a print book, its content boxes are more on the "one thing after another" model. The table of contents, for example, in an English book appears to be telling you what will follow. This is an illusion. In other linguistic traditions, the table of contents is the last thing in the book--for how do you know what will be there until you have written it? In any case, in early printing, tables of contents might misrepresent, be printed last, or simply be missing. The same one-thing-after-another model governs anthologies (name means collection of flowers), the oldest form I know of of gathering content objects in a codex. Anthologies and their cousins, commonplace books (collections of quotations and ideas people would keep in small diary-like books for themselves), do not necessarily relate their selections in any kind of hierarchy. They are simply composed linearly, from beginning to end. Items may be unrelated except by the gatherer's interest or access.
Almost everything I work with as an early modernist will stretch TEI. I chose the Lope project in part because existing editing conventions had made the plays all look alike, though the autograph manuscripts can differ quite a bit. I've had to limit my tagging to single words so my elements don't cross lines, and even then, multi-word names could potentially be a problem. That said, I still work in TEI, because I think that adhering to an international standard, even if I have to push at its boundaries, makes my scholarship more durable. However, I wouldn't expect a marked-up TEI document to stand for itself; for me at least, there needs to be traditional literary analysis along with it to explain what I've done and why. An even bigger problem for me than content hierarchy (which can largely be solved with a judicious choice of corpus and editing strategy) is subjectivity in tagging. We might all universally agree that Madrid is a place name, but what about a park name in Madrid that just means "retreat" (Retiro) -- would everyone recognize it as a place, or would some miss it? We might all agree on a body part, but what about an emotion? Is "friend," for example, an emotion word? I've debated this kind of thing on the Lope project at length and I still don't have a great answer. This is where, once again, other kinds of work, in this case literary analysis in prose, come in to explain the decisions made in markup.

**Comment by alexfell06** [comment]
One thing that really interested me was the interaction, or relationship, between scholar and reader. The article mentioned "study patterns and data sets" which caused me to think of statistics and some other math classes I have taken. One danger of statistics that my professor mentioned was, "the ability to manipulate the data to depict whatever you want." Going along with this notion, the article states that,  "The scholar’s choices of categorization and formalization may impact a reader’s interpretation of the text." Therefore, with the rising prevalence of digital humanities, one danger could be the misconstruing, intentional or not, of literary materials by the scholar marking up the text. The article's example of the interpretation of “metaphysicalDeceit” within a John Donne poem could be used as a minor example of this happening. Now, this may never arise as an issue within the digital humanity field, for numerous reasons, but it just struck me as an interesting comparison between two fields I've been involved with.

**Comment by ebeshero** [comment]
@alexfell06 That's a pretty important issue for markup projects and one that is very worth thinking about: In Digital Humanities, at the conferences I attend, we often discuss the importance of a project to share its code and data structure and include explanation of the markup you chose. In our first XML exercises in this course, we are just getting you warmed up to how the coding syntax works, but being thoughtful about the hierarchy you choose to impose on the text is important. It's one reason why people like @setriplette and I will choose to use the TEI (an XML language shared by a community of scholars in humanities and history and social sciences to describe cultural objects): There's an agreed-on "controlled" vocabulary for describing documents and everyone uses that and can read each other's code. Sometimes, as @setriplette noted, we wind up "bending" the TEI because the documents we're working with and our interests in marking them weren't predicted by the TEI community, or we have trouble getting the standard vocabulary to fit!

But I think it's important first to be able to write up your own XML hierarchy and think about some of the problems and limitations of XML as you're learning. Perhaps we can make it better (just like we can improve our writing) by finding more precise ways to describe what we are trying to study...

**Comment by alexfell06** [comment]
@Pomilui I would agree more with "the pragmatic argument that SGML and the following concept of OHCO, 'was not designed for fully describing texts' but the OHCO model still has practical applications and "accurately reflects the nature of text?"
Overall, I do not believe that the OHCO is a bad system; however, I agree with the article's analogy to the CD player and the iPod. Considering that the tools current digital humanitarians are using are not totally designed for them, in addition to the rapid rate at which technology is evolving in society today, I believe that more effort should be placed into the development of a new system rather than being wholeheartedly attached to OHCO. Therefore, I do not think OHCO should be abandoned, it does have some very useful practical purposes. However, I think placing more emphasis on the creation of a new system/program built specifically for the purposes of digital humanitarians would be beneficial.

**Comment by MarkTheShark01** [comment]
The different examples of overlapping are very interesting and confusing, such as the engineer line that is shown a couple times. Seeing the code itself made me confused as to what I was looking at, while at the same time, confused me as to how a line typed out like that could work. It always occurred to me that if there are any commands added within another command, then the first would end after the inner commands were ended. Just looking at the line command ending first before the word command ended made me think that it wasn't properly typed out. Although it's probably considered too simplistic, I feel that ending any and all innermost commands should be a top priority before finishing the outermost. 
I was also intrigued by the House of Leaves book, and how it uses different visuals to guide the reader along with which of the three authors is talking by using different fonts, thus giving the reader the opportunity to create different mental voices in their head while reading, should they so desire to. It does, however, pose a slight challenge when attempting to code the story due to the use of different fonts being used. If they're not included, it will become more challenging for the reader to see which author is speaking, since they would not be able to keep track of which author was talking about a certain topic before changing it. The explanation as to why this is important is "the narrators respond to one another and taking them out of context changes the effect of the novel." This also contradicts the OHCO belief that attributes and different formatting are not essential, since it would, again, make the code more challenging to read for both the person and the computer.
