### ISSUE TITLE
UX Discussion: LOTR, ORBIS, What's On the Menu?

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#414]
Choose one of the following digital archives to explore, and write a post in this thread discussing: 
1) how visual aids are used to convey information on the site, and how well (or badly) do these work? What seems unclear to you, and/or what seems to work really well? 
2) how effective is the (“UX”) in navigating at least one or two significant areas of the site? 
(Each of you should begin by writing a "UX review" of a site, and then read and respond to each other by looking at the sites others chose.) 

* [LOTR Project: Visualizing Tolkien’s Works on the Web](http://lotrproject.com/)
* [What’s on the menu?](http://menus.nypl.org/) (be sure to read the About page for the project goals)
* [ORBIS](http://orbis.stanford.edu/): The Stanford Geospatial Network Model of the Roman World

**Comment by alexfell06** [comment]
I chose the "What's on the menu?" website, concerning the New York Public Library's collection of historic restaurant menus.
1. The primary visual aids used on this site are the images of the historical menus themselves. These visual aids work extremely well, not only are the scanned menus in pristine condition, bu there seems to be images for each and every menu, even dating back to the restaurant menus from the 1850s. In terms of visual aids, nothing seems to be unclear to me, although having worked on a similar type of project to this allows me to understand how and why this project is designed how it is.
2. The main positive feature from this site in my opinion was the ability to take dishes from the current menu I was looking at and viewing all of the menus they could be seen on in the database. Additionally, I was able to see how frequently this dish appeared in different decades. For example, choosing an 1859 menu from the New York Hotel, I was able to choose "Broiled Ham" from the menu list to the right of the images and was able to see that broiled ham appeared in 622 menus on this database. Also, I was able to see that broiled ham appeared frequently on menus in the 1860s, and had small resurgences on menus in the 1880s, 1930s, early 1940s, and early 1950s. However, broiled ham has not been on any menu in this database after the year of 1970. Overall, I feel that being able to obtain all of this information for any food on any particular menu was an incredibly useful and interesting.
However, one feature that I felt could have been improved was the "Related dishes" feature. Continuing with the previous broiled ham example, the related dishes did not actually seem to be dishes similar to this dish. Rather, they were just the same dish with different spelling/capitalization. For example, related dishes to Broiled Ham were, "broiled ham", "Ham Broiled", "Broiled: Ham", "Ham, broiled", etc etc. While I understand that this happens because the same item is spelled and tagged differently within different menus, this feature would be much more useful if the related dishes were actually that, rather than just different spellings and capitalizations of the same dish.

**Comment by Pomilui** [comment]
# Being a LotR fan, I couldn't resist exploring LOTR Project.  

**1:  While most of the visual aides provide the user with easy access to useful information, the main page’s “Elf Lineage” visual aid requires the user to scroll right and down to explore the entire tree.  The legend for the lineage tree is also at the bottom left of the page and may go unnoticed.  Having this map on a separate page and separated into races would help.  The other visual aids like the map in the “Timelines” section, and of the charts in the “Statistics” section are easy to navigate and obtain various information about events, characters, and races from the stories in one or two glances.  The map in the “Timelines section” looks similar to GoogleMaps, which is nice, but there are many clumps of “red balloons”, and it’s hard to pick click on just one.  The color coding feature to the right of the “Timelines” map was hard to find, and is pretty useful in adding some contrast of color for on event to another.  However, there is no way to quickly get from the “Fourth Age” to the “First Age” without scrolling through all the events (and there are many).  Having hierarchical tabs like an owner’s manual in Adobe might benefit this section.**  

**2:  My User Experience for this site is mostly positive.  It encourages exploration even if the means to explore aren’t glaringly obvious.  The color schemes (mostly gray and white), responsiveness of links (highlighting when scrolling over them), and the sheer volume of info available make LOTRProject.com a fun experience.  My review of the “Maps” section is that is can technically be combined with the “Timelines” section.  However, the user could easily spend 5 minutes searching for an event in the list.  In terms of geographically learning more about LotR, this section is very useful.**

**Comment by Pomilui** [comment]
@alexfell06  **I see what you're talking about in the "Related Dishes" feature.  The instructions read, "
Related dishes
Click the + sign to add a dish to charts on this page or the eye to view its information page."
   When clicking on all of the dishes, you can get an idea of when this dish was popular (Guinea Chicken Saute, Fresh Mushrooms was on 167 with most of them from the 1910's).  While I like the vast amount of info on "What's on the Menu", I found it difficult to navigate the _depth_ of the info since there isn't much alphabetical organization, and scrolling is often required.  
**

**Comment by garrettjoiner** [comment]
1. I decided to look at the ORBIS website to get a feel for the historical aspect of data visualization. Overall the website works well for someone who is interested in extreme details, what I mean by that is that this website has a lot of information. The problem being that it might have to much information. the front homepage of this website is very busy to the eye at first glance which may turn the casual viewer away. With all this being said the thing that I found most interesting about this website was the fact that one can plot any point on the map so long as it is a town and find detailed information about the trips path and how many days it would take to get to a location. It does all of this while giving the viewer the ability to change the season and chose between fastest, cheapest, and shortest routes. While the website does a good job at showing us in detail the days and how long it would take in certain sections, it does not display the cost very well. The people who are on the website seem to be left to their own devises on this website.

2. Overall the user experience was great. I really enjoyed plotting out different areas on the map and seeing how routes were taken during these times. Visual aids like this serve the historical community well, with this we can look at historical information and draw people in to learn about stuff like this without that individual being bored to tears. My girlfriend even enjoyed messing around on the site and she gets so bored when I get excited about history. Overall I give this website and A!

**Comment by quantum-satire** [comment]
ORBIS is an extremely detailed and well-executed project that provides information in a user-friendly way. It's easy to navigate, and even comes with a handy "Tutorial" button. I took a few years of Latin in high school and I remember trying to learn a lot of the information the website gives its users for projects and papers, but the site makes it extremely easy for scholars to click a few buttons and have their answers right there on the screen within seconds. I particularly like the options for path coloring, which changes the lines to a gradient depending on the starting and end points of a path, and the icons for the departing season, which helps to make the UI "friendlier." The immediate About Page holds plenty of useful information up front and keeps the user from becoming confused as to where they should go to find, for instance, information about the research implemented in the project, or to find YouTube tutorials on how to use the interface to perform certain tasks. I honestly can't think of any criticism to make against the site. Overall, I'm very impressed by the amount of work and time that was most obviously poured into the project. (I took a look behind-the-scenes at the page source just for kicks and am doubly impressed.)

**Comment by dorothealint** [comment]
I looked at What's on the Menu and I love the graphics of the original menus.  I love how you can search an ingredient and have all the menus that have that ingredient come up...however, the drawback I found in searching is the lack of a really specific "and" option.  The search is well organized in that it gives you the menus ordered by year and the attention to detail is excellent in listing the ingredients to match a search.   However, I can see a case where someone might want to know the popularity of one ingredient in a specific year.  The + option on this gives you the ingredient for all years and all menus for the year you search, for instance if you search beef+1998 under the menu tab, you get all menus with beef dishes and all 1998 menus mixed together.  If you do this search under the dishes tab, you end up with the wine list from 1998.  A more refined ability to search would be the one change I would try to make to this site.
I also did a simple search for "rum" and when it brings up the menu, it tells you how many dishes are on the menu total.  I would love to be able to see how many dishes on each menu include the search ingredient at a glance.

**Comment by MarkTheShark01** [comment]
I chose the Lord of the Rings website because dude, it's Lord of the Rings!

1. The visual aides provide easy user access to the different sections of the website. The Elf Lineage on the main page, however, requires you to scroll down and to the right many times over just to see the entire tree. There are many different sections that are placed close to the bottom and at the far right that could potentially not be seen. Some sections, such as the Hedon tree at the very bottom, have the most potential to go unnoticed. There could be multiple pages that could separate the different branches and families to help make the tree more organized. This would help to ensure that many of the branches that go unnoticed can be easily accessed. The timeline section has sites on the page that can be clicked on to read about certain events that happen, thus making it easy to navigate. The way it sort of resembles Google Maps helps to give off a vibe of familiarity, making me feel like I'm not looking at anything confusing. That being said, the red bubbles all clumped together make it feel cluttered, and can sometimes lead to clicking on the wrong bubble. There's also no tabs that can take you to different ages throughout Middle Earth's history, instead leaving people to scroll through multiple lines of text to reach the different time periods. The statistics section does a good job at using the links at the top to automatically move the page to the very section. It does a good job at describing different events, races, and various characters throughout the different stories. 

2. I would say that my user experience was definitely positive. I thoroughly enjoyed going through the different features of the website, and learning more about the different lore of Middle Earth that I hadn't learned about just yet. The Timeline section will most likely be the most difficult part of the site to navigate due to the minimal amounts of means to search through the site. The different aspects of the presentation of the site and the amount of information that can be discovered make the website an absolute joy to explore if you're a fan of the series.
