### ISSUE TITLE
Discussion: Student DH Projects 

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#419]
Choose to explore and discuss one of the following project sites developed by students. Several of these are undergoing continued development this semester!  Describe (in your own words) at least one significant topic it seems to be exploring, and reflect on what research the developers might want to investigate next, the UX of the project site, and/or what ideas it inspires for new projects. In a gentle, constructive way (realizing that project developers may be monitoring the DHClass-Hub), mention what  issues or problems you can see with these sites. Those of us (instructors and returning students) who have been involved in these projects should help introduce them to our class and point out things that need work.

- [The Hamilton Project](http://hamilton.newtfire.org) Developed by @ahunker and @bsf15 last spring, and continuing development this spring!
- [Profanities in Quentin Tarantino's Screenplays](http://bamfs.obdurodon.org/index.xhtml) (Pittsburgh student project, with network analysis)
- [Graveyard Project](http://graveyard.newtfire.org): Developed by @jonhoranic and team last fall, and could be continued...
- [The Lope Project](http://lope.newtfire.org): ongoing project led by @setriplette begun last year.
- [Divergences in Machine Translation: Examining Harry Potter texts processed by Google Translate across multiple language families](http://translate.obdurodon.org/)

**Comment by alexfell06** [comment]
I chose to explore the Quentin Tarantino site due to my love for movies, and I was very intrigued and impressed with results. In general, the topic of the site was to examine the frequency of curses and slurs within Tarantino's 3 most recognized films (Pulp Fiction, Inglorious Bastards, and Django Unchained) as well as the relationship between gender and cursing. So, the goal of the project was to examine how frequently curses and slurs were used within these films, as well as how the gender of the speaker affected the frequency of these profanities.
Overall, the results were incredibly fascinating and, having seen all but 2 of Tarantino's films, logical. There was some mention of possible future paths in the "Further Research" portion of the conclusions path, but as I was reading through the site the next logical path that I would want to explore would be to include all 8 (technically 9 since Kill Bill is 2 volumes) of Tarantino's films. An interesting observation that could be made by including all of his films is to determine if there is any correlation between frequency of curses/slurs and national award recognition. For example, maybe the 3 films that were nominated or won academy awards were the least vulgar of the group.
Another idea I had for future observations while observing the site was to possibly analyze curses and slurs by the race of the speaker. The site already has incredible information for gender, but also exploring the correlation between race and curses could lead to the discovery or intriguing data.

**Comment by Pomilui** [comment]
I liked how the Graveyard Project preserves some history of this area, and I'm familiar with Brush Creek Cemetery.  The Home page is short and to the point, but lacks some depth to guide the user to anything further.  The color scheme of black lettering on light blue background gets the job done as well.  All of the About section is appealing to users, especially the description of methods with a couple of good links listed in the text.  
   While I read that the map image is "clickable" I was unable to load anything when I clicked on an inconspicuous part of the image (where the cursor turned to the "click hand").  Succinctly marking where the map it clickable would help the user.   The scrollable list of "People in Brush Creek Section I" contains lots of interesting info that encourages exploration, but the user probably needs more space to view the info as the cemetery map image only allows 1/4 of the screen to be used.  
   The Analysis section looks like it will be a nice touch once completed.  Changing the color schemes and moving some overlapping text boxes are needed.  
  The site definitely has potential, but my UX of it was straining.

**Comment by dorothealint** [comment]
I looked at The Lope Project. I absolutely LOVE the visualizations!  Those are awesome.  Having chosen to mark-up a play as my third xml exercise in the class, I thoroughly enjoyed the speeches by character and am curious how you did the tags for the characters to be able to end up with that graph.
I'm guessing the Prose tab is still under development because only the first link worked...which I looked at and from which came my question about future developments.  Since that first prose link is an English translation, I'm wondering if you will eventually look at the original Spanish along-side it.  I know that in translating, especially in translating emotions, often there are subtleties that are lost because the range of available words in the second language doesn't compare to the original.  It would be neat to be able to compare what has been lost, I think, in that category especially.
And now I'm going to have to go look up these plays and see what they are about because of the comparison in the home page to Shakespeare!  (And I took French so that's going to take me some time to remember the little Spanish I know!)

**Comment by setriplette** [comment]
So glad you liked Lope, Dorothea! The bar graphs by speaker in La dama boba is a set of bars drawn in svg. I used an xslt for each character to translate the number of speeches into the bar size and then put the outputs all together in my html and hoped for the best. @RJP43 did a lot of this and she probably remembers how it's done...I just looked at my old files and I think it might be hard to recreate, even with a play tagged the exact same way.

There are quite a few Lope plays in translation. We have one prose text in translation on the site because part of our project team needed to work in English. I'm not sure what I'll do with it long term.

**Comment by setriplette** [comment]
And Dorothea, the basic tag structure looks like this. It's the TEI way of doing dramatic tests. My graph counted number of sp elements for each speaker.

```<sp><speaker>FINEA</speaker>
<l>what Finea says</l></sp>

**Comment by garrettjoiner** [comment]
I decided to look at the project that had to do profanities in Quentin Tarantino. I liked the information that was given by the web page. Profanities are a huge part of his movies, and the way the words are broken down. I like the way it has curse words broken down in curse words into curse words and slurs. I thought it was funny how the n word was said more in Django Unchained then curse words or slurs in the other movies. The graphs were interesting I like how it has the curse words and slurs were broken down into genders and such. Something I would say in the future is to add more of his movies. This would be because there is a lot of information from the other movies. So I think rounding out all of his movies would offer a complete record of information. Overall this is a good piece of work. Keep up the good work.

**Comment by dorothealint** [comment]
@setriplette That way of tagging is much cleaner than the way I did my play mark up.  I'm glad I asked that for future reference!
