### ISSUE TITLE
Rick and Morty Project Proposal

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#424]
I will come up with another "real" project idea because I seriously doubt that this wouldn't infringe on a zillion copyrights, and the scripts are probably not available so transcribing them would be a nightmare (and it might already exist somewhere); but I think a really cool site to develop would be a look at _Rick and Morty_.  To track all the cultural references, the easter eggs, and other things necessary for analytic viewing of the show digitally in one place would be the dream of fans everywhere.  A map of the Rick and Morty universe would be really awesome too.
Even though there are tons of fan videos parsing every episode individually, and even media documentations of episode or season specific tracking of these, I don't think that there is a coded collection of them out there meant to allow users to extrapolate data digitally so fans can speculate better on what might come next!  Here is the Time Magazine link just for those who have never seen this show before so you can see the intelligence behind the creation of it.  This really is a THING we nerds do in our spare time.

http://time.com/4868184/rick-morty-easter-eggs/

If time wasn't an issue, I bet the creators would even give permission (or contract to share advertising revenue it would generate) for a project like this.  They might even hire the development of something like this.  If I wrote a show in which this type of attention to detail was required, I would love to be able to go in and digitally keep track of what we already used to track at a glance what might tie in to prior references.

**Comment by ebeshero** [comment]
@dorothealint I finally had a chance to look at the easter eggs site--and what impresses me is that the effort to develop the site seems like a kind of markup--adding some information to the episode. These are annotations in a way, and can be tied to specific episodes in time and place.  

Better news, though, may be that this *could* be a viable project because the transcripts are all available on wikia via "Rickipedia": http://rickandmorty.wikia.com/wiki/Category:Transcripts . I wouldn't recommend reproducing them publicly--I'm looking at the terms of re-use and I'm thinking we'd want to be careful of copyright infringement (of wikia? its media player? not sure)--but the transcripts are being made by volunteers, so I think it *might* be okay. But for our class, you wouldn't need to reproduce the text anyway (they're already posted right here). Instead, you could do markup and produce some analyses and visualizations from it!

**Comment by ebeshero** [comment]
Turns out these scripts are totally available via Creative Commons, as we discovered in class today! :-)

**Comment by jonhoranic** [comment]
@dorothealint I would imagine that this would be quite an extensive project to try to tackle, for there is a TON of content in the show to sift through and mark-up. It would be interesting, at least as a proof of concept, to try to do a hyper-focused study of one episode. This might be something to try pitching to the class for a project, or saving for later and working on with what you learn here in class!

Because the Spring half of the course is better structured for visualizing data, I picture a "content web" that weaves links/clips/commentary together on a page, and the background work being on the code. However! The Fall half of our coding courses may be better suited to investigate more of an "archivist" picture like the example link you gave us. Either way, I think it would be an interesting experiment!
