### ISSUE TITLE
Discussion of Network Analysis and Thalaba Project

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#425]
Read my blog  on an XML-based network analysis project I've been working on, [Spectacular intersections of place in Southey’s epic poem, _Thalaba the Destroyer_](https://digitalromanticist.wordpress.com/2013/08/23/spectacular-intersections-of-place-in-southeys-thalaba-the-destroyer/) and post here to reflect on the following:
- What are you coming to understand about network analysis and how it works?
- What kinds of things can you study with network analysis? 
- About the _Thalaba_ project: what do you think we are learning from using network analysis here? What questions do you have about how network analysis works, or about what we can learn from looking at the graphs?
- Look at some other network analysis projects are mentioned in the blog (such as the _social network analysis_ Six Degrees of Francis Bacon)? What ideas are you learning about the kinds of things or people or ideas can you network together?

**Comment by dorothealint** [comment]
Just to throw a comment out there, I was wondering what the plan is for the places that lack earthly coordinates like Heaven or Sodom and Gomorrah.  Will you attempt to plot the destroyed places at the coordinates of latest speculation?  A graphic of the accepted schematic of the universe in Southey's time period/imagination to plot places like Heaven?  These maps are really neat and the ones of, for lack of a better word, "imaginary" places are especially insightful in giving a mental picture to text.

**Comment by ebeshero** [comment]
@dorothealint Figuring out what to do with the imaginary places has been a fun speculation for me! For right now, I like having them in a network graph because the coordinate space is controlled by the *poem*-- Hell borders on Persia where? in Book 9!  But we could imagine trying to map these places--and setting the imaginary places in another plane above or below the planet. (What's also fun is that this poem shows you a view of the world in globe form--as if it's meditating on mapping of places...)

**Comment by ebeshero** [comment]
@dorothealint Southey's time was the early 19th-century--and this poem was published just about 17 years before _Frankenstein_!  It's fair to say that the cosmic "worldview" of Southey's time was modern/scientific or following the Age of Reason and Enlightenment. But he's looking to other times and places in his poems to model views of the world that are *not* of his time and place. It's..."out of this world". That makes it a challenge to "map" in conventional terms.

**Comment by Pomilui** [comment]
**Interesting read.  One part that I related to was when you mentioned how Tom Lombardi and your other colleagues imported their data from Excel to Gephi or Cytoscape.  However, your TEI code lets you have a large amount of samples (useful for any statistical analysis) that are, I imagine, already in some kind of hierarchy.  Thus, you can start the "sub-hierarchical" approach that OHCO requires.  

   I enjoyed playing with some nodes here:  http://ebeshero.github.io/thalaba/cytoscape3/#/ 
   It felt like peeling back an onion from the big round (important?) ones to see to what else its smaller parts were connected.  I'm relatively familiar with Data Visualization from a class I took last semester, "Human Factors in System Design", and I remember one saying about how quickly human eyes can take in info.  The concept seems like you said about zooming in close to get all the info to then step back an see the "worldly" (glaringly obvious) connections and some connections that inspire an elusive, almost intangible revelation. 

    Lastly, concerning metaphysics, I was reminded of this video concerning "The 10 Dimensions" : https://www.youtube.com/watch?v=p4Gotl9vRGs  ...  If I had a "favorite dimension" it would be the 5th, as I sometimes call it, "Imagination", but it can also be considered visual consciousness, or a combo of influence and choice.  It relates to how Southey's mind might have changed by seeing other people, places, and experiencing different influences in his travels (ie. the places stuck with him in his "writing mind").   **

**Comment by alexfell06** [comment]
I found this read really interesting. In terms of network analysis I think a critical part of this project hinges on the information found in this quote:
"Southey’s complicated epics challenge us just as they did his immediate audience, and might well expose us in our 21st-century weakness: we cannot easily assess their elaborate interplay of contexts, their investigative reading of a centuries-old archive of records on cultural encounters, their blending of ancient and contemporary sources from voyage logs and travel narratives."
Essentially, this is saying that these documents are difficult to analyze and digest for the naked eye. However, with the use of document analysis and XML markup, a number of things can be brought to light, depending on the goals and desires of the coder.
In terms of the graph, the most intriguing aspect to me was the notion of "closeness", especially considering that many of the places are of conceptual nature. As mentioned, closeness usually depicts a physical distance between two places, but it was very neat to see how these conceptual places were tied into the network analysis graph.

**Comment by garrettjoiner** [comment]
The whole network analysis aspect of this course is starting to come in to more focus. The reason we are marking things such as, male, female, person, place, date, etc. is so that we can extract the data later and use it to make graphs and other visual aid to demonstrate information. These visual aids bring words to life for individuals that find it easier to look at graphs than mine text. This kind of data visualization I believe will draw more people in to the field that are always tagged as being <boring>history</boring>! Instead of making individuals read layers of text that they find boring, but me as a historian find so intriguing is monumental. I feel we have only scratch the surface of a field that can literally bring history or literary works to life! Exciting times we live in amiright?

**Comment by MarkTheShark01** [comment]
I'm starting to understand the idea of network analysis more and more everyday. I like how we're marking up different people, places, and other things to later extract and use to make different visual aids. Being able to study virtually anything and everything- movie lines, songs, news articles, etc.- by putting them into code and breaking it all down is a major step forward in how we're able to obtain information through different mediums. Some questions I have mainly pertain to what else we could be capable of learning about through network analysis, such as radio frequencies, or even health conditions of a certain person. Just knowing that we're able to do so many things now, and think that we could be capable of learning so much more, is both scary and exciting to think about, and I'm definitely looking forward to seeing what happens next.

**Comment by dorothealint** [comment]
I've approached this class from the beginning from less of a programming standpoint than a network analysis standpoint.  I see what I might want to know in a group of documents and I can speculate what other people want to know.  My problem is the other way around, I want the extraction of the data to be easier than it is digitally!  I think as a programmer, I need to work on the limiting because I'm the one who is going to have to go through and pick out the stuff the computer should recognize.  I think the biggest thing I am learning from these examples of network analysis is that you can't code for everything, so choosing the most important items to your project is extremely important before you start writing code.
Technology is a double edged sword in my view.  I want to be able to give the computer a piece of text and have it know and be able to extract and categorize everything important about that text, I want computers to know EVERYTHING!...but I utterly hate the fact that my laptop and phone are aware of each other's existence, computers know too much.  Finding balance is the key to these markups.
