### ISSUE TITLE
Literature Project - Church Allegorical Plays (Spanish)

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#429]
I'm going to throw this out there too because it looks interesting from at least three perspectives: literary, historical, and religious...compiling a body of the auto sacramentals of the 16th and 17th centuries to mark up. (I'm already on YouTube going "oooh...I need to watch some of these")

Things that might lend themselves to a project like this include tagging the allegorical characters to see what sort appear, classifying them and perhaps looking for repetitious ones to find out why they were so important-perhaps tying in with historical events; searching for key words that indicate the presence of a sacramental reference; finding out where the plays originated in order to map the expansion of the Catholic religion through the use of performances of these plays; searching for comparisons to native religious tenets that were usurped by Catholicism in order to facilitate the acquisition of converts in the New World; and looking into how God is portrayed in the plays in which he appears.

Before I looked at _El Gran Teatro del Mundo_ today http://www.cervantesvirtual.com/obra-visor/el-gran-teatro-del-mundo--0/html/ff39e206-82b1-11df-acc7-002185ce6064_3.html (It says the English translation is on Project Muse but it didn't come up when I clicked on it), I actually thought about proposing a look into how "forbidden" characters or ceremonies were portrayed on stage (such as Faust summoning Mephistopheles without accidentally summoning a demon on stage or the portrayal of a representation of God) but I wasn't sure where this would lead and the body of work didn't seem to be as easy to define for me as this category specific group of plays is.  I thought of taking specific scenes out of a number of plays rather than having to mark up entire full length plays but the allegory plays are short so the time constraints of the semester would allow more to be done with them than full length plays!

I probably need a Spanish speaker though!  I can recognize the language and grab maybe a hundred words but I am by no means able to sit down and READ the play in Spanish.  I was thrilled I could understand that title upon seeing it.  Having a Spanish speaker would help in searching through the original words because translations always lose something...and that's if enough plays are available in English translation.

**Comment by Pomilui** [comment]
###  I enjoyed reading Sor Juana Inés de la Cruz's "Loa to Divine Narcissus" in Dr. B's Pre-19th Century American Lit class, and I think that there is loads of potential with this project.  
###   Of these:  "searching for key words that indicate the presence of a sacramental reference; finding out where the plays originated in order to map the expansion of the Catholic religion through the use of performances of these plays; searching for comparisons to native religious tenets that were usurped by Catholicism in order to facilitate the acquisition of converts in the New World; and looking into how God is portrayed in the plays in which he appears."...  I'd most enjoy the geographic part of _finding out where the plays originated (or were conducted in the New World / New Spain / Other colonies in order to map the expansion of the Catholic religion_   Since there are so many plays, we could stick with one author and investigate a series of his or her works (narrowed to certain scenes).  On the other hand, we could, like you said, pick a time period/location to take specific scenes out of plays on a broader scale.

**Comment by jonhoranic** [comment]
@dorothealint This would be something you might want to collaberate with @setriplette for since her Lope project has some overlap with this concept! One thing I would like to note, that idea of looking for the "forbidden" characters/content would make for an interesting data network. With mark-up, it can be difficult to represent what does NOT appear when using mark-up. However, if you know what is not represented in the text or what is changed, you can use code to "fill in those gaps" with additive information/referencing.
