### ISSUE TITLE
Proposal 1:  Quantum Physics and Christianity in "A Wrinkle in Time" 

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#430]
###  The books aren't exactly freely available for markup, but maybe we could purchase the book(s) on a Kindle ($25 tops) and put the text into something else.  Let me know what you all think.  Thanks.

### - Nick**

**Comment by dorothealint** [comment]
I had never heard of this book until this summer when my friend Shaena told me it was her favorite and I should look into it .  I'm all for quantum physics and religion discussions!  But Shaena had another angle that might broaden the scope of interest in a project on this to education majors.  The portrayal of the characters on an intelligence continuum versus social continuum.  She resonated with the book because of the potential for integration of students of different aptitudes...I'm thinking plots of the characters on an IQ vs EQ graph and find out where the cut-offs would be to the ability to relate to one another or attempting to put them on a psychological personality scale and chart the inter-relatability between personality types (who needs another personality type in the room to introduce interaction vs which characters are comfortable talking to each other naturally could be a useful way to graph this to be a reference for team building).

**Comment by quantum-satire** [comment]
I find this project intriguing because of my love for physics (username relevant) and I'd love to work with this text! However, you'll want to be careful about copyright here--when you stated that the book was not free, it sent up some flags and I did some digging. The book is not yet in public domain, and this could cause some issues if we went to work with it for a project.

Hey @ebeshero is it feasible to work with copyrighted texts for our projects? I know it would probably be best to stick to public domain, but this might apply to my proposal as well now that I think of it... Navigating copyright is very tricky.

**Comment by ebeshero** [comment]
@quantum-satire It's probably best we don't republish copyrighted texts unless the owners give us explicit permission. We could identify and grab **data** from the texts (but that means we need to get hold of digital copies)--adding our layer of digital markup to them (our own intellectual interpretation), and visualize that without representing the text on a public website, and that's what some projects in our Pitt DH courses have done in past years. We'll need to think about source texts, too--how readily available is electronic plain text of a document? We don't want to be breaking laws to get hold of text we can work with.
