### ISSUE TITLE
Project Proposal: Analysis of Karl Overholt's Diary

### ISSUE THREAD

**Issue by alexfell06** [ebeshero/DHClass-Hub#433]
My project proposal is to do an analysis of Karl Overholt's diary. Karl Overholt was a member of a Mennonite community in Scottdale, PA. Scans (and potentially the original document) of the document are currently held at the archives at West Overton Village & Museums.
I have looked through the diary, and a majority of it contains stories about people within the villages or just information about current or past events in the village. Additionally, there are things in the diary such as Mennonite recipes, among other miscellaneous items.
For the project, the document could be marked up a number of different ways, including references to people, places, or businesses.

**Comment by Pomilui** [comment]
### I like this historic approach to marking and possibly mapping relationships and community building in humble beginnings.  I imagine that a phone call and/or a visit to the Museum might result in obtaining a copy the diary.  We could show the Overholt families influence in the region through their connection with Henry Clay Frick and the coke/steel alliance between him and Carnegie.  I'm guessing there could be a geographic map somewhere in the project based on the events mentioned in the diary along with Mennonite history and growth in the area.

**Comment by quantum-satire** [comment]
This could be a really cool project, especially for the history of the local area. I like the fact that there could be different aspects to the project, such as marking up not only stories and letters but recipes as well. You said the document has been scanned, but do you know if the diary is also already transcribed? This may prove to be difficult if you need to transcribe the diary by hand--this takes lots of time, which is something to keep in mind.

**Comment by jonhoranic** [comment]
@alexfell06 This could be a very interesting way to show how we can open up the use of West Overton's  historical information/data to the community! A coding project like this can boost accessibility and interest for otherwise "forgotten" content. Being a student project with access to materials like the ones you wish to work with will be an interesting show of skills and respect for this information. I would be really interested to see this project start up, even if it is only as a proof as concept that other students can assist on developing in the future.
