### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#44]
`We have a separate template rule that matches the <listOrg> elements (holding the lists of organizations), so it will be invoked as a result of the preceding <xsl:apply-templates> instruction, and will fire once for each <listOrg> element in our Site Index`  --Could somebody explain what this means? I understand that it is matching the <listOrg> elements (I think) but I what does the rest of it mean?

**Comment by CodyKarch** [comment]
@ebeshero @ghbondar @RJP43

**Comment by CodyKarch** [comment]
Hello? Anybody?

**Comment by ebeshero** [comment]
@CodyKarch Hi Cody! Just saw your post. Here's what I meant: basically you want to write a **template rule** for this:

`<xsl:template match="listOrg">
    .

</xsl:template>`

Think about why we need that! When you do XPath over my site index file, you'll see there are multiple `<listOrg>` elements, and our outermost list is going to collect all of them in a single list. You want to match on something that holds all the listOrg elements up in your template that matches on the document node ( the one that holds the outer structure of your html document: `<xsl:template match="/">`   and you want that to hold the thing that contains your output list (either `<ul>` or `<li>`)... 
And then, since each listOrg has a distinct identifier: you're going to match on that in a **separate template rule** so each one is output as a list item. 

Then you need to set up, **in each one of those list items**, a new list to sit inside it.

**Comment by ebeshero** [comment]
@CodyKarch We talked about some of this in class, and you can see some examples of list code and XSLT that some of the other students have pushed to GitHub in Class Examples in XSLT. Browse away--looking at those will likely be helpful!

**Comment by ebeshero** [comment]
@CodyKarch One more thing, because I think we discussed this in class after you left for your advising appt.: If you're confused, try writing your code one step at a time, and **run your transformation after each step** to see what you're outputting. That can be a clue to how your template rules are working. Remember to select the "HTML" button before you run the transformation, so you can toggle between the text and the html view in the output window.

**Comment by CodyKarch** [comment]
Great! This should help, and I believe you mentioned that before I left; I've used that rule, and I agree with you on it. Thank you!!!
