### ISSUE TITLE
Discussion: Steve Ramsay and "Screwing Around" with Computers

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#452]
Over the next few days (before Monday 2/19), choose at least one of the following two articles by Steve Ramsay to read and discuss: ["The Hermeneutics of Screwing Around; or What You Do with a Million Books"](https://web.archive.org/web/20140604085234/http://www.playingwithhistory.com/wp-content/uploads/2010/04/hermeneutics.pdf) **AND/OR** ["In Praise of Pattern"](http://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1056&context=englishfacpubs)

Here's a discussion prompt to get us started:

- As you are working on and thinking about your projects and reading Steve's work, what do you notice about the way you're thinking about "doing research" with coding? What do you think of Steve's perspective on "screwmeneutics" (for example) and the way we explore humanities with tech tools to find patterns?

**Comment by dorothealint** [comment]
"We think of the computer as a device that has revolutionized search—“information retrieval,” to use the formal term—and that is of course true.  Until recently, no one was able to search the content of all the books in the library."
My first thought on this article is an answer to this quote:  THEY STILL CAN'T.
However broad the "new" way of searching for things is, it isn't really "new".  We did this before computers even existed.  It just took a little longer with card catalogs and indexes.
BUT I can hand you a book right now that doesn't list every relevant use of a term in the index because whoever wrote the index wasn't thorough.  The same is true for searches using technology.
The first thing you have to know is what you are looking for.  And the second thing you have to do is hope someone else at some point in the digitization of the library thought it was important enough to catalog.
It doesn't matter how much technology you have, you still have to have people reading the books, pulling out the relevant information, labeling it, and categorizing it or no one will be able to access it when they search a library database.
I think that's the biggest fear in the attempt at merging digital technology with humanities.  That people are afraid no one will look deeper into things than what an algorithm can find if that technology permeates the discipline.

**Comment by Pomilui** [comment]
Ah, the serendipitous approach to research vs. the thoroughly established "science" of information retrieval.  "Hey, I found this old 18th century text in my attic/Wikisource/a time capsule that relates to this subject!  What did you find from your 4+ plus searches on Google's 'individually-tailored' results that 500 other scholars already found?" ("Duck it" for repeated searches on 1 computer). 
     The point I think that Ramsay is trying to make in "Screwing Around" is it's best not to rely on "the essentials" or the efficient, logical approach to research to have an individualistic touch to your knowledge on a subject.  I agree with Dorothea that the fear of someone not being on the same wavelength as me in order to justify my waltzing through the library and pulling books off the shelf can be considered "research".  "How could ___" not be in this section?!"  

    I liked the section concerning Martin Mueller's notion of "felicitous reading".  I'm guessing that it's a broad approach to verifying that "your network of associations corresponds to the actual one..." simply by seeing WHY a book or paper is in the archive at the moment you find it.  I also liked Greg Crane's library of data mining books, although the term "useful information" might be too vague to be tailored to "any given human being of any culture".

**Comment by Pomilui** [comment]
## What do you all think about screwing around on modded forums?  Do you stop in on Reddit and ask for the "essentials" on a new music genre you'd like to explore?  Why take the advice of ONE "professional" concerning a list of 100 best tracks or 100 best inventions when you can get a dozen favorites from 30+ ENTHUSIASTS in a forum?

**Comment by alexfell06** [comment]
@Pomilui I think you bring up an excellent point with your question about the Reddit forum, and I think this is a key reason on why Reddit is so successful and loved. When used correctly, community-driven sites can be equal parts academic and enjoyable. Personally, going off of your music hypothetical, I would much rather receive suggestions from multiple enthusiasts than one "professional". One bonus of the community site is the ability to interact. A music analyst from Rolling Stone or Vibe magazines is incredibly unlikely to respond to your comment on his album review. However, when used correctly, a site like Reddit can generate highly informational and interesting discussions about topics many people enjoy.

**Comment by alexfell06** [comment]
The overall premise of the article "The Hermeneutics of Screwing Around; or What You Do with a Million Books" is an ambitious and ultimately very daunting task. The analogy that was used about browsing a library was helpful in attempting to wrap my head around this premise, and I think @dorothealint made an excellent point by stating that not only do you have to be aware of what you are looking for, but somebody else had to be aware of that same thing previously. 
I have had comparable situations in which I wanted to search something abstract regarding a hip-hop artist or an NBA player/statistic, but if nobody else who could have created/posted something regarding the topic had the same thought, my search will come up empty.

**Comment by dorothealint** [comment]
Adding to what @alexfell06 says about searching and having nobody else who had the same thought before...if the people who do the first searches are trying to label everything, they can get bogged down in the labeling and categorizing and miss some awesome new interpretative aspect of a concept and then you lose that part of the research as well.  It's a balancing act between too much information and too little thought and no where to find the information to start from!
