### ISSUE TITLE
Starting Early on XQuery 2

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#461]
@ebeshero @quantum-satire @alexfell06 @MarkTheShark01 @garrettjoiner @dorothealint @jonhoranic 

Here we go again, eh?  My first question concerns #3 B:  what are the"particular texts in the collection"?

I'm guessing that they are simply P elements in the body, and I found them with 
`let $coll := collection('/db/mitford')/*
let $body := $coll//tei:body
let $texts := $body//tei:p
return $texts`

Simple stuff, but I gotta start somewhere.  :1234:

**Comment by dorothealint** [comment]
Working on mine now.  the particular texts in the collection are each individual letter.  They are the titles of the files that contain a body element.

**Comment by ebeshero** [comment]
@Pomilui @dorothealint and all: greetings from Iceland, near the Keflavik airport where I have a short layover before heading to Germany! I wanted to say I disagree with both of you—and you can take me literally on the assignment page when I say to look for “the particular texts in the collection, starting from the `<body>` element in our TEI files. (You’ll need this later.)”

I was really just intending for you to set a variable on the `//body` element of each file in the collection. @Pomilui  , you must be thinking of all the different *text nodes* throughout the document, and angling for the smallest units of text(). That wasn’t what I had in mind for the question, but I see today why you might think that after our discussion of the text() node yesterday! Anyway, what I wanted you to do is find the `<body>` elements of the files, **because** a TEI file has two main sections (two children of its root): a `<teiHeader>` element and a `<text>` element. Inside the `<teiHeader>` is a lot of meta-information *about* the document being represented: who wrote it, where is the source document located, etc. Inside the `<text>` element is the document itself, so I really could have asked you to isolate that element here! In my documents for the Digital Mitford project, I have inside `<text>` a `<front>`, `<body>`, and `<back>` element, and the `<front>` and `<back>` each have some more “meta” info about the Mitford document that we don’t need— the main “body” of the document (a whole Mitford letter or play or other piece of writing by Mary Mitford) is coded inside the `<body>` element. We are basically going to be “drilling down” into the `<body>` element to pull out Mitford’s mentions of people she knew, etc, so we want to define a variable kind of like a bookmark to isolate the chunk of each file that contains Mitford’s writing! Hope that helps.

**Comment by ebeshero** [comment]
So, when I refer to the particular “texts” in the collection, I really just mean the stuff you return with your `$body` variable, @Pomilui !
