### ISSUE TITLE
My computer hates me and other adventures in XQuery 

### ISSUE THREAD

**Issue by garrettjoiner** [ebeshero/DHClass-Hub#462]
xquery version "3.1";
declare default element namespace "http://www.tei-c.org/ns/1.0";
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $MitfordColl := collection('/db/mitford');
return $MitfordColl

So I am having troubles with this, same issue I had before where I can not move past this point. I keep getting an error that says, "Cannot compile xquery: exerr:ERROR org.exist.xquery.XPathException: err:XPST0003 unexpected token: $ [at line 5, column 8]"

John and I tried to fix the issue on Friday, I still can not resolve the issue. (FRUSTRATING). 

If anyone has suggestions on how to resolve this issue I am all ears.

I have tried to clear the cache on my laptop with no results. 

Sincerely,
Frustrated Guy On Laptop

**Comment by ebeshero** [comment]
@garrettjoiner @jonhoranic The issue is simple (thank goodness!) You can only use a `return` statement when you are writing a FLWOR! You really want to just indicate `$MitfordColl` without the word return when you are using the `declare variable` syntax.

So, just remove the word `return` and you'll be fine.

Now, the other way is to write this as a FLWOR the way we were doing in class. You'd do that by setting the variable using a `let` statement like so:

```
xquery version "3.1";
declare default element namespace "http://www.tei-c.org/ns/1.0";
let $MitfordColl := collection('/db/mitford')
return $MitfordColl
```
Notice, when you write a FLWOR like this, you don't want a semicolon after the variable declaration. 

One other small thing (not a problem here) but notice that you declared the default element namespace as TEI, and then also declared the *prefixed* namespace as TEI. You'll need to pick one or the other. As you proceed with that assignment working with the Mitford collection, you are going to be outputting HTML, and I'd advise not prefixing the HTML elements--so I'd set the HTML namespace as default. That'll mean you need to prefix all your TEI elements. Sorry--but that's life working with namespaces. Meanwhile, though, I am relieved that there isn't anything wrong with your laptop, and this was just a syntax issue with assigning variables.

**Comment by dorothealint** [comment]
We couldn't get the LET statements to work with the html table output on Friday which is why we started using declare variable statements.  We didn't know why, only that it worked that way!
