### ISSUE TITLE
Overholt Project Questions

### ISSUE THREAD

**Issue by alexfell06** [ebeshero/DHClass-Hub#466]
Having scanned in the diary, I was wondering what the next step to take with the project would be. I know we discussed using OCR on the document previously, however, I was curious if the OCR available to us would work on handwritten documents, as the diary is handwritten. Additionally, I was wondering if there is a size limit to the OCR program. Currently I have the jpeg images of the diary (341 pages) stored on a USB file.

**Comment by quantum-satire** [comment]
Hey Alex! The OCR program available is currently installed on the computer in FOB 131, in the Center for Digital Text. I used it a lot for my project last semester, though our documents were typed by typewriters, so I haven't used it for handwriting before. @jonhoranic would know more about this...

If you want to meet after break I can show you how to work with the program. It's really very easy, but also time consuming--though not nearly as time consuming as it would be to transcribe all of your scanned images by hand. As far as size limits, I _believe_ you should be alright...

**Comment by ebeshero** [comment]
@alexfell06 People have done OCR on handwriting with ABBYY Finereader, but it takes time to train the software to recognize the letters of the alphabet and punctuation marks reliably. @jonhoranic is our ABBYY expert, since I set him to work learning the software last year—but we have to my knowledge only trained it on print documents. (It works great on newspaper scans, for example.) I think we will all be learning how to do OCR of handwriting via your project...and the question may be whether the time required to train the software is worth the trouble. (Maybe it is! But maybe you could also be transcribing the diary yourselves and compare the time it takes to do some entries.

Spring Break is a great time to work on this for the long connected hours you could spend. The Center (FOB 131) is available to you with the door passcode as long as you can get into FOB.

**Comment by alexfell06** [comment]
@jonhoranic Hey I was wondering if you would be able to meet any other time than your office hours tomorrow to guide me through OCRing the Overholt Diary. I work 9-2 every Tuesday/Thursday and I have a class 4-515, but other than that I'm free. Could you let me know if any time works for you?

**Comment by ebeshero** [comment]
@alexfell06 Can you push the images of the diary to your project repo so we can get a look at them?

**Comment by ebeshero** [comment]
@alexfell06 Check the file size on each image: is it over 150MB? If so, GitHub may choke on the filesize. We'll try Box instead--use your shared file directory with me for DH class file returns. Also, you'll want to save a version with smaller file size--Try opening the image in an image editor and clicking "save as" to review options for saving for web view, etc. You can use Photoshop in the campus labs for this, or you may have another image editor you can try.

**Comment by quantum-satire** [comment]
@ebeshero You can actually resize multiple photos at once with this trick: https://www.easytechguides.com/resize-pictures.html

This may help with cutting down on file size and help to save some time.

**Comment by ebeshero** [comment]
Oh, that's a neat trick--thanks @quantum-satire !

**Comment by alexfell06** [comment]
I just uploaded all of the diary entries into Box.
