### ISSUE TITLE
Network Analysis Questions

### ISSUE THREAD

**Issue by dorothealint** [ebeshero/DHClass-Hub#468]
First of all, I realize that I have no idea if our namespace for documents we upload to the exist db is the tei?

Then I tried to adapt the example to one episode script of rick and morty and realized that when we name the characters, we do it in an attribute because nothing in the scripts is standardized so the graph wouldn't come out unless we used our standardized attribute.  Can we use an attribute value in the for loop when attempting to pull the character names or do I need to go back and re arrange some markup on this script?  This is the only one with this much dimensional interaction so it is the one I'd want the graph for.

What I'd like the graph to do is pull out each main character as a primary node and link them to each dimensional character they are in either a conversation with for the first tier, or in a scene with for the second tier.  Main and Dim[ensional] are attributes added to the script by us.

I know this matters because there is ONE other dimensional morty who responds to the MAIN character rick...and that's not supposed to happen!  That is a connection that would come out in the graph. (I saw this while trying to separate the conversations and I want to see what other relationships are occurring between dimensions.  I can already see from doing the markup that dimensional characters are only able to personally interact with certain main characters-they ignore others in the room- and I think seeing the different connections would be interesting!)
@quantum-satire working on a network analysis graph for our project!

@ebeshero if it's too much to attempt to fix remotely and you have a meeting time today (Tuesday) I'd be interested in some help! My file and my attempt at xquery is saved in my exist db folder.

**Comment by dorothealint** [comment]
I think it might generate the graph I want now.  They are in lint_rNm_networking and lint_rNm_xml in my existdb folder.
if I was confident what file path to put in for it to follow to find the file!

The graph I want is main character personal and casual encounters with dimensional characters.

**Comment by ebeshero** [comment]
@dorothealint Sorry for my delay in responding...but I think we covered most of these questions when we met yesterday! For the first point about namespaces: Your own home-cooked XML isn't in a namespace, so you don't need to worry about declaring a default namespace. 

(Sidenote: You can actually create your own namespace by using the @xmlns attribute on your root element. You can make up anything you like, as in <root xmlns="http://dorothealint.org"/> and create a special dorothealint.org namespace of your own! You can make up prefixes for it, etc. Mostly we don't do this in Real Life but there are some uses of inventing your own namespace sometimes in advanced processing. The usual place where people run into namespaces is when you're working in a shared vocabulary for code, as in TEI and HTML. We'll run into namespaces again on Friday when we write XSLT in the xsl: namespace.) 

I'm excited to see how the TSV we worked out yesterday turns out for Rick and Morty!

**Comment by ebeshero** [comment]
@dorothealint Sorry I missed replying to this...but I think we fixed the

**Comment by ebeshero** [comment]
oops--accidentally closed this in passing...let's keep it open as we're working on your network!
