### ISSUE TITLE
SVG Ex 2 Circle Radii

### ISSUE THREAD

**Issue by Pomilui** [ebeshero/DHClass-Hub#479]
@ebeshero @dorothealint @setriplette @alexfell06 @jonhoranic @quantum-satire 

  Hey, all.

   I'm attempting to use `$matchingDates` and `$countLetterFiles` to increase the circle Radii accordingly, but with no luck yet.    

<img width="530" alt="capture343" src="https://user-images.githubusercontent.com/35349892/38178961-92bff7ca-360c-11e8-8b4e-0e383255e38d.PNG">

 I must define 2 variables to be used in a for loop to produce varying counts of files.  Where should this for loop go?  Thanks.  

Update:  Here's what I tried.  
<img width="489" alt="355335" src="https://user-images.githubusercontent.com/35349892/38179135-15b9c226-360f-11e8-8179-805f3ccf2dec.PNG">

 - Nick

**Comment by ebeshero** [comment]
@Pomilui Think about where these circles are going to be placed with respect to the hashlines and text we plotted on the line. There's going to be a circle for every year, so you should do this within the same for loop you're using.

You're on the right track with your variables, but I think there's a problem with your `$lettersDates` variable, because it's not catching the letters for the current year. Look at the `$matchingDates` variable we constructed in class last time: That is designed to isolate the letter years that are the same as the current year we're on in the for-loop. Perhaps you want a count of those?
