### ISSUE TITLE
Introduce Yourself and Experiment with Markdown

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#500]
Introduce yourself and get familiar with how to write issues in markdown here! Can you include code blocks? Can you create [a link](http://dh.newtfire.org)? Can you include a screen capture? Can you write a list, and a checklist? 

https://guides.github.com/features/mastering-markdown/

**Comment by alnopa9** [comment]
# About me!!

Hello, everyone! My name is *Alyssa Argento*!

A few things about myself,

* I have a 1.5 year old son, Parker
* I've played soccer for nearly 20 years
* Knitting, sewing, and crochet are some of my hobbies
* My favorite color is green
* And I __love__ hockey
  * LET'S GO PENS!! :penguin: :penguin:

![Pittsburgh Penguins logo](https://www-league.nhlstatic.com/nhl.com/builds/site-core/295cb47d229bd587588369d442110d98ccc58a5c_1535568005/images/logos/team/current/team-5-light.svg)

## Weekend Plans
- [x] Buy and wrap present to give to Tyler (Parker's cousin)
- [x] Go to Dave & Buster's to celebrate Tyler's birthday
- [x] Visit Grammy and Pappy
- [x] Create a repo for Digital Humanities
- [x] Add content to personal repo and DHClass-Hub
- [ ] Pack swim trunks and baby pool for Parker
- [ ] Spend family time with family!

### Repo Link
Click the [link](https://github.com/alnopa9/my_page) to visit my personal repo for our class!

>Nothing is true
> 
> Everything is permitted

**Comment by bnm29** [comment]
A little bit about me...more like a LOT. But it is worth the read and I hope someone is like me in some ways.

1. My name is Brooke Moon.
2. I absolutely love animals...and not so much humans haha.
3. I enjoy snowboarding.
4. I have been riding dirt bikes since I was 2 years old, but just started racing last summer. And I actually ride a bike that is typically bigger than the bikes most grown men ride. 
5. I have lived on the river my entire life and I absolutely love it. We used to have a couple boats down at our dock, but now we just have 1 boat and a few Seadoos (jet skis). 
6. You will occasionally find me wrapped in a blanket outside in the sun while it is 90 degrees (I am not exaggerating) because I am cold 99% of the time.
7. I have never been considered a girly-girl, but I can make myself look girly if I have to. 
8. I learned to drive a manual when I was about 7 years old. 
9. I know how to run and use anything with a motor, even heavy machinery (like skid steers, excavators, etc.) which I could do all day, considering I am usually making new woods loops for practicing on my dirt bike. My dad actually taught me how to use machines like these when I was about 6 years old. 
10. I grew up getting muddy and doing fun but goofy things. For example, anything that you can attach to a rope that is hooked to the back of a quad, we will ride or pull. Our favorite things to pull are a train of stripped down tractors that barely steer anymore because of how how dangerously we ride them. (helmets and other protective gear is always worn hahahah)
11. I am naturally this blonde, which explains why I am extremely air-headed 24/7. 
12. My favorite color is an army/olive green.
13. I do not swear, never drank alcohol, partied, or anything else along those lines and I am 20 years old. 
14. I usually look like I want to hurt you because of my facial expressions, but I am actually quite easy to get along with. 
15. I played soccer for about 13 years and basketball for about 3. I quit playing sports because I am not a fan of the all of the drama and attitudes from most of the girls I ever played with, which is why riding dirt bikes is the way to go for me.
16. I love going to the gym, but since I started college it has been hard to find time to go.
17. I actually have never had a real job in my entire life. I have worked with/for my dad or by myself doing landscaping, grass cutting (I love cutting grass), building, construction, etc., but that is about it.
18. There are many unusual animals that I hope to have as pets some day, like a raccoon, an opossum, and an otter.
19. My entire life I have been looked at as the rich and snobby kid that is spoiled to no end, but I really am not. I do not act like it at least. So please do not judge like many people do. 
20. I am absolutely terrible with technology. I am lucky I know how to use the calculator on my phone, so I have no idea why I am in this class...

![img_0214](https://user-images.githubusercontent.com/42811976/45015177-df67d000-afee-11e8-80f4-7953609bdafa.JPG)

Click this [https://github.com/bnm29?tab=repositories] to see my repository/repositories for this class.

**Comment by awoods25** [comment]
<h3>About Me</h3>

*Hello everyone my name is Alec Woods and here is a few things about me:*

1. My major is Information Technology and I am in my senior year.
2. My favorite sport is basketball and my favorite team is the Chicago Bulls.
3. I played basketball from 3rd grade until my senior year of high school.
4. Both my injuries in basketball came in pickup games. I broke my thumb and partially tore my anterior talofibular ligament which connects the fibula to part of your ankle.
5. Durning the summer I got into Penetration Testing which is Ethical Hacking and I would like to pursue a career in Pen Testing.
6. I love to fish. My grandparents have a house in Jamestown, PA by Pymatuning Lake where I do most of my fishing. I have been deep sea fishing twice and would love to go again.
7. I have a 16 year old Jack Russell Terrier named Milo. She is named after the Jack Russell in the movie The Mask starring Jim Carey. I was 5 when I got her and that was my favorite movie at the time and she was the same breed as the dog in the movie. 

![milo](https://user-images.githubusercontent.com/42811973/45043485-46ab7180-b03b-11e8-82b3-8c7238e77d91.JPG)

**Comment by alexlavelle** [comment]
Hi there, my name is Alex Lavelle, here is some interesting things about me:

1. I am an IT major here at UPG, but I also have an Associates degree in Network Administration from WCCC.  
2. I am back in school hoping to to do either IT security or earn enough experience to one day become a Systems Administrator.  
3. When I was in WCCC, I took an HTML class which seems very similar to xml, and so far I've been able to enjoy this class and find the work interesting without many issues.  
4. I have a few hobbies, My favorite of my hobbies is cars. I've owned 7 cars so far and currently have 3.  A 2005 Honda Accord, a 1997 BMW 328i, and a 2006 Mazdaspeed 6.  The Mazda is m main car which gets most of my attention, the BMW never runs, and the Honda gets me where I need to go everyday.  Below is a picture of the Mazda.  
5. I also enjoy gaming, which was my initial pathway into computer science.  My family never had much money, so everything I got I learned to take care of and fix myself. 
6. I hope to build a budget gaming PC sometime in the neer future.
7. I have a funny little cat named Mr. poe poe after the DBZ character.  
8. I was born and raised in Jeannette, but now live in Greensburg.  

Here is a piece of code from our previous assignment:

` <discription title="Lord Byron Letter To His Mother Catherine Gordon Byron" Author="Byron">
            Lord Byron Letter To His Mother Catherine Gordon Byron
        </discription>
        <Title title="Harrow-on-the-Hill"> 
            Harrow-on-the-Hill, <date weekday="Sunday" month="May" day="1st" year="1803">Sunday, May 1st, 1803</date>
        </Title> `

[My Repository](https://github.com/alexlavelle?tab=repositories)

![autocross1](https://user-images.githubusercontent.com/42811911/45047682-bd4e6c00-b047-11e8-9f27-c1165f586899.jpg)

**Comment by bman8932** [comment]
**About Me**

- My name is Ben McCoy
- I am a supervisor on the night shift at UPS in New Stanton
- My favorite sport is football
- In my free time I enjoy riding dirt bikes and motorcycles
- I am an IT major at UPG
- I have 3 semesters until I graduate
- I have a dog, Riley

![riley](https://user-images.githubusercontent.com/42811960/45052006-9eee6d80-b053-11e8-834a-b723eda9a1d3.JPG)

In this class I hope to:

- [ ] Learn about XML
- [ ] Create a cool project
- [ ] Get an A

Here is a link to my Repository: [click me](https://github.com/bman8932?tab=repositories)


Here is a block of code from XML assignment 3: 

`<neededItems>Items You'll Need to Fix a Flat Tire
These items should have come with your vehicle:
<jack type="car jack"> </jack>
<wrench type="lug wrench"> </wrench>
<spareTire type="fully inflated spare tire"> </spareTire>
<ownersManual type="vehicle owner’s manual"> </ownersManual></neededItems>`

**Comment by Julegirl** [comment]
**About Me**
Hi everyone, my name is Juliana Moeslein, but I go by Julie. Here are a few things to know about me. 

-  I am a Professional and Creative Writing major; writing fiction is one of my biggest passions.
- I am a commuter and I live in the little town of Hunker. 
- I have a huge sweet tooth and I like to bake in my spare time. 
- I love music! I used to sing in talent shows and on my school's worship team in high school. 
- I have two cocker spaniel puppies; their names are Jake and Gracie. 
![img_0568](https://user-images.githubusercontent.com/42812069/45063649-f6550380-b07c-11e8-8da1-1c53a791d564.jpg)

During this class, I hope to 
- [ ] pass the class (of course) 
- [ ] learn how to apply coding to future writing projects 
- [ ] learn more about XML

Here is a [Linkl](https://github.com/Julegirl) to my profile on GitHub.

**Comment by JustinCampbell9** [comment]
### **About Me**

Hi everyone. My name is Justin Campbell. Here are a few things to know about me. 

- My major is Information Technology and I'm a junior.

- I currently play soccer for UPG 

- I've lived in Greensburg for my entire life

- My friend and I own a DJ company 

- I love building and messing around with computers 

- I've put a lot of time and effort into my desk space at home 

![bb5a7f33-6183-46b3-be27-1ce83075a49b](https://user-images.githubusercontent.com/42811949/45065383-e17d6d80-b086-11e8-9830-417f7bd68c62.JPG)

During this class I hope to: 


- [ ] Pass 

- [ ] Learn XML 

- [ ] Feel more confident coding 

Here's a piece of code from our previous assignment. 

</Main_Letter>
    <The_Complimentary_Close type="Number 1"> Goodnight, dear. </The_Complimentary_Close> <The_Complimentary_Close type="Number 2"> Ever yours, </The_Complimentary_Close>
    <Signature>Oscar</Signature>
</Oscar_Wilde>

**Comment by KSD32** [comment]
# Hi Everyone!

My name is Kiara, and here are a few things about myself:

- I am the eldest of three children 
- I love to travel 
   - I have been to England, Canada, South Korea, and Italy 
- I am a history major with a minor in Spanish 
- I have played soccer since I was 5 and play for Pitt Greensburg 
- I live in Philadelphia 
- I currently own a dog named Zoe and 10 stray cats
- I love to read, write and play my Xbox 

Goals for this semesters:
[ ] Learn more about XML and coding 
[ ] Win a championship for Pitt Greensburg 
[ ] Get an A in this course 

Here is the link to [my repo](https://github.com/KSD32/my_page.git)

Here's a picture of my outside the Trevi Fountain when I went to Rome! 
![img_7991](https://user-images.githubusercontent.com/42811975/45066146-f4923c80-b08a-11e8-8ff9-ee2613d24999.JPG)

**Comment by RLG95** [comment]
**Hello** 
*My name is Rachel Garstecki and here is a little bit about me:*

* I am currently majoring in Mathematics and minoring in Computer Science.
* I am a cat person.
* I never wanted to go to college and still don't lol.
* My favorite color is blue.
* I want to visit Iceland.
* I make YouTube videos.
* I would like to be a photographer one day, here is the only edited shot that I can find on my computer at the moment (I took it like two years ago and its ugly but Halloween is coming so):

![ghost](https://user-images.githubusercontent.com/42811963/45067943-45a62e80-b093-11e8-863a-61bc685b7319.jpg)

**Goals for this Class**
- [ ] Don't fall behind on work
- [ ] Do well on homework and projects
- [ ] Pass this class with an A

**Repo Link**
Click [here](https://www.github.com/RLG95/garsteckir) to visit my repo.

> I can't find the specifics on this assignment (I am assuming I am staring at them yet missing them) so I am just guessing on what to do.

**Comment by ebeshero** [comment]
These are terrific so far, everyone! This assignment was just meant to introduce everyone and get you all used to writing markdown on GitHub, since we'll be using it all semester! Nice to meet you all online! :-)

**Comment by emb184** [comment]
Hello!
I'm Emily Buckel and here are some fun facts about me:

- I have an obsession with cats

- I have a fish named George

- I am a creative writing major

- I'm really bad at fun facts
![image](https://user-images.githubusercontent.com/42811959/45089371-f33c3080-b0d9-11e8-8250-d50d78d47128.png)
