### ISSUE TITLE
UX Discussion (for Friday 9/7)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#505]
**Choose one** of the following digital archives to explore its features. Spend some time investigating until you're reading some marked-up documents on the site (a manuscript page or an historical document or a poem, etc), and think about how markup was used to design this. Then write a post on this thread that addresses:
1) something interesting the site is inviting us to explore about centuries-old texts, and 
1) the effectiveness of the user experience (“UX”) in discovering, reading, and learning about these texts.

Archives:                
                    * [Shelley-Godwin Archive: Frankenstein Notebooks](http://shelleygodwinarchive.org/contents/frankenstein)
                                    * [Map of Early Modern London](http://mapoflondon.uvic.ca/index.htm)
                    * [Emily Dickinson Project](http://dickinson16.newtfire.org/) (made by Pitt-Greensburg students in 2015-2016)
                    * [The Homeric Hymn 7 to Dionysus within the Perseus Project](http://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0013.tlg007.perseus-eng1)

**Comment by BMT45** [comment]
I looked through the Map of Early Modern London and I found it interesting that they had an option to show the areas of interest in early London through color coding.   This makes it very easy to find certain areas I might need to see when doing research on early London.  The information is well organized which makes it very easy to find documents that are relevant to learning more about how the map of early London was laid out.  For the documents,  I like how they labeled if the document was a draft or published but I wished the author of the website would have just placed the document in the link like they did in the published rather than making me press view document after I already clicked on the link to look at the document.   It's just kind of annoying and just adds some unnecessary links to the website which makes it kind of obnoxious to access some information on the site.

**Comment by alexlavelle** [comment]
The site I chose was the Map of Early Modern London, it seemed like an interesting concept to explore and it was.  The site has appealing colors and design, and its easy to find where the map is.  I like that the map is interactive and shows different buildings in the city.  The different colors of each site makes it appealing to look at, I'm surprised to find that there were only 3 bars in the city.  I feel that the site does a good job of providing information about early London.

**Comment by Julegirl** [comment]
I chose to look at the Emily Dickinson site. Being a writing major, I've read a number of her works in the past so I thought the website would interest me. The site was very well constructed, but I will say that it was a little bland. However, the creators made it very simple and easy to navigate. I thought it was amazing that the creators were able to compare the different publications of Dickinson's poems, and they were able to make it so you could view the comparisons all at once. I found it to be very useful and easy to access. Although, I think that the directions for navigating the publications should have gone on the homepage so it is easier to find. Other than that, the website was great.

**Comment by RLG95** [comment]
I chose the Map of Early London, I thought it would be interesting to see how much London has changed. I like how easy the site is to navigate, with the large boxes leading directly to the different parts of the website. I like how nothing is really "hidden" or difficult to find, and it is all very straight forward. The interactive map is really helpful in gathering information and makes it easy to find something that you are looking for. I also think the website makes it really easy for research considering it has a pop up for citations for MLA, APA, Chicago, TEI, etc. It features many different ways to cite and has the work already done for you, I think it is a really good feature for an informational website.

**Comment by alnopa9** [comment]
I chose the Shelley-Godwin Archive: Frankenstein Notebooks. I remember having to read Frankenstein for English call in high school and thought it would be interesting to be able to see the actual notebooks that were used to write it. The archive is very well organized and you can sort through the notebooks in two different ways, by work or by manuscript. One thing that i especially liked is that when you read the transcripts, there are also different viewing modes. You can view it in standard mode, which is resembles the notebook word-for-word including edits like strikethroughs, reading mode, which has all changes applied and the editing marks left out, and TEI, which shows the XML markup for that page and shows a real-world application for what we are learning in class.

**Comment by KSD32** [comment]
I choose The Homeric Hymn 7 to Dionysus with the Perseus Project as the digital archive I would be exploring, due to the fact that I am interested in text surrounding Greek Mythology. While exploring the site, I found site very easy to navigate the page due to a well constructed and detailed layout with text that was clear to read and at a size that was perfect for any user. The site was also helpful in providing annotations, a map of place referenced, URI and a search engine that was quick and easy to use. There was also a table of content located to the left to the selected text, which had for easy location of additional text regarding the various gods, how many there were, and where to find them.
