### ISSUE TITLE
Project Proposal: O Brother: Where Art Thou?

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#517]
I have been stumped with trying to think of project proposals. I had in mind doing a comparison of a book and movie, and was considering Fight Club, but that would go against the first two rules. This morning, though, I had an idea. Parker decided to play tag, tag me, and run out of the room. I then said a line from one of my favorite movies, "He done r-u-n-n-o-f-t". The light bulb turned on, because the movie "O Brother, Where Art Thou" is loosely based off a famous work of fiction: "The Odyssey" by Homer. My proposal is to see just how similar the two are, where the movie strays from its inspiration, and why these differences may have been included in the film.

**Comment by Julegirl** [comment]
That's a good idea. I will be honest, I've never watched the movie (and that might make you hate me now :)), but I think it's something that we could do. We could do this for any movie that was based on a classic writing piece.

**Comment by ebeshero** [comment]
@alnopa9 I just posted this on @RLG95 's proposal post, but I think it's relevant here too. For this and some of the other project proposals I'm reading, it may help to browse movie scripts on the public web! Usually you can download and work with this, and in a unit of the course coming soon, you'll be learning how to automatically "up-convert" the text of regularly formatted documents like movie scripts into XML (so you don't have to do it by hand). I bet you can find *Oh Brother: Where Art Thou?* on one of these sites in a format that you can copy as plain text and paste into oXygen (or a text editor). If you can do that, you're in a good position to "up-convert" a script to XML, and we should be able to work with the material. Here are some resources where you might find it.

    The Internet Movie Script Database: https://www.imsdb.com/
    Simply Scripts: https://www.simplyscripts.com/movie-scripts.html
    https://www.nyfa.edu/student-resources/10-great-websites-download-movie-scripts/

 We may have some copyright restrictions to deal with depending on the script, but it's unlikely that this will be a problem if the scripts are already released to the public. We'll help you investigate if there are problems. (The worst that could happen is that you may not be able to post the full scripts yourself, but you can post the results of your research.) 

As for *The Odyssey*, you can almost certainly find a good translation of it available on Project Gutenberg: (Try https://www.gutenberg.org/ebooks/search/?query=Odyssey ) We like Project Gutenberg as a source of literary texts when coding because all its resources are freely shared: the developers specifically want people to be able to work with the texts as they choose--it's a very open and accessible resource.
