### ISSUE TITLE
Project Proposal: Car Styling Over Decades

### ISSUE THREAD

**Issue by alexlavelle** [ebeshero/DHClass-Hub#520]
I've always been into cars and thought it would be cool to make a site that compares the styling of cars over the decades. cars from the 1980's look much different from the cars on sale today.  The could also be sub-categorized by make, model, region (USA, Asia, Europe).  Things like pop up headlights, thicker pillars, pointy headlights vs boxy headlights. We could also analyse trends in colors, like how silvers and grays seem to be the current color trends while back in the 70s and 80s browns and beiges were popular.  
We could also discuss the reasons behind these changes in styling.  thicker pillars due to rollover safety, smother front end designs for pedestrian safety, fuel efficiency, and just changes in styling in general due to time.

**Comment by ebeshero** [comment]
@alexfell06 This is a neat project idea, and a little unusual. It reminds me a little of @jonhoranic 's Graveyard project (http://graveyard.newtfire.org/ ) and @quantum-satire 's War of Currents project (http://warofcurrents.newtfire.org/ ). Because you're wanting to track changes in construction details over time, it reminds of Graveyard project because it would rely on collecting images. And it's like War of Currents because your project would be finding a new way to show change over time. 

I think the challenge here is going to be with collecting material for your digital archive: you need images as well as text. In the Graveyard project, the text came from cemetery records, but the team recast those in a systematic form of XML--they regularized the information they were collecting. And using their coding, they were able to research some details about average age of death of men vs. women in a portion of the graveyard representing the early 20th century, for example. I think your project idea could develop in a similar way--but projects like these do take some work early on to build your collection of images and text to structure in XML. 

It would help, I think, to begin with some resources on the subject available on the public web--for example: https://en.wikipedia.org/wiki/History_of_the_automobile and https://www.thehenryford.org/collections-and-research/digital-resources/research-databases/  You could work with (and cite) these resources in your project to provide you a starting point, but you'll want, I think, to accumulate your own image and text archive for the project. If this proposal becomes a real project, I think it'll be a good challenge for organizing information in XML!
