### ISSUE TITLE
HTML Exercise 1 issue

### ISSUE THREAD

**Issue by BMT45** [ebeshero/DHClass-Hub#531]
I’m having an issue with my image not showing up and I’m getting a box with an x on it where my image should be when I place my html document onto my server.

**Comment by ebeshero** [comment]
@BMT45 I had a look at your website files. Two issues:
1) There is no image file on the server. For an image to be shown on your webpage, you need to upload your image file into your file directory, and you need to refer to its *relative* file location--relative, meaning its position in relation to your file. 

2) You've changed the filenames to follow the Courseweb file name conventions. That's not what you want to do on your web space, because you've now removed the index.html page. The page you are making **should be** named index.html, as it is the root page of your website. If you don't have a index.html page, you have to type out the full web address to view your page--it's the difference between:

http://newtfire.org/~bmt45/   *(which doesn't open your page)

and 

http://newtfire.org/~bmt45/THomas_09-28_HTML.html

which is really hard for anyone to type correctly. Keep these file names simple.

And upload your image file to the server.

**Comment by ebeshero** [comment]
@BMT45 Take a look at your image file name, too. I am looking at the code you sent to the server and I see this:  `Brad%20Thomas%20Picture.jpg`  

For you, those `%20` parts probably look like white spaces. It's for this reason we don't recommend putting white spaces in file names--it's likely to cause problems. Rename that image file so it doesn't have white spaces, too (and check to be sure you've referenced the new filename. And make sure it's sitting on the web server alongside the HTML and CSS.

**Comment by BMT45** [comment]
I fixed those two issues.  Thank you!

**Comment by Julegirl** [comment]
I don't know if anyone is still checking in, but I need help too. I'm trying to connect on Filezilla, but I can't remember the port and host.

**Comment by quantum-satire** [comment]
@Julegirl the port is 22, and the host should be `firebelly.newtfire.org`

Try that and see if it works!

**Comment by Julegirl** [comment]
It said that the port was wrong. Am I missing any more numbers?

**Comment by quantum-satire** [comment]
Are you getting any error messages when you try to connect? If so, what are they? Is it saying it can't connect to the server or something else?

**Comment by Julegirl** [comment]
Yeah, it's telling me that there's a protocol error and there is an unknown protocol identifier.

**Comment by quantum-satire** [comment]
Aha! https://www.akliz.net/manage/knowledgebase/23/How-to-Fix-FileZilla-Unknown-protocol-identifier-wrong-port-etc.html

You might have downloaded the wrong version of FileZilla. Try downloading this one: https://filezilla-project.org/download.php?platform=win64

**Comment by Julegirl** [comment]
Yes! I think that's it. When I went to download it, there were two versions I could download and I chose Filezilla Server. That's what happened! I got it now, and I'm connected. Thank you!

**Comment by ebeshero** [comment]
Huzzah! That is some seriously expert debugging @quantum-satire !
