### ISSUE TITLE
HTML 2 Issue

### ISSUE THREAD

**Issue by RLG95** [ebeshero/DHClass-Hub#536]
I changed the layout of my website so now it is all centered and the picture isn't so big, it showed the website how I wanted it to look locally, but when I uploaded all of the new files to the server, the site I have now looks exactly the same as before. I changed out the old index and CSS with my new ones, I'm not sure what the problem is?

**Comment by ghbondar** [comment]
@RLG95 It looks centered to me. Try reloading/refreshing the page in your browser.

**Comment by ebeshero** [comment]
@RLG95 Browser caching is a familiar problem with updating one's CSS on a website. The problem is that your local web browser caches (or stores) an older version of your CSS file from when it previously loaded your site. Reloading while pressing `shift + F9` can help, or opening your page in another web browser so long as you're sure the files are indeed all on the server in the correct location. (We can check that for you, too, if on trying these things, you still don't see the changes.)
