### ISSUE TITLE
Exercise 5 (Help)

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#54]
I was wondering how I pick out the individual poems. I was trying to use this, but I know the poem part is wrong. `<xsl:apply-templates select="$dickinsonColl//poem"/>
            </body>` And I also was wondering how to test it, should I have every poem open as an XML and test it with my XSLT or what?

**Comment by CodyKarch** [comment]
I take back the "poem" part. I realized it what I was looking for.

**Comment by CodyKarch** [comment]
I take it back, I'm very lost..

**Comment by nlottig94** [comment]
You're right, your problem is the `//poem` part.  There aren't any `<poem>` elements, are there?

**Comment by CodyKarch** [comment]
No, but I'm confused at what I'm looking for. What singles out ever individual poem?

**Comment by nlottig94** [comment]
Well everything we need rests in what element of the poem?  We don't need every single poem because the XSLT is looking over the whole collection, so all of the poems are formatted the same way in the XMLs.

**Comment by nlottig94** [comment]
As long as we look at one of the poems, the XSLT will apply to all of the poems.

**Comment by CodyKarch** [comment]
Well, all the information we need is in the body.. so I was thinking `<xsl:apply-templates select="$dickinsonColl//body"/>`

**Comment by nlottig94** [comment]
Exactly!

**Comment by CodyKarch** [comment]
And now I need a template rule with that, right?

**Comment by nlottig94** [comment]
Yes.  Have you done your `@mode` yet?

**Comment by CodyKarch** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    exclude-result-prefixes="xs math"
    xmlns="http://www.w3.org/1999/xhtml"
    version="3.0">
    
    <xsl:output method="xhtml" encoding="utf-8" doctype-system="about:legacy-compat"
        omit-xml-declaration="yes"/>
    <xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>
    <xsl:template match="/">
        <html>
            <body>
                <h1 align="center">Emily Dickinson’s Fascicle 16</h1>
                <h2>Table of Contents</h2>
                <ul>
                    <xsl:apply-templates select="$dickinsonColl//body" mode="toc">
                        <xsl:sort order="descending"/>
                    </xsl:apply-templates>                         
                </ul>
                <hr></hr>
                <div id="main">
                    <xsl:apply-templates select="$dickinsonColl//body"/>
                    
                </div>
            </body>
        </html>
    </xsl:template>
    <xsl:template match="$dickinsonColl//body" mode="toc">
        <li>
            <a href="body"> 
                <xsl:apply-templates select="//body//title"/>
                <xsl:apply-templates select="//lg[1]/line[1]"/>
            </a> 
        </li>
    </xsl:template>

    
</xsl:stylesheet>

**Comment by CodyKarch** [comment]
This is what I have....

**Comment by nlottig94** [comment]
You're right as far as I can see so far!

**Comment by CodyKarch** [comment]
The strange thing is that with all of that, NONE of it will show up when I test it

**Comment by nlottig94** [comment]
I actually just noticed that you don't need to link within the `<li>` element.  And don't you want to number the poems?

**Comment by CodyKarch** [comment]
Oh.. Okay.. I'll check that out.. and it said that this line can't find a file (this does not exist) `<ul>
                    <xsl:apply-templates select="$dickinsonColl//body" mode="toc">`

**Comment by nlottig94** [comment]
Is your XSLT saved in the same space as your collection of Dickinson poems?

**Comment by CodyKarch** [comment]
ohhh... It was, but I moved it, that matters?

**Comment by nlottig94** [comment]
Yeah that matters.

**Comment by nlottig94** [comment]
Did it do anything since you moved it?

**Comment by CodyKarch** [comment]
Nope. I placed my XSLT into the folder with my files, and tested it, and nothing changed.

**Comment by nlottig94** [comment]
It doesn't have to be in the folder.  For example, if your Dickinson folder is sitting on your desktop, then your XSLT has to be sitting on your desktop as well.

**Comment by CodyKarch** [comment]
I tried that... I placed my folder of Dickinson files on my desktop, and I placed my xslt on my desktop and tested it, but still the same...

**Comment by nlottig94** [comment]
I copy and pasted your XSLT into my oxygen and I'm coming up with something.

**Comment by CodyKarch** [comment]
Did the whole thing work for you???

**Comment by nlottig94** [comment]
Yes, except the poem titles aren't in order.  I think its because of your `<xsl:sort>` element.

**Comment by CodyKarch** [comment]
See... I can't get the entire thing... I literally can only get the H1 and H2 parts of my HTML

**Comment by nlottig94** [comment]
![image](https://cloud.githubusercontent.com/assets/14095715/10777746/08fc8eea-7cf5-11e5-91e5-513d2220ec42.png)

This is what it came up with on mine.

**Comment by CodyKarch** [comment]
In that section, I get: `<!DOCTYPE html
  SYSTEM "about:legacy-compat">
<html xmlns="http://www.w3.org/1999/xhtml">
   <body>
      <h1 align="center">Emily Dickinson’s Fascicle 16</h1>
      <h2>Table of Contents</h2`

**Comment by nlottig94** [comment]
Hmmm.... @RJP43 any suggestions??

**Comment by CodyKarch** [comment]
I think there is a problem with my variable, but I can't pick what out...

**Comment by RJP43** [comment]
Does assignment 5 even ask about sorting or using links? And yes in class I explained in detail how the two parts of your variable were a name you choose for the collection and then the file path to the collection from where your xslt sits and suggested to keep them in the same place so that you could use the same path I had shown in class.   It looks to me like in the matches you are asking for more than what is necessary to but you should still be getting output. Consider this your initial selections in your first match inside of your html setup are saying anything you grab will be from the body elements of the files from the collection so then when you make a match you can just say for all of the body elements you don't need to repeat that you are going into the collection because XSLT already knows this from your first match. So you could just say `match=body` . Then in your selects inside of the match on body elements you can simplify and say go from here `.` and go down to the title element and output all of those .. etc. I am not sure entirely why you aren't getting output and Nicole is and by the looks of what you have you should be getting something my only other suggestion than what Nicole has already said is that you need to check to make sure you chose the right file in the XSLT window ... otherwise I'm not sure. @ebeshero suggestions?

**Comment by RJP43** [comment]
Feel free to refer back to our [in-class example](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/ExamplesFrom10-26_10-28_10-30/sonnets.xsl)

**Comment by RJP43** [comment]
Also @CodyKarch it looks like you are selecting elements that don't appear in the source XML files ... I suggest you take a closer look at that the elements are that you are trying to grab and reconsider how you are going about completing the assignment. Here is a snippet of the Dickinson XML:
 ` <body>
         <head>
            <title>Poem 1 (J 327: 1862/1891)</title></head>
         <lg>
            <l>Before I got my eye put out—</l>
            <l>I liked as well to see</l>
            <l>As other Creatures, that have Eyes—</l>
            <l>And know no other way—</l>
         </lg>`

versus the sonnets XML I used in-class:
`<sonnet number="I">
    <lg type="quatrain"><line>From fairest creatures we desire increase,</line>
        <line>That thereby beauty's rose might never die,</line>
        <line>But as the riper should by time decease,</line>
        <line>His tender heir might bear his memory:</line></lg>`

I have suspicion you may also be looking and possibly grabbing from the wrong in-class example. Refer to my last comment for the right example because the [sonnets2.xsl](https://github.com/ebeshero/DHClass-Hub/blob/master/Class-Examples/XSLT/ExamplesFrom10-26_10-28_10-30/sonnets2.xsl) is more along the lines of what we will be covering today in class using xsl:sort and making AVT links. 

This worries me because I posted those examples as a reference for you guys in hopes that you can refer back to the example **if** you get caught up in trying to work out the XSLT on your own for the assignment. The in-class examples are never exactly like the homework so obviously element names and several similar things (like hierarchy) cannot be replicated simply by copying from the example... the point is that you consciously work through the assignment on your own and then if you get stuck use the example to see where you are getting errors. 

Hopefully this helps.

**Comment by RJP43** [comment]
Also thank you @nlottig94 for jumping on this issue ... I was engulfed in other homework and hadn't even noticed the GitHub pings until obviously much later.

**Comment by ebeshero** [comment]
@CodyKarch @RJP43 Good morning from Lyon, France! Cody, I just ran your XSLT, after saving it in a directory sitting immediately above the Dickinson collection of files. I'm getting output, just as @nlottig94 did. Since two of us are getting output, I think the problem really must be where you are positioning your XSLT in relation to the collection directory--and I'm trying to anticipate what could be going wrong for you: Could it be one of the following?
* Have you renamed the Dickinson collection folder? (If so, you need to point in your XSLT folder to wherever that collection folder is. OR just make sure your collection folder is named Dickinson.) 
* Is your XSLT file saved in the PARENT directory, sitting just above the Dickinson folder? When you look at where you've saved your XSLT file, does it look something like this?

CodyXSLTEX5.xsl
[Dickinson]  **your Dickinson folder sitting here**

Since your XSLT really and truly is working for me all the way out here in France, I can only think the problem has to be where you're positioning your file and the Dickinson directory.

* I wonder if you've got this directory structure set up--could you be saving your XSLT in two different places by accident--and when you're running your XSLT you're actually running it from the wrong file location? Try closing all your open files in oXygen and reopening your XSLT from the right directory! 

Hope this helps!
Dr. B

**Comment by RJP43** [comment]
Even further clarification: with the path we showed in class and how you have it in what you have sampled here fore us the XSLT sits beside not inside the folder that contains the collection files.

**Comment by RJP43** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/10786784/9cc9811c-7d42-11e5-8a8c-a1c5a87c4c88.jpg)

**Comment by RJP43** [comment]
or if inside of a folder instead of on your desktop it might look similar to how we have things saved here on GitHub for the class example ---- found [here](https://github.com/ebeshero/DHClass-Hub/tree/master/Class-Examples/XSLT/ExamplesFrom10-26_10-28_10-30)

**Comment by RJP43** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/8645521/10786853/0acfdc2e-7d43-11e5-89ea-79db0e84f9d6.jpg)

**Comment by RJP43** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/10786903/63753e0a-7d43-11e5-96e3-ca078792126a.jpg)

**Comment by spadafour** [comment]
I'm having a very similar issue to Cody; I can't seem to get anything at all to output besides the html frame that I created. I'm getting this message:
`FODC0002: The file or directory file:/Users/spada4/Documents/School/Pitt/Fall%202015/Digit%20Humanities/5.%20XSLT/Dickinson does not exist`

That is in reference to this:
`<xsl:apply-templates select="$dickinsonColl//body"/>`

This is a screenshot of my file locations, just to show that:
![screen shot 2015-10-28 at 9 03 11 am](https://cloud.githubusercontent.com/assets/14111815/10789283/cf091600-7d52-11e5-961f-481b8b0e97d2.png)

I'm unsure how to continue if I can't check what I'm attempting to output.

**Comment by nlottig94** [comment]
Do you have your `collection()` value as "Dickinson"?  Like this? `<xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>`

**Comment by spadafour** [comment]
Yep:
`<xsl:variable name="dickinsonColl" select="collection('Dickinson')"/>`

I moved the Dickinson collection into the parent folder (where the error message seemed to be pointing), and I found this error:
`SXXP0003: org.xml.sax.SAXParseException; systemId: file:/Users/spada4/Documents/School/Pitt/Fall%202015/Digit%20Humanities/5.%20XSLT/Dickinson/.DS_Store; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.`

**Comment by nlottig94** [comment]
Did you try just putting them both on your desktop?

**Comment by spadafour** [comment]
Okay, just tried that. Still a fatal error, same one as my last comment.

**Comment by nlottig94** [comment]
Hmmm...do you have everything else finished for the assignment?  I could compare it to mine before class and we could see what's up with it.  You available before class?

**Comment by spadafour** [comment]
I can meet up before class, but I don't have the assignment done, I've spent all my time just trying to figure out how to produce something at all from the Dickinson files.

**Comment by RJP43** [comment]
Retry saving the Dickinson collection to your desktop by syncing and copying the folder from the GitHub desktop client

**Comment by RJP43** [comment]
I can wait to post solutions and will keep the upload link active and we can have a look at it before class. My first class ends at 10:20 so I will get to the classroom ASAP

**Comment by RJP43** [comment]
Thasks @nlottig94

**Comment by spadafour** [comment]
@RJP43 @nlottig94 Thanks, I'll be hanging out around the classroom in one of those comfy chairs

**Comment by nlottig94** [comment]
I can get there around 10!  I'll either be in the classroom or out in the hall!

**Comment by amielnicki** [comment]
For @spadafour 's issue, it was an issue with Mac OS X. The operating system creates ".DS_Store" files in every folder to preserve sorting, views, etc. so they are the same every time you look in the folder. This creates an issue for Oxygen, because it is looking at the collection in the folder, and trying to look inside the .DS_Store file first, instead of the XML file. How to solve it is to delete the .DS_Store file from the command line as such:

1. Open the Terminal application
2. Navigate to the folder having the issue
3. Use the command: `ls -al` You will see the .DS_Store file
4. Use the command: `rm .DS_Store` to remove the .DS_Store file

**Comment by nlottig94** [comment]
Just an FYI for everyone, CourseWeb isn't working right now...So for anyone who is trying to submit stuff, the webpage won't load.
