### ISSUE TITLE
Regex 2

### ISSUE THREAD

**Issue by Julegirl** [ebeshero/DHClass-Hub#541]
Ok, how do I add the paragraph tags again? I was able to get everything else, but I am having problems with the paragraph tags.

**Comment by ebeshero** [comment]
@Julegirl When you say "everything else", do you mean you marked the chapter headings before you did the paragraphs? If you're following the assignment, you'd be doing paragraphs pretty early in the process...Can you show us/tell us what you've done already so far?

**Comment by ebeshero** [comment]
@Julegirl We have to ask this because, depending on what you marked already, you might need to do things a different way. But the idea is usually we mark the most frequent and smallest unit first. So a novel is full of paragraphs, and we just mark everything as a paragraph at first, figuring will change the other things (like chapter headings) later.

Anyway, the key to finding paragraphs is working with your line breaks. Use that newline match here: `\n\n` should help you find the spaces in between all the paragraphs, and once you found those, you can mark them. When you find the spaces in between stuff, you have found the **end** of the previous paragraph as well as the **beginning** of the next paragraph. (It's very zen, isn't it?) :-) The end is only/is also the beginning. You can find the linebreaks, and replace with an end-tag followed by a start-tag. Then you have to just remove the one extra end-tag from the top of the file, and set it at the very end to close the last paragraph. Is that what you were needing help with?

**Comment by ebeshero** [comment]
Anyway, the key to finding paragraphs is working with your line breaks. Use that newline match here: `\n\n` should help you find the spaces in between all the paragraphs, and once you found those, you can mark them. When you find the spaces in between stuff, you have found the **end** of the previous paragraph as well as the **beginning** of the next paragraph. (It's very zen, isn't it?) :-) The end is only/is also the beginning. You can find the linebreaks, and replace with an end-tag followed by a start-tag. Then you have to just remove the one extra end-tag from the top of the file, and set it at the very end to close the last paragraph. Is that what you were needing help with?

**Comment by Julegirl** [comment]
Yeah, I give it a try. And yes, I did do the quotes and chapter headings first. I didn't think it needed to be in any order.

**Comment by Julegirl** [comment]
I was able to fix it and make it work. Thank you Lisa!

**Comment by ebeshero** [comment]
@Julegirl Huzzah! You don't really need to do these in order, but it does help us to know how to help you if you tell us a few details about how you approached the assignment first. :-)
