### ISSUE TITLE
Re-posting

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#55]
Hey @RJP43 , I was trying to re-upload my assignment for today, but the "upload" spot was gone... Help??

**Comment by RJP43** [comment]
Hey sorry about that I accident;y had it set to 8:30 am ... it should be available now! @CodyKarch @spadafour @KariWomack  

@rCarls we extended the assignment till this evening so if you want to make a submission the link is available till 8:00 pm ... others were having issues with accessing the collection so that is reason for the extension ... good opportunity for anyone that wants to get the assignment in or fix mistakes without penalty.
