### ISSUE TITLE
Xpath Exercise 3 

### ISSUE THREAD

**Issue by BMT45** [ebeshero/DHClass-Hub#550]
I'm having trouble with the last part of number 3 on the homework.  When I type in (//div[@type="book"]//p[descendant::geo[@select="lat"] and name(placeName?)=> count() gt 2][last()], I get an error message because of my parenthesis. I don't know where to place the name function within the statement to be able to return the names of the placeName elements in the paragraph

**Comment by ebeshero** [comment]
@BMT45 Okay, so let's take a look at what you need to find (this is a combination of 3d. and 3e on the homework): 
* First, you need the very first paragraph holding more than two latitude records, that also holds more than one placeName element. 
* Then you need to return the contents of the placeName elements.

So, you already know the name of the element you want to retrieve. It's `<placeName>`. You won't need to use the `name()` function for this. (I only use it when I'm retrieving any elements `*/name()`or any attributes `@*/name()` and I don't know the names already). You can simplify your Xpath expression a bit.

Now, let's talk about those parentheses around the expression. The only time I use these is when I am looking through the whole XML document, and I want to get the **very first** or **very last** of something in a sequence of results. It looks like you're missing the closing parenthesis in this one, based on what you've pasted in here. 
(Xpath/expression/here/)[1]

(I think this question is asking for the very first result, right?) 

And I think you want to set your count() gt 1 here (more than one placeName)? Otherwise, you're on the right track here, and good job with the arrow operator! Try modifying your expression, and let's see if this works...

**Comment by ebeshero** [comment]
@BMT45 You were worried about your predicate, but I think it's actually fine the way you've set it up. Just remove the name() function around your placeName. And make sure your *outer* set of parentheses is wrapping your whole expression so you can return the first one in your series of results.

**Comment by ebeshero** [comment]
@BMT45 How's it look now?

**Comment by BMT45** [comment]
I got it.   I tried to use the name function to give me the names of the places within the placeName elements that I found in the search.
