### ISSUE TITLE
Schematron Help

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#560]
Hello!
I am trying to write a rule for my hockey schedule that goes:
    the following date must be greater than the previous date
Possibilities I've tried:
```
<assert test="number(game/date) lt number(following-sibling::game/date)">
<assert test="number(game//@iosDate ! tokenize(., '-')[3]) lt number(following-sibling::game//@iosDate ! tokenize(., '-')[3])">
<assert test="number(game[@iosDate]) lt number(following-sibling::game[@iosDate])">
```
My xml document is set-up like so
```
<schedule>
    <division type="divisionName">
        <organization team="teamName">
            <season type="Regular or Post">
                <year term="2018 or 2019">
                    <months class="month">
                        <game number="gameNumber" iosDate="yyyy/mm/dd">
                            <day>Mon|Tue|Wed|Thu|Fri|Sat|Sun</day>
                            <month>Oct|Nov|Dec|Jan|Feb|Mar|Apr</month>
                            <date>1-31</date>
                            <time>gameTime</time>
                            <destination>home|away</destination>
                            <against>teamName</against>
                            <outcome (type="ot or so")?>
                                <win pts="2">Winning Team</win>
                                <lose pts="0 or 1">Losing Team</lose>
                            </outcome>
                        </game>
                    </months> 
                </year>
            </season>
        </organization>
    </division>
</schedule>
```
where there can be any number of games nested within the month and there are multiple months within the year/season
Here's a link to the file on my repo but you'll have to open the Raw version
https://github.com/alnopa9/my_page/blob/master/Schedules/schedule_master.xml

Any help would be appreciated! 👍 
Thanks,
Alyssa Argento

**Comment by ebeshero** [comment]
Yay! Happy to see you are playing with Schematron for real-life purposes! :-) I'm taking a look now while I'm waiting at the airport for my flight.

**Comment by ebeshero** [comment]
@alnopa9 Okay, I've pulled in your files and I'm taking a look. The first thing I noticed was your Schematron wasn't associated with the XML file, so I've just done that--and some of the rules are working--good!  However, the Schematron is running very slowly, taking a long time to check the document (which isn't all that big). I think the issue is that for the rule you're working on to control the sequence of months, you've set a context on each month, but you write a test that starts at teh document node (with those two leading `//` in your `@test` attribute. 

My sense is that there is a less brittle way to do this, working with your ISO formatted dates. Did you get the tests working in our Schematron exercise on the Digital Mitford site index, to check if death dates are later than birth dates? The same thing would apply here. I think you can leave your context the same, but change your test to read along the `preceding::` or `following::` axis...I can explain more if you like...Does this help?

**Comment by ebeshero** [comment]
@alnopa9 AHA! I've gone back to re-read your post. I think the Schematron code I saw in your repo didn't include the tests you posted in this issue. Now that I look at the issue again, I think your second test is on the right track. You are breaking apart the `@iosDate` attribute (that's spelled as you spelled it in your code), and checking the month value only. I think the issue with that second test is simply that you've pulled the wrong token. Try testing this in the XPath window: `//game/@iosDate ! tokenize(., '-')`
Take a look at the window: Which token is the month? (The thing to remember about tokenize is that the character is, it splits on gets removed from the tokens--it's not one of the tokens.) 
Change the token number and the test *should* work. If it doesn't, try applying the number() function. 



(I would, by the way, change the name of your attribute to `@isoDate` since that's what you're referring to, the International Standards Organization date format. That's not the issue at hand just now, though! :-) Remember if you change it in the XML and RNG schema to update the Schematron.)

**Comment by ebeshero** [comment]
@alnopa9 Yay! Let me know if it works!

**Comment by alnopa9** [comment]
I'm still having a bit of a problem with the @isoDates, but I was able to rewrite the rules for the months and I like this method more.
```
 <pattern id="orders">
        <rule context="year[@term='2018']">
            <assert test="months[1]/@class => distinct-values() eq 'october'"> october should be the 1st month in the list</assert>
            <assert test="months[2]/@class => distinct-values() eq 'november'"> november should be the 2nd month in the list</assert>
            <assert test="months[3]/@class => distinct-values() eq 'december'"> december should be the 3rd month in the list</assert>
        </rule>
        <rule context="year[@term='2019']">
            <assert test="months[1]/@class => distinct-values() eq 'january'"> january should be the 1st month in the list</assert>
            <assert test="months[2]/@class => distinct-values() eq 'february'"> february should be the 2nd month in the list</assert>
            <assert test="months[3]/@class => distinct-values() eq 'march'"> march should be the 3rd month in the list</assert>
            <assert test="months[4]/@class => distinct-values() eq 'april'"> april should be the 4th month in the list</assert>
        </rule>
    </pattern>
```
