### ISSUE TITLE
Help me, please!

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/DHClass-Hub#58]
I literally am not understanding any of this homework for tonight. I can't get anything to work. My links won't work - I am having the id count the preceding h2 elements, but all of them are just coming up as 1. And my sorting won't work no matter what I try. I thought that `<xsl:sort>` automatically did alphabetical order? Nothing is working for me. My xsl is a mess and I don't even know where to begin to fix it. I have pushed it to the troubleshooting folder. Please help me!

**Comment by RJP43** [comment]
@blawrence719 I will take a look at it now

**Comment by spadafour** [comment]
For your `<xsl:sort>`, there are 2 things I can think of (mistakes that I also made):
1st off: you need to make sure that you are sorting the `xsl:apply-templates` within the unordered list where you are actually outputting the table of contents, NOT inside where you are matching it. Otherwise, you are essentially telling oxygen to sort individual poems, and then it will output an unordered list.

2nd: my output was acting funny with alphabetical order, too. It wasn't until I completed the `translate()` function step (having the document ignore `'`). Before I did that, oxygen was outputting `Before` before `Afraid`.

I hope some of that helps.

And for your links, I didn't use any counting (maybe you can do it this way, I have no idea!). But there is an element within each Dickinson document that holds an ID number (hint: that element is literally called `idno`). All you have to do is label `h2` with an attribute `id` and set it equal to the `idno` of that specific poem... okay that sounds more complicated than it actually is. Do basically the same thing for `<a>`, use the attribute `href`, and set `href=` the idno of the poem.

Things to remember about that:
1. Use curly braces for defining your `href` and `id`
2. When you set the attributes `href` and `h2` = an element from the old document, you have to tell oxygen specifically where it is (just like when we use `xsl:apply-templates select=//elementInTheDocment`)

I was super confused by some of this, too. Thanks @RJP43 for the help earlier.

**Comment by RJP43** [comment]
Okay so for this assignment you will want to add links to your existing table of contents with specific `@href` attributes pointing down to specific `@id` attributes on each of the poem titles later in the body. To do that you will use `{ }` curly braces / Attribute Value Templates and the `<a>` anchor element with `#{blahblah}` for inside of the links and just `{blahblah}`AVTs in the body titles.

Then To sort that table of contents you are on the right track with `<xsl:sort select='translate(upper-case(.), "&apos;", "")'/>` except unlike our in-class example your first argument needs to point to the specific element you want alphabetized (the first lines). The `(upper-case(.)` indicates a dot as the first argument and the uppercase was a function we needed to fix bad XML for the skyrim files ... if you say dot in your translation you are actually saying you want to alphabetize the body elements and XSLT doesn't understand. You are doing the sort in the right place by what I can see from your file in troubleshooting

Then you will need to create a second table of contents that sorts by the number of variants in each poem... for that you will need XSLT to count the variants and sort according to that. 

And I think the last thing to do for this assignment is to create a CSS that styles the `<span>` elements

**Comment by RJP43** [comment]
important to note you are creating the `<a>` elements and the `@href` attributes associated ... the values of the `@href` attribute will use an AVT to point to `#` (saying later in the same document) and `<idno>` element which will match on the `@id` attribute you need to create on your `<h2>` elements and the values for those `@id` attribute will be an AVT `{ }` that points to the same `<idno>` elements (you will need to use XPath step downs to get to the `<idno>` elements since you will be writing the AVT inside of a match on body)

**Comment by RJP43** [comment]
with @spadafour earlier we found that xsl:sort wasn't giving us exactly what we wanted without putting the `@order` attribute and a value of `"ascending"` ... in theory it should but sometimes oXygen likes to be difficult soooo yeah just add that in to avoid issues

**Comment by RJP43** [comment]
Side Note: your welcome @spadafour ... I am glad you took advantage of my help while I was on campus ... same to you @nlottig94

**Comment by RJP43** [comment]
any of this help @blawrence719 ?

**Comment by blawrence719** [comment]
Sorry, I was in a meeting until now. I am going to try working on it now and will post if I continue to have issues.

**Comment by blawrence719** [comment]
I got my links to work, but I am still having trouble with the sort. Here is what I have now: `<xsl:sort select='translate(/lg/l[1], "&apos;", "")' order="ascending"/>`

**Comment by RJP43** [comment]
double slash is necessary here because you have to redirect XSLT as to where you are in the document  since you are specifying the location inside of a function.. this was the little thing Andrew got caught up on in class too

**Comment by blawrence719** [comment]
It won't let me put a double slash

**Comment by RJP43** [comment]
what do you have now?

**Comment by RJP43** [comment]
oh ok sooooo since we want to extract the value of a selected node you are going to want to open up the `xsl:sort` and instead of having `@select` on `xsl:sort` do an `xsl:value-of` and have the `@select` there with your translation ... also did you add predicate on the `<lg>`?

**Comment by blawrence719** [comment]
Am I on the right track with this? It's still not working
`<xsl:sort  order="ascending"><xsl:value-of select='translate(/lg[1]/l[1], "&apos;", "")'/></xsl:sort>`

**Comment by RJP43** [comment]
yes ... but now add your extra slash

**Comment by blawrence719** [comment]
Ah, thank you so much!

**Comment by RJP43** [comment]
Yeppers ... tomorrow before class starts I want to talk to you in person as of why we need to specify the path location its just too hard to explain over messaging and its getting too late for my brain to even try lol
