### ISSUE TITLE
UX Discussion: LOTR, NYPL Menus, ORBIS

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#590]
Choose one of the following digital archives to explore, and write a post in this thread discussing: 
1) how visual aids are used to convey information on the site, and how well (or badly) do these work? What seems unclear to you, and/or what seems to work really well? 
2) how effective is the  user experience (“UX”) in navigating at least one or two significant areas of the site? 
(Each of you should begin by writing a "UX review" of a site, and then read and respond to each other by looking at the sites others chose.) 

* [LOTR Project: Visualizing Tolkien’s Works on the Web](http://lotrproject.com/)
* [What’s on the menu?](http://menus.nypl.org/) (be sure to read the About page for the project goals)
* [ORBIS](http://orbis.stanford.edu/): The Stanford Geospatial Network Model of the Roman World

@koshinf @SparkTheDragon @Skapfer13 @JAG240 @James-f117 @achen298 @abdual1100 @NADGIT @frabbitry @alnopa9 @KSD32 @BMT45

**Comment by koshinf** [comment]
I've picked the Tolkien project since I'm a huge fan of Tolkien's works.  The person who made this took a pretty unique approach to categorizing all the lore that has been given.  It has done some good and some bad things with this approach.  The good is that it does a good job of sectioning off important people.  Right away you can see that the one at the very top of the document is Eru Iluvatar, or god, and below that is the Valar, Nienna is one of these who is Gandalf's master, and Maiar, Gandalf and Saruman.  It's neat that it shows as well which Valar are associated with each other as well by linking them.  The bad that comes with this kind of approach is that because they decided to use Tolkien's work.  Tolkien is famous for his attention to detail and a tree chart is going to be massive and unwieldy when trying to link every single character and their relations to other characters.

The UX, while really large, does a good job teaching the user about the characters.  It's easy to just click on a name to get a brief summary of who they are.  A second neat UX is the Map that is on the site that shows important areas and events in Middle-Earth.

**Comment by James-f117** [comment]
I agree with my two classmates in saying that this is a very unwieldy and difficult to understand UX. The scope of this tree and the connections it is trying to make is just awe inspiring. I am a huge fan of Tolkiens work and when I first looked at this tree I understood what the creator was trying to accomplish, but I think this approach is to daunting to those who are not aware of the lore of middle earth. For any one who has only seen/read just the lord of the rings this would make little sense and I don't think it would interest that person. However, I do find this as a very useful tool in making the connections of characters families and having it all in one place. I also enjoyed the maps UX that is also on the site and you can tell that the creator really has a passion for the world of middle earth.

**Comment by frabbitry** [comment]
I looked at the NYPL Menu project thought that it was very interesting. The New York Public Library is in the process of transcribing its collection of about 45,000 historical menus, some of which date back to the 1840s. Currently, the team working on the project has organized the menus by associated metadata, such as the location of the restaurant where the menu is from, the name of that restaurant, and the date from when the menu was first transcribed. The menus are also geotagged by restaurant location. 

This naturally provides a wealth of information for those interested in knowing about what people ate and how they ate it in the past. Interested parties, including historians, chefs, or nutritional scientists, can now answer specific questions, such as "How much did coffee cost in 1907?" or "Where were oysters served in 19th century New York and how did their varieties and cost change over time?" This treasure trove of information, in my opinion, is kind of neat. I think that the fact that a searchable repository of historical menu information exists is kind of cool. 

From a UX perspective, though, the focus is on whether the treasure trove is accessible and easy to use. UX was born out of a shift in website and application design that occured in the early 1990s; websites and applications ceased to exist merely to present information and started to exist to present information well. The experience of the user using the application or website came into play, and this meant that websites started to be more accessible, more intuitive, and even, in some cases, more fun to use. There is a lot of information present in the NYPL Menu project, but is it easy to access? Is it easy to learn how to access the information? Moreover, would your grandma think that the information is easy to access? These are the kinds questions that must be considered when judging a project from a UX perspective. 

I thought that the website was well-organized. The menu at the top of the screen facilitated easy website navigation, and it was broken up by menu and dish, and then further broken up by a date range that you were looking for. You could then click on the dish or menu that you were looking for and be directed to an informational page describing that dish or menu. Interesting information about, for example, dish frequency in a time period is included. These things are all pluses from a UX standpoint. 

All in all, I thought that the project was interesting and well-organized. It was mentioned in the FAQs that the project is nowhere near completion, even from a organizational standpoint, and I think it would be interesting to see what happens with this project in the future.

**Comment by abdual1100** [comment]
I also looked over the Lord of the Ring project. The features and the images on that website were _hard to look at first._ When you click on the link, it looks confusing right from the beginning. Theres too much information at first and it makes you want to click away. The big and puzzled tree is all over the website going from left to right, up and down, etc is _difficult to follow_ by knowing where each link is heading. If I didn’t know any information about the Lord of the Rings, I would find this website extremely unhelpful. Trying to organize would make it longer and harder to find information would still let people click away from the site. One of the feature, I really liked about the site _is the map_. It was a good idea to track from where there coming from and it _made it easier for the people_ that clicked on it for the first time. The _navigation bar_ on the top of the page made it easier to go somewhere on the website especially for the people visiting it for the first time. To me thats the most important feature on the whole website, without that feature people would be lost and confused. Overall, I found it difficult to understand the UX especially for the first timers that clicked on the website and for me because this is my first time getting to know UX. I think the tree could be shorter and more organized. The website all together was organized by having the navigation bar and the map to track everything down by making it easier for the people that either have knowledge or don't by making them stay on this site and getting to know everything.

**Comment by NADGIT** [comment]
I checked out the New York Public Library's  "What's On The Menu?" database. I honestly didn't expect for there to be such a project, so I just had to take a look. The design and visual aids themselves are easy to understand: pick a menu, click on its pages, and see the dishes on the side of the webpage.

However... The site itself had some functional problems. Maybe it was just my machine, but I experienced frequent errors when viewing menus and pictures. The website's design may have been easy to use, but the errors were frustrating. The website also had another slight problem: the organization of dishes. It seemed that if two dishes were spelled even slightly differently, they would be considered two different dishes. This means that "tomatoe juice" and "tomato juice" were not listed as the same dish. This got even worse if another juice entry was listed as "Chilled tomato juice". Luckily, there was a "recommended tags" list to the right, and this could help display a few of the various forms of tomato juice. That did help find other similar dishes, but I feel that the tags should be sorted into more overarching categories that would make it easier to navigate.

That being said, I don't hold those two flaws against those who are running this project. The first one - the errors - could be my machine, and since they do have a way to contact them with errors, they are most likely already aware of these issues and are doing their best to fix them. I can't ask for anything more than a development team that really cares about their project, and it's reassuring to know that they're staying in touch with their users. The second issue, the categorization of tags, could be thanks to a limitation in XML or their implementation. It doesn't really prohibit me from viewing information, so it's not that big of a deal but I still think that there should be more consolidated categories.

Overall, I think it did a great job of presenting information: the site looked nice and the way the site was arranged made perfect sense, there were just a few minor hiccups.

**Comment by frabbitry** [comment]
I agree with @JAG240, @koshinf, @James-f117, and @abdual1100. The home page of the LOTR project is a mess because it doesn't meet standard hardware specs for any web page: be sure to fit with any machine's screen-size requirements. Since I viewed the page on my laptop, I assume that it's even worse on a phone or tablet. The genealogy tree for the LOTR looks really cool, but it stretches beyond my screen, which makes it hard to navigate.  I wonder if they could have included a smaller depiction of the entire tree (so that it fits on the page better) and then allowed the user to select a part of the tree to "zoom" into. It's neat information, but the website doesn't present it well.

The rest of the website, in terms of user experience, is much better. The map, for example, fit on the page, was layered with a nice introductory pane that explained what the map was and how to navigate it. Then, there was an intuitive menu on the side of the page that facilitated exploration of different sections of the map. I thought that the Timelines and Statistics sections were similarly well-presented. 

In addition, I liked how colors and fonts were used to create a kind of theme for the website. It added to the experience.

**Comment by abdual1100** [comment]
I agree with @frabbitry when I looked over the NYPL Menu in the link above. In UX standard its okay by being able to access it but for first time user, Its hard to know where to go from that point on. Having first time users understand it, is the area where the creator has to focus on in order to achieve there goal. The website was well organized by having the top navigation bar. It gave subcategories for first time users to know where to go by understanding the topics on the website. You can click on an item and would lead where you needed to go. Overall, the website was well organized and interesting on how they designed it. They could however improve it for the first time users.

**Comment by SparkTheDragon** [comment]
I Looked at the Lord of the Rings link. On the main page, the tree was poorly designed. From a meta perspective, the information inside of it is very accurate to Tolkien's lore, but it is almost impossible to look at. The tree is so large that it becomes very difficult to navigate and see macro relationships. On mobile, it is slightly better because the user can pinch and pull the screen to see the tree in its entirety. My suggestion for the tree is to design it almost like a map. Allow the user to use the scroll wheel to zoom in and out of the tree as desired. This should not be difficult to implement and would allow both desktop and mobile users to access the information easily. 

I think the Geospatial map is exceptionally well done in almost every area. The only criticism that I have is that the map icons should be color coded based on each adventure. For example, the Fellowship of the Ring should not have the same color as Bilbo's journey. I Think that that missed detail makes the map much harder to navigate if someone wants to track a particular person or party.

**Comment by SparkTheDragon** [comment]
Generally, I think that everyone that looked over the Lord of the Rings site all concluded roughly the same thing. I think that that is a good indication that the design was either poorly created or poorly executed. I find it interesting that most everyone else came to nearly the same exact conclusion.

I will say that others were more lenient on the map portion of the website than I was. I really think that someone as simple as color coding could have made the map perfect.

**Comment by BMT45** [comment]
I looked over ORBIS The Stanford Geospatial Network Model of the Roman World.  I like how they give you the option to pull up the about page which gives you several different options to read about describing information about the authors and the project itself.  The visual information provided by the map can give the viewer how long it would take to travel between two places based of several variables that include season and type of travel.  The drop box on the left hand side of the site properly shows this information allowing you to choose the two destinations and variable speed.  The map will adjust based off the what you choose in the drop box showing the rate of travel based off the colors of the path.  The site also provides a tutorial on how to use the site's map functions to help someone who has not used the site to properly use the site after reading the tutorial of the site.  This helps better the UX of the site for both first time visitors of the site and returning visitors who are using the site for researching how much time it took for travel during the Roman era of history.

**Comment by achen298** [comment]
I also looked at the Standford  Geospatial Network Model of the Roman World and I say it is the better one out of the other two in my opinion and agree with BMT45. The visual representation of the page is very clear and colorful in ways of what it was intended to be used for. It was easy to use with the checkboxes to shrink the size of the search criteria. It told you how long the trip would take with the total distance traveled by the ability to go on air, land, ship, and etc.. There are also options on the right-hand side where you can pull up previous searches that were used and reset the map if needed. It is one of those pages where people will come back and continue to us due to the easy access for many people, young to old. So far there doesn't seem to be a single error that would make the page flawed and everything is working properly.

**Comment by Skapfer13** [comment]
Visual aids are often essential when conveying a message, especially in a dining menu. A lot of people want to see what they are getting before it actually arrives. I work at a restaurant, so I felt it would be fitting if I glanced over "what's on the menu?". Upon first opening the link, there were several sea food menus to choose from. These covers had a variation of sea related photos like a lobster, a captain, or a swordfish. I began with The Famous Anchor Sea Food House, and quickly became disappointed. There were no pictures of food, only a long list and prices against a white background. I thumbed through a couple pages but quickly lost interest. There was no color, no images; no stimulation from this menu at all. There are many times I'm working and people will point at the picture to indicate what they want to order. Perhaps they are too lazy to read, or that the picture looks more appealing than the name. Legal Sea Foods was slightly better, for they had pictures of the real menu(which itself did not contain pictures) however this gave you a feel for an old time sea food restaurant. I personally feel that a food menu should have pictures of the food or related topics.

**Comment by Skapfer13** [comment]
> I've picked the Tolkien project since I'm a huge fan of Tolkien's works. The person who made this took a pretty unique approach to categorizing all the lore that has been given. It has done some good and some bad things with this approach. The good is that it does a good job of sectioning off important people. Right away you can see that the one at the very top of the document is Eru Iluvatar, or god, and below that is the Valar, Nienna is one of these who is Gandalf's master, and Maiar, Gandalf and Saruman. It's neat that it shows as well which Valar are associated with each other as well by linking them. The bad that comes with this kind of approach is that because they decided to use Tolkien's work. Tolkien is famous for his attention to detail and a tree chart is going to be massive and unwieldy when trying to link every single character and their relations to other characters.
> 
> The UX, while really large, does a good job teaching the user about the characters. It's easy to just click on a name to get a brief summary of who they are. A second neat UX is the Map that is on the site that shows important areas and events in Middle-Earth.

I totally agree with Koshinf! I am a huge fan of LOTR and was truly excited when I first opened the page.  The creator took such an innovated approach to categorizing and laying out each character in their family tree. I appreciate the information that is given, along with little extras presented in the blogs such as additional info and tidbits directly from the books. I think this is a great way to express LOTR visually.
