### ISSUE TITLE
Schema help

### ISSUE THREAD

**Issue by SparkTheDragon** [ebeshero/DHClass-Hub#594]
Hi there, there is on particular line of code that I need help with. 
![schema stuff](https://user-images.githubusercontent.com/46506618/51286577-99ba0b80-19c1-11e9-82cb-a14b0cbc4ecc.PNG)

I want to make a datetime format so people can enter the year, the date, and the month. What did I do wrong with my code?

**Comment by ebeshero** [comment]
@SparkTheDragon You're running into issues with that line b/c you specified a sequence of three datatypes, I think. But you're in luck, because there's a *special* datatype just for dates: xs:date. It's on my tutorial, but I'll add it here:
```
when = attribute when {xsd:date | xsd:gYearMonth | xsd:gYear} 
```
Also you may find it easier to just copy and paste from oXygen into the Issues here. You can surround your code with three "tick" marks above and below--that's the upper left key on your keyboard.

**Comment by SparkTheDragon** [comment]
thanks for that! I did see that on the tutorial before but I didn't think it was relevant to the form in which the date would be entered, thanks for clarifying

**Comment by ebeshero** [comment]
Sure thing! I want to talk more about datatypes in class tomorrow.
