### ISSUE TITLE
Discussion: Past Student DH projects

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#595]
Choose to explore and discuss one of the following project sites developed by students. A few of these are undergoing continued development this semester!  Describe (in your own words) at least one significant topic it seems to be exploring, and reflect on what research the developers might want to investigate next, the UX of the project site, and/or what ideas it inspires for new projects. In a gentle, constructive way (realizing that project developers may be monitoring the DHClass-Hub), you may comment on issues or problems you can see with these sites. Those of us (instructors and returning students) who have been involved in these projects should help introduce them to our class and point out things that need work.

* [The Hamilton Project](http://hamilton.newtfire.org): (developed by @ahunker and @bsf15 at Greensburg, with lots of network visualizations and a graph of motifs and their frequency of repetition in the musical)

* [Lega Toscana project](http://toscana.newtfire.org/): multi-semester Pitt/newtfire project by @zme1 studying English-Italian language adaptation and membership in a Pittsburgh Italian society, with a terrific range of graph types.

* [Profanities in Quentin Tarantino's Screenplays](http://bamfs.obdurodon.org/index.xhtml) (Pittsburgh student project, with network analysis of offensive language spoken by/to male and female characters)

* [Nell Nelson: City Slave Girls](http://nelson.newtfire.org/): (developed by @RJP43 and a Greensburg project team to investigate a series of newspaper articles documenting labor conditions for women factory workers in Chicago, with networks of objects and owners mentioned in the articles) 

*  [Graveyard Project](http://graveyard.newtfire.org): (developed by @jonhoranic and team at Greensburg) 

*  [The Lope Project](http://lope.newtfire.org): (ongoing project led by @setriplette begun last year.)

*  [Divergences in Machine Translation: Examining Harry Potter texts processed by Google Translate across multiple language families](http://translate.obdurodon.org/): (Pittsburgh student project)

**Comment by ebeshero** [comment]
NOTE: All students, including student mentors (@BMT45 @alnopa9 @KSD32) participate in this discussion, warming us up for the new semester projects!
@JAG240 @koshinf @James-f117 @frabbitry @abdual1100 @SparkTheDragon @BMT45 @achen298 @Skapfer13

**Comment by frabbitry** [comment]
I’ve been toying around with some rudimentary sentiment analysis (basically where you analyze the emotions present within a text) in my XML assignments, so I went to look at the Lope Project. Some of the comments I received on my assignments mentioned it as a larger project that deals with sentiment analysis. Of course, I could see that the Lope Project did more than sentiment analysis, but I wanted to see how emotions were systematically tagged within the documents. 
One of the primary challenges with sentiment analysis is that it can be hard to be objective when categorizing and identifying emotions. What one person perceives as one emotion can be perceived by someone else as a different emotion. In the Lope Project, emotions are tagged only if they are present, and no attempt is made to categorize the tagged emotion. This then increases the objectivity for how emotions are marked. (I also thought that it was interesting how the emotions were then classified as different grammatical units (nouns, adjectives, etc.)) It’s harder to contest the presence or absence of an emotionally charged word than it is to contest the exact emotion present within that word. 
I read in the “About” section of the website that emotions were identified and then tagged through close reading. I wonder if using a different process could improve both efficiency and, probably more importantly, objectivity. I know that sentiment analysis of text documents, such as Twitter posts or Yelp reviews, is conducted via machine learning algorithms. Linguists have developed vast banks of words classified as either positive or negative (in many different languages), and you could, using one of these repositories, train an algorithm to classify words within a text as either positive or negative. A support vector machine algorithm immediately comes to my mind as a supervised classification algorithm that produces a binary output, and something like that could be useful for a project like this. You would collect the relevant words (words not including stems, etc.) of the text you are analyzing and then have your classification algorithm identify your emotionally charged words for you. With this, you have not only identification of words that simply imply the presence of an emotion but also an indication of whether those words imply positive or negative emotions. Once the algorithm has classified the words in the document, you could then go through and tag them. 
Of course, there are drawbacks to this kind of method. Words aren’t considered in context, and this makes something like sarcasm difficult for an algorithm to detect. Perhaps a more sophisticated set of supervised and unsupervised clustering algorithms that are trained using sentences or phrases could improve the accuracy. However, for this reason it would be necessary to still have a human monitoring the process so that errors could be caught. The machine in no way replaces the role of the person supervising the project. Still, it could be useful with something that could become a menial task if you're going through a ton of documents.  
Perhaps I’m just overthinking things and making them more difficult than they need to be, especially if you’re only tagging one or a couple of documents. I’m just curious about sentiment analysis in general.

**Comment by ebeshero** [comment]
@frabbitry I'm glad you, in particular, had a look at the Lope project! One of the issues I remember that @setriplette confronted in exploring sentiments is the historic/medieval or Golden Age Spanish of the Lope plays, for which I think she didn't find word lists readily available. However(!) an interesting experiment might be to see what happens with automated sentiment analysis as a first pass on historic material and to see whether the results come out as workable...You could, with some Python (or other) programming, feed the text of a corpus into a sentiment (or other linguistic) analysis library and script it so the results come back in XML for further processing. (We've tinkered with this in a small way on, for example, [the Eldritch project](http://eldritch.newtfire.org) a while back and I'd love to explore this kind of processing some more if people are interested this spring.) A question we might apply to historic material is, how well does sentiment analysis working with contemporary language work with materials from the past? Another is, how well (even when applied to contemporary language), does it handle complexities like sarcasm? If something is just plain "sick", we can quickly figure out whether that means "awesomely cool" or "diseased"...Much could depend on how/whether you can train a system to take syntactical context (neighboring words/phrases) into account.

**Comment by NADGIT** [comment]
I decided to look at the Graveyard Project. This interesting project created a database of the occupants of the Bush Creek Cemetery and mapping out where each plot was in Section I.

First of all, I really appreciate that they put such work into researching each occupant. It would be simple enough to only record the names and the dates of birth and passing, but they have also found the living places, causes of death, and ethnicities of each of the deceased (whenever they could, that is). This database is an important resource, and it documents a history of the area.

The site itself was very simple to navigate and I could easily pick up on it. I only have two suggestions for them: First, because I clicked on a link from a broken image, I was brought to this page:
http://graveyard.newtfire.org/occupants.html
I would really suggest that there would be a link to this page from somewhere else on the website. It's normally displayed below the map, but when I view it like this, as its own page, I can really appreciate the list of entries as a whole. I think it's a great resource on its own.

Second, as to what they should research next, I think they have two options: they could continue recording more from the same cemetery, or they could take it as a semi-random sample and it compare it to a sample from a different cemetery. These both have various appeals depending on what they would like to accomplish: recording the whole of the Bush Creek Cemetery would make for a very good historical project, while taking samples from different cemeteries would be an interesting statistical viewpoint. Either way, I think that they should continue recording more data and further develop the site's features.

**Comment by abdual1100** [comment]
I choose to look at the Quentin Tarantino website due to my interests in movies and I was very surprised and impressed with results the past students came up with. The topic of the website was to explore the frequency of slurs and curse amounts within Tarantino's 3 films that he’s most famous for (Pulp Fiction, Inglorious Bastards, and Django Unchained) as well as the website discussed the differences between gender and cursing. To me the goal of the project was to explore how many times you curses and slurs were used within these films and as well as how the gender of the speakers in the movies affected the audience with all the profanity in the movies of Tarantino. Overall, the results were incredibly interesting and, having seen some Tarantino's films, we as the audience can understand how these movies can affect us due to the use of Slurs, curses within these 3 movies.  I feel like they can add more movies or movies in the same category as these movies as I read in the Conclusion. Exploring more movies in the same category can raise more ideas of how the website can function my comparing more than 3 movies will have the audience in believe when comparing the results by seeing the correlation between the facts shown. 
Another idea I had for future observations for this website was to possibly analyze curses and slurs by the characters in this movies versus in other movies they were in. Exploring the correlation between the characters in this movie vs. the other movies will show the slurs and curses by having a difference or not. 
Overall, this website highlighted a lot of cool features which the audience never took account of and hopefully they will continue there further research with Tarantino movies.

**Comment by SparkTheDragon** [comment]
I reviewed the Graveyard Project. I chose to focus on the functionality of the site rather than its content, as I know some of the contributors and know that they produce quality projects.

The positives:

Simple layout. This site does not need to be flashy or to draw in new viewers. I think that the focus of this project was to make a demonstration of curation, which it accomplished.

Intuitive navigation. Navigating the website was intuitive, and did not cause me to hunt down links to find relevant information.

Detailed information: The information was all relevant, and I did not notice any fluff.

The negatives:

Website navigation: It was extremely difficult to navigate to different pages. Pop-up windows from mousing over website links opened extra windows to click on. This, however, posed a massive problem. The window is not connected to the pop-ups, and so the window fades before the links can be clicked. It is possible, but requires multiple tries, and is extremely frustrating.

The map: The map is a great idea, but was executed poorly. When I clicked on the map, sometimes whole sections were selected, and sometimes individual graves were selected. Sometimes, no graves were selected, but still displayed information on graves in the area. The map and the information below it were extremely disjointed. Also, there was a little indication on what the was and was not clickable on the map. I think that ultimately the map was not useful.

Conclusions: The information seems to be well researched and well put together. Unfortunately, the technical errors of the website made it a pain to get to the information. I think that the website needs a lot of technical work to be presentable. These errors do not seem difficult (relatively) to fix, as the underlying website format and information is a solid foundation.

**Comment by koshinf** [comment]
I chose the *Tarantino Profanities* project since I've seen all his movies and was interested in seeing just how much he uses profanity in them. (It's a lot)

### UX design:

**Good**

- Use of graphical representation of information is well executed and sectioned off.
- Feels like an essay in web form, but it works.

**Needs Improvement**

- Color choice of the body element should be something that isn't close to the color of the text on the page.  Makes it hard to read, especially with the script looking font they chose.
- On the **Method** section at the bottom under **Network Analysis**, the links provided cover up the text above them.
- Conclusion tab needs some extra space to the right of the text to fit with the other tabs.

### Ideas for next research

Instead of focusing on just three of his films, take it to the next level and add all of his films to the list.

**Comment by KSD32** [comment]
I choose the Hamilton project to review. The main purpose of the Hamilton project was the analyzing and visualization of the song lyrics of the Hamilton musical in order to gain an understanding of the history being portrayed in the musical. 

The site was very well done, with a user experience that is very easy to navigate. The developers provided quick and easy links (that are still active) to make it easier for viewers to easily find what they are looking for. I had no real issue navigating the site. They also provided great visualizations, such as graphs and networking in order to clearly demonstrate the purpose of their project. 

A possible idea that the developers may want to move forward with is researching the ambiguous lyrics found within the lyrics of Hamilton, to further distinguish if they are fact or fiction.
