### ISSUE TITLE
“7 Days to Die” update log project proposal -Donald Denne

### ISSUE THREAD

**Issue by SparkTheDragon** [ebeshero/DHClass-Hub#599]
The what: 
This project will markup and analyze the update patch notes for the game 7 Days to Die.
Graphics and statistics will be made to both conceptualize and visualize relevant data.

The why:
To determine the change in focus from the Developers over time to determine educated guesses on the future development of the game.

The How: TBD

Sources: 
https://7daystodie.com/news/
https://7daystodie.com/a16-early-streaming-release-notes/
https://7daystodie.com/alpha-15-release-notes/

These three sources span 3 years of development from the game.

**Comment by ebeshero** [comment]
@SparkTheDragon Would you edit the above post in markdown to add some links out to the patch notes and/or relevant info so we can get a sense of the data and text available for your project proposal?

**Comment by jonhoranic** [comment]
@SparkTheDragon Since 7 Days to Die has had some relatively mixed internet buzz, I wonder if you could get a lot more quantifiable data by checking review aggregate sites or the user reviews off Steam. That way you can compare the reviews to each iteration of the game, perhaps gain some insight from the reactions of players and/or reviewers each time a new patch changes the game were launched.

**Comment by SparkTheDragon** [comment]
@jonhoranic My goal is not to figure out public opinion, my goal is to determine the direction and development of the game from 2016 until present. Categorizing all of the updates will provide percentile statistics on which area of the game they are focusing on.

If really needed, I am sure I can pull up other dev posts where they talk about what they plan on doing for the game.

**Comment by jonhoranic** [comment]
@SparkTheDragon Ah! I see now, thank you for the clarification! So this is more internal examination of the game's development rather than the outside perceptions from the game's development.

With that in mind, I do not know how strict the writing standard is for their changelogs from the passing glances I made earlier. If they have a set format? Great, easy for classifying so you can churn out mark up like a well oiled machine. If they do not? It will be worth it to create your own classification system, just be sure note how and why you made your content categories as you make them. Methodology is half the battle, as it helps your group and others coming viewing the site have a shared understanding of your mark up.

Trust me...those graveyard records were spotty to begin with without having to mess with the changes in wording on forms and certificates! The Graveyard Project spent a good week coming up with shared terms before we even got to mark up!

**Comment by frabbitry** [comment]
I have never played *7 Days to Die* (I honestly don't really play video games), but I like the idea of using update patch notes to analyze trends and make predictions. 

What would you use to make predictions? What aspects of the patch notes would you consider as significant to future updates? Mentions of things that the developers would like to do that haven't been done yet? How would you quantify it?

I do think that it sounds like a fascinating project. I'm just curious about what your methodology would be.

**Comment by abdual1100** [comment]
I agree with @frabbitry that I also never played _7 Days to Die_ but the idea seems really interesting of how you want to analyze trends thats related to this topic. The process is going to be difficult as with the mark up. While reading @jonhoranic comment, The Graveyard Project took them a lot of time to set it up before starting the mark up. But it'll be an interesting way to see how you set it up.

While looking at the resources/links you provided, I can see that the sequence of it would be interesting on how you can put it all together. So thats kind of my big question, How will you use this idea to make predictions or it being important in the future update for the game?

Overall, can't wait for the finished outcome.

**Comment by James-f117** [comment]
I find this project proposal very interesting and think that it would be a fun and interesting one to pursue. I agree with @abdual1100 where I find that analyzing the patch notes to create a connection to future patches and updates would prove fairly difficult. However, it would prove useful to see why new patches were released and what was the way/reasoning behind the patches. Although I have also never played this game so in doing so would not have much of an understanding as to what the notes mean for example the blood moon horde, and the importance of vending machines being introduced as stated in the "Alpha 15 Release Notes". I would however find this project very interesting and would like to find out what you discover.
