### ISSUE TITLE
Counting distinct-values within for-each

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#60]
So I've been trying to output a list of distinct values within a selection of a text, and then outputting a number of instances of that distinct value within the document next to it. It'd look something like this:
`femVoice [Count= 4]`
`mascVoice [Count= 2]`
...and so on for each.

I can output the list of distinct values just fine, but I can't figure out how to get a count to work alongside of it. This is what I've got so far:
`<ul>`
`            <xsl:for-each select="distinct-values(//articleBody/*/name())">`
`                <xsl:sort/>`
`                <li xml:id="{.}">`
`                    <xsl:value-of select="."/>`
`                    <THE COUNT INFO WOULD GO HERE>`
`                </li>`
`            </xsl:for-each>`
`            <!-- ras: Outputs an alphabetized list of the names of distinct values within <articleBody> -->`
`       </ul>`

And this is my attempt to get a count:

`[Count: <xsl:value-of select="count(//articleBody/*[current()/@xml:id])"/>]`

I've tacked on `xml:id` onto the list item as an attribute as a way to provide a reference to my count (unsure if this is the right approach). I tried to follow the obdurodon instructions, but their example doesn't actually call distinct-values, they just use a list that's already made within the original document.

I don't think that I can call to higher nodes of the document within a for-each, which I would need to do to get a count for each element. I think?

I'd help to know the structure of the document: basically, its a bunch of elements without any attribute values floating inside of text, all held within `<articleBody>`. Looks like this:

`        <articleBody><date when="1888-07-10">Tuesday, July 10</date>, according to instructions from`
`                <ref to="theTimes">THE TIMES</ref>, I made up for the role of shop-girl, and with a`
`            list of factories in one hand and gentle peace in the other sailed down <location`
`                type="streetName">State street</location> under a brown braise veil as impenetrable`
`            as an iron mask. I applied at two <industry>feather factories</industry> and three`
`                <industry>corset shops</industry>, but aside from the exercise up and down several`
`            flights of stairs got nothing. The feather people did not need any help and the corset`
`            folks had not started on the winter trade. <workingConditions category="positive">I was`
`                treated with civility, however, and given permission to “drop in a week or`
`                so.”</workingConditions> The fifth place on my list was the <company`
`                name="identified">“Western Lace Manufacturing Co.”</company>`
`            <location type="address">218 State street</location>.`
and so on.

**Comment by ebeshero** [comment]
@spadafour This is really smart work! I like your idea to create w distinct XML:ID for the articles, and your way of constructing it. OK--what you want to do with distinct-values is a process of indexing, really, and it's a very common application of XSLT that is a little more complicated than you might expect! We can definitely do this, and it's worth learning how! Here's what's going on, and what has to happen for your plan to work. 

1) You take distinct-values() and that makes a text string, really: pulls out all the values of something from the XML tree and removes their XML context by just making a simplified list of single entries where there used to be multiples. We lose XML hierarchy info when we take distinct values, but that's OK, because our next step is...
2) Our next step is to put those XML values back--or rather, to **map** the distinct-values entries to particular spots on the tree, so you can output where each distinct value is marked: 20 instances here, 15 there, etc. This process is basically how we make an **index** of any collection of stuff--a book of poems, a series of newspaper articles, etc.

So, how do we do this? I'll post this now and explain more in my next post--we're about to take off from Lyon to Frankfurt, on our way back home today!

**Comment by ebeshero** [comment]
OK--now I'm in Frankfurt waiting for the next flight, to Toronto! So, back to this question. 
What you want inside each `<li>` is each member of your list of distinct values (which I think you are successfully delivering here), followed by a count of how often that value appears in the XML file within `<articleBody>`. So, we need to look up the actual nodes on the XML tree, and **wherever they match a particular distinct value**, count them. 

You want to step through the tree, and write a predicate expression for this, **to indicate a match to the current context** being processed by your XSL template.

**Comment by ebeshero** [comment]
AND...I see the problem, @spadafour, that you were having with my colleague's tutorial on Obdurodon: http://dh.obdurodon.org/xslt-basics-2.xhtml
He doesn't give an example of how to work with distinct-values in an xsl:for-each statement. So, let me give this a go--and maybe this will be a useful example to go over together in class! 



`<ul>`
`            <xsl:for-each select="distinct-values(//articleBody/*/name())">`
`                <xsl:sort/>`
`                <li xml:id="{.}">`
`                    <xsl:value-of select="."/>`
`                    <!--THE COUNT INFO WOULD GO HERE-->`
` <xsl:value-of select="count(//articleBody/*[name() = .])"/>
`
`                </li>`
`            </xsl:for-each>`
`            <!-- ras: Outputs an alphabetized list of the names of distinct values within <articleBody> -->`
`       </ul>`

I didn't write that in an actual XSLT file--just plotted it here, so beware of typos. But give this a try, and note that you might need to use current() in the count() function instead of the usual dot (.) -- The Obdurodon tutorial explains this a bit. I think the dot ought to work in this case, but if it doesn't, current() will definitely refer to the current context node of the for-each group.

**Comment by spadafour** [comment]
I keep getting this error:
`F [Saxon-PE 9.6.0.5] XPTY0020:`
`Leading '/' cannot select the root node of the tree containing the context item: the context item is not a node`


w3.org describes the error like this:

`err:XPTY0020`
`It is a type error if, in an axis step, the context item is not a node.`

This error occurs when I am using both `current()` as well as `.`. This is what lead me to believe that my issue lies with my attempt to step back up into the document.

I think it might not be possible to do with the way the document and my each-of statement are set up.

After reading some more, I THINK that distinct-values is a dynamic argument. Within my for-each, I attempt to do a count over static elements, which is inside of the dynamic argument (which would be a no-no). Here's where I read that:

`[Definition: A type error may be raised during the static analysis phase or the dynamic evaluation phase. During the static analysis phase, a type error occurs when the static type of an expression does not match the expected type of the context in which the expression occurs. During the dynamic evaluation phase, a type error occurs when the dynamic type of a value does not match the expected type of the context in which the value occurs.]`

`The outcome of the static analysis phase is either success or one or more type errors, static errors, or statically-detected dynamic errors. The result of the dynamic evaluation phase is either a result value, a type error, or a dynamic error.`

`If more than one error is present, or if an error condition comes within the scope of more than one error defined in this specification, then any non-empty subset of these errors may be reported.`

`During the static analysis phase, if the Static Typing Feature is in effect and the static type assigned to an expression other than () or data(()) is empty-sequence(), a static error is raised [err:XPST0005]. This catches cases in which a query refers to an element or attribute that is not present in the in-scope schema definitions, possibly because of a spelling error.`

`Independently of whether the Static Typing Feature is in effect, if an implementation can determine during the static analysis phase that an expression, if evaluated, would necessarily raise a type error or a dynamic error, the implementation may (but is not required to) report that error during the static analysis phase. However, the fn:error() function must not be evaluated during the static analysis phase.`

`[Definition: In addition to static errors, dynamic errors, and type errors, an XPath implementation may raise warnings, either during the static analysis phase or the dynamic evaluation phase. The circumstances in which warnings are raised, and the ways in which warnings are handled, are implementation-defined.]`

`In addition to the errors defined in this specification, an implementation may raise a dynamic error for a reason beyond the scope of this specification. For example, limitations may exist on the maximum numbers or sizes of various objects. Any such limitations, and the consequences of exceeding them, are implementation-dependent.`

Sorry for the wall of text. Basically, its stuck evaluating a list of distinct-values(defined in my for-each), so it has no way to do a count of elements (they don't exist in the list that is being looked at).

**Comment by ebeshero** [comment]
@spadafour I discovered the problem and a solution this morning, by looking this up in Michael Kay. Apparently when I've done what you're trying here, I've been working in a different XML transformation processing language called XQuery, which lets me do things the way I was writing here! But it won't work in XSLT which has a different syntax for this kind of thing. 

To do this in XSLT, you need something that amplifies `<xsl:for-each>` and effectively lets you work with the distinct values in a collection of nodes. It's called `<xsl:for-each-group>`, and we haven't written any tutorials on it, so maybe we'll have to write one! You can read about it if you have the Michael Kay book, on pages 326-344 (lots of examples here). I got your XSLT to work by writing up an `<xsl:for-each-group>` and moving it up into your template that matches the document node. I want to explain how it works, since the code is going to be totally unfamiliar to you! But it works, and this is the element in XSLT that's designed to do the kind of work you want with the element names here!

**Comment by ebeshero** [comment]
@spadafour I'm going to push my modification of your code into the Troubleshooting folder. But here's a view of the `<xsl:for-each-group>` coding:

`
<h3>Elements:</h3>
                <ul>
                    <xsl:for-each-group select="$nelsonColl//articleBody//*" group-by="$nelsonColl//articleBody//*/name()">
                        
                        
                        <xsl:sort select="count($nelsonColl//articleBody//*[name() eq current-grouping-key()])" order="descending"/>
                        <xsl:for-each select="current-grouping-key()">
                            <li>
                            <xsl:value-of select="current-grouping-key()"/><xsl:text>, Count:</xsl:text>
                          <xsl:value-of select="count($nelsonColl//articleBody//*[name() eq current-grouping-key()])"/>
                        </li>
                        </xsl:for-each>

                    </xsl:for-each-group>
                </ul>'

**Comment by spadafour** [comment]
Awesome, I've integrated this into my code and resubmitted! Thanks!

**Comment by RJP43** [comment]
For Students who wish to access this for help on the Exam
