### ISSUE TITLE
Pokemon Map: Project Proposal- Jacob Gonos

### ISSUE THREAD

**Issue by JAG240** [ebeshero/DHClass-Hub#600]
**The Project:** 
To pick a Pokemon region (Kanto, Sinnoh, etc.) and find information about this region and marking it up. Ultimately, Using a map to allow users to click on a route, landmark, etc. and have relevant information display. Information on these landmarks that will be available are Pokemon encounters, important characters, level range expected from wild Pokemon, and any other important information. 

**The Purpose:** 
Using this tool can help to understand how Game Freak makes great game settings. Relating this map with other regions can show parallels and differences throughout the years and help understand how each is unique and developed. 

**The Steps:**
Comparing a realistic render of the region to the in-game map to show where there are landmarks. Then, using bulbapedia and other online resources to find all relevant information about each landmark and marking it up. This map is using the game universe as it's basis for information. 

**Resources:** 
https://bulbapedia.bulbagarden.net/wiki/Main_Page
https://www.serebii.net/pokearth/
https://pokemon.fandom.com/wiki/Pok%C3%A9mon_Wiki 
and many more

**Comment by ebeshero** [comment]
@JAG240 Would you edit the above in markdown to add some links to this proposal (to bulbapedia, Game Freak, etc) and help get us a sense of the available data for the project?

**Comment by ebeshero** [comment]
Great-- Thanks for fleshing this out, @JAG240 .

**Comment by jonhoranic** [comment]
@JAG240 I would also like to note that GameFreak and Nintendo love to bring in real-world inspiration into the names and designs of areas, characters, and individual pokemon. It would be interesting if you could compare the fictional aspects of the games to their real world equivalents in some way! I know a lot of fan forums and YouTube creators like to do "factoid" based content with that information but it is rarely comprehensive.

I personally think Kanto or Johto would work best, partially due to their relative simplicity but mainly due to the rich amount of content that can be pulled from those worlds.

**Comment by abdual1100** [comment]
This sounds like a very cool project idea. I'm a fan of Pokemon so I want to see how this all comes together. The map idea seems like an interesting idea but how would you put all the information together so you can map it out as one of the main features of this project?  Looking at your resources, I feel like this would be cool idea to go with and I can't wait to see the finished outcome of how you put all this information together.

**Comment by abdual1100** [comment]
This sounds like a very cool project idea. I'm a fan of Pokemon so I want to see how this all comes together. The map idea seems like an interesting idea but how would you put all the information together so you can map it out as one of the main features of this project?  Looking at your resources, I feel like this would be cool idea to go with and I can't wait to see the finished outcome of how you put all this information together.

**Comment by quantum-satire** [comment]
You have a lot of great ideas here, but I might recommend choosing one of them and focusing on it rather than spreading yourself out too far--the semester is short and these projects take time! I might recommend creating a map of a particular region, marking up information about cities, locations of pokemon in that region, and maybe the history of the region / important characters. You'll get a deeper focus and stress less on plotting points for your map.

I could see an interactive map that, when clicked on a certain point, will expand the information about that particular city or route.

**Comment by ebeshero** [comment]
Project scope can be difficult to know right now as we're starting out, but we'll figure this out. While I'd ordinarily agree with @quantum-satire (who was a student in this class last year and worked on the [Rick and Morty project](http://www.rickandmorty.newtfire.org/) and the [War of Currents project](http://warofcurrents.newtfire.org/)), I also think you can cover a lot of regional ground for mapping use regular expressions and autotagging, which we'll be learning in the next unit. If you can locate all the place names in a large pile of Pokemon texts, you can spread out your datapoints for a map. But your markup of all the available lore documents might not be equally dense. You could decide to do a diffuse kind of markup over lots of texts (going fishing for place names), while you also concentrate other kinds of markup on a particularly interesting area. This is something a new team will need to survey and experiment with over the next couple of weeks, and we'll talk more about scoping the projects as we go.

**Comment by ebeshero** [comment]
Thinking a little more about this, @JAG240 , how would your project proposal add to what's available in the Bulbapedia projection, here?
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_world_in_relation_to_the_real_world
