### ISSUE TITLE
Project Proposal: Bloodborne Lore - Frank Koshinskie

### ISSUE THREAD

**Issue by koshinf** [ebeshero/DHClass-Hub#601]
### Goal:
* Analyse the lore to determine which characters and places hold the most relevancy to the game.
* Take relevant characters and places and see how they relate.
* Link characters and places to the dream, nightmare, or waking world
### Reason:
The lore of Bloodborne is kind of all over the place and I feel it would be nice to be able to visually represent who goes where and such.  The concept of the dream world and waking world being real places that you can traverse between is difficult to understand when you somehow enter nightmares through dreams and also through the waking world?  Lovecraft is odd, so I feel that this project might help gain insight into what exactly is going on.
### Information Source:
* https://bloodborne.wiki.fextralife.com/Lore

**Comment by jonhoranic** [comment]
@koshinf Do not know if your use of the "insight" was an intentional reference or not, but hey, bravo!

Anyway, yes! The lore of the game is rather obtuse, but I could imagine that having all the rich dialogue and _very_ precise wording of the item descriptions marked up in one place will make it easier to tie all the treads together. I believe that most, if not all, of that content is available on the web. 

One potential hurdle I see here is how you intend to represent the lore "structures" of Bloodborne. Knowing that the game has an overarching plot but with many smaller interwoven narratives, where would you start in order to begin pulling everything into one perspective? Go plot point by plot point "semi-chronologically" as a player would through progression and fill in as you go? Complete the smaller narratives and then weave them together to form the larger web? Lots of different ways to head, I would be interested to see what your methodology might be.

**Comment by NADGIT** [comment]
Man, we're coming up with some really good project ideas!

I'm a fan of the Souls series, but I've only tried Bloodborne. Still, Miyazaki's style of storytelling and the lore of his games is definitely one of my favorite parts: trying to piece together stories and create theories as to the history of the universe of Bloodborne and the Souls series is half the fun of the games.

If I had to give a suggestion, one way that would definitely work as a way to structure the lore would be tag any involved entities in item descriptions & other tidbits of text. This way, when a person views a certain entity such as a character, they would be able to see all the lore that mentions them. It's just a small suggestion, but I think that people will enjoy having centralized pages where they can easily view all the lore associated with a certain entity.

A wise man once described the lore of the Soulsborne series as "Lies, speculation, and speculation about lies". It'll be very interesting to see a project like this, and I think it's a perfect choice for XML!

**Comment by jonhoranic** [comment]
@NADGIT Wise man! Though I would be willing to argue that there are LAYERS of lies that add to that confusion, much like Lovecraft intended with his unfathomable cosmic entities. 

I am interested on your take, as your suggestion reminds me like how one would form a loose "bestiary" of sorts. Taking the information from all the related bits in order to merge them at an established center point sounds like an interesting way to proceed.

**Comment by frabbitry** [comment]
Again, I don't really play video games, so I've never played *Bloodborne* and don't know much about it. I'm just going through everyone's proposals and asking questions because I can. 

How would you map this information? What would you use to translate information about where characters go and such into data that you could put on a map?

**Comment by koshinf** [comment]
> How would you map this information? What would you use to translate information about where characters go and such into data that you could put on a map?

Probably could just use something like an ERD if I wanted to make an actual visual map of the relationships.  There aren't that many locations in the game, but finding out what goes where is the hard part.

**Comment by ebeshero** [comment]
For those unfamiliar with the acronym, I think @koshinf is referring to an Entity Relationship Diagram, and here are [some examples](https://www.google.com/search?q=entity+relationship+diagram&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj6nYydpYzgAhVRPN8KHXeNAUwQ_AUIDigB&biw=1152&bih=575). There are a few different ways we can generate diagrams of relationships, and one way we've been featuring in this course is with network analysis--of which you've seen examples on several of [the student projects we were discussing last week](https://github.com/ebeshero/DHClass-Hub/issues/595).

**Comment by quantum-satire** [comment]
I haven't played Bloodborne, but for your project, you may want to consider having tangible texts for markup if possible--that is, any in-game letters, documents, or even dialogue between characters for your markup. It would give a good starting point for you to support your project's main research question. I see that in the Wiki page you linked to there are some notes pulled directly from the game, though I would advise finding a larger corpus of canon texts just to make it easier for you!
