### ISSUE TITLE
Project Proposal: The Complete Discography of Tangerine Dream 

### ISSUE THREAD

**Issue by NADGIT** [ebeshero/DHClass-Hub#602]
**The Complete Discography of Tangerine Dream**

Tangerine Dream is a German electronic music band founded in 1967 and they have had few hiatuses throughout their years of creating music. As a result, [their discography is quite massive!](https://en.wikipedia.org/wiki/Tangerine_Dream_discography) With such a large list of items and the complexity of their musical career, I figured it would be a very interesting project to organize and markup their various albums.

**Why Tangerine Dream?**
Tangerine Dream is an interesting band, and has been very influential to the musical ecosystem. They've been making electronic music since it was practically invented, even predating when electro became popular in the early 70s. On a more personal note, I think they've got something for everyone: from energetic and catchy short tracks to ambient and progressive longer compositions. Not to mention, they have also experimented both within electro's different styles and in other genres of music. So, I think this project isn't just an opportunity to document a piece of music history, but can also be a chance to discover some great music.

**You mentioned complexity?**
Tangerine Dream's experimentation is only the surface of their varying roles: They have composed for several different labels, band members have joined and parted ways, and even made soundtracks for movies and video games. As a result, there is a wealth of data to sort out, and several different ways to approach it.

**So, how _are_ we going to approach it?**
That depends: what are we trying to accomplish? I haven't got a goal lined out, but I think this is something that should be discussed. After all, with material like this there are many options and goals to choose from. Are we trying to compile a historical document? Are we trying to help fans find that perfect Tangerine Dream track? It's really all about what we'd like to do.

**Comment by jonhoranic** [comment]
@NADGIT I think it would be really interesting to try to find all the different places their music has appeared, as that could show how widespread their influence is. That can be contrasted with things like sales numbers, downloads, or review scores as a sort of gauge of relative "success" (there is probably a better fitting term for this) with other media. I know that they were involved with the soundtrack for Grand Theft Auto 5 for example, and that game sold like hotcakes!

For an alternative, you could chart out their main discography in a similar way. Since members of the band have come and gone, it could be interesting to compare the level of "success" they had, either solo or in another band, against Tangerine Dream. That way you could also show a network of relationships within the music industry stemming from their members and/or work!
