### ISSUE TITLE
Project Proposal: The Ulysses Project - Fiona Carter 

### ISSUE THREAD

**Issue by frabbitry** [ebeshero/DHClass-Hub#603]
There's this book called *Ulysses* by this guy named James Joyce. It's 730 pages of hard-to-get-through stream-of-consciousness writing about one day in the life of the main character, Leopold Bloom, which means that it's not the kind of book you read for fun. However, there's a ton of references in it, and there's about a hundred different ways you can interpret it. Joyce himself mentioned after he wrote it that this book would keep scholars occupied for a long time, and he was right. There is a 525-page book listing the references in *Ulysses* alone. 

Joyce was Irish, so *Ulysses* is set in Dublin. There's a lot of references to Dublin locations in *Ulysses* just like there's a lot of literary allusions and other references in *Ulysses*. I think that it would be pretty cool to map out the locations of Ulysses (probably more realistically it would be a section of *Ulysses*, maybe the Cyclops section or something), because the city of Dublin plays a pretty big role in all of Joyce's works. What's cool is that other people have already done the work of finding out the street names and numbers of the location references in *Ulysses* (one annotation that I know of off the top of my head is "Notes for Joyce" by Gifford and Seidman), and there's actually already paper maps detailing Bloom's trip through Dublin. What I propose is that we could translate what people have already done on paper into geodata that we could put into a GIS (maybe ArcGIS or GRASS). We could also create networks connecting the Dublin locations in Ulysses to literary allusions and such. I think that there's a lot you could do with Ulysses, and I like to tag references. 

(A possible extension of this project would be to do something with sentiment analysis and text mining. Because *Ulysses* is written in fairly modern English, it could be easy to get ahold of some emotion-word lexicons and run some text through R to assist with emotion tagging. I don't know if adding that sort of dimension would result in a monster project that we couldn't finish, though.) 

Anyway, here's the breakdown:
**What:** Create geographical and/or network map(s) of references in *Ulysses* (or a section of *Ulysses*) by James Joyce 
**How:** You can get a copy of *Ulysses* from [Project Gutenberg](http://www.gutenberg.org/ebooks/4300), and we could use annotations, such as *Notes for Joyce* by Don Gifford and Robert J. Seidman.

**Comment by jonhoranic** [comment]
@frabbitry With the amount of content that can be pulled from _Ulysses_, this is an interesting path to take. This could be quite a substantial project just focusing on the places alone!

I would be very interested to see a network that indicates the frequency of locations mentioned in the text, perhaps with some added historical or geographical data attached. I would think that if you did it by say, "frequency of locations visited relevant to the plot" it would take MUCH longer to string that together unless you had a thorough understanding of the text. Either way, nothing wrong with "starting small" because a project with with a singular goal and a LOT of data can be equally enlightening as a project with many goals and a single set of data.

**Comment by NADGIT** [comment]
Man, we're coming up with some really good project ideas!

Though I've never read Ulysses, I do think it's a very good pick for an XML project. Its length would seem daunting at first, but I think that's more of an advantage than disadvantage: there's that much more data to process, and it offer a lot of ground for a powerful analysis to process.

Also, I think Ulysses is a good choice because of its origins as a stream-of-consciousness novel. Many other works of literature have had the XML treatment, but Ulysses is markedly different: since it was written in the style of an internal thought process with little to no structure and even less of an apparent plan. This sort of book would be interesting to tag because many XML conventions simply wouldn't apply, as the book sometimes even forgoes the use of sentences. On top of that, analyzing a book meant to emulate a human thought process would be an interesting angle in and of itself. Definitely a really good choice!

**Comment by KSD32** [comment]
This is a very interesting project idea! Personally, I have never read _Ulysses_ so it will be very interesting to see how the project comes about. And the fact that it is a form of author writing style, in this case stream of consciousness, that it not used often in popular writing will be a fascinating aspect of the project. I like the idea of creating a networking map for references.
