### ISSUE TITLE
Project Proposal: Sports (NFL) Project 

### ISSUE THREAD

**Issue by abdual1100** [ebeshero/DHClass-Hub#605]
**The Project:** The goal of this project proposal is to research data involving sports. The Super Bowl is coming up soon so I thought it would be a good idea to research data on the most televised event. Through the examples you showed us, I haven't seen any sports themed one. Our group would pick the most watched Super Bowl event, top 5, and research them by looking up information as when it was watched the most (time). etc. Then we would compare the following information to the next years event seeing if there was any difference or not. We could also have a map Tracker where the event has been taken place. We would coordinate to see if the location has made a difference on the event being or not. 

**The Goal:**  The goal for this project is to test different features in order to show and understand how these big events work by being scripted or not. Having the map will help us understand if the location plays a major factor or not. It will help us understand why recently the trend is rising. 

**The Steps:** Having the map will help us understand location. How many people showing up will determine the outcome of the game? The map will be a big step by continuing the website and seeing if it will major outcome on it or not.

**Resources:** 
https://www.statista.com/statistics/216526/super-bowl-us-tv-viewership/
https://www.sisulizer.com/online-help/XmlContext.shtml
http://geoawesomeness.com/top-9-maps-charts-explain-super-bowl/

**Comment by jonhoranic** [comment]
@abdual1100 Interesting way of going about this! Less about the inner aspects of the game (players, score metrics, etc.) but more the atmosphere and environment AROUND the event-that-just-happens-to-be the game. 

There are a ton of different elements at play (pardon the pun) for Superbowl coverage; commercials, promos, news stories before/during/after the game, number of views on various networks/devices, attendance numbers, the list goes on! Even if you just took a small selection of related items, those networks of relationships would look really interesting, even more so if you make multiple networks to compare and contrast the data.

This is a great project idea with a lot of promise, and I would highly recommend early on to select the specific things you want to cover. That way you can save room for extended research later on as optional additions. It can be tricky when you have a lot of data to recognize and organize, which from working on the Graveyard Project, I can easily say that "content juggling" is not easy! Haha, do not let me dissuade you though, these projects tend to take off once you start to dig in and find interesting little bits of information to share!

**Comment by frabbitry** [comment]
I like this project idea. I like how there's a lot of data that you could work with. 

I think that the question you are trying to answer is very interesting. Do outside factors influence the outcome of a Super Bowl game? Furthermore, is the game rigged, then? There's a lot of data that you could analyze (location, attendance, etc.) and then graph to see if its at all correlated to the game outcome. It would also be very easy to map the locations because you'd be dealing with modern locations in the U.S. Getting relevant geodata would be trivial. 

I think that this is a great project idea. The only problem I would see with your research question would be connecting the data that you're analyzing to whether the game is rigged or not. Unfortunately, correlation does not equal causation. I don't know if it's possible to actually analyze and determine whether the game is rigged given the type of data we're able to use. It would be very interesting to see if things like attendance and location are related to game outcomes, though.
