### ISSUE TITLE
Bad Graphs! A discussion and tour of lying, faking, and other misrepresentations with visuals

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#608]
It's much too easy to lie with numbers and graphs on digital humanities projects, and in the digital world generally! We will be posting links here of the good and the bad with graphing and using digital visualizations to share information on DH projects. 
Please begin by reading [**"A short tour of bad graphs"**](http://people.stat.sfu.ca/~cschwarz/Stat-650/Notes/PDF/ChapterBadgraphs.pdf)  Also, take a look at [this set of slides](http://www.slideshare.net/ebbondar/bad-infographics-some-examples ) to illustrate problematic graphs.

### Discussion points (due for Monday, 1/28)
- See if you can understand what's wrong with the examples in the reading, and if you have questions, about examples or advice in the reading, post them here! 
- Each of you in your posts should look on the web for two examples of bad graphs, and tell us what's wrong with them!
- There's no minimum or maximum number of posts: We'd like you to comment on each other's examples, discuss interesting examples from the reading, and locate two examples of your own from the web, just to practice your critical eyes and give this some thought collectively! Let's see what you all come up with.  

(For GitHub practice, try downloading image files of bad graphs, pushing them to the DHClass-Hub Sandbox folder, and linking to them here in the Issues discussion. To make a link to a file, go find it in a new tab and copy its web address. You can just paste the address here. Or try pasting the image into the issue.)

@koshinf @SparkTheDragon @Skapfer13 @JAG240 @James-f117 @achen298 @abdual1100 @NADGIT @frabbitry @alnopa9 @KSD32 @BMT45

**Comment by abdual1100** [comment]
I managed to close a comment on github while commenting on a project
proposal idea. and now I can't see it on the issues tab. Is there a way to
undo it? Let me know Thanks

**Comment by ebeshero** [comment]
@abdual1100 You can always look for closed issues and reopen one. Look at the top of the Issues page where it now says 21 open issues. Next to it is the number of closed issues, and if you click on that number, you can see them all, and sort them from Newest to Oldest. And on every closed issue is an option to reopen it. But I just checked and I don’t see any issues closed recently except the ones I myself closed yesterday. Maybe you deleted or resolved someone’s comment? If a comment was deleted, we will have to do some digging to recover it. Can you tell me which issue was affected?

**Comment by ebeshero** [comment]
@abdual1100 Okay—I see what happened! You closed an issue but also figured out how to reopen it. No worries then!

**Comment by abdual1100** [comment]
I figured it out
Thanks

**Comment by frabbitry** [comment]
@NADGIT I also, before reading this article, did not know anything about "ducks" and am now curious as to why those drawings are called "ducks." Was there some awful event in this history of graphing involving ducks? Or is it just implying that the data can "duck" behind the drawings and be obscured? 

Graphs are used to tell a story with data. They are used to communicate, and are especially helpful for facilitating communication between the people who know how to extrapolate information from raw data and the people who don't. As with any other method of communication, then, you can't use it to lie. You can't use it to lead people astray. For this same reason, we try not to plagiarize or spread false information. The story that you tell using the graph should be an accurate story, and that was the gist that I got from the article. 

That being said, different types of graphs are suited to different purposes; the graph that you use depends on the story that you want to tell. If you want to show a change over time, for example, you want to use a line chart. If you want to highlight a comparison between two or more things, you want to use something like a histogram or a bar graph. 

While pie charts are useful because they immediately imply a comparison of parts to a whole, I actually agree with the article in that pie charts are awful. They're awful because they make it harder for people to accurately determine percentages of data without a bunch of labels and extraneous information added in. Pie charts are harder for people to immediately grasp the meaning of, especially when "slices" are similarly sized or there are multiple pie charts. Bar graphs, which serve a similar storytelling purpose, are much easier for people to "get." If you're interested, there's [another article](https://www.perceptualedge.com/articles/visual_business_intelligence/save_the_pies_for_dessert.pdf) that explains it all better than I can. Anyway, in conclusion, I don't like pie charts much either. They make it easier to lie with data because they're harder to immediately grasp.

**Comment by NADGIT** [comment]
@frabbitry Thank you for the article, I now better understand the criticisms of pie charts. It seems that the main issue is that it is difficult to convey precise measurements, especially when these measurements change over time. I do agree with the article that when comparing percentages that change, or when the measurements need to be precise, it is better to use a different sort of graph. I mean, when researching this a little more, I found a pie graph split into 5 parts that were all slightly less or more than 20%. I couldn't tell which was which!

My only pet peeve is that bar graphs don't really help me perceive parts of a whole. Since the maximum value on the scale seems to change every time, it's hard to tell at a glance the approximate proportion of each value. An example would be something like this: if one bar graph has 40% as its maximum value, then a bar that goes halfway up is 20% of the whole. However, if the maximum value in a different graph is 60%, then halfway up would be 30% of the whole. This makes it hard for me to easily associate bar heights with certain values. Does anyone else have this same problem or is it just me?

But don't worry: either way, I will not be using pie charts any more as most people find them unhelpful. However, while researching this I found something very interesting: apparently, many people find waffle/square-pie charts to fulfill the same function as a normal pie chart, but can more accurately represent data. They look quite odd, and I don't think I've ever seen them in a presentation before. That being said, though I find it easier to visualize percentages with them I think that they have a fairly fatal flaw: Depending on how the user arranges the tiles in the waffle, the graph is either quite informative or extremely deceptive. For instance: [This Graph](http://homepage.divms.uiowa.edu/~luke/classes/STAT4580/img/waffle.png) makes perfect sense and you can easily compare the change over time while also seeing the part-to-whole relationship. On the other hand, [this other graph](https://depictdatastudio.com/wp-content/uploads/2017/09/Waffle-Automation.png) makes understanding the different values very difficult: Because the way that the user has spread the gray tiles out, it wasn't immediately apparent that it took up almost half of the chart. On a second look, the values also do not add up to 100%, so it might just be a patently bad graph. Since these waffle charts are kind of rare, and I don't think the articles we read talked about them, what do you guys think about them?

**Comment by abdual1100** [comment]
The main issue to me is about the Pie Charts. I agree with the article that when comparing percentages that change or don’t , or when making measurements that need to be accurate, theres other graphs that you can use besides pie graph. Having it shown like that can lead to confusion for the reader, 

Bar Graphs are good in some cases when measuring something precisely but they also have fault in them to. It doesn’t always show the most accurate representation of everything what the maker of the graph wants you to see, the main point. While I was researching on this subject I found out that people understand pie charts/pie graphs to be easier to understand than bar, line or any type of graphs on the internet. I always thought that those kind of graphs would be easier to understand as they are precise in any way you look at it. It leads to a lot of solutions in my opinion. I find it easier to visualize whole numbers as being compared to pie graphs which are in estimated percentages. For example **[this graph](https://www.statisticshowto.datasciencecentral.com/wp-content/uploads/2014/01/usa-today-1.png),** talks about common injuries suffered in children's. It doesn’t tell you out of the total percentage it happens or the age isn’t categorized of what is the sample group in the graph idea comparison. The headline in that graph is misleading compared to the statistics. **[Another graph](https://www.statisticshowto.datasciencecentral.com/wp-content/uploads/2014/01/pie-chart-misleading.png)** that I looked at is the pie graph of the 2012 election. As you can see, the numbers don’t add up together to equal 100. As you can see, people find it tough to understand what would be happening as this pie chart won’t solve any of your answers about years election. Numbers in the Pie chart tend to be estimated as you can see in this example. Overall, I think Bar graphs are easier to understand than compared to the graphs listed in the article. Graphs make the understanding of comparing objects easier than it was before. Graphs tell the story in a another way which makes projects easier to understand and try to get the main point across. What do you guys think?

**Comment by SparkTheDragon** [comment]
Like everyone else commenting here, I am writing about the"pie chat controversy". I immediately concede that pie charts struggle with showing precise data. Despite this flaw, I believe that the Pie Chart has its uses. If the data is simple and wanted to be compared and contrasted, a pie chart is great.

An argument against pie charts was brought up in a previous post. The poster claimed that pie charts cannot even a general sense of percentages. Another argued that adding numbers to the pie chart's interface is not friendly to look at, and can be confusing.

My response to both of the arguments is this: Both of those arguments commit the Argument from Incredulity fallacy. https://www.logicallyfallacious.com/tools/qa/Bo/LogicalFallacies
To commit a logical fallacy is to be definitionally irrational.

I read an interesting article titled "In Defense of Pie Charts" (Which I highly highly recommend you skim through.) In the article, it explains that some information is more immediately recognizable in pie chart form than other forms. The article argues that the purpose of the pie chart is not for pinpoint accuracy, but for getting a general feeling of proportions. I wholeheartedly agree with the author's arguments for pie charts.

If you only read this and decide not to read the article, let me post its poignant conclusion.

"I don't accept the information design dogma that pie charts should never be used. Pie charts have weaknesses but they also have many strengths. Put them back in your bag of tools and pull them out when appropriate."

Heres the article: https://www.neoformix.com/2007/InDefenseOfPieCharts.html

also here's a nice looking ![pie chart](https://user-images.githubusercontent.com/46506618/51810445-e29d7a00-2275-11e9-90b6-d1d75b9eaef2.png)

**Comment by NADGIT** [comment]
> My response to both of the arguments is this: Both of those arguments commit the Argument from Incredulity fallacy.

That's pretty daring talk for someone in reasoning distance.

Seriously though, despite the fact that I'm mostly in the support of the pie, I wouldn't say those statements are fallacious: they're subjective. I guess you could say that a person could "refuse to believe that pie charts can be aesthetically pleasing, and fallaciously state they are not", but that's really a stretch. I mean, if you respond the same way by saying that you think they look nice, then you commit the same fallacy because you're using the contrapositive of the same argument: "I believe that pie charts can be aesthetically pleasing, therefore they are." It's really just up to what you think looks nice or not.

I think that the pie chart argument really boils down to what you're trying to convey and what data you have. If you're trying to show the portions of funds split between 4 groups, then I'd agree with the article that defends pie charts and say that a pie chart would make sense. On the other hand, let's say you're trying to model the various languages of the Turkic family... [Good luck...](https://upload.wikimedia.org/wikipedia/commons/7/73/TurkicLanguages.png)

But the more I think about it, the more I just want a peaceful life advocating waffle charts, but it's too late for that now. [I started this war and now I don't even know what I believe anymore](https://static1.squarespace.com/static/554aeefae4b0253bf44442f2/56bce4d2859fd06c3afd86c9/56bce5933c44d80c62470a31/1455220116332/regret.jpg)

**Comment by ebeshero** [comment]
If I may wade in here a moment, I think the issue with pie charts has to do with optics and our visual sense of proportion. When you don't have many categories (or "slices") to compare, and those slices are *quite* sharply different, they're easier to visualize in a round. @frabbitry's point about the labeling is significant for people like me--and soon *us*--who make graphs--it's kind of a pain to make the labels readable when you have a large number of them circling around. But a pie can work when things are easy to read. I tend to like them when I can fit my labels *on* the plot without it looking crowded. I know, that isn't often. 

 But I think the waffle plots might be more interesting to check out--really! We might have an easier time recognizing area in boxes than circles...

**Comment by koshinf** [comment]
I may not have a ton of things to say on this subject, but the pic below is something that should be avoided at all costs.  Not only is it visually lying to the viewer by showing one disproportionately larger than the other, it doesn't even start at 0.  

![alt text](http://getdolphins.com/wp-content/uploads/2018/02/DG5UK_WUAAAVQe5.jpg "Don't do this.jpg")

**Comment by SparkTheDragon** [comment]
> > My response to both of the arguments is this: Both of those arguments commit the Argument from Incredulity fallacy.
> 
> That's pretty daring talk for someone in reasoning distance.
> 
> Seriously though, despite the fact that I'm mostly in the support of the pie, I wouldn't say those statements are fallacious: they're subjective. I guess you could say that a person could "refuse to believe that pie charts can be aesthetically pleasing, and fallaciously state they are not", but that's really a stretch. I mean, if you respond the same way by saying that you think they look nice, then you commit the same fallacy because you're using the contrapositive of the same argument: "I believe that pie charts can be aesthetically pleasing, therefore they are." It's really just up to what you think looks nice or not.
> 
> I think that the pie chart argument really boils down to what you're trying to convey and what data you have. If you're trying to show the portions of funds split between 4 groups, then I'd agree with the article that defends pie charts and say that a pie chart would make sense. On the other hand, let's say you're trying to model the various languages of the Turkic family... [Good luck...](https://upload.wikimedia.org/wikipedia/commons/7/73/TurkicLanguages.png)
> 
> But the more I think about it, the more I just want a peaceful life advocating waffle charts, but it's too late for that now. [I started this war and now I don't even know what I believe anymore](https://static1.squarespace.com/static/554aeefae4b0253bf44442f2/56bce4d2859fd06c3afd86c9/56bce5933c44d80c62470a31/1455220116332/regret.jpg)

I do not think to agree that I am committing the same fallacy as the arguments I argued against. If my assumption that the arguments stated that pie charts cannot be aesthetically pleasing or useful is fallacious. Just because they cannot think of an example does not mean one does not exist.

My reasoning that there is at least one example of an aesthetically pleasing pie chart, and that that pie chart was the best medium for portraying the data. I believe I have met my burden of proof by posting such a pie chart.

**Comment by ebeshero** [comment]
There’s an old saying that you can never win an argument over aesthetics. If this is simply a matter of tasteful aesthetics, we could argue forever without accomplishing anything but upsetting each other. I think I have to ask those continuing to post in this thread please be respectful. I am getting uncomfortable with the attack and defense positions around the word “fallacious.” I’d rather be seeing pragmatic discussion of what can be done to make a complicated set of data be legible and easy to read in a visual form. I doubt that any of you are substantially disagreeing with each other on the matter of legible vs illegible plots in pie or other form.

**Comment by ebeshero** [comment]
To be clear about my own position and experience on this, I think our article was a bit heavy-handed in its condemnation of pies, but it was worth bringing up that they can distort impressions of data and be difficult to read when there is a high number of categories to plot. They can be beautiful expressions of parts and wholes when there aren’t a lot of categories to compare. And I have worked with students on projects in this class to plot pies—Graveyard project was where we experimented with that. If it looks like a good way to visualize something, we’ll try it! But I don’t want to see us getting polarized into arguments when we really mostly agree on this. Can we move on?
