### ISSUE TITLE
Final Voting: Banksy Project

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#613]
Vote here your interest in joining the Banksy project by replying to this issue and indicating whether this would be your **first** or **second** choice. [Review the Banksy Project Proposal](https://github.com/ebeshero/DHClass-Hub/issues/609).

**Comment by alnopa9** [comment]
This is my **first** choice!
Going to try and do another sales pitch because I think this would be a really fun project.
Banksy is **anonymous**! No one knows who he is. He's a vigilante who fights the "man" with a spray can.
Banksy installed a secret shredder in a piece of his just in case it ever went up for auction:
https://www.youtube.com/watch?v=ekzjYZHs27E
Banksy speaking out against Zehra Dogan's imprisonment (she made a painting)
https://hyperallergic.com/432950/new-banksy-mural-mural-turkish-kurdish-artist-zehra-dogan/
And one of my favorites, Banksy made a theme park (Dismaland):
https://www.youtube.com/watch?v=V2NG-MgHqEk

**Comment by ebeshero** [comment]
Copying post from @abdual1100 on the Banksy Proposal issue: 
This is my first choice.

_Originally posted by @abdual1100 in https://github.com/ebeshero/DHClass-Hub/issues/609#issuecomment-458722433_

**Comment by BMT45** [comment]
This is my 3rd choice

**Comment by James-f117** [comment]
This is my 1st choice.

**Comment by frabbitry** [comment]
This is my third choice

**Comment by achen298** [comment]
third choice
