### ISSUE TITLE
Steve Ramsay: "The Hermeneutics of Screwing Around" and "In Praise of Pattern"

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#628]
Here's a reading and discussion exercise we'll be running for the next few days. Please complete your posts by next Monday, 2/25. Choose at least one of the following two articles by Steve Ramsay to read and discuss: ["The Hermeneutics of Screwing Around; or What You Do with a Million Books"](https://web.archive.org/web/20140604085234/http://www.playingwithhistory.com/wp-content/uploads/2010/04/hermeneutics.pdf) and /or ["In Praise of Pattern"](http://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1056&context=englishfacpubs).

* As you are working on and thinking about your projects and reading Steve's work, what do you notice about the way you're thinking about "doing research" with coding? 

* What do you think of Steve's perspective on "screwmeneutics" (for example) and the way we explore humanities with tech tools to find patterns? 

 @koshinf @SparkTheDragon @JAG240 @James-f117 @achen298 @abdual1100 @NADGIT @frabbitry @alnopa9 @KSD32 @BMT45

**Comment by NADGIT** [comment]
I'll be a little honest: I read the "screwmeneutics" article, and I'm not quite sure what the writer is trying to say. I understand that he is comparing the older forms of searching and browsing with their newer counterparts, and I think I understand that he is saying that there is a change from the traditional "search" and "browse" and its newer replacement, the community of sharing that is the internet. Is that right? It's a little hard to tell.

Also, I was thinking: have we truly seen the death of the anthology? I mean, search engines work on relevance and popularity as defined by an algorithm. What this means that finding documents is already predetermined by a procedural system and general consensus. So, in a way, we have might have ceased the study of compiling anthologies, but instead have begun studying ways to automate anthologies.

I think an interesting idea would be to set up a database that's just quickly scraped texts - no question to their purpose or relevancy to any topic - and simply have a user open up a random one. I think that this would be an interesting way to browse, since it would be a lot easier to find obscure works.

But I'm also secretly worried I misinterpreted the article and that my response doesn't apply at all.

**Comment by frabbitry** [comment]
I also read "The Hermeneutics of Screwing Around", and, once I got past the part where they were talking about the metric of measuring books by lifetimes (who's going to be reading a book a day at the age of three days old?), thought that it was an interesting read. 

Humans have been collecting things, even concepts such as information, since the beginning of time. Ramsay cites some of these collections in his article, but anthologies exist in the first place because people wanted to collect information. Books exist because people want to collect information. In the same way, databases, and the search engines used to navigate them, exist because people want to collect information. 

As people taking a class on the Digital Humanities, we're learning about ways to collect and classify information (and then, with this class specifically, represent that information on something like a graph). We tag documents to preserve aspects of a document. We tag documents to, in some way, store them. But are we storing the right information? Are we storing them in the right way? These are the kinds of questions that become apparent when you scratch the surface of this kind of research. Why are we even doing this? 

The prevalance of web companies that dominate users' viewing content using algorithms are scary, because suddenly people have the illusion of ingesting large amounts of information when in reality they're only viewing a carefully controlled, narrow scope of content. Polarization is then fostered by people who think that they are seeing the whole picture when really they're only seeing a slice of it, and this creates problems: segregation and division.

Do databases or websites monitored by tech companies provide only a limited view of information? Yes. Do anthologies provide only a limited view of information? Yes. Do summaries provide only a limited view of information? 

I thought that Ramsay was arguing that by nature the collection of information is going to be limited, and I would agree with him. The only thing that is changing here is the technology that we're using to collect and store information. Therefore, @NADGIT, I thought that your response was applicable, because of course search engines are collections of information like anthologies, and as such they're going to be limited. 

I think that the problem here then is not that using technology to store information is going to result in a limited view of information as a whole, but that we need to recognize that fact and deal with it. Perhaps this means that we catalogue information in a different way. Perhaps this means that we catalogue different information. Nevertheless, we, as humans, are going to want to collect and store information. We just need to, like the generations before us, be mindful of how we're doing it.

**Comment by abdual1100** [comment]
I also read "The Hermeneutics of Screwing Around", and I agree with @NADGIT  that the reading at first was boring about the measuring metric books with units about lifetime, I thought it was an interesting read. When I got to the part talking about "Screwmenuatics", I thought that it was different from his other perspectives on how people use tech tools these days to determine what is needed and what is not. Find ing tech tools that can help us with the technology we use everyday is tough because its hard for technology to say on top everything if we have people doing stuff that is triple amount of the information the day before.

Taking a class like Digital Humanities and working with our project makes us learn ways to collect and examine information on the other side. We question our selfs about what it takes to do the right information. Who knows if we are storing the right information as it all implies to coding. We've been doing programming that I thought was impossible to do.Being in  this class helped me to find out how to complete these tasks with just a regular laptop. Finding these patterns will result us to get better for the future but having the right tools with this technology will help us result is finding what is better for this generation.  Ramsey is this article, is trying to compare information and searches with old models vs newer forms/models. 

To me I thought Ramsey’s main argument is relating the collection of information we’ve been getting that is not being changed compared to newer vs older forms. It lets us be limited in stuff we don’t understand causing us to wonder if the newer forms are worth it spending the money on it or not. Technology is gonna be changing for the better or worse but its up to the people to see if they can handle it or not. The technology we have store, I believe that we will also have limited viewing as what we can view in the future. We as the population are gonna collect and store information every day and it is up to the technology to keep it going. That shows why Ramsey is worried about how everything is gonna end up if the technology is gonna slow down and the people are gonna keep sharing everyday. 
Technology is gonna change, we as the human beings have to be ready for it.

**Comment by achen298** [comment]
After reading the first one i totally agree with these guys. Nowadays our generation is falling into a trap where we don't need to process information at all unlike how it was back in the older days. We all believe that technology is the key to the future and it somewhat is true but technology depends on us humans and what we're capable of. Storing information is manual labor, we have to store it ourselves for the computer to know what is it. 

With our class, Digital Humanities, I'm pleased that we are learning how to do this by our own hands and that we don't need a lot more than just a program and a normal average computer to do it. Just writing code and able to apply that to store information in our computers will go along way in the future and thats what Ramsey is somewhat trying to say in the article if i understand it correctly.

**Comment by koshinf** [comment]
I kind of just skimmed the In Praise of Pattern one, mainly because of how it's written, couldn't understand what he was trying to say half the time.  From what I picked up though it seemed it was about how the ability to find patterns in the stuff you are researching is significant in finding all of what you need.  Kind of similar to our first exercises with regex and how we had to find patterns in order to determine what was what.  I noticed that I've learned a lot more about what I have been researching by setting up the parameters that will serve as the patterns to be found.

**Comment by SparkTheDragon** [comment]
> After reading the first one i totally agree with these guys. Nowadays our generation is falling into a trap where we don't need to process information at all unlike how it was back in the older days. We all believe that technology is the key to the future and it somewhat is true but technology depends on us humans and what we're capable of. Storing information is manual labor, we have to store it ourselves for the computer to know what is it.
> 
> With our class, Digital Humanities, I'm pleased that we are learning how to do this by our own hands and that we don't need a lot more than just a program and a normal average computer to do it. Just writing code and able to apply that to store information in our computers will go along way in the future and thats what Ramsey is somewhat trying to say in the article if i understand it correctly.

I disagree with you on this. I do not think it was a trap. Automating tasks only frees up time for more innovative work. I don't see what difference it makes whether technology is reliant on us because the alternative is for us to rely on us. Storing information is not manual labor, but it is a manual task.

**Comment by SparkTheDragon** [comment]
I somewhat read "In Praise of Pattern". It was a very very heavy reading, but the author said something that I thought of for a long while now. The author mentioned that discerning patterns of comedy and tragedy are not intuitive, and not useful. That if it is not obvious to the reader intuitively, then there is a problem with the statistics, not with the person.

I disagree with the author in this situation. I do not think that intuition should be a determining factor. That sounds absurd to me. If we all went on our intuition, we would believe so many false things about the world and would be worse off for it. Intuition is unreliable, and thus is a terrible mechanism to determine the truth. While the author disparages statistics, it is through science that we determine true and not true things. Unless I took the author out of context I fundamentally disagree with this point on this.

**Comment by KSD32** [comment]
For this I read “In Praise or Pattern”. The article was well written and touched on a subject that is important to researching while using any type of coding - patterns. Personally, when I research, especially in regards to the project matter for this class I try to look for any type of basic patterns. Sometimes those patterns are found on purpose and others by complete accident. When using tech tools to find patterns within humanities discipline, I think that it is good to go in with an open mind and be ready for anything that may come about.

**Comment by ebeshero** [comment]
Steve Ramsay and I have something in common--we're both people trained to study literature and we're both interested in using computers to help us investigate it. So for me, I take what he's saying as something I recognize and worry about, too. In "In Praise of Pattern," he talks about making network graphs of Shakespeare's plays--and  it might surprise you to learn that this is something you'll be doing shortly with student project code.  What does he mean by "graphing" those plays? Here's an example I dredged up from the interwebs--showing a network of locations in the play *Coriolanus*:

![https://texttechnology.humanities.mcmaster.ca/~texttech/ramsay_figures/plate_5.jpg]

Think of a play having scenes/distinct locations, not unlike the Pokemon universe or the movements of Ulysses around London. Steve was asking questions about how the action and events of a scripted play interconnect the locations in a fictional world. In a way I wish he had shown us more of that work in "In Praise of Pattern," but his emphasis here was in discussing *how to interpret* this kind of work and whether we should be relying on the evidence we're seeing to show us, well, how to *read* a Shakespeare play. He doesn't sound very confident that what patterns we produce with our computers can be taken as scientific authority. Then again, scientists will tell us that they rely on patterns too, and perceptions of "truth" emerge from consensus and reproducibility of methods. In Humanities (which is my home, after all) we're at home with the concept of *serendipity*. You've seen Ramsay use that word in both of these articles, and really his concept of "screwmeneutics" (based on hermeneutics, *the study of how we make interpretations*) is all about serendipity (the happy chance of stumbling on just what you need). Serendipity *seems* chancy, and I think several of you in this thread are expressing a little discomfort with that chancy-ness--that it's based on luck. Perhaps there is no luck--there are only ways of stumbling into a network of patterns after all.

Humanists (like me) are often okay with stumbling around in the dark with a research project, uncertain of what we'll find, but secure that we'll find *something* serendipitously worth sharing. I feel that way about the projects we're running this term: you all are investigating questions and questing for patterns, and I'm curious to see what we find out--but you should be aware of how you yourselves are constructing some of those patterns--setting the limits on what you're marking and where you're looking. Ramsay talks about sharing his work with people in a Math department, and he was a little scared because he's not a mathematician by training--he was also surprised that they were happy to *play* with this data and raise questions about it. It makes you realize that no act of interpretation is ever going to be the last word. You can keep on reinventing your tools and scopes you're using for investigation, and maybe what we're really doing after all is just screwing around to see what we can see. I'm okay with that--especially since I'm able to look around in more dimensions with help from my computer than I could just reading with my eyes.
