### ISSUE TITLE
Pushing / Pulling from GitHub Repos

### ISSUE THREAD

**Issue by i-myers** [ebeshero/DHClass-Hub#667]
I do not believe I've been added as a collaborator yet and need to be added as one. My username is @i-myers. @ebeshero

**Comment by ebeshero** [comment]
@i-myers Not so! You are already a full collaborator here, as I just tested here. The fact that I can “ping” you with the `@` symbol helps demonstrate one of the perks of membership in this repo. Also you were able to open a new issue here, which only a collaborator on this repo can do!

**Comment by ebeshero** [comment]
@i-myers Are you having trouble with pushing a file to the repo? Let JD know what trouble you are seeing...

**Comment by i-myers** [comment]
@ebeshero 

I am unfortunately. What happened is that I copied in my xml file to the sandbox. Problem is my CPU didn't seem to recognize it being there when I tried to copy my sandbox file from my CPU here to the DHClass-Hub here on Github. Did I have to make a repo first then copy my sandbox file to here or am I just missing something?

**Comment by ebeshero** [comment]
Hmmm. Tell me if I understand this right: 
* Have you cloned the DHClass-Hub to your computer so you see its file directories? 
* If so, did you do a `git pull` on the repo to pull in anything new? (your classmates have been pushing files recently, and you won’t be able to push anything new from your computer until you have pulled in their changes.) What happens when you `cd` to the DHClass-Hub and try `git pull` there? 
* Check and see: is your new file indeed saved in your local computer’s DHClass-Hub/Sandbox directory?

**Comment by i-myers** [comment]
@ebeshero 

I did clone the DHClass-Hub onto my computer, it is in my documents right now. Specifically in my Schoolwork folder.

I don't think I did do a git pull yet. Though now I'm gonna try it. First I should probably make my repository though for putting the sandbox file in it.

Yes, my I copied and put in my XML file which I'll use for this into my Sandbox directory. Though first I'm gonna make my repository then try the git pull.

**Comment by ebeshero** [comment]
@i-myers To pull and push from DHClass-Hub, first of all, you won't need to make a new Sandbox directory! But try this: 
* `cd` into DHClass-Hub and try a `git pull` to make sure you can pull in changes.
* If that is successful, save your new file into the Sandbox folder that is already in the DHClass-Hub.  You don't need to make a Sandbox directory because it is already in the DHClass-Hub. You just need to save a file into that directory.
* Once you have saved a file there, go into your Git Bash, and do the series of commands:
`git add`
`git commit -m "your commit message here"`
`git push`

**Comment by ebeshero** [comment]
@i-myers note: I just edited my post above, so take a look at it on GitHub. :-)

**Comment by ebeshero** [comment]
@i-myers I just logged in on my desktop here at home and pulled in your successful commit! Congratulations! You pushed your XML file to the Sandbox here on DHClass-Hub!

**Comment by ebeshero** [comment]
See https://github.com/ebeshero/DHClass-Hub/tree/master/Sandbox

**Comment by i-myers** [comment]
@ebeshero 

Thank you for all the help, I highly appreciate it a ton!

**Comment by ebeshero** [comment]
No worries! I renamed this issue and I'll leave it open for a bit in case others need similar help!

**Comment by ebeshero** [comment]
And thank you for posting--that's exactly what DHClass-Hub is here for!

**Comment by lmcneil7** [comment]
hello, I'm having a similar issue. I've put a file into the Sandbox of DHClass-Hub, but every time I use the command git pull, it keeps saying "already up to date". I've tried multiple ways in putting the file into the Sandbox, deleting the file and re-uploading and it's still not working. At this point I'm just stumped.

**Comment by ebeshero** [comment]
@lmcneil7 Did you figure it out? `git pull` will pull in any changes made to our DHClass-Hub in terms of files that the rest of us have been pushing. To push your own file, try doing 
`git status` to see if your repo is noting any changes. If you've saved your file in your Sandbox, you should see a change.
Then try `git add .`
and `git commit -m "your commit message"
and `git push` 
Hope this works!

**Comment by lmcneil7** [comment]
I think I did it now. I ended up just using a computer in the computer lab. I'm not sure why it didn't work on my laptop, but I'm pretty sure I did it.

**Comment by ebeshero** [comment]
If you have your laptop with you today, let's take a look at it quickly before or after class and see if we can figure it out...
