### ISSUE TITLE
UX Discussion of Digital Archive projects

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#668]
**Choose one** of the following digital archives to explore its features. Spend some time investigating until you're reading some marked-up documents on the site (a manuscript page or an historical document or a poem, etc), and think about how markup was used to design this. Then write a post on this thread that addresses:
1) something interesting the site is inviting us to explore about centuries-old texts, and 
1) the effectiveness of the user experience (“UX”) in discovering, reading, and learning about these texts.

Archives:                
                    * [Shelley-Godwin Archive: Frankenstein Notebooks](http://shelleygodwinarchive.org/contents/frankenstein)
                                    * [Map of Early Modern London](http://mapoflondon.uvic.ca/index.htm)
                    * [Emily Dickinson Project](http://dickinson16.newtfire.org/) (made by Pitt-Greensburg students in 2015-2016)
                    * [any documents in the Greco-Roman section of the Perseus project](http://www.perseus.tufts.edu/hopper/collection?collection=Perseus:collection:Greco-Roman), and explore the features here.

**Comment by i-myers** [comment]
So for this I will be going off the Frankenstein Notebooks, an archive detailing Mary Wollstonecraft Shelley's development of her popular novel _Frankenstein_. 

Now, this website opens up with really two major details along the front. On the top is a bit of information on the background of both the novel's planning and the archive's work itself. It goes into a ton of detail about how Mary got the idea of the novel but also all her publishing associates involved with the work. However, below this finely detailed biography of it is a timeline of the developments they have collected from MWS's collections. How first it all started out as just a mere draft, but with time and more writing she expanded her plans further into the finer details such as a more linear sequence of her work when she was finishing up the novel. This will lead me into the next part (and most important of all) that the archive itself has to offer.

Below this timeline are three volumes in which MWS wrote the book, volumes I, II, and III. Each showed different developments in many parts of the book. All the entries themselves show the specific pages in which the text itself was written. Along with all the revisions made as MWS was writing the storyline out. Now the unique part is that the archivists wrote out all the words as some of them are illegible to read. What is more important are how certain words are crossed out, italicized and bolded according to the meanings of the texts. Now the markup itself actually plays a very important part in allowing the reader to read what the page says verbatim. As her handwriting is quite slim, and not everyone can read it clearly. The digital markup itself allows the archivists to straighten out the page format exactly how it is shown in the actual page. Not to mention in showing all the exact words that are crossed out and replaced, in the same places they are written along the page. The coding markup even goes so far as to allow us, the reader, to view her previously chosen words along the sides of the page. If the markup wasn't used here, it would be very hard for the reader to make out what MWS wrote. As her cursive writing as stated before, is very slim and some letters are easily confused with others.

**Comment by bairjon** [comment]
I chose to look into the Shelley-Godwin archive: Frankenstein Notebooks.  The document opens up with a generalized details of the origin of the manuscripts as well as some of the timelines.  I do find it interesting how the mark up was with each page of the original manuscript.  I also find it interesting how difficult it must have been to translate and tag the original manuscript of the 3 volumes.  This is set up by the generalized details of the origins and then break it down into the manuscript and tags with each page. The effectiveness of the user experience is well as it states how many leaves in each manuscript such as c.56 consisting of 62 leaves, c.57 having 94 leaves, and c.58 having 30 leaves. Each part showed how the development of the volumes took place even though some of the leaves were not recovered.  Digital markup played a very big rule in all of this as it took something that is almost illegible to sorting it very neatly.  It also gives the user experience in the way it shows the original words, even the ones crossed out.  It would be very difficult if not impossible to the average reading without the markup revision of the manuscripts.

**Comment by ajw120** [comment]
I chose to take a further look into the Emily Dickinson Project. They begin their site on what seems to be an introduction page, establishing the meaning behind their project and what they are hoping to accomplish with sharing the material. They explain that they have went through and organized the original manuscripts of Emily Dickinson's poetry, this being before they were edited by editors and published to the general public. When going through their site, they had linked their repository for site visitors to look at and see how they had went with coding the manuscripts using XML. It was interesting to see the thoroughness that was put in to creating mark ups on the documents, as well as how they decided to make the layout of their project site. The mark ups were able to be so inclusive that the viewers and readers on the site can see the initial grouping of Dickinson's original fascicles (16 and 6), making the markups to be read in a clear and effective manor.

**Comment by amberpeddicord** [comment]
For this assignment, I chose to look into the Emily Dickinson Project. This is a project that looks at Dickinson's poems in *Fascicle 6* and *Fascicle 16* and codes variations in line structures both in Dickinson's original manuscripts and in published versions of the poems. 

What was immediately interesting to me was the way that the world allowed you to compare each edition of the poems directly. On the left side panel of the page for each poem, there is a list of each of these editions. When you click on one or a few of these, it brings up the poem line-by-line to showcase how each lines compare or contrast *directly*. This allows the reader to focus more on the details of line structure, which is the basis of the project. On the right side panel, they even included photos of the documents that they coded, which color-coded sections highlighted that match the highlights in their coded documents. Overall, the site is really well-thought out and organized.

This makes for a great user experience, as any information that a reader needs is laid out for them! Finding the poems themselves is fairly simple, and there are instructions included on each poem page that make navigation within poems even simpler. Because everything is arranged in a way that puts important elements beside on another, it is easy to compare the different editions. I really liked clicking through the site and seeing everything that they had worked on!

**Comment by lmcneil7** [comment]
For this assignment, I chose to look into any documents in the Greco-Roman section of the Perseus  project and explore the features there. At first glance, I see a list of all the documents and even further lists among some of documents similar to the outline in XML. The interesting part comes when you open up a document (fun fact: I didn't read that some of the documents were in Greek, so I got really confused when I opened up and saw no English).

Something interesting that I immediately noticed was this system at the top of the page specifying the text, chapter and section that you were in, highlighting it with blue. It stated "Your current position in the text is marked in blue. Click anywhere in the line to jump to another position." and offer other parts to click on. The reason I think it's interesting is that it takes centuries-old text and makes it available in a more modern way. It simplifies all the text into sections and chapters that we're used to seeing in archives. It helps to limit the text that you need and makes it easier to find specific information. Also, it would say "Click to jump to [blank]", telling you exactly what section that you would be going to, so if you wanted to confine you search to the public life of Cicero, it would tell which bar to push to immediately go there. The system is also present on the side as a view button which again is an interesting way to go through all that information. 

This makes it very efficient for the user experience to locate what they need without having to read an entire document. Not only was there a Table of Contents, but you could click on specific words to gain more knowledge on that specific thing. The system on text, section and chapter makes it more accessible to certain information and even limits what information you want to be looking at any given moment. Another thing was the XML document wasn't hard to read or analyze and even with a different language such as Greek, I was still able to locate the translation of the document into English. It's a easy digital archive while still containing a lot of information.

**Comment by jwa32** [comment]
I choose the "Map of Early Modern London" and I selected view page source to read the XML format of the page. I like how the easy to read and organized the page's hierarchy is due to its distinct start and end tags. This also helps people coding in XML to visually see how to code a document for public use on the internet. 


view-source:https://mapoflondon.uvic.ca/map.htm

**Comment by haggis78** [comment]
Taking the questions in reverse order:

I decided to have a look a the Map of Early Modern London project, since some of my work has looked at how geography and history relate. I started by reading a broadside, "The Severall Places where You May hear News", a little poem about the sorts of places where people gather and gossip. Each type of place is a hyperlink, so I clicked on "Alehouse" and it took me to a list of known alehouses/taverns/inns in early modern London. Some of these are identifiable on the Agas Map, an Elizabethan map of London, and clicking the link takes the user to them. I could even tell the map to highlight all the alehouses, and for good measure, all the churches at the same time! It seemed quite easy to navigate (the UX), at least as far as I went with it. A limitation, though: we know exactly where all of the parish churches were, because churches are well-documented and tend to stay in the same place for many centuries; but the same is not true of alehouses. Only some can be placed on the map: for the majority, there is only a name. Therefore, highlighting alehouses will not show their actual geographical distribution, since most cannot now be located.

In addition to the fact that one could have a lot of fun down this rabbit-hole, there is a very serious point: the historical and literary texts that we read referred to real places, and the people who wrote or read or heard these texts had mental maps in their heads. Even a silly ditty such as "The Severall Places where You May hear News" would have prompted the average Londoner to think of _her_ parish, _her_ tavern, _her_ local market. It reminds us that these were, in one sense, generic places -- the alehouse -- and in another sense very specific places, though different ones for different readers. Reading the text by itself today only takes us to the generic, but the MoEML reminds us that this was the granular stuff of people's lived experience.

**Comment by Bennediction** [comment]
I decided to focus on the Mary Shelley site. The most interesting thing that the site does is show different rough drafts of Frankenstein and the context behind each rough draft. This lets the user see the progress behind how Mary Shelley came up with the final draft of Frankenstein.

     The interface is effective in letting the user discover the information, at least in mobile view. The list of drafts is shown at the top of the page in the form of a timeline. It is well organized, easy to explore, regardless of whether the user knows what they're looking for. The only thing I can think of that may be worth adding is a text version of the older drafts due to their legibility.

**Comment by Bennediction** [comment]
I decided to focus on the Mary Shelley site. The most interesting thing that the site does is show different rough drafts of Frankenstein and the context behind each rough draft. This lets the user see the progress behind how Mary Shelley came up with the final draft of Frankenstein.
The interface is effective in letting the user discover the information, at least in mobile view. The list of drafts is shown at the top of the page in the form of a timeline. It is well organized, easy to explore, regardless of whether the user knows what they're looking for. The only thing I can think of that may be worth adding is a text version of the older drafts due to their legibility

**Comment by smdunn921** [comment]
I decided to look at the Emily Dickinson project. The homepage of the site gives information on what the site includes and what their goals are. They looked at Dickinson's *Fascicle 6* and *Fascicle 16* and looked at differences between the original documents and the other publications. The top of the page allows you to click to different sections, including an "About" page, the separate sections for the fascicles, the analysis, and a "Contact" page. When in one of the fascicle sections, one can select which poem they want to view and then get to look at the comparison between the different editions.

I know that @amberpeddicord has commented on it, but I agree that it's super cool that the user is able to directly compare the different editions of a poem. They can pick and choose which editions they want to view, and the site will highlight (the highlights are even *color coded!!!*) the differences in each of the editions all on the same page. And then, of course, there is the option to view the original XML of the page, which again is super cool. This seems to make for a great and efficient user experience in that it's not a hard site to navigate and the poems and their comparisons are beautifully laid out for the user to approach with ease.

**Comment by bobbyfunks** [comment]
I looked at the map of London site.  The whole site is very well organized and is broken down in a way that, no matter how specific the topic you are looking for, you will be directed to articles mentioning it in relation to early mondern london.  I've always liked maps but this is like a map on steroids. I started picking random topics and not only does show the location in early modern london but it brings up refrences in articles from the time.  I especially like the various XML versions because it gives great insight into how to organize the hierarchies in XML, which is great for this class!  This kind of map structure would be great for a any city around the world to get a real sense of the history of a place.

**Comment by lewisabia** [comment]
I read Frankenstein, or the Modern Prometheus. Something interesting about the site that invites us to explore about these text is how they show us the transition from the texts' draft to final versions. This site shows the actual images of the handwritten draft with actual edits by the author. This is interesting because the site wants us to explore the writing, since he author's hand-writing is mostly unreadable, it is translated into text form including the errors. The effectiveness of the user experience is evident here because by organizing the images and sections in a way that is visually appealing and also interactive like the various links, it makes the information more interesting and easily accessible.

**Comment by dylanmore** [comment]
I decided to read about the Map of Early Modern London. The site does a fantastic job of providing hyperlinks to different parts and pieces of what it is explaining, which redirect to other avenues of the site. The layout of the site is extremely effective as well, as it makes it easy to make it to anywhere on the site by one click of a button, instead of having to search through the whole site for a single piece of information. This is also where the hyperlinks come into play, as they use them when they mention new information, providing the links on their site to this information to learn more.

**Comment by ChinoyIndustries** [comment]
Okay, back from my radio silence here on Github, can finally add my comments here. As someone who's always loved staring into maps for hours on end I had to click on the "Map of Early Modern London" and go explore. Looking at the amount of interactivity they managed to cram into the Agas map of London, and the amount of external information they made accessible through it, I must say I was very impressed. The site has taken a scanned image and turned it into a map that can be navigated in ways that are Google-Maps-familiar, and cataloged the vast majority of the visible features on the map by type, allowing you to select any category of building or place; or to select any individual item, zoom to it, and see links to articles mentioning said item, provided in the form of a whole entire mini-encyclopedia explaining each item and small library of documents which refer to them. The work that went into identifying all these places based on external sources must have been immense.

The interface itself is exceptionally intuitive--as I had mentioned, navigating the map worked exactly as we are accustomed to online maps working--with color coordinated categories and plenty of cross-referencing to let you find everything on a particular item from any particular mention of it. I have one particular and very small complaint: in the map view, the order of the categories of map objects bugs me. They're almost in alphabetical order, but not quite, and things like "Non-Textual Markings" and "Transcriptions of Text", which seem more like metadata categories than object categories, fell right in the middle of the list instead of at the end, where I would logically expect to find them.

In any case, part of what appealed to me about this particular project is that it reminds me of all the possibilities there might be for implementations of GIS information--I took a class in ArcGIS several semesters ago and I miss getting to work with that kind of data--alongside XML, etc. in a digital humanities project. Besides that, it makes me think about what kinds of map data I have that I could work with in a similar fashion--for example, my 1889 Rand McNally "Railroad Map of the United States, Canada & Mexico", or the often-reprinted 1928 Railroad Atlas of the United States. Turning one of those a fully interactive online resource instead of a hard-to-find paper map or book would be very interesting.
