### ISSUE TITLE
A few issues when associating my schema 

### ISSUE THREAD

**Issue by amberpeddicord** [ebeshero/DHClass-Hub#672]
I'm working with the oxyMeta.xml file that Dr. B sent out, and when I associated my schema, it is giving me a few error messages that I can't figure out how to fix. 

One issue is that oXygen is marking all of the "line" elements (after the first one) and saying they aren't allowed. In my schema, I have this as far as this element goes: 

```
poem = element poem {line+}
line = element line {text}
```
```xml
<element att='1">....</element>

```

Also, in a few spots, it's marking the text as "not allowed". Is there any way to debug this?

**Comment by ebeshero** [comment]
@amberpeddicord To see your code better, I made it into a little code block, by putting three of those tick marks above and below it. (Click to edit your post to see how that looks.) Now, actually, those rules look fine to me because you have correctly indicated that you want one or more of `line` inside `poem`. Here's a question: Did you save your schema? In oXygen, if a file is unsaved, the little tab above it that shows the file name turns bold and has an asterisk after it. Do you see the asterisk? If so, save, and then click on the checkmark button again to refresh oXygen's validation of your XML. 

If not...hmm. Let me know and we'll take another look.

As for text not being allowed, that suggests that you need to include text in the content model of one of the elements in your schema.

**Comment by amberpeddicord** [comment]
@ebeshero Saving the file again worked! Thank you!

**Comment by ebeshero** [comment]
Yay! We'll leave this open a bit in case it's helpful to anyone else. :-)
