### ISSUE TITLE
the mongols

### ISSUE THREAD

**Issue by bobbyfunks** [ebeshero/DHClass-Hub#686]
I'm currently taking dr. aldous' history of the mongols class.  It could be interesting to categorize their timeline and places they conquered, weapons they used, major rulers, etc. There is plenty of online data available.   I'm not sure what kind of research question I'd be asking but their is plenty of information that is out there on the Mongols.  There would need to be maps, and dates and family trees to organize I guess

**Comment by alnopa9** [comment]
@bobbyfunks I like this idea! [Magellan Project] did something similar by marking up Ferdinand Magellan's logs on route across the Pacific Ocean and creating a map. You could use KML to make a map, but instead of pinpointing locations, you can have the whole area that's conquered be covered. A timeline for this would also be fun to do.

**Comment by ebeshero** [comment]
@bobbyfunks The Magellan project worked with an English translation of Ferdinand Magellan's logs, so I was thinking--what good texts might be available on the Mongols? There's a famous epic chronicle from the 1200s called (in English translation) *The Secret History of the Mongols* and I see there's a freely available open access version available online here: https://cedar.wwu.edu/cgi/viewcontent.cgi?article=1003&context=cedarbooks 
This is a PDF document and I think we can open it up and "scrape" the text from it to explore with XML. In a few weeks you'll be learning how to rapidly convert a regularly organized document like this into XML using "autotagging" so you don't have to do it line-by-line by hand, and we can get you started with that for a project fairly soon if this one attracts interest!

Now, I don't know whether you can easily make a timeline from this document by itself, since it seems to be a body of mythic folklore which tends to flatten/simplify time spans, but you could maybe investigate things like who were the celebrated heroes and villains in this epic? How violent is this history? How is the chronicle organized in time (as in, maybe, how many distinct historical events does it seem to be covering?)  How is the chronicle organizing space and time:  can we tell where events are taking place?

**Comment by ads171** [comment]
I'm in this class as well and I'd love to see this project when it's finished.  I have a map from his class that shows the basic outline of the empire but I'd be interested in more of the nitty bitty details of their empire, weapons, and logistics.
