### ISSUE TITLE
Schematron 2 HELP

### ISSUE THREAD

**Issue by CodyKarch** [ebeshero/DHClass-Hub#69]
I am trying to get to the `assert` that says you can not have content longer than half of the first content given, and the best I have gotten to is:
`<assert test="string-length(child::content[3]) not(&gt;) sting-length(child::content[1])">`
Which I believe says "the string-length of the child of content 3 should not be greater than the string-length of the child of content 1." ANY HELP??? I know I'm off, but how do I work towards what I want?

**Comment by ebeshero** [comment]
Hi Cody: I'm not in front of my computer right now, but just eye-balling your code, so fair warning about any code I try to type from the top of my head! But I notice a couple of things: 
1) remember, assert is supposed to tell you when a given condition is NOT being met. So don't you want your @test to be the opposite of what you're saying here?
2) I see a typo that could be giving you problems: you've got "sting-length" instead of "string-length" for child::content[1]

**Comment by CodyKarch** [comment]
`<report test="string-length(content[2]) &gt; string-length(content[1])">`
is the best I could make...  but for some reason, it was valid for any occasion. Help??

**Comment by CodyKarch** [comment]
Here's an update: 
`<report test="string-length(content [position()&gt; 2]) &gt; string-length(content[1])">`

**Comment by CodyKarch** [comment]
Well, I am not feeling good, so I'm going to go to sleep & as well, I'm going to hold off on submitting my work. @ebeshero I shall go look over this with you after class tomorrow to try and figure it out... Thanks for the help you gave....

**Comment by ebeshero** [comment]
@CodyKarch I'm still on France time, so I went to bed pretty early and missed the homework discussion of the 11pm hour. But I'm awake now and looking at this. You've found a good XPath function to determine the length of the article, but as @spadafour notes in the other Schematron issue thread, your formulation of it here won't work: string-length() needs to sit at the end of the XPath and doesn't wrap the expression. (Test out an XPath function first in the XPath window to make sure you're writing it the right way.)

But there are a couple of larger issues here:  First of all, there's an easier way to be sure you're testing on *any article that has an article preceding it*: Think about XPath axes.

Second of all, you're not just testing whether an article's string-length() is less than or greater than the preceding one. You want to constrain its length so that it is *never more than half the size of the previous article.* Think about a simple way to say that: it means the previous article can't be *less than twice the size* of the following article...And think about whether it makes sense to use assert or report, keeping in mind the difference between the two:

`<assert>` fires when a condition you express with XPath is *not* being met.
`<report>` fires when a condition you express with XPath *is* being met.

You could write your rule either way, but you need to think about how you want to say it.

**Comment by CodyKarch** [comment]
See, I would have used the preceding part like you suggested, but in the instructions, it says that would not work because there is nothing preceding the first article. that's why I was basing thing off of exactly the first one. 
And also, that phrase `can't be less than twice the size of the following article` doesn't seem to fit.. because with that, you'd be basing the first article off the following articles, and we don't want that, right?

**Comment by CodyKarch** [comment]
Here is the best I've probably come to... 
`<report test="(.[2]/string-length()) &gt;  ((.[1]/string-length()) div 2)">`
 And by the looks of the chatter on here, I may have to end up submitting this.

**Comment by ebeshero** [comment]
@CodyKarch I was in class, so I missed your posts until now, but in your second-to-last post here, you were wondering about why I was referring to how a preceding article couldn't be less than twice the size of the following article. That's another way of saying a following article can't be longer than half the size of a preceding article, isn't it? The first can't be smaller than twice the size of the next. The next can't be larger than half the size of the first. 

There's a way to make your context apply *only to the content elements that have no preceding content element*. Check out the discussion thread of Brooke Stewart and Rob Spadafore on this for more clues.
 https://github.com/ebeshero/DHClass-Hub/issues/70

Hope this helps!
