### ISSUE TITLE
Project Proposal:  The Size and distance of the Stars 

### ISSUE THREAD

**Issue by ads171** [ebeshero/DHClass-Hub#698]
I've always loved astronomy, it's fascinating to me.  One thing I love about astronomy is the sheer size of the stars and how our own star dwindles in comparison to others. I'm also fascinated by the sheer distance of how far our neighboring stars are from our own. I'd like to make a web page showing the stars and their respected size side by side to each other. I'd also achieve this by using household objects to represent said stars.  Better giving a  representation of just how much bigger some stars really are to others.  The same could be said about the distance part which will better represent how far other stars really are and show us just how big the known universe really is.

**Comment by haggis78** [comment]
That's an interesting idea. I wonder about the feasibility of scale. Not only because there are enormous numbers of stars, but because some are much bigger, or farther away, than others. A quick Wikipedia check shows that there are stars that are more than 1,000 times the diameter of our sun. So if you depicted our sun the size of a poppy seed, about 1 mm across, the smallest you can see on a computer screen, the largest known stars would have a radius of about 5 feet. Differences in distance would be much more extreme. 

There used to be a cool graphic you could find online called Magnifying the Universe, where you could use a slider tool to zoom in and out, all the way from atoms to galaxies. I just looked for it and it seems to be defunct, or I'd share it with you. That might be one way to handle it, though: you don't have to show the smallest and largest next to each other; you could click to zoom in and out by orders of magnitude.

**Comment by ghbondar** [comment]
What kinds of documents do you anticipate marking-up with XML? Remember that these are mark-up projects first-and-foremost... the website is for displaying the results of your mark-up, it is not the goal in itself.
