### ISSUE TITLE
Schematron Question

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/DHClass-Hub#70]
This may be an obvious question, but when using `report` does it fire as an error when the rule does occur? I know when you use `assert` it fires as an error because something doesn't comply with the rule. Is this the same for `report`? It's just confusing because it seems backwards to me.

**Comment by brookestewart** [comment]
Also, if what I asked above is true, I figured out how to get it to fire when the content is *less than* the previous content, but I can't figure out how to get the less than *half* the previous content. Any hints?

**Comment by spadafour** [comment]
I did some light googling, you can divide like this:
`div`
Here's an example:
`count(//node) div 2`
That just says get a count of a thing called node and divide it by 2.

And I think you are right about the report and assert functions. From what I recall, report says: 'report when this rule is happening.' Assert says 'Assert that an error is made when this rule isn't met.'

You might be running across a similar problem that I'm having: we need to do a count of all characters within `content`, but there actually aren't any characters there! They are all within the `p` children. How the heck do we do a count on all of that stuff? I'm sure its something that we've done before that I totally forget right now. Maybe you've figured it out?

**Comment by spadafour** [comment]
Well I think I already solved my issue; instead of running this:
`string-length(content)`
I used this:
`content/string-length()`

and that seemed to fix my issue.

**Comment by spadafour** [comment]
...maybe not. I keep outputting errors when I don't want them, and can't get them when I do want them. This is what I have:
`<assert test="(following-sibling::content/string-length(normalize-space())) &lt;= ((./string-length(normalize-space())) div 2)">`
So I'm pretty certain this says: Output an error when this is UNTRUE: the following sibling called 'content' is less than or equal to the current 'content.' The xsl I am running this on does meet the requirements (meaning tis rule should not fire), but it does for each `content.`

Any ideas?

**Comment by ebeshero** [comment]
@spadafour and @brookestewart Rob, you're correct about how you need to write `string-length()`. I was momentarily flummoxed by that myself, but I tested it in the XPath window, which is always handy when trying out a function in XSLT or Schematron.

With your assert test, I think you are telling the processor to test when the following sibling's content is less than or equal to half of the length of the current, and to output an error when that condition is not being met. The trouble is, in the XML document the `<content>` elements *are not siblings of each other* are they? They are not children of the same parent. When you run your assert test, the Schematron parser looks for `following-sibling::content` elements to compare, and failing to find them, issues an error on each one. 

So, what we need here is an alternate XPath, one that we haven't used very often, but it's good to know about and use in your project! Instead of working with the `following::sibling` (or `preceding::sibling`) axis, there is another way to look up and down and preceding and following instances of a particular node. You might be thinking you need to step up and look an ancestor article elements and down into content elements, but there's another axis to use that we have not discussed very much to this point. It's called the **`following::axis`** and it's mirrored by the **`preceding::axis`**. Read about them here, and notice how they are different from (longer than) `preceding::sibling and `following::sibling`: http://dh.obdurodon.org/introduction-xpath.xhtml#axes  (I discover, incidentally, that I need to add preceding:: and following:: to my "Follow the XPath" tutorial, so this is a useful reminder!)

With preceding::* and following::* we can look up at all prior or following instances of a node, including previous siblings and previous instances on elements earlier in a sequence. It's common to use this axis when you are hunting for all the prior instances of something like the `<content>` element in our homework example, when these are not all siblings of each other, but perhaps nested inside other elements that precede the parent of content in the document hierarchy. 

Okay, so I tried modifying your assert test, using `following::` instead of `following-sibling::`, and it *sort of* worked, but not quite. This time, with correct article input (nothing munged, each article less than half the size of the preceding), I had an unexpected error on the **last** instance of content. But there's nothing wrong with that content, so why should I get an error? Think about it: There is no following:: content to compare to, and lacking that condition, the last article's content will always fail our assert test. 

So, let's rethink this. We need to be comparing each article against something preceding it or following it. The first article has nothing preceding it. The last article has nothing following it. We need a schematron rule that **tests only the articles that we need to test**. We don't need to test the very first article, do we? (It can be as long as it likes!) The point of our test is to check the responses to the article, to be sure that each is *less than half the size* of the previous. That means, the content elements you're testing must be the ones that appear after some previous content, right? (There's a way to write that in XPath, of course, to *filter out* the content you don't want to test.) 

So...thinking about this again, and understanding that you want a different XPath axis because the content elements are not siblings, does this give you enough to modify your rule?

There's something more: You don't need quite so many parentheses: you can unwrap them. You're doing division correctly--good. We should probably make a list of simple XPath arithmetic operators, but as you discovered, these are pretty easy to find on the web: 
* is for multiplying (and that's the one I used for this solution!)
We'd want to use / for dividing, but it means a path step, so we use the word "div" instead
+ and - work for addition and subtraction.  

 If you need to divide by two, you've written that correctly. But you don't need all those parentheses. They don't hurt anything, but they're not necessary either and could introduce a source of error, making the code a little too brittle.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
