### ISSUE TITLE
Problem trying to get my ssh key on my home computer

### ISSUE THREAD

**Issue by ads171** [ebeshero/DHClass-Hub#702]
Everything works fine until I reach the "ssh keygen -1" part.  It says ssh protocol v.1 is no longer supported.  I'm following every step to my knowledge.  Sorry for the inconvenience.

Anthony

**Comment by ghbondar** [comment]
@ads171 It's a lowercase-L, not a one, but you can skip that step.
The next step is super important:
**ssh-copy-id username@firebelly.newtfire.org**

**Comment by ghbondar** [comment]
... of course, you would type:
**ssh-copy-id ads171@firebelly.newtfire.org**

**Comment by ghbondar** [comment]
from here, you can jump into the instructions for FileZilla.

**Comment by ebeshero** [comment]
@ads171 Did you get it working at your house? Let us know if you're still stuck...

**Comment by ads171** [comment]
I've been trying all week.  It's saying i'm logged in and I have to restart my Git hub like you would on step 5 of the instructions.  Even when I attempt to skip that step and go straight to ssh keygen -l it says host sever not available.  This is so frustrating to me because I can't bring my home pc in like I could with a laptop.   I was going to come into your office tomorrow and see what you think might be wrong.  I apologize so much for this, I know I have to do this, it's just frustrating to me because I don't know what's wrong and I don't want to bother you guys 24/7 on the weekend.
________________________________

**Comment by ghbondar** [comment]
@ads171 It's no bother. Instead of the instructions on CourseWeb, just do these:
1) open a NEW Gitbash shell (close any old Gitbash windows).
2) In GitBash, type: **ssh-keygen**
_This just created a new set of keys on **your computer** that you are using **now**._
3) In GitBash, type: **ssh-copy-id ads171@firebelly.newtfire.org**   
This will prompt you for your newtfire.org password.
_This is copying your key (named id_rsa.pub) from your computer onto your web space._

4) Now, open any file-folder in Windows. On the menu-bar, go to "View" -> boxes next to "Hidden items" and "File name extensions" must be checked.

5) Now, to use the keys to connect your local machine to the firebelly.newtfire.org server, **startup FileZilla**, then add your private key to the list of authenticated keys. To do this…
a) Go to FileZilla (on menu bar) -> Edit -> Settings…
b) Under Connection, click SFTP.
c) Click ‘Add key file’ to browse for your private key:
It will be in: C:\Users\(your username)\.ssh 
**Click the file named id_rsa**
_Do NOT select id_rsa.pub_
d) Click “OK” to save your changes.

5) Now, use FileZilla to connect to our newtfire.org web domain. In FileZilla, do this…
a) Go to File --> Site Manager
b) Under the “Advanced” tab, change the Server Type to Unix, and click the checkbox next to Bypass proxy
c) Under the “General” tab, add firebelly.newtfire.org to the host name, and change the Protocol to SFTP
d) Change the logon type to Key file, and enter your username where prompted.
e) You'll need to locate your private key one more time: 
It will be in: C:\Users\(your username)\.ssh 
and select your id_rsa key as you did before. 
_Do NOT select id_rsa.pub_
f) Click connect. You can access this SFTP site connection again, and give it a name over on the left-hand panel: we named our site connection "newtfire". Now you can transfer files easily from your local computer to the remote server.

**Comment by ebeshero** [comment]
@ads171 I logged in to take a look in your directory on newtfire, and I can see that you have already put several keys on the server already. You've been generating a lot of keys, and you probably don't need to generate any more of them.

The part I think you're probably stuck on is logging in with FileZilla. Can you set up the FileZilla connection and show it where to locate your private key? If you're having trouble, remember that 
* you need to be able to see hidden files on your home computer. See https://github.com/ebeshero/DHClass-Hub/issues/670 on how to do this.
* you need to be able to navigate and find where your .ssh keys are being stored on your home computer. You can find out exactly where in your bash shell with `cd` followed by the space bar, then return. (That takes you "home".) Then typ `ls -lisat` to see any hidden directories. You should then see `.ssh` and you can move in to find your private and public keys. Find the exact filepath with:
`pwd` (which means "print working directory"): that will give the filepath to the key file.
* FileZilla needs to know where to find your private key. You can copy and paste the filepath you found in the bash shell.
