### ISSUE TITLE
Error pushing to project repo

### ISSUE THREAD

**Issue by Bennediction** [ebeshero/DHClass-Hub#706]
Everytime I try to push my commits I'm faced with 
"$ git push
remote: Permission to ajw120/Undertale.git denied to Bennediction.
fatal: unable to access 'https://github.com/ajw120/Undertale.git/': The requested URL returned error: 403"

**Comment by ebeshero** [comment]
@Bennediction I'm taking a look now! Can you tell me if you've made a successful push to the repo since the start of the Undertale project?

**Comment by ebeshero** [comment]
@Bennediction The commit history on the Undertale web (remote) repo does not have any commits from you, so you must not have been able to push a commit for the project yet. I suspect this may be because you still are not an official member of the repo? I can't quite tell this because I'm not the owner of the repo. So we'll need to check in with Lexi!

@ajw120 We need to make sure @Bennediction is a member of the repo so he can push commits. Can you, as the owner of the Undertale repo, check on this? Here's how: 
* go to your web repo: <https://github.com/ajw120/Undertale> 
* click on the Settings tab (it's the tab on the far right with the gear that only you can see as the owner!)
* click on Collaborators (near the top): you'll be prompted to log in to GitHub
* Check to see if @Bennediction accepted an invitation to the repo.

If he did not, send him an invitation (and maybe also send him a quick message online to make sure he gets it).

If he *is* a member of the repo, let us know! There may be something else wrong that is preventing @Bennediction from pushing his files! We'll figure it out...

**Comment by ebeshero** [comment]
@Bennediction @ajw120 Did you figure out the problem and make sure Bennediction is a member of the project repo?

**Comment by ebeshero** [comment]
@Bennediction Apparently you were sent an invitation to join the repo (probably a couple of weeks ago) and needed to accept it. Can you see if you can find it in your e-mail? Look for ajw/Undertale or Undertale or messages from GitHub. And I'll see if there's a way we can find you the invitation link to join the repo again.

**Comment by ajw120** [comment]
I sent a new request Ben! Let me know if you get it or we can figure something out.
