### ISSUE TITLE
XPath: function and attribute at war

### ISSUE THREAD

**Issue by haggis78** [ebeshero/DHClass-Hub#716]
On Xpath assignment 3, I'm stuck on 2 b (and thus 2c and probably following). I can find the attributes well enough, but I can't successfully modify the query to search using name(). None of the following work:
```
//TEI//name(attribute())
name(//TEI//attribute())
```
or either of those using @* instead of attribute(), nor if I put => name() after an expression that previously worked to find the attributes. In both cases an error message reads 
```
Xpath failed due to: A sequence of more than one item is not allowed as the first argument of fn:name() (@role, @full)
```
The only part of this that I can understand is "Xpath failed", which is plain enough anyway!
I went through the newtFire and obdurodon tutorials, and I couldn't find anything specific about using functions with the attribute axis. No doubt I'm just missing some parentheses or something similarly simple, but the ducky and I haven't figured it out. What am I missing?

**Comment by ebeshero** [comment]
@haggis78 Indeed, if we enter your expression `name(//TEI//attribute())` or `//TEI//name(attribute())` we reproduce the error message you are seeing. This is because your XPath is saying, give me the names of this long sequence of attributes in the entire document. Remember `(//a//b)` is going to get you a sequence of one or more items, and when your sequence is lots of attributes, that's a big list. The `name()` function really can only handle one thing at a time, so it has to come at the end of an expression, or it is something you can use our **simple map** `!` operator to handle, since this indicates handling just one thing at a time: 

`//TEI//attribute() ! name()`
or
`//TEI//attribute()/name()`

should work! Try them and let me know if they don't. (They worked for me just now...)

**Comment by haggis78** [comment]
Thank you. Perhaps this "simple map" use of ! was gone over in class and I missed it -- it isn't in either newtFire or obdurodon. Or is it just time to invest in the big book?

**Comment by haggis78** [comment]
Nevermind - finally found ! on DHClass-hub.

**Comment by ebeshero** [comment]
I modeled the simple map `!` in class on Friday. For me, it's sort of interchangeable with taking another path step. It's not on my XPath tutorial because I learned it after writing that, but it's probably time to update it. The big Michael Kay book doesn't have it--it's a little too old for that. (It's about the XPath and XSLT 2.0 specs). Unfortunately, Kay says he won't write another book--but that just means we look stuff up on tutorial sites! And thanks for reminding me that I did already write it up here:

https://github.com/ebeshero/DHClass-Hub/wiki/XPath-Simple-Map-and-Arrow-Operator

**Comment by haggis78** [comment]
Another attribute question, on XPath 4, questions 3b-c. I've located the Fridays, circled back up to their parent node, and I know the name of the attribute. But what I can't find on the various tutorial pages (or by searching elsewhere on line, so far) is how to have it deliver back the _contents of the quotation marks that follow the attribute name_. If I knew that step, I could probably figure out how to get the distinct-values. What am I missing?
