### ISSUE TITLE
Seven Days of GitHub

### ISSUE THREAD

**Issue by alnopa9** [ebeshero/DHClass-Hub#740]
# [Seven Days of GitHub](https://newtfire.org/courses/dh/CDVSyll.html#d2020-01-13)

On the syllabus, there is a week long assignment called **GitHub Practice**. This requires you to create your own personal repository! With this assignment, we hope for you to familiarize yourself with GitHub and Git by pushing to your repository and the DHClass-Hub at least once a day for the week.

Remember!

**Always pull before you push**

**Comment by alnopa9** [comment]
@ChinoyIndustries @smdunn921 @amberpeddicord @bobbyfunks @lmcneil7 @benjaminc2020 @Bryant-LettucePrime @biancamaginley @robftg @frabbitry @BMT45 @ebeshero 
👀 👀 👀 👀

**Comment by frabbitry** [comment]
Just a few quick tips for any who might be interested: 

- The Sandbox folder is a great place to put random files (memes, pictures, Powerpoint Slides you used for a class in High School, etc.) on the DHClass-Hub repo for this assignment. 
- Also (and the following steps should be done from within the repo you're interested in pushing a file to):
1. `git pull`
2. `git status` (should present your changes in red)
3. `git add . `
4. `git status` (your changes should now be green)
5. `git commit -m "your commit message here" `
6. git push
7. Some of you haven't changed your git config files yet, so you'll be asked for your GitHub username and password. Go [here](https://dh.newtfire.org/explainGitShell.html) for instructions on how to add your account to the config file, which will mean that you won't have to type your username and password in every time you try to push something. But just enter them in for now so that you can push.
8. Voila! A file should be added.
