### ISSUE TITLE
Discussion: Past Student Projects (UX and Research Directions)

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#743]
Choose to explore and discuss one of the following project sites developed by students. A few of these are undergoing continued development this semester!  Describe (in your own words) at least one significant topic it seems to be exploring, and reflect on what research the developers might want to investigate next, the UX of the project site, and/or what ideas it inspires for new projects. In a gentle, constructive way (realizing that project developers may be monitoring the DHClass-Hub), you may comment on issues or problems you can see with these sites. Those of us (instructors and returning students) who have been involved in these projects should help introduce them to our class and point out things that need work.

* [Ulysses Project](http://ulysses.newtfire.org): (developed by @frabbitry and team: a study of how James Joyce's *Ulysses* associated various locations in the city of Dublin with literary and mythic allusions. Creates a map as guide to parts of Dublin that are associated with passages in *Ulysses*.)

* [Banksy Project](http://banksy.newtfire.org/): (developed by @alnopa9  and team: a gallery and study of the works of the artist Banksy, where in the world they are distributed, and what media forms they have taken.)

* [The Hamilton Project](http://hamilton.newtfire.org): (Greensburg project with lots of network visualizations and a graph of motifs and their frequency of repetition in the musical *Hamilton*)

* [Profanities in Quentin Tarantino's Screenplays](http://bamfs.obdurodon.org/index.xhtml) (Pittsburgh student project, with network analysis of offensive language spoken by/to male and female characters)

*  [Divergences in Machine Translation: Examining Harry Potter texts processed by Google Translate across multiple language families](http://translate.obdurodon.org/): (Pittsburgh student project)

* [La Lega Toscana Protezione](http://toscana.newtfire.org/) multi-semester Pitt/newtfire project by @zme1 studying English-Italian language adaptation and membership in a Pittsburgh Italian society, with a terrific range of graph types.

@ChinoyIndustries @smdunn921 @amberpeddicord @bobbyfunks @lmcneil7 @benjaminc2020 @Bryant-LettucePrime @biancamaginley @robftg @frabbitry @BMT45 @ebeshero

**Comment by frabbitry** [comment]
Anyone who goes over the Ulysses Project can feel free to absolutely rip it to shreds. I might be presenting it at a conference and need all of the feedback I can get. 

That being said, I know that most of the website needs to be updated to match the "theme" that's going on on the home page and some of the works pages. Consistency in design is important with any website.

**Comment by ebeshero** [comment]
Well, be kind, everyone! Keep in mind that some of the developers are working with you this semester--but yes, that's exactly why *real, honest* feedback is important. There is much to admire in each of these projects, as well as much to critique, and these are some of them (like *Ulysses* and *Banksy*) ongoing works in progress.

**Comment by benjaminc2020** [comment]
The project I reviewed was the La Lega Toscana Protezione. The purpose of this project is to show transcripts of documents, data, English loanwords, and statistics that relate to the Tuscan League, a beneficial society from 1915 until 1971, made up of Tuscan immigrants that moved to Pittsburgh. The appearance of this site, right off the bat, is elegantly designed. I think the project members did an excellent job making use of contrast, font choice, and color themes. 

The Anglicisms tab provides insight into a wealth of data visualizations and graphs pertaining to the project research. I thought this was laid out well. Being that this is a research project, this website does an amazing job of providing information about anything and everything relating to the Tuscan League. In my own opinion, the amount of information offered is almost overwhelming. This project requires an extensive amount of reading to understand what you're looking at and what the graphs mean. If the website could be improved, I would suggest adding shorter graph descriptions.

I suppose the developers could research more into this project by providing either more information about the Tuscan immigrants before moving to Pittsburgh and the current status of the Tuscany residents. Overall this website is really cool and leads me to contemplate other types of projects that could run parallel to this type, such as information about other languages, like american sign language and its prominence in the areas of either the U.S. or PA.

**Comment by smdunn921** [comment]
@frabbitry don't worry i got your back and looked a bit at Ulysses! :eyes:

It generally is pleasing to the eye and i enjoy that on the home page i get to scroll and read a brief description on each section before i click it. UX-wise, I think it's a little wack having the links to image sources unable to be clicked on the page, so you might want to make them clickable. I enjoy getting to hover over different sections of the About page to get more info. 

Right near the top of the site, the goal is mentioned, stating "With the Ulysses Project, we are attempting to examine how James Joyce recreated the city of Dublin in Ulysses using allusions." So right at the beginning they have stated what they were looking at, and there are sections about their graphics and methodology, with the actual texts having a way to color/style "people, allusions, reference, and said" though it does not state what this means or have colors/styles up in the "click to highlight" box to let users know which is what. 

The graphics section maps settings and has heat maps based on allusions, though this does not seem like it is completely finished because some of the sections are missing info, though this seems to only be in the first section (The Telemachiad). The background of each of the sections shows the heat maps being talked about. A normal map in the locations of each section, heat maps which display the concentration of the allusions on each of the maps, and a network map relating the allusions and locations are featured in each of the sections as well, which does seem mega cool and they all have a brief description by them talking about what each of them are and what they found through it. The network graphs seem to have a lot going on but the magnifier on it makes up for it to be able to see what is going on in any given section of it, though it is a bit difficult to read the small print sometimes even with the magnifier.

**Comment by lmcneil7** [comment]
I chose to explore and discuss the Profanities in Quentin Tarantino's Screenplays Project!

One crucial topic this team seems to be exploring is the usage of profanity between male and female characters. As they mention in the section explaining their research question, they hypothesize that men would use profanity more in their dialogue while women would use less. I think it's an exciting topic to explore because it does show the director's bias (if he believes profanity is unfeminine) and the effect that profanity has on characterization. The slurs used as well, but I think they missed an essential part of slurs. Slurs are only slurs if used in a derogatory way. Meaning a black person saying the n-word stops it being a slur word, which I think should be added into the final number or mentioned in conclusion. If a black person says the n-word, it becomes profanity.

One thing that the developer could investigate next is the effect of the profanity on emotions. Another idea is the usage of profanities. The impact of the swearing on emotions could be talking about which emotion each character has when told a cursing, ex: Anger or sadness. You could also track which feeling the person cursing has when they say the curse word.  The usage of profanities is why they're cursing. For instance, they're cursing to incite a fight. Ideas that they give me for other projects would be to choose a movie and to track something they do a lot in the film.

UX Experience: The site looks pretty cool, and I like the network map. A suggestion would be to add other visuals to the website as a whole. I would also suggest that you used a different font for the headings when they're red.

**Comment by bobbyfunks** [comment]
I looked at the Hamilton project.   Overall it was a great site.  It was easy to navigate and had lots of information about the musical. Hamilton.  I liked the character section that gave general stats about each character, and people mentioned.  Perhaps a little bio excerpt to go along with each character that could get one.  And a picture of the character, both a real and a in the show pic to go along would help familiarize people with both the actual person and the character.

The graphics section had 5 different visualizations.  I enjoyed the map of places mentioned in the show and the line graph of repeated phrases.  These were the easiest to read.  The bar graph of fact, fiction, and ambiguity in the lyrics is an interesting take on the script, but since the ambiguous portion is the vast majority it was not as visually appealing as the others.  The  network analysis of speakers and references was kind of a jumble visually but had good information.  The timeline could be enhanced by making the indicators a little bigger, especially for the smaller outliers.

Overall it was great.  I liked the song index page, with the links to different pages and the music, obvi.

**Comment by Bryant-LettucePrime** [comment]
The Banksy project is really damn cool.

It basically synthesizes info from a few different sources about his work, places it all in a fun little gallery, and offers brief descriptions of each piece, as well as whether it's still around.  The whole feel is appropriately urban, with a stark red/white color scheme, fun typefaces, and fancy Javascript cursor shenanigans.

The functionality of the site is especially impressive.  It features a Google map embed curated with Banksy's tags, a timeline of his work that accesses the relevant pages of the site, and really stylish links to every individual team-member's Github.

If I had to critique:
- The visuals on the analysis page are really really small.  One needs to open in a new tab and even still the resolution is tiny.
- Images turning white and displaying the name when I mouse over them is cool, but also a lil' annoying and impedes functionality.  Maybe something a bit more subtle.
- This last one might be super nonsense, especially because you've gone to all the effort to implement a timeline, but I kinda wish the galleries were grouped chronologically instead of alphabetically.  I think I'd understand Banksy a bit better if the layout of info on the page naturally marked the state of the world and of his most incendiary political opinions at the time.  Your mileage may vary on that, though.

Overall, I really liked the website and it makes me excited to start!

**Comment by amberpeddicord** [comment]
I looked into the La Lega site! 

The site contains a lot of historical background--which is important for the nature of the project and for the nature of the class that the research comes from--so it is at first difficult to find the graphics and digital aspect of their project. This is something that I would fix in the future of the project. However, to their defense, the graphs are incorporated well onto each page, and correspond with the background of the members/organization. So, maybe this is just a "me" issue.

That being said, I love the amount of information and graphs/graphics that they included! They covered a *lot* of background and data on the Lega Toscana. It's clear that they put a lot of work into their project. In addition to that, their graphs utilize a lot of javascript to include even *more* information. This is something I'm trying to learn how to do better for this semester, so seeing the way that they used javascript to show/hide details about the graph is great!

**Comment by zme1** [comment]
@amberpeddicord One problem we consistently faced in our project development was the ongoing attempt to reconcile usability/legibility and informational richness from our research. In a lot of ways the Toscana interface can be seen as alienating, especially in terms of the information presented on a single page with no easy way to navigate the information at a glance. One thing for you and @benjaminc2020 to think about with your own projects is how to consolidate your own findings, maybe to simply show your research in more bite-size or user-friendly ways so that our audience can more easily grasp what your research is about.

**Comment by amberpeddicord** [comment]
@zme1 Noted!

**Comment by ebeshero** [comment]
Hi @zme1 ! For those wondering, @zme1 is Zac Enick, the developer of the Toscana project! We have some long-standing members of DHClass-Hub who will take note when we're conversing about their projects. :-) Thanks for this wisdom, Zac!

**Comment by biancamaginley** [comment]
I looked into the Ulysses Project! 

I thought that the home page was super cool, you don't see the links to other parts of the website like that very often. The graphics looked good, and it was cool that it was the same scroll format as the home page. 
The critiques I have are small and just based on the look of the site. The chapters page looked like it was unfinished. The whole site has so much detail but the chapters page is a little rough. I do really like the individual chapters though. Its convenient to be able to highlight the characters and Allusions. Also, in the individual chapters, the side bar blocks the tabs at the top of the page.
