### ISSUE TITLE
Project Proposal: Alicia: My Story

### ISSUE THREAD

**Issue by biancamaginley** [ebeshero/DHClass-Hub#752]
Alicia: My Story is a book that was written by Alicia Appleman-Jurman, a holocaust survivor. She wrote about her personal experience from escaping the Polish Ghetto to marrying her husband, Gabriel. I would like to take that novel and both connect her experiences with what was going on around her at the time, and make a visual to show where she was. We would obviously use the book itself as one of the main sources, and she has also made some videos talking about courage and many other things she thinks are extremely important.

**Comment by ebeshero** [comment]
@biancamaginley We'd need to work with an online text of this, and we'd probably be facing the same copyright restrictions as with the Dune proposal. But it's possible if there is a digital copy available that we mark it up in private and process and visualize the data in public view. That's not really ideal for our work, since we do want to share the data publicly. 

Can you think of an alternative project with openly available text resources online that we can work with?
