### ISSUE TITLE
SVG HW 3: Sorting on the X-Axis

### ISSUE THREAD

**Issue by spadafour** [ebeshero/DHClass-Hub#76]
I've got all of my bars correctly charted to the y-axis, but I'm having issues with my approach to sorting. I don't really know what angle to take. Right now, I'm just outputting the `position()` times an interval, but this creates 2 problems: I'm outputting blank space for the 2 questions with different answers, and they aren't easily sorted with my setup.

I know that I'll have to get a count of the `@n` value and make a sorted list out of that, but how am I converting that to points along an axis? Any hints for this one?

**Comment by ebeshero** [comment]
@spadafour Hi Rob! You should make a point of excluding those two questions that don't fit in your graph--that is, get the XSLT parser to select only the <fs> elements that feature the Yes or No answer questions. That way you won't generate those blank spaces.

For sorting, that's kind of up to you--you can sort your bars on whatever survey response looks interesting to you... but first of all, see if you can get the right output, and then see if you can get something to sort...

**Comment by ebeshero** [comment]
@spadafour As for the other part of your question: You'll be using sum() much as you did with XSLT Exercise 3 (so you might want to review your XSLT Ex 3 file)--but you'll do something more. We're asking you to plot a percentage, not the literal numbers (and that's to deal with the problem of having different total numbers of respondents for some of these. So, you need to calculate percent values, and that'll play in to how you scale your X and Y axis, creating a plot based on 100 (or 100 * some scaling factor).

You want the position() for  one coordinate, yes, and for the other, you need to calculate a percentage for each response to a particular question. So, the percentage of "Yes"es would be: the `@n` for Yes divided by the sum() of all the `@n` responses to a particular question, and multiple that result by 100. 

That value is going to have lots of decimal places after it, which is just fine for plotting your bars. But if you want to output the percent value as, say, a label on each bar, you'll want to try a function we mention in the assignment sheet to either limit the number of decimal places or round up to the nearest whole number. Hope that helps!

**Comment by spadafour** [comment]
Well as far as omitting the 2 questions without Yes or No responses:
This is the XPath that I've used to find it:
`//f[@select="Yes"]/parent::*`
but I am not able to match on this in my XSLT; it says:
`Unless XSLT 3.0 is enabled, the only axes allowed in a pattern are the child and attribute axes`
so I'm not entirely sure how to correct this. That's why I continued to write my rule with a simple match on `//fs` until I could figure out how to solve it. Is this an issue with the way I'm calling this?

**Comment by ebeshero** [comment]
@spadafour Apparently the "pseudo-XPath" pattern matches on `<xsl:template match="stuff">` are a little more restrictive in XSLT 2.0 than 3.0. So in 2.0 the XSLT parser doesn't understand how to find the parent:: axis (just on *that* attribute because it's not a literal XPath). Apparently it would be fine in version 3.0, so you could go look up how to set up your stylesheet in 3.0, but there's really no need to do that. Can you write your own expression a different way, so that the element you want to find is not sitting at the end of the expression? Hint: you've done this a lot before. Double-hint: Use another predicate.

**Comment by spadafour** [comment]
Ugh, I figured the first part out, I way definitely overthinking that one, thanks.

**Comment by spadafour** [comment]
Also: I've already solved all of my y-axis stuff, so graphing with percentages wasn't an issue. I'm just figuring out how to plot my sorted percentage bars. I'm not sure how to convert that sorted information into something I can multiply by an interval. I'll poke around with it, but I'm just not sure which angle to tackle this at.

**Comment by ebeshero** [comment]
@spadafour You should probably apply the sort as the last thing you do, after you're outputting each of your bars. If this helps, the sort should determine the output order of all the bars on the graph. (I'm not sure what's giving you problems with the sort, so I'll wait for clarification.)

**Comment by spadafour** [comment]
This is what I'm playing with:

`        <xsl:variable name="xSort">`
`            <xsl:for-each select="fs[.//@select='Yes']">`
`                <xsl:sort/>`
`                <xsl:value-of select="fs[.//@select='Yes']//@n"/>`
`            </xsl:for-each>`
`        </xsl:variable>`
`        <xsl:variable name="xPos" select="$xSort/position() * $Interval"/>`

`xPos` will be my variable for both `x1` and `x2` for my bars. I'm using a separate variable named `xSort` to play around with a means to actually do the sorting. `xPos` is where I can hopefully multiply the position after sorting by my `Interval`. It's not working right now (outputting the value of my `Interval` only, probably because the `position()` is always 1. I'm not sure how to turn that sorted list (which I'm not sure if that is firing properly, either) into a value that represents its position in that list.

**Comment by ebeshero** [comment]
@spadafour Ha! I'm curious about how you'd use the results of a sort *as* a variable...You'd need to *call* the variable with xsl:value-of to see if it's working as you want it to. (It probably will output a list of sorted values of @n. But you might be using a variable in a way that's creating *more* complexity rather than less...You want to write variables when you want to give a complex thing a simple name so you can quickly call it later, so that works for things like $xPos and $yPos and $barSpace. There might be occasions to store a series of values inside a variable so you can loop through them, too. But I don't think this is one of those cases.

Think of the <xsl:sort> as something that needs to happen at the moment when you first call for all your output to be generated. You will only need to call it once in the whole document, and when you set the value on which you want to sort, what should happen is that all your bars reshuffle their position based on whatever value you select to apply your sort to, and what order you set on the sort.

**Comment by spadafour** [comment]
So what I should do is go back to defining my x-Axis Position as `position() * $Interval`, and then when I use `xsl:apply-templates` for outputting my bar graph, I should use `xsl:sort` inside of that? And then that `sort` will override the initial `position()` of the 'fs' in the document and redefine it?

**Comment by spadafour** [comment]
Yep, that works, thanks

**Comment by ebeshero** [comment]
:+1: Yay! good.

**Comment by ebeshero** [comment]
Probably let's leave this open a few days in case anyone else needs to read it!

**Comment by ebeshero** [comment]
@spadafour Rob: go read my comments on your SVG Exercise 2 (in Box)--about that experimental way you found to automatically mark the Y axis. That was really cool! And yes, there's a less brittle way to do it.

**Comment by CodyKarch** [comment]
Hey @spadafour , do you think you could comment on my issue how you figured out the height of your bars? I understand how, I just do not understand the format for it.
