### ISSUE TITLE
Steve Ramsay: "The Hermeneutics of Screwing Around" and "In Praise of Pattern"

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#766]
Here's a reading and discussion exercise we'll be running for the next few days. Please complete your posts by next Monday, 2/24. Choose at least one of the following two articles by Steve Ramsay to read and discuss: ["The Hermeneutics of Screwing Around; or What You Do with a Million Books"](https://web.archive.org/web/20140604085234/http://www.playingwithhistory.com/wp-content/uploads/2010/04/hermeneutics.pdf) and /or ["In Praise of Pattern"](http://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1056&context=englishfacpubs).

* What do you think of Ramsay's perspective on "screwmeneutics" and finding patterns in texts? 

* What kinds of patterns was Ramsay exploring with StageGraph? What could those stand to show us about Shakespeare's plays?

* As you are working on and thinking about your projects and reading Steve's work, what do you notice about the way you're thinking about building your project and "doing research" with coding?

**Comment by ebeshero** [comment]
(I've edited the post to improve the discussion questions.)

**Comment by lmcneil7** [comment]
I decided that it would be beneficial to read both articles since I couldn't remember  _ "The Hermeneutics of Screwing Around; or What You Do with a Million Books"_ mentioning anything about StageGraph. 

Honestly, on my first read-through, I didn't understand "screwmeneutics" and what it was. However, skimming through it again, I came to the conclusion that a lot of what he was saying made sense. First, he points out that the relationship between "books" and "knowledge" and how it can never be equal. At one point, maybe, but now there's no way of keeping up with all the books created as there are bound to be books that go unnoticed or read. Our knowledge will never accurately represent everything that's in existence. And yet, that's how we grow. It's that limit that leads us to the creation of bibles and other similar texts. As in Steve Ramsey's words, "It is, after all, at the end of history that one undertakes summation of 'the best that has been thought and said in the world' (190)". It's accepting that limit by using our knowledge to create more. When we believe we have reached the end, instead of filling in the gaps and searching for what we haven't found, we create more to continue forward. 

Now, what I did understand for the first time around is StageGraph. StageGraph is a tool that helps with defining the vagaries of text, works, etc. For example, he talks about Shakespeare. He uses vague wording like "another part of island" or "a room in the palace." Here's what he has in mind versus the many ways it could be. StageGraph is a tool to analyze the many different ways the setting could be and present them. It adds the coding to the English. It focuses on making graphs of Shakespeare (ex. locations) and analyzes the similarities and differences. StageGraph also allows for a subgraph of the characters' movements as well. One could even make a graph that it's interconnected; for example, giving one each color like red and yellow and then making the color change to orange when they're in the same location. One of the major issues he faced was what's concrete "interpretative" evidence.

When I compare this to _Teen Titans_, it's almost on par with what I imagined for the project. It points out how to create a precise mapping of Shakespeare's plays while also discussing the characters' movements. It's beneficial in understanding the implications and issues that I need to consider for my project. Steve Ramsey also addresses the problems that we will have about Teen Titans: it's mostly our interpretation. However, it makes good points about what's wrong with the argument and using it as evidence. Both articles were interesting and will be helpful in the development of our website.

**Comment by amberpeddicord** [comment]
I read "The Hermeneutics of Screwing Around", and I really like what he says about browsing and "screwmeneutics", especially with how it relates to the Digital Humanities.

 With many projects, there's always a strong knowledge of the enormity of information and only so many people who can dedicate their time to it. Thus, the goal becomes finding a way to parse through this information and notice the various paths that exist within it. Reading this immediately made me think of the Digital Mitford Project. With projects like Mitford, that seek to create a digital archive of a writer's work, there are enormous amounts of information that need to be coded and worked into the final database. As Dr. B says, "I'll be working on Mitford until I die." However, the project has succeeded in finding these paths that work their way through large amounts of text and information. Within the project, there are people working specifically on Mitford's plays, her letters, her novels, as well as tracking and accumulating the references she makes *within* all of those. 

Looking at the project's logo, which shows puzzle pieces representing the different aspects of Mitford's life and work, the goal of the project can be seen. It is less about just digitizing a large amount of information and more about bringing together different tracks of Mary Russell Mitford's life. With many digital projects, there is a similar need to tie together loose ends of a bigger project. If you are faced with "a million books", you're going to read the ones that are important to you, whether that means a greater purpose, or just "screwing around" and finding ones that you enjoy. As projects progress, you pick up more loose ends and things that you didn't even know you needed to know, and you must find a way to incorporate those into the roadmap of the project.

**Comment by robftg** [comment]
What I found interesting with "The Hermeneutics of Screwing Around" was how it was all viewed with a closed mortality to it. Where everything was brought up as a list of books to read within ones' own life. Ramsay was exploring the idea that it isn't the experience one gains from reading the book itself but the knowledge one comes out with after reading the book. Where if there was the definitive book on doing your taxes every person should read that book, but it's not the experience they gain from reading it but the knowledge gained. If that know how was gained with experience or another book then reading the first would be obsolete or useless. I agree with this point that there are not books that people should read but lessons that people learn from books that are necessary or just good foundations for being a person. 
The analysis of patterns is something that proves intriguing until the pattern is exposed. Any little scope can be seen as just random events seemingly without repetition but by widening the scope that one looks at human history, either through books or any other medium. The question comes up are patterns inevitable in humans and/or a defining law of our reality or is there such thing as a random event in history. Is the repeated destruction of knowledge just a symptom of ruthless dictators and tyrannies or is it a pattern that can be extrapolated and planned for in the future?

**Comment by frabbitry** [comment]
I don't know if I should be contributing to this discussion or not (my comments occasionally spark fierce debate, such as the pie chart debacle last year), but here's two cents of mine: 

Last year, I only read "The Hermeneutics of Screwing Around," which I appreciate for its nuanced take on information retrieval in the digital age, but this time around I read "In Praise of Pattern." 

I feel compelled to confess at this point that I'm a math major, and so the part of the article where he talked about presenting StageGraph to the math department at Middleberry College made me cringe and feel quite a bit of second-hand embarrassment for him. I am more inclined to view graphs like the mathematicians did: means by which mathematical properties can be visualized. It's how I've been trained. However I can see his point, too.

I kind of wish I could see some of his graphs, though, and was kind of sad that they weren't included with the article. 

Anyway, it reminded me of some things I've been reading recently about using GIS in the Humanities. GIS, and maps in general, are, at heart, graphs. They're different than a pie chart for sure, but, like other kinds of graphs, they're means by which data can be visualized. For maps, the kind of data that is visualized is spatial data. GIS is of course special because of the way non-spatial data can be layered with spatial data; the power of the database married to mapping. However, like with most digital technologies, GIS relies very heavily on exactness. Something is either there or it isn't. The problem, then, with using GIS for humanities research is fundamentally epistemological. David J. Bodenhamer notes that "GIS delineates space as a set of Cartesian coordinates with attributes attached to the identified location, a cartographic concept, rather than as relational space that maps interdependencies, a social concept." Literary locations are imprecise by nature and often intention, particularly in works for which location really means something. Because, in literary works, the intention is often not to use location for what it literally is - a space in time - but for what it means. How, then, can this tension be reconciled? With vague interpretations of location, only vague conclusions can be made, and how is that useful? 

I think that Ramsay's answer is that the quantitative origins of graphs should not distract us from our original questions: "Not because interpretation must be careless and bold, but because it has to risk the perils of subjectivity in order to keep true  to  its  own  objectives—objectives  which,  in  the  context  of  literary study, seldom involve the amassing of verified facts." Digital technology is a tool to be used and it always has been. Here, it is used not to change humanities research into something it is not but to aid in humanities research. Ramsay argues that "[t]he goal is to say something new, provocative, noteworthy, challenging, inspiring—to put these texts back into play as artifacts reconstituted by re-reading" not "to prove something." As such, vague conclusions are not a problem. In some cases, they are even desired.

**Comment by benjaminc2020** [comment]
I read "The Hermeneutics of Screwing Around". I found the article to be pretty dense in some parts, but in all, I found it to be very interesting and engaging on the idea of near mindlessly stumbling upon written knowledge. I'm most pulled to the idea of having multiple paths to obtaining knowledge, research, and information when the source bucket being pulled from appears almost bottomless. I related well to Ramsay's example of walking into a library when you already have the path somewhat constructed towards how you will gather your referenced information, as opposed to browsing. That seems to be the way students are taught all throughout their high school and college careers when doing research papers. I never considered the idea of approaching a research paper by merely hopping from interest to interest as long as it related to the papers in some manner or another. However, I can see many benefits to this approach and am very fascinated with the 'hermeneutics' of it.

As I continue working in this class's project, I do often find myself in a position where I may not know exactly what to search for, or where to search. Rather, I often find that I'm in a position of simply taking in information and learning as I go. Occasionally, I may be pulled in one direction to find more out about such and such a topic. Or I'll take ideas from completely unrelated topics that can be converted in a manner to proves to be beneficial to the project as a whole. By this, I enjoy the unpredictability of not having a path already envisioned with signals and signs already in place as a product of pattern, but simply a direction of where to start. I understand how there can be instances where a pattern may fall into place, but at least it's natural and not artificially produced in a sense.

**Comment by ebeshero** [comment]
@frabbitry: I think Ramsay wanted us to wince along with him as he took his Stage Graph project to the mathematicians at Middlebury, but they seemed to be a pretty appreciative, enthusiastic audience, as I've often found math specialists to be. I especially find liberating the idea that the visualization is just one way of viewing data, and there will always be some other way to look at it. I wish he had shared a view of Stage Graph's visualizations, too, but I think maybe he wanted to place emphasis here on the experience of cross-disciplinary encounter. 

But here's something I want to add about the experience of coming out of Humanities to work on computational matters that involve dabbling and experimenting and, to borrow Ramsay's term, "screwing around" with math and stats we weren't trained in. I started experimenting with network analysis (which we'll be tinkering with shortly) in the context of XML and the kinds of nested hierarchies I could build to express dependencies and coexistences in poetry. I didn't really know much about network theory, but I did a lot of reading and experimenting based on a project, and I came to a kind of understanding that I appreciate, but also realize is limited--like the gateway to something I can keep exploring, but--crucially--I have to recognize that I ought to find help to explore my findings if I'm going to start making serious claims about them. 

Not everyone in our class would call themselves a "humanities" person the way Steve Ramsay and I do, starting out as we did in English Lit. And I do like teaching this class because I get to work with a cross-section of majors: we really do bring lots of disciplines together even with just a few smart people as we have this semester. And I think that's what I've come to appreciate the most about this "Digital Humanities" phenomenon, except I think it might better be just called "interdisciplinary cultural computation" or something. ;-) 

I've been learning interesting things from a mathematician friend, Patrick Juola of Duquesne University, when he came to visit us at Pitt-Greensburg to teach us about his methods and the software he developed for authorship attribution and stylometry (doing analysis of word patterns including data on things like average word length in a sentence, counts of articles like "a," "an," and "the" and other strange things we don't tend to look for in the way we study language in English classes. Patrick and I sat down to lunch one day last May and he told me that when he goes to Digital Humanities conferences, he sees humanities scholars playing fast and loose with math. And they ought to be recognizing that people like him with PhDs in the maths and computer science have years and years of training in these fields and deep understanding that a humanist simply can't fathom. It's humbling to realize where Digital Humanities walks a fine line between, um, pretension (shall we call it that?) and illumination. I like to think we humanities people raise interesting questions, but we ought to find ourselves friends in math to help us explore the patterns we're coming across and see what we can make of them. We need alliances across disciplines to make this work. I'm glad to work with Patrick, to provide him lots of data in my XML archives from the Digital Mitford project and the benefit of what I've studied, so that he can refine his software and help it yield new insights to people like me. There's a mutualism here that I appreciate very much, and I think Steve Ramsay might have been discovering that, too, in visiting Middlebury's math department.

**Comment by frabbitry** [comment]
@ebeshero Yes, I agree that the emphasis of the article was on the cross-disciplinary encounter. I'm just a nerd who likes to look at graphs, and it sounded like the graphs were displaying some pretty cool stuff. (Also there were numerous references to links but no actual links?) And I wanted to bring up some cool things I was reading about GIS in the Humanities, because I geek out over things like that. 

I also agree that one of the advantages of the cross-disciplinary nature of the digital humanities is that we all can draw on the expertise of those who have studied for much longer on topics that we haven't. Math is important. Getting it right is important. It's important to not be misled by false statistical claims, and it's also important to not put forth research that doesn't put the emphasis on rigorous mathematics that it should. Going to mathematicians and computer scientists for help is beneficial, then, even so for both parties. I believe that the silos, which can present themselves in academia, can and should be broken down by interdisciplinary research. If the end goal is to further human knowledge and understanding, then why wouldn't you collaborate? Both sides can gain from a greater understanding of the other. This results in stronger research, and I dare say that it might be to society's benefit, as well. Many of the ethical concerns surrounding technology might be mitigated if a more humanities-style approach was taken when developing and implementing it. But, then again, this big-tent kind of approach doesn't usually make a lot of money, so I suspect that it'll be a while before it happens. 

(And here is where I go out on a limb and make claims that I, as an undergraduate who has only dabbled in the field, have no right to make. I apologize in advance and feel free to smash me. I'll learn from it, haha. )

That being said, I believe that humanities and mathematics research are fundamentally different. I think that the fundamental questions they ask are different, and that this is evident in their origins. Mathematics, as it was first developed by the Babylonians and the Greeks, was a means of describing the outside world: tallying time, measuring pyramids, calculating the distances from ships to the shore. While it is arguable whether that is objective or not, math was used to describe that which was external. Math, and, later, science, was used to describe external reality, the world. Literature, which is the field of humanities I am most familiar with and what Ramsay referenced in his article, is used to describe that which is internal. The study of literature and literary research asks questions of the human nature, the internal psyche; Sidney's "Defense of Poesy" described it as window to the realm of Platonic ideals and the most effective way that those values can be expressed and communicated. Only more recent cultural developments have portrayed human nature as something quantifiable, measurable, and discrete. The study of psychology, for example, developed only recently. I don't think that the digital revolution would be possible or that its effects would be as pervasive without the extensive influence Postmodernism has had on Western culture. Now, we can use digital and scientific methods to study literature, and I think that that's wonderful and has led to some very fruitful research. But while literary research focuses intensely on what it is that makes literature literature, mathematical research focuses on what it is that makes math math. Using mathematical methods to study literature does not change the fact that literature is still what's being studied, just as using literary methods to study math would not change the math that is at the heart of the question. While the methods of study might be interchangeable, that which is being studied is not. 

As such, the graphs used for each field of study are going to be different because the data is different. The data is driven by different questions. 

And I don't think that that's a bad thing. Like you're saying, diversity in knowledge is a very good thing, just as diversity in the human race is. Two people from different places and from different backgrounds are still both people, and mathematical and literary research are both research, both trying to advance human knowledge. However, saying that one person from one culture is completely the same as another person from another culture is to disregard both of their cultures and minimize their experiences. The only way that a live plant could be the same as a fake one is to burn them both to ashes. Similarly, math is not the same as literature, and it shouldn't be. Pursuing both yields a more complete understanding of the world and the people who live in it. Diversity is most definitely a good thing. 

This has been a very long comment, but I believe my point is that I thought that Ramsay was saying that even though mathematical and literary research are different and result in different kinds of data to be displayed on graphs, interdisciplinary collaboration is a good thing because it fosters growth and understanding on both sides. Basically, then, I think that we agree with each other. I just wanted to expand on my comment so that it wouldn't seem like I was saying that humanities researchers just disregard math because they don't need it. They do need it, just in a different way. Or at least, that's my take on it.

**Comment by ebeshero** [comment]
For @frabbitry and all who find interdisciplinarity interesting:  I was looking up Steve Ramsay's contact info for Teen Titans project (since I think they may really really benefit from seeing anything he can share about Stage Graph) and I rediscovered his bio page at U. Nebraska Lincoln: https://www.unl.edu/english/stephen-ramsay You need to go check out the book he co-authored with our friend Patrick Juola, and best of all you can read it online: 
https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1055&context=zeabook

**Comment by ebeshero** [comment]
And you can find him on GitHub here: https://github.com/sramsay

**Comment by ebeshero** [comment]
@sramsay Greetings from Pitt! My students have been reading your work and are excited about it! :-) Some of them are pretty inspired by Stage Graph and want to see something more of it...(see their commentary on this issue). Hope all's well with you and delighted to find you on GitHub!

**Comment by sramsay** [comment]
@ebeshero Hello, Elisa!  Forgive me for the late reply.  I haven't made it all the way through the comments in that thread, but certainly, I wanted to help with the StageGraph issue.  So let me give you two things:

1. A chapter from a forthcoming book that talks about using StageGraph on _Antony and Cleopatra_ at some depth (and actually, it might help to put the issues in "The Heremeneutics of Screwing Around" more on the ground for them).  It only has a couple of graphs in it, but it does a better job than the _TEXT/Technology_ piece at contextualizing the whole thing.  This is unpublished work, so please don't post it anywhere terribly public.  But feel free to circulate it locally to any students who might be interested!

2. A folder that contains all the Shakespeare graphs.  These are unlabeled, unfortunately.  With a bit more time I can give them meaningful filenames, so they know what play they're looking at, but I wanted to get it to them as quickly as possible.  These are also unpublished.  I may do something with them at some point, but they're not going into the book (I probably couldn't afford the subvention for this many graphs!)

I hope this helps!

As for GitHub: I've been on it for so many years, I think I've forgotten life without it.  I tend to keep DH code in our CDRH repo, and book manuscripts and code I wrote for myself in private repos.  And so my public repo just contains code that I wrote for fun.

(You'll be amused to discover that my greatest accomplishment as a software engineer is actually a command-line program for pulling down weather data.  I've actually been rewriting it over the last few months, because the people who maintain the API for the previous version closed down free access to it.  Which is a shame, because the program was in Homebrew and dozens of Linux distributions.  It does demonstrate the fact that the stuff you labor endlessly over might go nowhere, while some code you tossed off in an afternoon gains a worldwide following!  You just never know.)

Anyway . . .  Good to hear from you.  And let me know if I can provide your students with anything else.

[ramsay_how.pdf](https://github.com/ebeshero/DHClass-Hub/files/4262515/ramsay_how.pdf)

[shakespeare_slides.tar.gz](https://github.com/ebeshero/DHClass-Hub/files/4262517/shakespeare_slides.tar.gz)

**Comment by ebeshero** [comment]
@sramsay Thank you very much for the article and the graphs! I love the new chapter but I promise I'll just keep it "in-house" for my DH students, who are great fans of your work! :-) From time to time, some of them might clamor to find out more, so don't be surprised if you get another invitation to come speak to my class one of these years...:-)
