### ISSUE TITLE
Network Analysis for Projects

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/DHClass-Hub#90]
Here is a general purpose issues board for students working on network analysis projects and following my Cytoscape Tutorial: http://ebeshero.github.io/thalaba/cytosc.html

As of December 2015, this involves a couple of project teams in the Obdurodon DH course (http://dh.obdurodon.org), but in Spring 2016, we'll be doing a unit on network analysis in the newtFire DH course (http://newtfire.org/dh/), and since I need to expand my materials on the subject this Issues page is a useful place to record questions, troubleshoot problems, etc. For the moment, I am inviting some members of Obdurodon here to discuss network analysis to share resources for my development of the spring DH course. @djbpitt @aprokh @eprokh @alexkrongel @andrewntz23 @TELVINS

**Comment by abc49** [comment]
Hello all! As Elisa and David requested, I'm going to put up some of our email correspondences so that everyone can benefit our discussion on network analysis! For our project on Profanities used in Tarantino's screenplays, we wanted to do a co-occurence network analysis of all the curses/slurs used by male or female characters in the three screenplays we analyzed. We specifically used XSLT to do format the table that would be imported into Cytoscape, but you could also used XQuery as well. 
Here is the basic breakdown as described by Elisa (originally via email) of how to create the XSLT sheet: 

I’ll simplify this to just one kind of Node 1 – Edge –Node 2 output: In Thalaba (Elisa's original project using network analysis), I make a network of each place to each other place in a chunk of text, and the chunk of text makes my edge.

1) In a template match on the body of my document, I first do an xsl:for-each on each place in the whole document (regardless of the unit of text). This is retrieving Every Place Tagged Everwhere Across My Full Collection of All the Chunks of Text. (And I’m reaching into an attribute that helps ensure I’m working with a standard canonical place name. In your case, I think, you’re reaching into an attribute to get the stem of your curse word.)
 
2) In this for-each, I define a variable that I call “Node-1-Edge” because it contains Node 1 and its Edge Information (the Chunk of text it’s sitting in). For me that’s a line-group or a stanza of poetry. For you that’s a movie. The xsl:variable takes me a few lines to code, because within it I output the value of the current place, then a tab character, then the Edge-Chunk information. I *don’t output the variable yet* but I just define it in this outer for-each loop.
 
3) Then I make an inner for-each that matches on every other place that isn’t current and is within the Same Chunk. My code for that looks like this:
<xsl:for-each select="ancestor::lg//placeName[not(. = current())]
 
In your case the ancestor lg is replaced by the ancestor document title or whatever forms your edge that identifies a Tarantino movie and defines co-occurrence. Here it’s delimiting how many others are making the network.
 
4) Inside the inner for-each, I do the following:
* I output my variable that I defined up above:  $Node-1-Edge. (Why? because I want the current context to be output on each line with the Edge info (the Chunk of text), for each one of the connected other nodes. I found that it was easier to output Node-1-Edge as a variable so I could invoke it inside this inner loop)
* Then I just output the @ref, which is set to the inner for-each loop. (And in my code that’s simply a matter of <xsl:value-of select="normalize-space(@ref)"/> so I don’t have to mess with current() or dot or anything. My inner for-each loop simply selected the elements I wanted and then I stepped in here to output their @ref attributes.) 
All along I’ve been outputting tab characters or commas or whatever I needed for my separators.All along I’ve been outputting tab characters or commas or whatever I needed for my separators. 
The separators could be simple as a ',' or tab.

**Comment by abc49** [comment]
Hello! I was wondering if there was anyone who could help me with the node size. I set it to the degree column as was instructed in Elisa's Cytoscape tutorial but I just can't figure how to make the node sizes bigger. I tried adjusting the graph displayed but it seems to not be having the effect I want it to have on the nodes. After I did this part, I had more trouble moving the actual nodes on the graph to different positions. I was wondering if you had any advice on how I could change the node size so we can make it more visible in the network analysis. Any help would be greatly appreciated!!!

**Comment by ebeshero** [comment]
@abc49 Abbie-- Thanks for posting the substance of our earlier messages here! I'm happy to take a look at your work--And I'm adding you now as a collaborator on this repository, so you will have push access. @alexkrongel and @djbpitt can show you how to clone and push to our Troubleshooting folder, which is where we take on files that we're testing. I'll push your Cytoscape file there in a few minutes.

**Comment by ebeshero** [comment]
@abc49 I am so sorry I was not more timely help to you with this, but I didn't know how to reply easily in words and my own classes became overwhelming last week. There are really powerful ways to control the node sizes in the styling menu, and you really just need to explore how they work for within Cytoscape. For example, there is a way to make node sizes increase by a proportion that you set with a little graph on a particular property. So, if you imported attribute data, and you set node size to the appropriate column, you can right-click I think (or the equivalent on a Mac) and bring up a little graph that you can manipulate so node size increases at a more rapid even exponential rate. There's a good illustration of this titled "Continuous Editor for Node Size" here: http://opentutorials.cgl.ucsf.edu/index.php/Tutorial:Introduction_to_Cytoscape

As for changing position of nodes, there are so many different ways to do that that I don't really know how to respond: You want to experiment with the many different layouts available after you have run the Network Analyzer to calculate the network statistics on your data.

**Comment by nlottig94** [comment]
Closing for Spring 2016.
